### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by zhangtuoparis13** [Homebrew/homebrew#42578] opened 2015-08-06 21:38 UTC
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

**Comment by zhangtuoparis13** [comment] 2015-08-06 21:39
this is the bug when i run brew update

**Comment by mistydemeo** [comment] 2015-08-06 21:49
Duplicate of #42553.

**Closed by mistydemeo** 2015-08-06 21:49 UTC
