### ISSUE TITLE
libbpg 0.9.5 causing SIGBUS (Misaligned address error) on 10.10.5

### ISSUE THREAD

**Issue by stirlingpoon** [Homebrew/homebrew#43708] opened 2015-09-08 16:55 UTC
When running bpgenc img.jpg (see attached image), it terminates with a SIGBUS signal with a zero-byte BPG file generated. Both the default jctvc encoder and the x265 encoder fail with the same error.

Tested on other images and the error does not appear.
![404](https://cloud.githubusercontent.com/assets/4289911/9741628/fa60e440-568d-11e5-9a4c-f61c758459c7.jpg)

**Comment by DomT4** [comment] 2015-09-08 17:50
Unless this doesn't reproduce with a `libbpg` built outside of Homebrew this may be something that needs reporting upstream.

**Comment by stirlingpoon** [comment] 2015-09-08 18:38
You're right, the error was reproduced on libbpg built outside homebrew. I don't think libbpg is on Github though.

**Comment by DomT4** [comment] 2015-09-08 19:01
Looks like bugs need reporting to `fabrice@bellard.org`. Is the only suggested place to send suggestions/help/etc I could find upstream.

**Comment by mikemcquaid** [comment] 2016-04-02 15:48
This is an upstream issue Homebrew can't fix so closing it.

**Closed by mikemcquaid** 2016-04-02 15:48 UTC
Labels: upstream issue
