### ISSUE TITLE
libtiff fails with 'has no symbols'

### ISSUE THREAD

**Issue by edjacks** [Homebrew/homebrew#38522] opened 2015-04-10 17:44 UTC
Discovered while trying to 'brew install wine' and subsequently 'brew install liftoff'  

GIST URL:  https://gist.github.com/1a6158d1429c7736db03

The install fails with the following messages:

libtool: link: ranlib .libs/libtiff.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: .libs/libtiff.a(tif_jbig.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: .libs/libtiff.a(tif_jpeg_12.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: .libs/libtiff.a(tif_lzma.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: .libs/libtiff.a(tif_jbig.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: .libs/libtiff.a(tif_jpeg_12.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: x86_64 file: .libs/libtiff.a(tif_lzma.o) has no symbols

**Comment by mistydemeo** [comment] 2015-04-10 17:51
Looks like the actual error is:

> /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found

Which is a duplicate of #38514 - closing this as a duplicate. Thanks for the report!

**Closed by mistydemeo** 2015-04-10 17:51 UTC
