### ISSUE TITLE
F# 3.1 extension paths wrong

### ISSUE THREAD

**Issue by haf** [Homebrew/homebrew#36286] opened 2015-01-27 16:48 UTC
I'm opening an issue here, to get a suggestion for how to solve

https://github.com/fsharp/fsharp/issues/328

This is the way these directories look:

```
➜  xbuild git:(upgrade/mono) tree /usr/local/Cellar/mono/3.12.0/lib/mono/xbuild/
/usr/local/Cellar/mono/3.12.0/lib/mono/xbuild/
├── 12.0
│   └── bin
│       ├── MSBuild
│       │   ├── Microsoft.Build.CommonTypes.xsd
│       │   └── Microsoft.Build.Core.xsd
│       ├── Microsoft.Build.Engine.dll -> ../../../gac/Microsoft.Build.Engine/12.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.Engine.dll
│       ├── Microsoft.Build.Framework.dll -> ../../../gac/Microsoft.Build.Framework/12.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.Framework.dll
│       ├── Microsoft.Build.Tasks.v12.0.dll -> ../../../gac/Microsoft.Build.Tasks.v12.0/12.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.Tasks.v12.0.dll
│       ├── Microsoft.Build.Utilities.v12.0.dll -> ../../../gac/Microsoft.Build.Utilities.v12.0/12.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.Utilities.v12.0.dll
│       ├── Microsoft.Build.dll -> ../../../gac/Microsoft.Build/12.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.dll
│       ├── Microsoft.Build.xsd
│       ├── Microsoft.CSharp.targets
│       ├── Microsoft.Common.targets
│       ├── Microsoft.Common.tasks
│       ├── Microsoft.VisualBasic.targets
│       ├── Mono.XBuild.Tasks.dll -> ../../../gac/Mono.XBuild.Tasks/4.0.0.0__0738eb9f132ed756/Mono.XBuild.Tasks.dll
│       ├── xbuild.exe
│       ├── xbuild.exe.config
│       ├── xbuild.exe.mdb
│       └── xbuild.rsp
└── Microsoft
    ├── Portable
    │   ├── Microsoft.Portable.Core.props
    │   ├── Microsoft.Portable.Core.targets
    │   ├── v4.0
    │   │   ├── Microsoft.Portable.CSharp.targets
    │   │   └── Microsoft.Portable.Common.targets
    │   └── v4.5
    │       ├── Microsoft.Portable.CSharp.targets
    │       └── Microsoft.Portable.Common.targets
    └── VisualStudio
        ├── v10.0
        │   └── WebApplications
        │       └── Microsoft.WebApplication.targets
        ├── v11.0
        │   └── WebApplications
        │       └── Microsoft.WebApplication.targets
        └── v9.0
            └── WebApplications
                └── Microsoft.WebApplication.targets

14 directories, 26 files
➜  xbuild git:(upgrade/mono) tree /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/xbuild/
/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/xbuild/
└── Microsoft
    └── VisualStudio
        ├── v
        │   └── FSharp
        │       ├── Microsoft.FSharp.Targets
        │       └── Microsoft.Portable.FSharp.Targets
        └── v12.0
            └── FSharp
                ├── Microsoft.FSharp.Targets
                └── Microsoft.Portable.FSharp.Targets

6 directories, 4 files
```

Is it advisable to let the `fsharp` formula symlink to the `mono` formula, like is suggested?

Should a PR be sent to the mono project to support the new extensions? Or should @rneatherway or @dsyme or someone with push access to the F# repo add in build extensions for mono?

**Comment by rneatherway** [comment] 2015-01-28 14:35
Ideally I think they should just be placed in the mono folders, as the fsharp installation is normally on top of an existing mono installation. Symlinking should also be fine, as long as xbuild can find these targets in the expected places (alongside the normal mono ones).

**Comment by haf** [comment] 2015-02-08 11:18
Default installation:

`Using F# targets file: "/Library/Frameworks/Mono.framework/Versions/3.12.0/lib/mono/xbuild/../Microsoft SDKs/F#/3.1/Framework/v4.0/Microsoft.FSharp.Targets"`

With homebrew:

`Using F# targets file: "/usr/local/Cellar/mono/3.12.0/lib/mono/xbuild/../Microsoft SDKs/F#/3.1/Framework/v4.0/Microsoft.FSharp.Targets"`

**Comment by haf** [comment] 2015-02-08 11:56
Like this, perhaps? Compiling to test it now... `brew edit fsharp`

![screen shot 2015-02-08 at 12 55 44](https://cloud.githubusercontent.com/assets/193115/6096458/d8558bc4-af91-11e4-8a51-7ac34e7212f9.png)

**Comment by haf** [comment] 2015-02-08 14:19
Getting 

```
/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/Microsoft.FSharp.Targets: error : Error executing tool '/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe': ApplicationName='/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe', CommandLine='-o:obj/Debug/logibit.crypto.dll -g --debug:full --noframework --define:DEBUG --optimize- --tailcalls- -r:../../packages/FSharp.Core/lib/net40/FSharp.Core.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/mscorlib.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Numerics.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Core.dll --target:library --warn:2 --warnaserror:76 --fullpaths --flaterrors --highentropyva- AssemblyInfo.fs Crypto.fs SampleValidate.fsx ', CurrentDirectory='/Users/henrik.feldt/dev/logibit/logibit.web/src/logibit.crypto', Native error= Cannot find the specified file
```

But running the above command by itself works fine.

**Comment by rneatherway** [comment] 2015-07-28 16:26
Hi, we are having some more problems with the F# formula, see https://github.com/fsharp/fsharp/issues/451. Somehow, `brew install fsharp` is deleting the `/usr/local/lib/mono` symlink created by `brew install mono`! Looking at `fsharp.rb`, I cannot see any deletion. Why would this be occurring?

**Comment by mistydemeo** [comment] 2015-07-28 16:45
That's by design.

Both mono and fsharp install contents into `/usr/local/lib/mono`. When mono is installed, the directory is created as a symlink into mono's private prefix because it's not used by anything else; when F# is installed, any symlinks to directories used by both of them are replaced by actual directories containing symlinks into the appropriate private prefix. This is the standard way Homebrew manages merging overlapping directories from multiple packages.

**Comment by rneatherway** [comment] 2015-07-28 16:55
@mistydemeo: thanks that is very useful to know! So we have a problem where a tool (xbuild) installed in the mono keg is canonicalising its paths, so it expects to find certain files in the mono keg, when they are in fact present in the fsharp keg.

The fsharp recipe symlinks these files under `/usr/local/lib/mono`, but that doesn't help because xbuild is looking in the mono keg. Looking at the [recipe](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fsharp.rb#L40), it looks to me as though it is trying to symlink them into the mono keg (`"#{prefix}/../../mono/#{mono_ver}"`), but that isn't where they end up.

If we can make that symlink work, is that the way to go? And can you see a problem with the recipe as it stands?

**Comment by mistydemeo** [comment] 2015-07-28 17:30
It sounds to me in this context that the issue is with xbuild in this context. The general intention with Homebrew's symlink structure is that tools should use the links in `/usr/local` when present, and shouldn't canonicalize them. For example, a C program linking against `/usr/local/lib/libxmp.dylib` should link against that name and not `/usr/local/Cellar/libxmp/4.3.9/lib/libxmp.dylib`.

The `prefix` variable in the F# formula refers to F#'s private prefix, not to the Homebrew prefix; it actually is intended to be installing into its own private prefix, which will be merged with Mono's in the way you're noticing when they're both linked publicly.

**Comment by rneatherway** [comment] 2015-07-28 21:15
> It sounds to me in this context that the issue is with xbuild.

I think xbuild is designed to behave in this way deliberately, so that even if a symlink is made, the files that sit relative to it are still found. It isn't expected that a complete parallel hierarchy would be made like this.

> The prefix variable in the F# formula refers to F#'s private prefix, not to the Homebrew prefix; it actually is intended to be installing into its own private prefix, which will be merged with Mono's in the way you're noticing when they're both linked publicly.

Right, but it looks like the `../../mono/#{mono_ver}` afterwards is intended to go from fsharp's private prefix in the Cellar to mono's private prefix. Isn't that right? I can't see why that would end up under `/usr/local/lib/mono`. If this doesn't work, is there another solution that doesn't involve modifying xbuild?

**Comment by rneatherway** [comment] 2015-07-29 05:57
@mistydemeo: on investigation, I remembered that `/usr/local/bin/xbuild` is a small bash script that calls the real xbuild.exe with mono:

```
#!/bin/sh
exec /usr/local/Cellar/mono/4.0.2.5/bin/mono $MONO_OPTIONS /usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild/12.0/bin/xbuild.exe "$@"
```

As you can see this script points at the keg copy of xbuild.exe rather than the symlink under `/usr/local/lib/mono`. So, from what you said earlier, sounds like we should change the mono recipe to modify all these loader scripts (but particularly this one). Does that sound right to you?

**Comment by mistydemeo** [comment] 2015-07-29 06:09
That sounds right. Do you mind tweaking your copy of the script to see if that works? If so, I can adjust the recipe to fix this!

**Comment by haf** [comment] 2015-07-29 06:58
:fireworks: progress :) yey for @rneatherway

**Comment by rneatherway** [comment] 2015-07-29 09:46
Thanks a lot for your help, I'll try that tonight.

**Comment by rneatherway** [comment] 2015-07-29 22:03
Sorry to say that adjusting the script to the following didn't work:

```
exec /usr/local/bin/mono $MONO_OPTIONS /usr/local/lib/mono/xbuild/12.0/bin/xbuild.exe "$@"
```

It seems that xbuild uses a .NET library function (ToolLocationHelper.GetPathToDotNetFramework)[https://github.com/mono/mono/blob/master/mcs/tools/xbuild/Main.cs#L66], which in turns uses reflection to (find the location of mscorlib.dll)[https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolLocationHelper.cs#L52].

So I don't think it will be possible to change this behaviour. Is there any other way we can work around this?

**Comment by rneatherway** [comment] 2015-07-29 22:20
I tried adding the missing symlinks (from the fsharp keg direct into the mono keg) with:

```ruby
    %w|v v12|.each do |vs_ver|
      %w|Microsoft.Portable.FSharp.Targets
         Microsoft.FSharp.Targets|.each do |fsharp_targ|
        
        tree_dir   = "lib/mono/xbuild/Microsoft/VisualStudio/#{vs_ver}/FSharp"
        source_dir = File.expand_path "#{prefix}/../../mono/#{mono_ver}/#{tree_dir}"

        mkdir_p source_dir
        ln_sf "#{prefix}/#{tree_dir}/#{fsharp_targ}", "#{source_dir}/#{fsharp_targ}"
      end
    end
```

However, building an F# project still fails because the F# dlls are not present in the mono keg where all the build machinery is looking for things. I guess I can symlink *everything* in the fsharp keg into the mono keg, which gets more and more ugly, or we could consider installing F# as part of the mono recipe so that it all goes in the same place which is how it is designed.

**Comment by mikemcquaid** [comment] 2015-07-30 09:10
This seems like it's probably something that could/should be fixed (possibly more easily) upstream in Mono/F#.

**Comment by haf** [comment] 2015-07-30 09:11
+1 for fixing upstream

**Comment by dsyme** [comment] 2015-07-30 11:47
It seems to make sense to try the approach where we symlink everything in the F# keg into the Mono keg. It shouldn't be too hard to do that recursively should it? 

F# just expects to be installed into the same place as Mono and always has done. That's not something that's particularly pleasant to change at this stage because any change would impact the target file paths used in all existing F# project files, and would be incompatible with other F# tooling.  

Alternatively we combine the recipes into one.

**Comment by mikemcquaid** [comment] 2015-07-30 11:59
> It seems to make sense to try the approach where we symlink everything in the F# keg into the Mono keg. It shouldn't be too hard to do that recursively should it?

We don't let formulae modify the kegs of other formulae for various reasons (the short version is it breaks under various circumstances).

> F# just expects to be installed into the same place as Mono and always has done

Sure. This is an upstream assumption that can be fixed, though. Homebrew always installs packages into separate prefixes and always has done.

**Comment by dsyme** [comment] 2015-07-30 12:10
| Sure. This is an upstream assumption that can be fixed, though. 

I don't think the assumption can be changed except by breaking project compatibility with other F# installations (which would be bad).

I'll let @rneatherway answer, but AFAIK you can't have a compatible F# installation unless ``.../lib/mono/xbuild`` (under ``/usr/local`` and/or the mono keg) contains these files:

```
└── Microsoft
    └── VisualStudio
        ├── v
        │   └── FSharp
        │       ├── Microsoft.FSharp.Targets
        │       └── Microsoft.Portable.FSharp.Targets
        └── v12.0
            └── FSharp
                ├── Microsoft.FSharp.Targets
                └── Microsoft.Portable.FSharp.Targets
```

These files are referenced by thousands of existing F# project files and just have to be there one way or another.  

I think that's the only issue, perhaps there's a upstream solution that I'm not yet aware of that achieves this and maintains compat.

Cheers
Don

**Comment by rneatherway** [comment] 2015-07-30 21:23
Just to recap, the current situation is that mono is installed under `/usr/local/Cellar/mono/4.0.2.5/` and fsharp under `/usr/local/Cellar/fsharp/3.1.2.4`. The files in these folders are then recursively symlinked into `/usr/local/..`, maintaining the directory structure. This means that the F# targets files are in the "right" place:

```
$ ls -l /usr/local/lib/mono/xbuild/Microsoft/VisualStudio/v
lrwxr-xr-x 1 robnea admin 77 Jul 29 23:16 /usr/local/lib/mono/xbuild/Microsoft/VisualStudio/v -> ../../../../../Cellar/fsharp/3.1.2.4/lib/mono/xbuild/Microsoft/VisualStudio/v/
```

However, when xbuild is executed it has to determine where it thinks the .NET installation lives, and it does this [by](https://github.com/mono/mono/blob/master/mcs/class/Microsoft.Build.Utilities/Microsoft.Build.Utilities/ToolLocationHelper.cs#L52) (the C# equivalent of) `typeof<obj>.Assembly.Location`. This returns the copy under `/usr/local/Cellar/mono/4.0.2.5/` and everything goes wrong from there. The `/usr/local/...` folder hierarchy is ignored and the F# installation along with it.

I do not think it is feasible to fix this upstream, which would mean changing the behaviour of Mono. Changing F# or any of the target files will not help here. I think we have two options:

1. Symlink everything from the F# keg into the Mono keg. Cheap and nasty but it would fix this problem. Perhaps it would break in some unknown situations though?
2. Merge the F# recipe into the Mono recipe. F# is always intended to be installed on top of Mono anyway, so this really would be consistent with what you get when you use the official Xamarin installer, for example.

**Comment by mikemcquaid** [comment] 2015-07-31 07:11
> I do not think it is feasible to fix this upstream, which would mean changing the behaviour of Mono.

Changing the behaviour of Mono to mean that it fixes this behaviour (even optionally) seems reasonable to me. Most other software does not behave this way or have been fixed to work better with Homebrew.

> Symlink everything from the F# keg into the Mono keg. Cheap and nasty but it would fix this problem. Perhaps it would break in some unknown situations though?

This would not fix the problem. Think about what happens on e.g. `reinstall` or `upgrade` of Mono and not F#.

> Merge the F# recipe into the Mono recipe. F# is always intended to be installed on top of Mono anyway, so this really would be consistent with what you get when you use the official Xamarin installer, for example.

If we're very resistant to making upstream changes I think this is the only option.

**Comment by dsyme** [comment] 2015-07-31 09:21
> However, when xbuild is executed it has to determine where it thinks the .NET installation 
> lives, and it does this by (the C# equivalent of)  typeof<obj>.Assembly.Location .

@rneatherway Do you know the "right" way to do this in order to get ``/usr/local/lib/mono/...``? thx

**Comment by rneatherway** [comment] 2015-07-31 09:35
I'm afraid I don't know the right way. I tried following the implementation of `Assembly.Location`, but it quickly ended up in unmanaged code and it would take a few hours to start to understand how it all fits together. We could open a bug, but this affects the entire strategy for determining the GAC location as well so I think the chance of it being changed is essentially nil.

I have some sympathy with that possible outcome, because I don't think it is clear whether the current behaviour is wrong. In this case (complete reconstruction of file hierarchy with symlinks) it gives a bad result, but if a single binary was symlinked elsewhere it would still work fine, whereas if the runtime was changed to look relative to the symlinked location then that case would break.

**Comment by haf** [comment] 2015-07-31 10:25
To me it seems that the problem nor solution should be around `Assembly.Location`, but how lookups for non-assembly `.Target` files happen. And while that currently is by finding the full and resolved path to the assembly, this behaviour could be changed without affecting how assemblies are fetched from the GAC.

**Comment by rneatherway** [comment] 2015-07-31 10:31
@haf: I don't think that will be sufficient, because I tried symlinking the `.Target` files into the Mono keg: https://github.com/Homebrew/homebrew/issues/36286#issuecomment-126113588

However, the build then couldn't find `FSharp.Core.dll`, because it wasn't present in the Mono keg, which is where the GAC is. That being said, I didn't set `MONO_GAC_PREFIX` as instructed by https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fsharp.rb#L65, so it *might* work with that set, but I wouldn't view that as an acceptable installation either.

**Comment by haf** [comment] 2015-07-31 11:42
@rneatherway What won't be sufficient? I'm suggesting fixing it upstream; if that needs to be in both xbuild and fsharp.targets then so be it. I'm just saying that we don't need to change how Assembly.Location works.

So two issues:

 1. Finding the .targets files
 2. Finding the FSharp.Core.dll.

Just finding the target files are sufficient if you're using the FSharp.Core nuget which is rather a best practise.

@mikemcquaid How do other software solve pluggable build dependencies?

**Comment by mikemcquaid** [comment] 2015-07-31 11:48
> @mikemcquaid How do other software solve pluggable build dependencies?

Sorry, I'm not sure what you mean here. Can you elaborate a bit?

**Comment by rneatherway** [comment] 2015-07-31 11:53
@haf: xbuild finds the .target files through the standard MSBuild machinery, after calculating the value of `MSBuildExtensionsPath32`. This is done indirectly using `Assembly.Location`. Changing that will not be easy, and require significant changes to the mono implementation of MSBuild.

For the FSharp .targets file, are you suggesting just modifying it for homebrew, or changing it upstream? How do you propose changing it that would keep compatibility with standard installations of Mono and F#?

> Just finding the target files are sufficient if you're using the FSharp.Core nuget which is rather a best practise.

Whether that's true or not, this installation should work with existing F# project files.

**Comment by haf** [comment] 2015-08-02 13:49
@rneatherway Somewhere in that code there's something that looks up `MSBuildExtensionsPath32`; if you make it so that it can have multiple values of that flag, then the default will work for all projects out of the box that work out of the box now. It will also work for homebrew, because it can either control the environment xbuild runs in an enable that behaviour, or it can use a compiler flag to enable it. I'm not saying it's very easy, but it shouldn't be that hard either.

I'm more thinking changing the F# default project is a possibility. Right now it's tied to `MSBuildExtensionsPath32`, but it could be tied to something else like `FSharpMSBuildPath` and that could be defaulted to `MSBuildExtensionsPath32`.

@mikemcquaid What I mean is; are there other build systems that you have packaged, like Scala or Clojure that extend their build environment as extensively?

**Comment by mikemcquaid** [comment] 2015-08-02 14:36
> @mikemcquaid What I mean is; are there other build systems that you have packaged, like Scala or Clojure that extend their build environment as extensively?

I'm not sure, sorry.

**Comment by rneatherway** [comment] 2015-08-04 09:52
@haf: `xbuild`currently uses the environment variables `MSBuildExtensionsPath`, `MSBuildExtensionsPath32` and `MSBuildExtensionsPath64` as alternatives (see `man xbuild`) in a case like:

    <Import Project="$(MSBuildExtensionsPath)\TestTargets.targets"/>

But the F# project file uses a two-step process, first setting a variable and then importing it e.g:

    <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
    <Import Project="$(FSharpTargetsPath)" Condition="Exists('$(FSharpTargetsPath)')" />

In addition, even if `xbuild` did interpret things this way, resolving assemblies from the GAC is still an issue. It might be possible to work around it by setting `MONO_GAC_PREFIX` in the `xbuild` loader bash scripts, I'm not sure.

> I'm more thinking changing the F# default project is a possibility. Right now it's tied to MSBuildExtensionsPath32, but it could be tied to something else like FSharpMSBuildPath and that could be defaulted to MSBuildExtensionsPath32.

I don't see this as a viable option. Projects created in Visual Studio should build immediately on Mono.


I favour the option of installing F# as part of the mono recipe.

**Comment by apjanke** [comment] 2015-08-05 08:42
fsharp is failing to build on 10.11, at a symlink creation stage. Could that be part of this issue?  #42495

https://gist.github.com/3e263161995ea81f8fc6

**Comment by dsyme** [comment] 2015-08-05 12:09
Taking a quick look at that log...

First, these looks strange (no escape of the space in the path)

    ln -s ../../Cellar/fsharp/3.1.2.4/lib/mono/Microsoft F# Microsoft F#
    ...
    rm /usr/local/lib/mono/Microsoft F#

Are those actual bash commands being run or the diagnostic output of some script?

The actual error is here:

    The formula built, but is not symlinked into /usr/local 
    Could not symlink lib/mono/Microsoft SDKs/F#/3.0/Framework/v4.0/Microsoft.FSharp.Targets 
    Target /usr/local/lib/mono/Microsoft SDKs/F#/3.0/Framework/v4.0/Microsoft.FSharp.Targets 
     is a symlink belonging to fsharp. You can unlink it: 
       brew unlink fsharp 
     
     To force the link and overwrite all conflicting files: 
       brew link --overwrite fsharp 

The last four lines below also look fishy (there are extra ../../.. in the paths):

    ln -s ../../../Cellar/mono/4.0.2.5/lib/mono/4.5/xsd.exe xsd.exe
    ln -s ../../../Cellar/mono/4.0.2.5/lib/mono/4.5/xsd.exe.mdb xsd.exe.mdb 
    ln -s ../../../../../../../Cellar/mono/4.0.2.5/lib/mono/Microsoft SDKs/F#/3.0/Framework/v4.0/Microsoft.FSharp.Targets Microsoft.FSharp.Targets 
    ln -s ../../../../../../../Cellar/mono/4.0.2.5/lib/mono/Microsoft SDKs/F#/3.0/Framework/v4.0/Microsoft.Portable.FSharp.Targets Microsoft.Portable.FSharp.Targets 
    ln -s ../../../../../../../Cellar/mono/4.0.2.5/lib/mono/Microsoft SDKs/F#/3.1/Framework/v4.0/Microsoft.FSharp.Targets Microsoft.FSharp.Targets 
    ln -s ../../../../../../../Cellar/mono/4.0.2.5/lib/mono/Microsoft SDKs/F#/3.1/Framework/v4.0/Microsoft.Portable.FSharp.Targets Microsoft.Portable.FSharp.Targets

**Comment by rneatherway** [comment] 2015-08-05 13:20
By way of an update, Xamarin are currently investigating this problem to determine the best way to fix it. Let's wait a bit to see what they say.

**Comment by mikemcquaid** [comment] 2015-08-09 08:24
> By way of an update, Xamarin are currently investigating this problem to determine the best way to fix it. Let's wait a bit to see what they say.

Great news :+1:

**Comment by sgtz** [comment] 2015-08-18 03:41
how is this progressing?  Is any other assistance needed at this time?

**Comment by haf** [comment] 2015-09-01 12:38
@rneatherway any update on this?

**Comment by rneatherway** [comment] 2015-09-01 16:19
Xamarin have been having a go at it, but nothing workable yet. I think the best approach is to merge the mono and fsharp recipes into one.

**Comment by mistydemeo** [comment] 2015-09-01 16:32
Is there an upstream Mono issue for this?

**Comment by haf** [comment] 2015-09-01 16:34
@rneatherway ok thanks for the update!

**Closed** 2015-10-07 09:22 UTC
