### ISSUE TITLE
Elm fails to build from source

### ISSUE THREAD

**Issue by enilsen16** [Homebrew/homebrew#50012] opened 2016-03-11 05:55 UTC
### Bug reports:

I was able to build Elm from source without brew, but I get a few compiler errors using `brew install elm --HEAD`

```
==> cabal install --jobs=8 --max-backjumps=100000 --only-dependencies elm-compiler elm-package elm-make elm-repl elm-r
Last 15 lines from /Users/eyes/Library/Logs/Homebrew/elm/04.cabal:
trying: elm-compiler-0.16 (user goal)
next goal: elm-package (user goal)
rejecting: elm-package-0.17 (conflict: elm-compiler==0.16, elm-package =>
elm-compiler==0.17)
rejecting: elm-package-0.5 (conflict: elm-compiler==0.16, elm-package =>
elm-compiler>=0.15 && <0.16)
rejecting: elm-package-0.4 (conflict: elm-compiler==0.16, elm-package =>
elm-compiler>=0.14.1 && <0.15)
rejecting: elm-package-0.2.2, 0.2.1, 0.2 (conflict: elm-compiler==0.16,
elm-package => elm-compiler>=0.14 && <0.15)
Dependency tree exhaustively searched.
```

I am still having issues with `brew gist-logs`, which may be a separate issue...
```
~/Projects brew gist-logs elm
Error: HTTP 404 Not Found (expected 201)
```

**Comment by mikemcquaid** [comment] 2016-03-11 08:30
CC @ilovezfs for `cabal` thoughts.



> I am still having issues with brew gist-logs, which may be a separate issue...

Yeh, could you create a separate issue? Thanks!

**Comment by ilovezfs** [comment] 2016-03-11 10:26
@mikemcquaid The problem is that version 17 of elm-compiler is in branch `dev` not `master`, but the formula just says
```
head do
    url "https://github.com/elm-lang/elm-compiler.git"
```
This raises the question what we really want HEAD to mean.

The current situation is
```
elm-compiler
  master (v. 0.16, tagged on 2nd Oct 2015)
  dev (v. 0.17 tagged on 8th Feb 2016): This branch is 62 commits ahead, 2 commits behind master.

elm-package
  master (v. 0.17, tagged on 20th Feb 2016, requires elm-compiler == 0.17)

elm-make
  master (v. 0.17, tagged on 16th Feb 2016, requires elm-compiler == 0.17)
  next: [actually behind master]

elm-repl (last commit 9th Oct 2015)
  master (requires elm-compiler >= 0.16 && < 0.17)

elm-reactor (last commit 22nd Nov 2015)
  master (requires elm-compiler >= 0.16 && < 0.17)
  next: (requires elm-compiler >= 0.16 && < 0.17) This branch is 156 commits ahead, 1 commit behind master.
```
At the moment, I think we should define HEAD as
```
elm-compiler => dev
elm-package => master
elm-make => master
elm-repl => master + --allow-newer, which may or may not build
elm-reactor => next + --allow-newer, which may or may not build
```
I'll check if that works locally.

It may be the case that elm-repl and elm-reactor don't really belong in the same formula as the others, or they just haven't had a chance to catch them up yet.

**Comment by ilovezfs** [comment] 2016-03-11 19:30
@enilsen16 @mikemcquaid https://github.com/Homebrew/homebrew/pull/50034

@enilsen16 you should be able to `brew pull 50034` if you want to try it :)

**Comment by enilsen16** [comment] 2016-03-11 21:45
Thanks @ilovezfs :smile:

**Comment by mikemcquaid** [comment] 2016-03-13 16:34
> brew install elm --HEAD

We don't really support `--HEAD` installs, FYI. If you can't debug/fix them: you probably shouldn't be using them :wink:

**Comment by DomT4** [comment] 2016-03-14 03:14
Closing in favour of https://github.com/Homebrew/homebrew/pull/50034. Given the reliability issues of Cabal/etc, supporting `HEAD` for related formulae feels like asking for pain but ho hum :smile:.

**Closed by DomT4** 2016-03-14 03:14 UTC
