### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by christopherdumas** [Homebrew/homebrew#42855] opened 2015-08-12 13:48 UTC
I also ran `brew update` to fix this, but it just said that I'm already up to date. I haven't been configuring or doing anything strange with brew. I'm on OS X Yosemite. In case this helps, here are the packages I've installed: (brew list)
`ant			cmake			gdk-pixbuf		gobject-introspection	libgpg-error		libtool			openssl			ruby			wine
atk			emacs			gettext			gtk+			libgphoto2		libusb			p7zip			sane-backends		winetricks
autoconf		fish			ghc			harfbuzz		libicns			libusb-compat		pango			sqlite			xz
automake		fontconfig		git			hicolor-icon-theme	libksba			libyaml			pixman			stow
bash			freetype		glib			icu4c			libpng			little-cms2		pkg-config		tree
cabal-install		gawk			gmp			jasper			libsigsegv		makedepend		python3			unrar
cabextract		gd			gnu-smalltalk		jpeg			libtasn1		nettle			qemu			vim
cairo			gdbm			gnutls			libffi			libtiff			node			readline		wget`

And heres the error:
`Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:227:in 'loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in 'factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in 'block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in 'each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in 'report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in 'update'
/usr/local/Library/brew.rb:125:in `<main>'`

**Comment by mikemcquaid** [comment] 2015-08-12 13:51
Duplicate of https://github.com/Homebrew/homebrew/issues/42553. Don't worry this is a one time error and it won't happen again.

**Closed by mikemcquaid** 2015-08-12 13:51 UTC
