### ISSUE TITLE
povray failed to build on 10.9.5

### ISSUE THREAD

**Issue by j6thomps** [Homebrew/homebrew#45317] opened 2015-10-25 22:35 UTC
I am currently trying to install povray under OS X 10.9.5, but the build fails.

I've been through the troubleshooting checklist and I think I've taken care of everything I can.

My gist is located here:
https://gist.github.com/anonymous/c40518ffa0379f708bb7

I've seen some old posts about issues with shared_ptr (https://github.com/Homebrew/homebrew/issues/23612), but I think since I am installing povray 3.7.0, that should not be a problem.

**Comment by dunn** [comment] 2015-10-27 02:03
I'm seeing the same error on El Capitan.

If you could try building povray outside of Homebrew, that would help us figure out if this is something with our formula or an upstream issue.

**Comment by j6thomps** [comment] 2015-10-27 10:46
Hi Alex,

I've tried compiling povray 3.7.0 stable from source, but it fails during the ./configure step, where it fails to link with the boost thread library. The output from the terminal, and config.log are located here: https://gist.github.com/j6thomps/602147d1c016fa2fa349. I'm not sure how to diagnose the problem further, whether it is a problem with where boost is located on my system, and ./configure can't find it properly, or whether it is a problem with the Boost library as installed by Homebrew.

**Comment by c-lipka** [comment] 2015-10-28 10:09
It seems to me that your build environment in general is in bad shape; it seems your clang compiler disguises as the GNU C++ compiler (responding to gcc and g++), and your automake/autoconf seems to not be in tune with this mimicking, concluding incorrectly that it has genuine GNU C++ at its disposal; even if this turns out to not be the root cause of your problems, it doesn't seem a good thing either.

The log also indicates that you're suffering from the typical boost library ailment; using `LIBS="-lboost_system -lboost_thread"` in the -/configure command line may help.

**Comment by j6thomps** [comment] 2015-10-28 11:54
Hi c-lipka,

I have tried including the line LIBS="-lboost_system -lboost_thread" when compiling povray from source, but the build fails when checking if the C compiler works, rather than checking whether the boost environment works.

Programs
--------
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/j6thomps/Downloads/povray-3.7-stable':
configure: error: C compiler cannot create executables
See `config.log' for more details

As for the problem of clang responding when gcc is called, apparently this is the expected behaviour for OS X 10.9 and higher version (https://support.enthought.com/hc/en-us/articles/204469410-OS-X-GCC-Clang-and-Cython-in-10-9-Mavericks). gcc and g++ are present on my system, installed via Homebrew, and the directory where they are located is in $PATH, but they are not being called by ./configure, and I am not sure how to make it call them, or whether that is a good idea (see point 2 in the first comment in the linked article).

**Comment by c-lipka** [comment] 2015-10-28 12:09
I consider it a bad move from Apple to disguise a different C/C++ compiler as GCC in the first place (which is what they seem to have been done previously already), and to disguise clang as the disguised other C/C++ compiler certainly doesn't help.

The proper solution would be to fix the compiler detection in autoconf/automake (or Homebrew's fork thereof) so that it defaults to clang on Mac OS X.

Until then, you may try explicitly requesting the use of clang, by passing `CC=clang` and `CXX=clang` to the ./configure script.

**Comment by j6thomps** [comment] 2015-10-28 12:47
I've tried using the the CC=clang and CXX=clang options but the build continues to fail. I have determined that boost_thread is not preset after a Homebrew install of boost, only boost_thread-mt exists in /usr/local/lib. I have replaced -lboost_thread with -lboost_thread-mt in the LIBS variable, but I still get the same end result:

checking whether the boost thread library is usable... no
configure: error: in `/Users/j6thomps/Downloads/povray-3.7-stable':
configure: error: cannot link with the boost thread library

Could the fact that boost_thread is missing indicate a problem with boost? I'm not sure how to check for problems with the install of the boost library. I've uninstalled and reinstalled it using Homebrew since I started investigating this problem, but it did not report any problems during the installation.

**Comment by c-lipka** [comment] 2015-10-28 12:55
Make sure you also have boost_system installed and accessible; problems with this library may be reported as problems with the boost_thread library. If you needed to append `-mt` for the thread library, chances are you also need to append the same extension to the other as well.

**Comment by j6thomps** [comment] 2015-10-28 15:36
Ok, I've checked that boost_system is present in /usr/local/lib, as is boost_system-mt. I've tried running ./configure with both options (-mt and not -mt for boost_system) in the LIB variable, but I get the same error. I've also tried using the flag --with-boost-thread=boost_thread-mt (recommended here: http://news.povray.org/povray.unix/thread/%3C52bf1526$1@news.povray.org%3E/), which can apparently help with this problem, via the ./configure command:

./configure COMPILED_BY="Jordan Thompson <j6thomps@gmail.com>" CC=clang CXX=clang --with-boost-thread=boost_thread-mt LIBS="-lboost_system -lboost_thread"

but this leads to:

checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/Users/j6thomps/Downloads/povray-3.7-stable':
configure: error: C compiler cannot create executables
See `config.log' for more details

replacing -lboost_thread with -lboost_thread-mt returns to the previous situation, where the net result is configure: error: cannot link with the boost thread library

**Comment by DomT4** [comment] 2015-10-30 00:11
Any chance `povray` silently needs a lower version of Boost than we ship?

**Comment by c-lipka** [comment] 2015-10-30 09:57
Slim chance, unless you still ship any pre-5.0 version of boost. Those tended to be less troublesome for us.

**Comment by DomT4** [comment] 2015-10-31 03:53
It's possible the Boost detection logic in the formula itself is having some issues, I guess. I presume nobody else in this thread is having any build trouble?

**Comment by j6thomps** [comment] 2015-11-03 14:05
Update: A new version of boost (1.59) has been added to homebrew. I have upgraded to this version and tried installing povray again, but it looks like I am getting the same error. The gist of my latest install is here: https://gist.github.com/6631303a9aa4f3a41529

**Comment by c-lipka** [comment] 2015-11-03 15:20
That looks pretty different to me though: This time, ./configure neither reported problems with the compiler, nor with the boost thread library, and concluded that `POV-Ray 3.7.0 has been configured.`. There seem to be problems with unmatched double quotes though, in both ./configure line 15723 (and following) as well as later in some unidentified file during make. If you could publish the `./configure` script as generated by prebuild.sh on your system, that might help diagnose the issue.

**Comment by j6thomps** [comment] 2015-11-03 15:33
That gist is from attempting to install povray inside homebrew. If I use the ./configure script outside of homebrew, I again get a failure to link the boost library:

checking for boostlib >= 1.37... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread-mt... yes
checking whether the boost thread library is usable... no
configure: error: in `/Users/j6thomps/Downloads/povray-3.7-stable':
configure: error: cannot link with the boost thread library
See `config.log' for more details

So it would seem that homebrew is getting further in the installation process, and encountering a different problem than an installation from source.

Does anyone on this thread know how to access the ./configure script used by Homebrew?

**Comment by metasim** [comment] 2015-11-30 02:09
Having the same problem (also 10.9.5).

**Comment by samrussell** [comment] 2015-12-09 08:30
This was caused by a typo in the formula, pull request removes this.

For those who are interested, this bug manifests itself under the install-man1 stanza in the Makefile, rendering $man1dir as "/usr/local/Cellar/povray/3.7.0.0_1/share/man"/man1" (note the trailing " after share/man)

**Comment by j6thomps** [comment] 2015-12-09 12:18
Thanks @samrussell , your edit to the povray.rb file fixes the problem, povray now installs successfully for me. Slightly annoyed at myself that I didn't realize the problem was that simple. Should I close this issue now or wait until this fix has made it in to the main Homebrew povray package?

**Comment by DomT4** [comment] 2016-01-06 00:40
Was fixed by https://github.com/Homebrew/homebrew/commit/9ee68c864165c6d82d991080ae5f5513cb9479e2.

**Closed by DomT4** 2016-01-06 00:40 UTC
