### ISSUE TITLE
boost-python failed to build on 10.10.3-x86_64

### ISSUE THREAD

**Issue by Marco93Antonio** [Homebrew/homebrew#38531] opened 2015-04-10 23:40 UTC
I'm having trouble building boost-python. Right before trying to build I updated CommandLineTools from xcode. 

Here's the gist link:
https://gist.github.com/anonymous/c5509494f87acd6df497

Here's the build output:

>>brew install boost-python
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-python-1.57.0.tar.bz2
v==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.57.0 --libdir=/usr/local/Cellar/boost-python/1.57.0/lib --with-libraries=python --with-py
==> ./b2 --build-dir=build-python --stagedir=stage-python python=2.7 --prefix=/usr/local/Cellar/boost-python/1.57.0 --libdir=/usr/local/Cellar/boost-p
...skipped <pbuild-python/boost/bin.v2/libs/python/build/darwin-4.2.1/release>libboost_python.dylib for lack of <pbuild-python/boost/bin.v2/libs/python/build/darwin-4.2.1/release>numeric.o...
...skipped <pstage-python/lib>libboost_python.dylib for lack of <pbuild-python/boost/bin.v2/libs/python/build/darwin-4.2.1/release>libboost_python.dylib...
...failed updating 108 targets...
...skipped 10 targets...
...updated 25 targets...

**Comment by tdsmith** [comment] 2015-04-11 00:13
The 6.3 headers are broken; you'll have to downgrade to 6.2.

**Comment by tdsmith** [comment] 2015-04-11 00:14
Previous CLT versions are available from http://developer.apple.com/downloads.

**Comment by tdsmith** [comment] 2015-04-11 00:16
Closing as duplicate of #38514.

**Closed by tdsmith** 2015-04-11 00:16 UTC
