### ISSUE TITLE
MU4E make error

### ISSUE THREAD

**Issue by poika** [Homebrew/homebrew#38601] opened 2015-04-13 02:40 UTC
EMACS=$(which emacs) brew install mu --with-emacs --HEAD
==> Installing dependencies for mu: autoconf, automake, libtool
==> Installing mu dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring autoconf-2.69.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.1M
==> Installing mu dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring automake-1.15.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
==> Installing mu dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtool-2.4.6.yosemite.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing mu
==> Cloning https://github.com/djcb/mu.git
Cloning into '/Library/Caches/Homebrew/mu--git'...
remote: Counting objects: 336, done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 336 (delta 45), reused 166 (delta 22), pack-reused 0
Receiving objects: 100% (336/336), 2.21 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (45/45), done.
Checking connectivity... done.
==> Checking out branch master
==> autoreconf -ivf
==> ./configure --prefix=/usr/local/Cellar/mu/HEAD --with-gui=none
==> make
1 error generated.
make[3]: *** [mu-msg-iter.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by xu-cheng** [comment] 2015-04-13 11:06
Please read the [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) and post all of the requested diagnostics, thanks!

**Comment by jacknagel** [comment] 2015-04-17 18:57
I tested this and it looks like this is the Xcode 6.3 __debug header thing, so closing as a duplicate of https://github.com/Homebrew/homebrew/issues/38514.

**Closed by jacknagel** 2015-04-17 18:57 UTC
Labels: needs response
