### ISSUE TITLE
doxygen fails to build on 10.11

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#41710] opened 2015-07-14 16:10 UTC
[gist](https://gist.github.com/aw1621107/a41bd1ec234fa8a9f8c2)

qt is unlinked because it was compiling at that moment. Failed to compile, but I think there's an issue for that already.

Let me know if more info is needed

**Comment by DomT4** [comment] 2015-07-14 16:19
Not a 10.11 thing; Dupe of #39642. Should build fine without the clang option invoked.

**Closed by DomT4** 2015-07-14 16:19 UTC
Labels: 10.11

**Comment by aw1621107** [comment] 2015-07-14 16:31
I'm pretty sure I built it without any flags...

**Comment by aw1621107** [comment] 2015-07-14 16:33
Er, unless that is part of the formula? I'll check when I get back

**Comment by DomT4** [comment] 2015-07-14 16:50
Looks like you built it with the flag?

Normal compile is just `==> ./configure --prefix /usr/local/Cellar/doxygen/1.8.9.1`.

The Clang element only gets invoked if you choose it to do so:

```ruby
option "with-libclang", "Build with libclang support."

    if build.with? "libclang"
      args << "--with-libclang-static"
      llvm = Formula["llvm"]
      inreplace "configure" do |s|
        s.gsub! /libclang_hdr_dir=\".*$/, "libclang_hdr_dir=\"#{llvm.opt_include}\""
        s.gsub! /libclang_lib_dir=\".*$/, "libclang_lib_dir=\"#{llvm.opt_lib}\""
      end
    end
```

**Comment by aw1621107** [comment] 2015-07-14 17:41
Hmmm... I'll have to check. I tried both with and without clang, so I hope I didn't get the two mixed up. Give me ~40ish minutes

**Comment by aw1621107** [comment] 2015-07-14 18:52
[new gist](https://gist.github.com/aw1621107/a121a1374a33e7c2291f), running `brew gist-logs doxygen`. Not sure how that clang flag got there...

**Comment by DomT4** [comment] 2015-07-14 21:39
I'm still seeing the Clang usage?

```
./configure
--prefix
/usr/local/Cellar/doxygen/1.8.9.1
--with-libclang-static
```

It may be worth wiping out the old logs manually, doing a clean `brew install doxygen` and then doing another `gist-logs` if you hit failure.

**Comment by aw1621107** [comment] 2015-07-14 21:57
Yeah, I was wondering about that too. 100% sure that I didn't pass it in the initial command, though.

Where would I find the old logs? The doxygen folder isn't in the cellar, and I didn't see anything either in /usr/local or /private/tmp...

**Comment by aw1621107** [comment] 2015-07-14 22:02
Oh huh, it's working now. Strange... Guess cleaning things out was the right thing

**Comment by DomT4** [comment] 2015-07-14 22:09
Homebrew's default log location is `~/Library/Logs/Homebrew`.

Glad things are working as expected now.
