### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by egprentice** [Homebrew/homebrew#42557] opened 2015-08-06 15:35 UTC
Last login: Thu Aug  6 08:32:50 on console
egp:~ edprentice$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
egp:~ edprentice$ brew doctor
Your system is ready to brew.
egp:~ edprentice$ brew update
Already up-to-date.
egp:~ edprentice$

**Comment by dunn** [comment] 2015-08-06 15:37
Closing as a duplicate of #42553.

**Closed by dunn** 2015-08-06 15:37 UTC
