### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX Please report this bug

### ISSUE THREAD

**Issue by leegee** [Homebrew/homebrew#44942] opened 2015-10-14 11:03 UTC
```3:01:10 $ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:265:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `send'
/usr/local/Library/brew.rb:124
13:01:46 $
13:01:46 $ brew -v
Homebrew 0.9.5 (git revision ee13a; last commit 2015-10-14)
13:02:08 $
```

**Comment by bfontaine** [comment] 2015-10-14 12:06
Closing as a duplicate of #42553. Thank you for the report!

**Closed by bfontaine** 2015-10-14 12:06 UTC
