### ISSUE TITLE
Several verbs ignore naming conflicts in external taps

### ISSUE THREAD

**Issue by jawshooah** [Homebrew/homebrew#37846] opened 2015-03-18 23:52 UTC
I have a [custom tap](https://github.com/jawshooah/homebrew-nodenv) with formulae for OiNutter's version of [nodenv](https://github.com/OiNutter/nodenv) as an alternative to the unmaintained version in the main repository. After running `brew install jawshooah/nodenv/nodenv`, I get the following for various `brew <verb>` commands:

```
$ brew tap jawshooah/nodenv
Cloning into '/usr/local/Library/Taps/jawshooah/homebrew-nodenv'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 18 (delta 4), reused 16 (delta 2), pack-reused 0
Unpacking objects: 100% (18/18), done.
Checking connectivity... done.
Warning: Could not create link for jawshooah/nodenv/nodenv, as it
conflicts with Homebrew/homebrew/nodenv. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install jawshooah/nodenv/nodenv
Tapped 3 formulae


$ brew install jawshooah/nodenv/nodenv
==> Installing nodenv from jawshooah/homebrew-nodenv
==> Downloading https://github.com/OiNutter/nodenv/archive/v0.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/nodenv-0.2.0.tar.gz
==> Caveats
To enable shims and autocompletion add to your profile:
  if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

To use Homebrew's directories rather than ~/.nodenv add to your profile:
  export NODENV_ROOT=/usr/local/opt/nodenv
==> Summary
🍺  /usr/local/Cellar/nodenv/0.2.0: 29 files, 136K, built in 2 seconds


$ brew info jawshooah/nodenv/nodenv
nodenv: stable 0.2.0, HEAD
https://github.com/OiNutter/nodenv
/usr/local/Cellar/nodenv/0.2.0 (29 files, 136K)
  Built from source
From: https://github.com/jawshooah/homebrew-nodenv/blob/master/nodenv.rb
==> Caveats
To enable shims and autocompletion add to your profile:
  if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

To use Homebrew's directories rather than ~/.nodenv add to your profile:
  export NODENV_ROOT=/usr/local/opt/nodenv


$ brew info nodenv
nodenv: stable 0.3.3, HEAD
https://github.com/wfarr/nodenv
/usr/local/Cellar/nodenv/0.2.0 (29 files, 136K)
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nodenv.rb
==> Caveats
To enable shims and autocompletion add to your profile:
  if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi


$ brew outdated
nodenv (0.2.0 < 0.3.3)


$ brew upgrade
==> Upgrading 1 outdated package, with result:
nodenv 0.3.3
==> Upgrading nodenv
==> Downloading https://github.com/wfarr/nodenv/archive/v0.3.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/nodenv-0.3.3.tar.gz
==> Caveats
To enable shims and autocompletion add to your profile:
  if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
==> Summary
🍺  /usr/local/Cellar/nodenv/0.3.3: 17 files,  72K, built in 2 seconds
```

As you can see, `brew info nodenv` incorrectly reports that `nodenv`, not `jawshooah/nodenv/nodenv`, has been installed. Similarly, `brew outdated`  and `brew upgrade` treat the installed version of `jawshooah/nodenv/nodenv` as an outdated version of `nodenv`.

Is this intentional? I would expect Homebrew to be able to differentiate between formulae in the main repository and those installed from an external tap.

**Comment by jacknagel** [comment] 2015-03-19 00:37
>Is this intentional? I would expect Homebrew to be able to differentiate between formulae in the main repository and those installed from an external tap.

Well, it's intentional that `brew info <formula name>` can report info on formula with that name from a tap. Any formula named "nodenv" will share the same cellar location (e.g. `/usr/local/Cellar/nodenv`) regardless of the tap from which it originates. `brew info nodenv` will list them all.

The tap implementation is constantly evolving so these things may be addressed eventually (though not necessarily in the manner you expect, some things just haven't been decided yet). Commands are always going to accept an unqualified formula name. What will improve is our ability to do what the user expects in the face of ambiguity.

Right now I'm working to make it possible to read tap info from the install receipt and then instantiate the formula object from the correct tap, which will let us fix the `brew outdated`/`brew upgrade` case (e.g. if you have a nodenv from a tap that is older than the one in core, it won't be upgraded and replaced with the one from core).

**Comment by jawshooah** [comment] 2015-03-19 00:43
> Right now I'm working to make it possible to read tap info from the install receipt and then instantiate the formula object from the correct tap, which will let us fix the `brew outdated`/`brew upgrade` case (e.g. if you have a nodenv from a tap that is older than the one in core, it won't be upgraded and replaced with the one from core).

That's great to hear! I'd love it if users who install OiNutter's version could just run `brew upgrade` without it being overwritten with wfarr's.

But once you can read tap info from the install receipt, couldn't you also use that in `brew info` to prefer the installed version?

**Comment by mikemcquaid** [comment] 2015-03-19 12:02
> which will let us fix the brew outdated/brew upgrade case (e.g. if you have a nodenv from a tap that is older than the one in core, it won't be upgraded and replaced with the one from core).

@jacknagel The problem is I've heard users say they want exactly the opposite behaviour which is why it behaves the way it does. I don't think there's going to be a solution here that makes everyone happy; we'll need to decide whether the tap or version always takes precedence. I think the longer-term solution here will be that people have to "prioritise" taps if they want to override versions in core.

@jawshooah The best current solution to that is to use a different name e.g. `nodenv-oinutter`. I keep suggesting this to people but seemingly no-one wants to do it :wink:

**Comment by jacknagel** [comment] 2015-03-19 13:54
>The problem is I've heard users say they want exactly the opposite behaviour which is why it behaves the way it does. I don't think there's going to be a solution here that makes everyone happy; 

I think you've possibly misunderstood what I'm saying? If I `brew install some/tap/foo`, right now `brew upgrade foo` will always use the `foo` from core. This is an implementation accident that we've always intended to fix. I can't imagine users would expect the existing behavior.

**Comment by mikemcquaid** [comment] 2015-03-19 14:00
> I think you've possibly misunderstood what I'm saying? If I brew install some/tap/foo, right now brew upgrade foo will always use the foo from core. This is an implementation accident that we've always intended to fix. I can't imagine users would expect the existing behavior.

Oh yes, I see what you mean. Yes, that case I think should be fixed. The case I was saying is debatable is if the version in core is a newer version: should it upgrade or not?

**Comment by jawshooah** [comment] 2015-03-19 14:15
The case for nodenv is that the version in core and the version in my tap
are entirely separate products, developed independently and with no
intention of cross-compatibility, so it simply doesn't make sense to
upgrade to the one in core regardless of version number.

To your point about renaming the formula itself, normally I would agree
that this is fine, but there has already been talk, both here and on
wfarr's and OiNutter's repositories, of replacing the existing,
unmaintained version with OiNutter's. I'd link to the relevant
conversations, but I'm on mobile at the moment.

**Comment by jacknagel** [comment] 2015-05-28 02:31
I think most/all of this is fixed on master now.

**Comment by jawshooah** [comment] 2015-05-28 03:31
@jacknagel Indeed! `brew outdated` output no longer contains `nodenv`.

**Comment by jacknagel** [comment] 2015-05-28 13:11
OK, closing then. If there are specific remaining issues, please do file them individually so we can address them.

**Closed by jacknagel** 2015-05-28 13:11 UTC
