### ISSUE TITLE
Nim 0.12.0 package seems to have a problem!

### ISSUE THREAD

**Issue by oderwat** [Homebrew/homebrew#45958] opened 2015-11-13 10:06 UTC
There seems to be a problem with the current Nim 0.12.0 package (https://github.com/Homebrew/homebrew/commit/5d7008e74d5cf7ea28601b5310cf47195342a02f).

Details can be found [here](http://forum.nim-lang.org/t/1797) and [here](http://forum.nim-lang.org/t/1782)

Problem is:

`I installed Nim using Homebrew and it didn't install the file stdlib.nimble next to system.nim.`

**Comment by oderwat** [comment] 2015-11-13 10:09
I am not sure who really is maintaining that formular @jmcnevin @mikemcquaid ?

**Comment by mikemcquaid** [comment] 2015-11-13 10:10
Formulae are not maintained by individuals but by the entire community of Homebrew contributors. We'll investigate this.

**Comment by oderwat** [comment] 2015-11-14 02:39
The maintainers of Nim found that it is an error with the last release. Hopefully we get the 0.12.2 Release soon which will fix that. Until then it can be fixed by `touch /usr/local/Cellar/nim/0.12.0/nim/lib/stdlib.nimble`.

**Comment by apjanke** [comment] 2015-11-14 06:39
Is there something we could add to the formula's `test` block that would exercise Nim and reproduce the error/verify whether this is working? Or at least some example code that would demonstrate the problem? I can't really understand the issue from the discussion threads you linked to; I think they presume more Nim familiarity than I and probably the other Homebrew maintainers have.

It seems a little weird that this would require just `touch`ing an extra file, especially given that Nim has what looks like a pretty custom-generated install script. One commenter, "Araq" (don't know if they're a Nim maintainer) in [this thread](http://forum.nim-lang.org/t/1797) claims it's a packaging bug in Homebrew, not Nim. Homebrew is just calling `bootstrap.sh`/`build.sh` + `install.sh` from the distribution; are there extra steps needed?

**Comment by oderwat** [comment] 2015-11-14 15:23
@Araq (the creator of Nim)  already said that he was wrong with his assumption that it is a packager problem. It is wrong in this distribution version and therefor "his" fault :)

The problem indeed is resolved by adding this file. Because that file triggers a namespace change for the modules contained in that directory. 

The problem itself was, that a system module had no unique name so a user module with the same name suddenly stopped working.

You could update the formular to create that extra file if it is missing or just wait for the new distribution.

A test block could test if the Nim compiler actually works. I am not sure if that is done for other compilers. Especially if it is installed from a blob there are chances that the system it is installed onto can not use Nim as it relies on a c compiler (usually xcode) existing.

**Comment by apjanke** [comment] 2015-11-14 23:39
Okay, that makes sense.

Sounds like a simple enough fix, we may as well do it in the formula.

Yep, for other compilers we'll compile a simple example program. Can add that here, too. Would you be able to supply an example "Hello world!" program in Nim which depends on the `stdlib.nimble` file being present (so it can verify the fix for this bug)?

**Comment by oderwat** [comment] 2015-11-17 02:06
There is no problem for me to create a PR besides that I don't want to learn how to change a homebrew formular I will never use. Esp. since there will be a new release anyway which renders this problem obsolete.

**Comment by mikemcquaid** [comment] 2015-11-22 16:13
@oderwat Ok, closing.

**Closed by mikemcquaid** 2015-11-22 16:13 UTC
