### ISSUE TITLE
pip3 can’t update itself after upgrading to Python 3.5

### ISSUE THREAD

**Issue by jonnybarnes** [Homebrew/homebrew#43952] opened 2015-09-14 20:05 UTC
Running OS X El Capitan GM release.

Here’s what happens:

```
➜  ~  pip3 install --upgrade pip
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 5, in <module>
    import zlib
ImportError: No module named 'zlib'
```

**Comment by tdsmith** [comment] 2015-09-14 20:29
I expect this is a duplicate of #41085. The best current workaround is to install the Xcode Command Line Tools with `xcode-select --install`. Sorry for the trouble.

This manifestation is also reported as pypa/pip#3110.

**Closed by tdsmith** 2015-09-14 20:29 UTC

**Comment by jonnybarnes** [comment] 2015-09-14 21:14
Just confirming the following commands from the other thread worked for me:

```
sudo xcode-select -s /Applications/Xcode-beta.app
xcode-select --install
brew reinstall python3
```
