### ISSUE TITLE
openconnect 7.04 error about openssl

### ISSUE THREAD

**Issue by winds18** [Homebrew/homebrew#36641] opened 2015-02-08 04:39 UTC
```bash
d1_both.c(1112): OpenSSL internal error, assertion failed: s->d1->w_msg_hdr.msg_len + DTLS1_CCS_HEADER_LENGTH == (unsigned int)s->init_num
```

**Comment by mistydemeo** [comment] 2015-02-08 04:44
Could you please provide some more information? What were you doing when this issue occurred? What version of OS X are you on?

Can you provide the output of `brew gist-logs openconnect`, read the [troubleshooting guide](http://git.io/brew-troubleshooting), and follow the steps here?

**Comment by winds18** [comment] 2015-02-08 10:23
OS X's version is 10.10
when i use the openconnect it display this error
```brew gist-logs openconnect``` it display ```no logs```

**Comment by DomT4** [comment] 2015-02-08 21:20
I can't reproduce your error. Your ` brew doctor ` would be useful, as Misty indicated. Might be useful to get a ` brew info openssl ` and ` brew info openconnect ` as well.

**Comment by winds18** [comment] 2015-02-09 03:47
when i reinstall ```openssl``` there is no error, although i don't understand why, thank you for your answer.

**Comment by asparagui** [comment] 2015-02-10 04:39
Closing per inability to reproduce/user has solved issue.

**Closed by asparagui** 2015-02-10 04:39 UTC
Labels: needs response

**Comment by loic** [comment] 2015-02-11 06:10
Having the same issue, probably since the last update of openssl.

**Comment by loic** [comment] 2015-02-11 06:20
FWIW I just downgraded to https://www.openssl.org/source/openssl-1.0.1l.tar.gz and openconnect is happy again.

**Comment by jkizman** [comment] 2015-02-11 12:17
Adding "--no-dtls" helped for me

**Comment by DomT4** [comment] 2015-02-11 19:34
Reported upstream and "fixed" (by switching to GnuTLS, which is the upstream default) in #36745.

**Comment by dwmw2** [comment] 2015-02-16 09:56
The linkage problem in #36745 is something different. This one is probably caused by OpenSSL failing to care about Cisco's old broken pre-standard version of the DTLS protocol. I'm currently staring at this commit as the probable culprit: http://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=68039af3

**Comment by dwmw2** [comment] 2015-02-16 10:52
Fix at https://mta.openssl.org/pipermail/openssl-dev/2015-February/000698.html

**Comment by dwmw2** [comment] 2015-02-17 20:52
And https://mta.openssl.org/pipermail/openssl-dev/2015-February/000710.html

**Comment by dwmw2** [comment] 2015-02-18 14:03
The next OpenConnect release will refuse to build against OpenSSL 1.0.2 by default. As with other broken OpenSSL releases in the past, you'll have to configure with --without-openssl-version-check to avoid the sanity check.

You should only do that if you've applied the patches to fix the above two bugs, of course. They are now [RT#3703] (http://rt.openssl.org/Ticket/Display.html?id=3703&user=guest&pass=guest) and [RT#3711] (http://rt.openssl.org/Ticket/Display.html?id=3711&user=guest&pass=guest).
