### ISSUE TITLE
mysql failed to build on 10.10.1

### ISSUE THREAD

**Issue by tmatsuno** [Homebrew/homebrew#36206] opened 2015-01-25 13:50 UTC
https://gist.github.com/92cda4bba3f08662e3a2

built with this command option and displayed these error.
```
$ brew reinstall --universal --with-archive-storage-engine --with-blackhole-storage-engine --with-local-infile --with-memcached mysql
==> Reinstalling mysql with --universal, --with-blackhole-storage-engine, --with-archive-storage-engine, --with-local-infile, --with-memcached
==> Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.22.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-5.6.22.tar.gz
==> Downloading https://github.com/mysql/mysql-server/pull/3.diff
######################################################################## 100.0%
==> Patching
patching file cmake/ssl.cmake
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql/5.6.22 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DMYSQL_DATADIR=/usr/local/var/mysql -DINSTALL_INCLUDEDIR=i
==> make
/usr/bin/ranlib libstrings.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: libstrings.a(longlong2str.c.o) has no symbols
/usr/local/Cellar/cmake/3.1.1/bin/cmake -E cmake_progress_report /tmp/mysql-V4pkX9/mysql-5.6.22/CMakeFiles  94 95 96 97
[  9%] Built target strings
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
mysql-connector-c++ cannot build with mariadb  (https://github.com/Homebrew/homebrew/issues/34578)
mysql failed to build on 10.10 (https://github.com/Homebrew/homebrew/issues/33448)
Packages with --with-mysql option not satisfied by mariadb (https://github.com/Homebrew/homebrew/issues/32973)
```

**Comment by jacknagel** [comment] 2015-01-25 15:36
Dupe of #33448

**Closed by jacknagel** 2015-01-25 15:36 UTC
