### ISSUE TITLE
wget fails to install on 10.6.8

### ISSUE THREAD

**Issue by ssreekanth** [Homebrew/homebrew#47556] opened 2015-12-31 10:35 UTC
pod2man complains about ```--utf8``` as an unknown option.

```
==> Downloading http://ftpmirror.gnu.org/wget/wget-1.17.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/wget-1.17.1.tar.xz
==> ./configure --prefix=/usr/local/Cellar/wget/1.17.1 --sysconfdir=/usr/local/etc --with-ssl=openssl --with-libssl-prefix=/usr/local/opt/openssl --disable-iri --disable-pcre
==> make install
Last 15 lines from /Users/sreekanth/Library/Logs/Homebrew/wget/02.make:
  /usr/bin/install -c wget '/usr/local/Cellar/wget/1.17.1/bin'
Making install in doc
make[3]: Nothing to be done for `install-exec-am'.
/bin/sh /private/tmp/wget20151231-20456-1ljxr8f/wget-1.17.1/build-aux/install-sh -d /usr/local/etc
./texi2pod.pl -D VERSION="1.17.1" ./wget.texi wget.pod

 ../build-aux/install-sh -c -d '/usr/local/Cellar/wget/1.17.1/share/info'
 /usr/bin/install -c -m 644 ./wget.info '/usr/local/Cellar/wget/1.17.1/share/info'
 install-info --info-dir='/usr/local/Cellar/wget/1.17.1/share/info' '/usr/local/Cellar/wget/1.17.1/share/info/wget.info'
/usr/local/Library/ENV/4.3/pod2man --center="GNU Wget" --release="GNU Wget 1.17.1" --utf8 wget.pod > wget.1
Unknown option: utf8
make[3]: *** [wget.1] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recurs
```

**Comment by uwehermann** [comment] 2016-01-11 04:09
Cannot reproduce this as of today on 10.6.8, wget builds fine for me after the final fix from #46566.

**Comment by ssreekanth** [comment] 2016-02-24 23:39
I'm still seeing this issue on 10.6.8. It never worked for me!

**Comment by mistydemeo** [comment] 2016-02-24 23:41
Can you `brew update`, retry the installation, and then provide all of the [troubleshooting output](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md)? Thanks!

**Comment by ssreekanth** [comment] 2016-02-25 03:57
@mistydemeo here is the ouput
```
➜  ~ brew update
Already up-to-date.
➜  ~ brew update
Already up-to-date.
➜  ~ brew install wget
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Installing dependencies for wget: pod2man
==> Installing wget dependency: pod2man
==> Downloading https://archives.eyrie.org/software/perl/podlators-4.06.tar.xz
Already downloaded: /Library/Caches/Homebrew/pod2man-4.06.tar.xz
==> perl Makefile.PL PREFIX=/usr/local/Cellar/pod2man/4.06 INSTALLSCRIPT=/usr/local/Cellar/pod2man/4.06/bin INSTALLMAN1DIR=/usr/local/Cellar/pod2man/4.06/share/man/man1 INST
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.
==> Summary
/usr/local/Cellar/pod2man/4.06: 15 files, 212.1K, built in 5 seconds
==> Installing wget
==> Downloading http://ftpmirror.gnu.org/wget/wget-1.17.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/wget-1.17.1.tar.xz
==> ./configure --prefix=/usr/local/Cellar/wget/1.17.1 --sysconfdir=/usr/local/etc --with-ssl=openssl --with-libssl-prefix=/usr/local/opt/openssl --disable-iri --disable-pcr
==> make install
Last 15 lines from /Users/sreekanth/Library/Logs/Homebrew/wget/02.make:
  /usr/bin/install -c wget '/usr/local/Cellar/wget/1.17.1/bin'
Making install in doc
make[3]: Nothing to be done for `install-exec-am'.
/bin/sh /private/tmp/wget20160224-89144-ecesbn/wget-1.17.1/build-aux/install-sh -d /usr/local/etc
./texi2pod.pl -D VERSION="1.17.1" ./wget.texi wget.pod

 ../build-aux/install-sh -c -d '/usr/local/Cellar/wget/1.17.1/share/info'
 /usr/bin/install -c -m 644 ./wget.info '/usr/local/Cellar/wget/1.17.1/share/info'
 install-info --info-dir='/usr/local/Cellar/wget/1.17.1/share/info' '/usr/local/Cellar/wget/1.17.1/share/info/wget.info'
/usr/local/Library/ENV/4.3/pod2man --center="GNU Wget" --release="GNU Wget 1.17.1" --utf8 wget.pod > wget.1
Unknown option: utf8
make[3]: *** [wget.1] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
wget fails to install on 10.6.8 https://github.com/Homebrew/homebrew/issues/47556
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
➜  ~ brew gist-logs wget
Error: HTTP 403 Forbidden (expected 201)
```

**Comment by ilovezfs** [comment] 2016-02-27 01:23
@ssreekanth Is pod2man installed? Try uninstalling it first, and then installing wget, which should get and use the right pod2man at build time.

**Comment by ssreekanth** [comment] 2016-02-27 03:16
Yes, It was installed.. I did try uninstalling it earlier, before executing 'brew install wget'. This time, I removed all the cached files, tried it, but still no luck..

Here is the output -

```
➜  ~ brew install wget
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Installing dependencies for wget: pod2man
==> Installing wget dependency: pod2man
==> Downloading https://archives.eyrie.org/software/perl/podlators-4.06.tar.xz
######################################################################## 100.0%
==> perl Makefile.PL PREFIX=/usr/local/Cellar/pod2man/4.06 INSTALLSCRIPT=/usr/local/Cellar/pod2man/4.06/bin INSTALLMAN1DIR=/usr/local/Cellar/pod2man/4.06/share/man/man1 IN
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.
==> Summary
/usr/local/Cellar/pod2man/4.06: 15 files, 212.1K, built in 8 seconds
==> Installing wget
==> Downloading http://ftpmirror.gnu.org/wget/wget-1.17.1.tar.xz
==> Downloading from http://mirror.easthsia.com/gnu/wget/wget-1.17.1.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/wget/1.17.1 --sysconfdir=/usr/local/etc --with-ssl=openssl --with-libssl-prefix=/usr/local/opt/openssl --disable-iri --disable-p
==> make install
Last 15 lines from /Users/sreekanth/Library/Logs/Homebrew/wget/02.make:
  /usr/bin/install -c wget '/usr/local/Cellar/wget/1.17.1/bin'
Making install in doc
make[3]: Nothing to be done for `install-exec-am'.
/bin/sh /private/tmp/wget20160226-1558-1c5oynk/wget-1.17.1/build-aux/install-sh -d /usr/local/etc
./texi2pod.pl -D VERSION="1.17.1" ./wget.texi wget.pod

 ../build-aux/install-sh -c -d '/usr/local/Cellar/wget/1.17.1/share/info'
 /usr/bin/install -c -m 644 ./wget.info '/usr/local/Cellar/wget/1.17.1/share/info'
/usr/local/Library/ENV/4.3/pod2man --center="GNU Wget" --release="GNU Wget 1.17.1" --utf8 wget.pod > wget.1
 install-info --info-dir='/usr/local/Cellar/wget/1.17.1/share/info' '/usr/local/Cellar/wget/1.17.1/share/info/wget.info'
Unknown option: utf8
make[3]: *** [wget.1] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
wget fails to install on 10.6.8 https://github.com/Homebrew/homebrew/issues/47556
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
```

**Comment by ilovezfs** [comment] 2016-02-27 04:09
I'm wondering if you modified something related to your system perl, something in your brew installation, or something in your user's environment, since this seems to have been fixed for the other people who were seeing this.

Can you provide output for the following in a gist?
```
cd /usr/local
git status
git diff origin/master
brew config
which -a perl
which -a pod2man
env
ls -l /usr/bin/perl
```

You can also try building in a different user, or with an empty brew installation.

**Comment by ssreekanth** [comment] 2016-02-27 07:33
I'm not aware if I made any modification related to my system perl. Check [here](https://gist.github.com/ssreekanth/b6cd1a6475b254e5c632) for output of the above commands.

**Comment by frickler01** [comment] 2016-03-06 09:31
FWIW: Last time I checked I had the same error after clean setup. Can't provide logs now since `reinstall` needs to update openssl first, which is borked at the moment (#49814).

**Comment by ilovezfs** [comment] 2016-03-06 09:33
@frickler01 When was the "last time you checked"?

**Comment by frickler01** [comment] 2016-03-06 09:42
10 days ago when the issue was resurrected.

**Comment by frickler01** [comment] 2016-03-07 09:32
Okay, now that I can try building again, I found that `$HOMEBREW_PREFIX/bin/pod2man` does not exist. There is no `bin` in the Cellar.

After building pod2man manually there are `./blib/script/pod2man`and `./scripts/pod2man`, but those are not copied on installation. This is `Cellar/podman/4.06`:
```
Changes              Library              TODO
INSTALL_RECEIPT.json NOTES
LICENSE              README
```

**Comment by ilovezfs** [comment] 2016-03-07 10:50
@frickler01 Are you saying you can reproduce the issue? I started from nothing (i.e., the entirety of /usr/local removed) and couldn't reproduce it at all.

**Comment by frickler01** [comment] 2016-03-07 11:12
Just tested again with fresh `/usr/local` - still the same, no `bin/pod2man` anywhere.

**Comment by ilovezfs** [comment] 2016-03-07 11:18
@frickler01 That's not the question. Are you able to install wget?

**Comment by frickler01** [comment] 2016-03-07 11:28
Obviously not, since `make` falls back to system `pod2man` which doesn't understand utf8. Therfore yes, I can reproduce the issue.

**Comment by mikemcquaid** [comment] 2016-03-07 11:39
@frickler01 That's not the file it falls back to, it's https://github.com/Homebrew/homebrew/blob/master/Library/ENV/4.3/pod2man in the build environment.

**Comment by frickler01** [comment] 2016-03-07 11:50
Exactly, but look what's inside. It checks all options, doesn't find anything at `$HOMEBREW_PREFIX/bin/pod2man` (see above) and then just uses `/usr/bin/pod2man`, which in turn causes the utf8 error.

**Comment by ilovezfs** [comment] 2016-03-07 11:52
@frickler01 It's a build time dependency, which means it doesn't get linked in `bin` unless you do that yourself later because you want to. That is all normal. Can you come on IRC so we can debug this interactively?

**Comment by frickler01** [comment] 2016-03-07 11:55
Sure, IRC where exactly? http://irc.lc/ircnet/homebrew/?

**Comment by ilovezfs** [comment] 2016-03-07 11:56
https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew

i.e., freenode #machomebrew

**Comment by frickler01** [comment] 2016-03-07 15:08
Should be fixed now with #49857. Thanks a lot @ilovezfs for the patient help!

Seems to have been a race condition where some part of the makefile executed in wrong order and prevented copying files. Separating `make install` helps.

**Comment by ilovezfs** [comment] 2016-03-08 00:14
@ssreekanth Now that https://github.com/Homebrew/homebrew/pull/49857 is merged, do you mind verifying that it has fixed this issue for you? Thanks!

**Comment by ssreekanth** [comment] 2016-03-08 22:05
Verified that it works on my mac. Thanks @frickler01 & @ilovezfs !

**Closed** 2016-03-08 22:05 UTC
Labels: 10.6
