### ISSUE TITLE
`brew instal` is a valid command

### ISSUE THREAD

**Issue by hgiesel** [Homebrew/homebrew#48410] opened 2016-01-24 11:24 UTC
Don't know if this is by purpose or now, but `brew instal` seems to be a valid command. I don't why this would be on purpose, and I don't believe it is my system.

```sh
$ brew instal<tab>
instal   install  
$ brew instal bash-completion
Warning: bash-completion-1.3 already installed
```

Can somebody explain this to me?

**Comment by DomT4** [comment] 2016-01-24 11:25
Yeah, this is intentional. You can see the full list [here](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/global.rb#L51-L66).

We essentially try to be a little bit forgiving of typos or alternative words that mean the same thing or are used elsewhere and people may be familiar with.

**Comment by bfontaine** [comment] 2016-01-24 14:40
It’s normal that it’s a valid command; however I don’t think it should show up on completion.

**Comment by apjanke** [comment] 2016-01-24 18:36
Yeah, there's [special logic in Homebrew's own `brew_bash_completion.sh`](https://github.com/Homebrew/homebrew/blob/ec5a0a0879635e94111821aa2816a749547ea4cd/Library/Contributions/brew_bash_completion.sh#L596-L600) to not have `instal` show up as a command.

When I load `brew_bash_completion.sh` in my `bash` session, `instal` is not presented as a completion candidate. `brew instal<TAB>` or `brew ins<TAB>` both complete to `brew install` without presenting multiple options.

From hgiesel's example, it looks like they also have the `bash-completion` formula installed. Perhaps that is interacting with, or replacing, Homebrew's own bash completion definition.

**Comment by bfontaine** [comment] 2016-01-24 22:18
Same here. Zsh *does* suggest both `instal` and `install` though.

**Comment by apjanke** [comment] 2016-01-24 22:31
Ah. I get the same in `zsh` too, when using the completions that ship with Homebrew. (I normally use the `brew` plugin from OMZ, which provides different completions, and doesn't suggest `instal`.)

I get this, with `instal` and redundant commands.

```
$ brew in
info     -- information about a formula
install  -- install a formula
info     instal   install
```

Looks like it's because Homebrew's zsh completions [use `brew commands --include-aliases` without filtering like the bash completions do](https://github.com/Homebrew/homebrew/blob/ec5a0a0879635e94111821aa2816a749547ea4cd/Library/Contributions/brew_zsh_completion.zsh#L79).

hgiesel, which shell are you running, and where are you getting your `brew` completions from?

**Comment by UniqMartin** [comment] 2016-01-27 10:17
> I get this, with `instal` and redundant commands.

The `zsh` completion has seen even less love than the `bash` completion. I think this duplication is horrible and even worse than `instal` being suggested, but not being a `zsh` user I'm neither skilled enough nor motivated enough to fix this. (Do we even have `zsh` users among maintainers?)

**Comment by xu-cheng** [comment] 2016-01-27 10:24
> Do we even have zsh users among maintainers?

AFIK, me, Mike and Andrew use zsh in a regular basis.

> I think this duplication is horrible and even worse than instal being suggested,

If anyone can come up to solve conflicting problem from git during `brew update`, I would like to see we move bash and zsh completion script inside `share` folder(similar to `brew.1` manpage). So users will always use official completion script instead of the one from other third parties like OMZ.

**Comment by shrx** [comment] 2016-01-29 12:58
Why no `brew udpate` ?

**Comment by DomT4** [comment] 2016-01-29 16:23
> Do we even have zsh users among maintainers?

:wave:. I use the OMZ plugin though, so hadn't noticed this before.

> Why no brew udpate ?

People more frequently make typos towards the end of words rather than the start, generally. With `install` it's also possible because it ends with a double `l` people think they've pressed twice when it has only registered once.

**Comment by bfontaine** [comment] 2016-01-29 16:35
Also we’re not going to accept all typos :smile: We support `instal` only because `gem` does the same.

**Comment by chdiza** [comment] 2016-01-29 18:41
It would be nice if `brew` accepted the shortest initial substring sufficient to identify a subcommand (and anything longer) a la Vim.  E.g., `brew in`, `brew upd`, `brew upg`, `brew upgra`, `brew upgrad`, etc., without needing to hit TAB.

But I personally don't care because I've already made my own shell aliases/functions to handle my own cases.

**Comment by apjanke** [comment] 2016-01-29 18:53
> Do we even have zsh users among maintainers?

I'm a big `zsh` head too. I'm also an OMZ user, and I use their `brew` plugin, so I don't run in to this much either.

Revamping `brew`'s `zsh` completion support is on my list of things I'd like to do when I have some spare time.

> It would be nice if brew accepted the shortest initial substring sufficient to identify a subcommand

I don't know if I'm a fan of this, because `brew` is used in scripting contexts, and we do bug reporting using copies of command lines. Because additional commands could be introduced in the future, and because users and taps can define custom external commands, and we don't restrict command name substring relationships, there could be some ambiguity or non-reproducibility. If we require full command names in base `brew`, then `brew` command lines remain more copy-pasteable between different users and configurations. And are more readable for people reviewing bug reports, IMHO.

**Comment by UniqMartin** [comment] 2016-01-29 18:59
> It would be nice if `brew` accepted the shortest initial substring sufficient to identify a subcommand

Personally, I'm not a big fan of this behavior. I see two major drawbacks:

- This can easily break as new commands are added, making the built up muscle memory useless and would cause a lot of frustration while adjusting. Short aliases (made with the shell or with [`homebrew/aliases`](https://github.com/Homebrew/homebrew-aliases)) should be preferred, as they offer convenience but also predictability.

- To be sure to make the right decision we would need to enumerate all available commands on every invocation. That's possible, but we would have to scan quite a few locations given we allow for external commands from the `PATH` and from taps. This is less of a concern for programs like `gem` that are not extensible and thus have a fixed set of subcommands.

**Comment by UniqMartin** [comment] 2016-01-29 19:04
@xu-cheng @DomT4 @apjanke If `zsh` users tend to use the OMZ `brew` plugin and that is in much better shape than the completion file we ship, maybe it's a better idea to drop our official completion file?

**Comment by apjanke** [comment] 2016-01-29 19:37
> If zsh users tend to use the OMZ brew plugin and that is in much better shape than the completion file we ship, maybe it's a better idea to drop our official completion file?

Nah, we should pull in improvements from the OMZ plugin if they're useful, and maintain our own official completions. We're in a better position to write the "best" completion definition, keep it up to date with new options etc, and support run-time discovery of commands. The OMZ development cycle is very slow, and we have commit rights to our own repo, so we can get changes through quickly. And then the completion definition file will track the `brew` version, so the completion definition in the local system will always match the installed `brew`.

And then it'd be available to all Zsh users without requiring OMZ. OMZ is quite popular with `zsh` users, but by no means universal, and some users really do not want to use it. I don't think we should require OMZ for anything.

**Comment by DomT4** [comment] 2016-01-29 19:52
Yeah. Andrew contributes knowledge/commits/etc to OMZ pretty regularly as far as I've seen so I'll gladly defer to him on this but it's by no means a universal thing and there's a lot of people who prefer alternatives like Prezto and Antigen (two of the biggest alternatives AFAIK).

It can also be difficult to get things merged into OMZ quickly, so having that under our control is a nice bonus I'd be reluctant to walk away from completely.

**Comment by mikemcquaid** [comment] 2016-02-01 18:05
I don't use OMZ/Prezto/Antigen but do use ZSH fwiw.

**Comment by apjanke** [comment] 2016-03-19 01:54
Think we can close this out because the consensus is "works as intended; will add better zsh completions when we can", right?

**Comment by UniqMartin** [comment] 2016-03-19 02:38
I agree.

**Closed by UniqMartin** 2016-03-19 02:38 UTC
Labels: question
