### ISSUE TITLE
mkvtoolnix-gui in 8.2.0 missing (--with-qt5)

### ISSUE THREAD

**Issue by elexx** [Homebrew/homebrew#42480] opened 2015-08-05 06:10 UTC
After updating mkvtoolnix (Build from source with: --with-qt5) the `mkvtoolnix-gui` executable is missing. What did I wrong?

```
$ brew info mkvtoolnix
mkvtoolnix: stable 8.2.0 (bottled), HEAD
Matroska media files manipulation tools
https://www.bunkus.org/videotools/mkvtoolnix/
/usr/local/Cellar/mkvtoolnix/8.2.0 (39 files, 12M) *
  Built from source with: --with-qt5
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mkvtoolnix.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: libogg ✔, libvorbis ✔, boost ✔, libmatroska ✔, libebml ✔
Recommended: flac ✔, libmagic ✔
Optional: lzo ✔, wxmac ✔, qt5 ✔, gettext ✔
==> Options
[snip]
```
```
$ ls $(brew --prefix mkvtoolnix)/bin
mkvextract  mkvinfo  mkvmerge  mkvpropedit
```
```
$ brew doctor
Your system is ready to brew.
```

**Comment by DomT4** [comment] 2015-08-05 18:33
Can you `brew gist-logs mkvtoolnix` please? Wondering if the executable is built but not installed automatically or something.

**Comment by bouvin** [comment] 2015-08-05 20:45
I have the exact same problem (had the -gui with version 8.0.0, but it is gone with 8.2.0).
> brew gist-logs mkvtoolnix
https://gist.github.com/765267de8fe696e56402

**Comment by DomT4** [comment] 2015-08-05 20:50
Looks like this might be known upstream:

> checking for Qt 5.2.0 or newer... no: the platform plugins directory could not be found

https://github.com/mbunkus/mkvtoolnix/commit/0c066727224ed210d88c76898db870b330e087f3

Will look into it tonight.

**Comment by elexx** [comment] 2015-08-06 06:49
Not sure if you still need it, but this is the log of my installation
> brew gist-logs mkvtoolnix
> https://gist.github.com/61c2a0673b805cebd0ee

**Comment by DomT4** [comment] 2015-08-07 01:26
Sadly, the upstream commit did not fix the issue, even after applying it and regenerating the configure script with the autotools.

This is the (unpatched) part of `configure` that generates the answer as to whether or not Qt5 is available:

```shell
    case "$host" in
      *mingw*)  wanted_plugin=windows ;;
      *apple*)  wanted_plugin=cocoa   ;;
      *darwin*) wanted_plugin=cocoa   ;;
      *)        wanted_plugin=        ;;
    esac

    if test x"$wanted_plugin" != x; then
      plugins_dir=
      for dir in `echo $QT_LIBS | sed -e 's/-l^ *\( \|$\)//g' -e 's/-L//'` ; do
        if test -f "$dir/../plugins/platforms/libq${wanted_plugin}.a" ; then
          plugins_dir="$dir/../plugins"
          break
        fi
      done

      if test x"$plugins_dir" = x; then
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no: the platform plugins directory could not be found" >&5
$as_echo "no: the platform plugins directory could not be found" >&6; }
        have_qt=no
      else
        QT_LIBS="-L$plugins_dir/platforms -lq$wanted_plugin $QT_LIBS"
      fi
    fi
```

Some semi-possible issues:

1) There is no `.a` file of `libqcocoa` in `HOMEBREW_PREFIX/opt/qt5/plugins/platforms` - There's only a `libqcocoa.dylib` file. Upstream check `.a`, `.so` and `.dylib` for Boost so perhaps that's a minor bug. Nonetheless, when I replaced the `.a` with `.dylib` it didn't magically resolve the problem.

`test -f /usr/local/Cellar/qt5/5.5.0/lib/../plugins/platforms/libqcocoa.a` returns 1, whereas `test -f /usr/local/Cellar/qt5/5.5.0/lib/../plugins/platforms/libqcocoa.dylib` returns 0.


2) The `sed` command returns the answer `-F/usr/local/Cellar/qt5/5.5.0/lib -framework\ QtCore`.

In truth I'm a little lost here. I've written Makefiles but the whole autotools side of things I actively run away from at speed. If he doesn't mind the ping, @mbunkus's input could be incredibly useful.

**Comment by mbunkus** [comment] 2015-08-07 08:01
Hey,

> Sadly, the upstream commit did not fix the issue, even after applying
> it and regenerating the configure script with the autotools.

Please let me start with me not being a Mac user. Over the past two
months I've successfully installed Mac OS in a virtual machine, and I've
spent just enough time to compile everything myself so that I can
provide a dmg.

As I'm not a Mac user I'm also very hesitant to spend any time on this
at all. I support Windows and various shades of Linux and BSDs, but
that's about it.

The current status of configure reflects this: I've only ever tested the
detection of the platform plugin with my self-compiled Qt (and my
Windows cross-compilation environment, of course). This self-compiled Qt
is dynamically linked, and yes, that includes libqcocoa.dylib. See the
DMG at [1].

That being said: I'd be delighted to receive patches. Basically this
section of configure is just basic shell scripting and figuring out
which state the file system is in at.

You may get more interesting debug output by inserting

set -x

somewhere prior to the plugin detection code, e.g. directly in front of

>     case "$host" in

Don't forget to insert »set +x« after the section, too, otherwise you'll
be spammed with shell trace output :)

I don't have access to my VM at the moment, so sadly I cannot tell you
exactly how I run configure so that Qt is found properly. I think I
didn't have to add any command line option for Qt per se, only for other
libraries, but I may be wrong about this.

Kind regards,
mosu

[1]  https://www.bunkus.org/videotools/mkvtoolnix/macos/MKVToolNix-8.2.0.dmg

**Comment by bouvin** [comment] 2015-08-11 10:58
If it's any help, everything worked fine with mkvtoolnix 8.0.0, so something must have changed and broken in the transition to 8.2.0.

**Comment by mbunkus** [comment] 2015-08-15 14:15
Today I've released v8.3.0. In the process I tried to build my Mac DMG which failed – pretty much with the same error. So I investigated and started to wonder how I was ever able to get that 8.2.0 DMG out of the door.

Anyway. I've pushed two commits that fix the Qt situation for me. The first one, mbunkus/mkvtoolnix@943ee96fc92b0686386e549af331b6f2e32f864f, fixes one use of sed not to use GNU sed extensions as Mac OS's sed is a BSD-like sed.

The second commit, mbunkus/mkvtoolnix@c14a01aed6950820c5c03cc04abdfda4782fefe4, causes configure to only look for the platform plugin (libqcocoa.a in the Mac OS case) if MKVToolNix is compiled against a statically linked Qt. That's what configure should have done already, and that's why configure only looks for ….a and not for ….dylib.

Neither of those commits is part of 8.3.0, unfortunately, as those problems were solved shortly before I was done compiling all of my binaries for 8.3.0 and I didn't want to start over. You can cherry-pick them for 8.3.0, of course, and they will be part of all releases after 8.3.0.

**Comment by DomT4** [comment] 2015-08-15 16:48
Thanks for chasing up on this @mbunkus. Appreciate you being able to look at the problem.

No dice here on the changes sadly:

```
*** Not checking for wxWidgets: disabled by user request
checking for moc... using supplied /usr/local/opt/qt5/bin/moc
checking for the Qt version /usr/local/opt/qt5/bin/moc uses... 5.5.0
checking for uic... using supplied /usr/local/opt/qt5/bin/uic
checking for the Qt version /usr/local/opt/qt5/bin/uic uses... 5.5.0
checking for rcc... using supplied /usr/local/opt/qt5/bin/rcc
checking for the Qt version /usr/local/opt/qt5/bin/rcc uses... 5.5.0
checking for Qt 5.2.0 or newer... no: test program could not be compiled
checking for lconvert... /usr/local/opt/qt5/bin/lconvert

The mkvtoolnix configuration is complete.
Optional features that are built:
   * compiler optimizations (-O1)
   * pre-compiled headers
   * FLAC audio
   * libMagic file type detection
Optional features that are NOT built:
   * debugging information
   * full optimization: due to bug 11962 in LLVM/clang only -O1 will be used for optimization
   * profiling support
   * make a static build of the applications
   * GUIs (wxWidgets version)
   * GUIs (Qt version)
   * online update checks (via libcurl)
   * translations (gettext)
```

```
/usr/local/Cellar/mkvtoolnix/8.3.0/bin/mkvextract
/usr/local/Cellar/mkvtoolnix/8.3.0/bin/mkvinfo
/usr/local/Cellar/mkvtoolnix/8.3.0/bin/mkvmerge
/usr/local/Cellar/mkvtoolnix/8.3.0/bin/mkvpropedit
```

It may be that the Homebrew Qt5 build is laden with problems. There are some very significant issues with it that honestly make me want to revert it to the last stable version until Qt sort it out upstream, but people apparently heavily prefer a broken newer version of Qt5 rather than a functional previous stable version.

**Comment by DomT4** [comment] 2015-08-15 16:52
If anyone wants to try locally just to check I'm not borked, this is the diff to apply to your formula:

```diff
diff --git a/Library/Formula/mkvtoolnix.rb b/Library/Formula/mkvtoolnix.rb
index 666696a..6e2a129 100644
--- a/Library/Formula/mkvtoolnix.rb
+++ b/Library/Formula/mkvtoolnix.rb
@@ -1,15 +1,22 @@
 class Mkvtoolnix < Formula
   desc "Matroska media files manipulation tools"
   homepage "https://www.bunkus.org/videotools/mkvtoolnix/"
+  head "https://github.com/mbunkus/mkvtoolnix.git"

   stable do
-    url "https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-8.2.0.tar.xz"
-    sha256 "eb6d3d7a0254bb4326dccc9983418801783198cdf4a259f31261dab4e843a5c4"
+    url "https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-8.3.0.tar.xz"
+    sha256 "87bd82222995d35c310a426ed43e0b27cbfefa0caadcbcca8296787314affc37"

-    # Fix GUI builds when "--without-curl" is passed, which we do by default.
+    # Fix assumption sed will be GNU-sed rather than BSD-sed.
     patch do
-      url "https://github.com/mbunkus/mkvtoolnix/commit/5c56d6544ffc212ca39ac59f4ed98b4f04761de8.diff"
-      sha256 "52f0ee02111c85bf6381d86ccf6a5333f8a89aa717235e7f0f919d3f686af2fc"
+      url "https://github.com/mbunkus/mkvtoolnix/commit/943ee96fc.diff"
+      sha256 "e6aecf484c96f70352fc9227579f3af6141cf6688d0cf6aa7ae9e830318a56c9"
+    end
+
+    # Only look for a static plugin for Qt5 if Qt5 was built statically.
+    patch do
+      url "https://github.com/mbunkus/mkvtoolnix/commit/c14a01aed69508.diff"
+      sha256 "a892060a0efc62388acfd183aca1ed76f7945e18a9080ee9be95d043e977a55a"
     end
   end

@@ -20,16 +27,16 @@ class Mkvtoolnix < Formula
     sha256 "c5652c2e926937cb17b520e5aefc9b2bf2533af43a38c268568e4366c80cb126" => :mountain_lion
   end

-  head do
-    url "https://github.com/mbunkus/mkvtoolnix.git"
-    depends_on "automake" => :build
-    depends_on "autoconf" => :build
-    depends_on "libtool" => :build
-  end
-
   option "with-wxmac", "Build with wxWidgets GUI"
   option "with-qt5", "Build with QT GUI"

+  # These three deps need to be made head-only again on the
+  # next release after 8.3.0. Used in stable here to regenerate
+  # working configure for GUI detection when Qt5 is used.
+  depends_on "automake" => :build
+  depends_on "autoconf" => :build
+  depends_on "libtool" => :build
+
   depends_on "pkg-config" => :build
   depends_on :ruby => "1.9"
   depends_on "libogg"
@@ -92,10 +99,8 @@ class Mkvtoolnix < Formula
       args << "--disable-qt"
     end

-    system "./autogen.sh" if build.head?
-
+    system "./autogen.sh" # Should be if build.head? again after 8.3.0
     system "./configure", *args
-
     system "./drake", "-j#{ENV.make_jobs}"
     system "./drake", "install"
   end
```

**Comment by mbunkus** [comment] 2015-08-15 16:55
Well, you now have a different error message: the test program couldn't be compiled. You should be able to get more information from `config.log`. You can send it to me, too, if you want me to take a look at it: moritz@bunkus.org

**Comment by DomT4** [comment] 2015-08-15 20:42
@mbunkus Build logs, including `config.log` available here: https://gist.github.com/anonymous/f794b1324c696be50f6b

**Comment by mbunkus** [comment] 2015-08-15 21:05
config.log line 1047: looks like configure might mangle the output of `pkg-config`. Can you please post the output of `pkg-config --cflags Qt5Core,Qt5Gui,Qt5Widgets,Qt5Network` and `pkg-config --libs Qt5Core,Qt5Gui,Qt5Widgets,Qt5Network`?

**Comment by DomT4** [comment] 2015-08-15 21:24
This error may be related to the Qt 5.5.0 bug [here](https://bugreports.qt.io/browse/QTBUG-47162).

In response to your questons. CFLAGS:
```
-I/usr/local/Cellar/qt5/5.5.0/include/QtWidgets -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtGui -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtNetwork -I/usr/local/Cellar/qt5/5.5.0/include -I/usr/local/Cellar/qt5/5.5.0/include/QtCore -I/usr/local/Cellar/qt5/5.5.0/include
```

Libs:

```
-F/usr/local/Cellar/qt5/5.5.0/lib -framework\ QtWidgets -F/usr/local/Cellar/qt5/5.5.0/lib -framework\ QtGui -F/usr/local/Cellar/qt5/5.5.0/lib -framework\ QtNetwork -F/usr/local/Cellar/qt5/5.5.0/lib -framework\ QtCore
```

**Comment by mbunkus** [comment] 2015-08-15 21:26
Thanks. Alright, then configure does NOT mangle the output. Are you sure that the backslashes in the `-framework\ QtWidgets` arguments are correct? Looks to me like your `.pc` files for Qt are broken.

**Comment by DomT4** [comment] 2015-08-15 21:33
> Are you sure that the backslashes in the -framework\ QtWidgets arguments are correct?

They aren't, in the slightest. See the upstream bug report linked to. All of the `pc` files are generated to be something like:

```
prefix=/usr/local/Cellar/qt5/5.5.0
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include


Name: Qt5 WebKit
Description: Qt WebKit module
Version: 5.5.0
Libs: -F${libdir} '-framework QtWebKit ' 
Libs.private: -F/usr/local/Cellar/qt5/5.5.0/lib -F/usr/local/Cellar/qt5/5.5.0/lib -F/usr/local/Cellar/qt5/5.5.0/lib -F/usr/local/Cellar/qt5/5.5.0/lib -F/usr/local/Cellar/qt5/5.5.0/lib -F/usr/local/Cellar/qt5/5.5.0/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework Carbon -framework AppKit -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WebKit/release/libWebKit1.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WebKit/release -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WebKit2/release/libWebKit2.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WebKit2/release -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WebCore/release/libWebCore.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WebCore/release -lxml2 -lxslt -lz -framework IOSurface -framework CoreFoundation -lsqlite3 -framework IOKit -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/ThirdParty/ANGLE/release/libANGLE.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/ThirdParty/ANGLE/release -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/ThirdParty/leveldb/release/libleveldb.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/ThirdParty/leveldb/release -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/JavaScriptCore/release/libJavaScriptCore.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/JavaScriptCore/release -Wl,-force_load,/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WTF/release/libWTF.a -L/private/tmp/qt520150721-3789-oqto74/qt-everywhere-opensource-src-5.5.0/qtwebkit/Source/WTF/release -licucore -framework QtSensors -F/usr/local/Cellar/qt5/5.5.0/lib -framework QtCore -framework DiskArbitration -framework QtPositioning -framework QtQuick -F/usr/local/Cellar/qt5/5.5.0/lib -framework QtGui -framework QtQml -framework QtNetwork -framework QtMultimedia -framework QtWebChannel -framework QtSql -framework OpenGL -framework AGL  
Cflags: -I${includedir}/QtWebKit -I${includedir}
Requires: Qt5Core Qt5Gui Qt5Network
```

Essentially, 5.5.0 is a hilarious pain to link to via `pkg-config` at the moment. I did manage to reproduce the failure though on a Qt5 that hadn't wrapped `Libs: -F${libdir} '-framework QtWebKit ' ` and similar in breaking quotes.

**Comment by mbunkus** [comment] 2015-08-15 21:54
:( For what it's worth I've compiled Qt without frameworks for my own DMG. As I have close to zero Mac development experience I couldn't figure out what they would be useful for, and I figured it'd be easier not having to deal with them.

Just to confirm, this is something you'll have to fix on your end? Or do you still need my input at the moment?

**Comment by DomT4** [comment] 2015-08-15 22:08
Is there any practical way to feed `mkvtoolnix` information on where to find the necessary elements without it relying on `pkg-config`? If so we might be able to work around the issue like that.

Otherwise, we're probably stuck until some answer is found upstream for the strange quotes in `.pc` files saga, and various other Qt5 issues.

**Comment by mbunkus** [comment] 2015-08-15 22:23
Circumventing `pkg-config` won't be easy; the configure script pretty much relies on it working properly.

You could try using custom `.pc` files for those Qt modules. Put them in a directory and set `PKG_CONFIG_PATH` to it.

**Comment by bolsoncerrado** [comment] 2015-08-25 00:37
Mine just brewed and not appearing on Applications either:

Alex:8.2.0 alex$ brew info mkvtoolnix
mkvtoolnix: stable 8.2.0 (bottled), HEAD
Matroska media files manipulation tools
https://www.bunkus.org/videotools/mkvtoolnix/
/usr/local/Cellar/mkvtoolnix/8.2.0 (39 files, 12M) *
  Built from source with: --with-qt5
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mkvtoolnix.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: libogg ✔, libvorbis ✔, boost ✔, libmatroska ✔, libebml ✔
Recommended: flac ✔, libmagic ✔
Optional: lzo ✘, wxmac ✘, qt5 ✔, gettext ✘
==> Options
--with-gettext
	Build with gettext support
--with-lzo
	Build with lzo support
--with-qt5
	Build with QT GUI
--with-wxmac
	Build with wxWidgets GUI
--without-flac
	Build without flac support
--without-libmagic
	Build without libmagic support
--HEAD
	Install HEAD version
Alex:8.2.0 alex$ brew doctor
Your system is ready to brew.
Alex:8.2.0 alex$

**Closed** 2015-09-28 21:20 UTC

**Comment by DomT4** [comment] 2015-09-28 21:23
`brew update && brew upgrade qt5` and this should work again as expected. Should be fixed by the https://github.com/Homebrew/homebrew/commit/fdbb338f2274e093b96209e7ca3ff9bf5460714e commit.
