### ISSUE TITLE
New version of BibTool

### ISSUE THREAD

**Issue by adamliter** [Homebrew/homebrew#40559] opened 2015-06-10 15:54 UTC
`bib-tool.rb` is currently set up to install version 2.57 of [BibTool](http://www.gerd-neugebauer.de/software/TeX/BibTool/index.en.html), but there is a new version available: 2.60.

**Comment by DomT4** [comment] 2015-06-10 16:22
Would you be willing to [submit a PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) to update it? You only need to change the `url`, update the `sha` (preferably to `sha256`) and remove any `revision` in the main formula.

**Comment by adamliter** [comment] 2015-06-10 16:54
@DomT4 Yes, I am working on submitting a pull request. Trying to run `brew install bib-tool` with the updated URL and sha256 leads to:

    Error: Failure while executing: tar xf /Library/Caches/Homebrew/bib-tool-2.60.tar.gz

Would this be a problem with the zipped tar file that I should report to the maintainer? If I just download the zipped file myself and try to run `tar -xvf` on it, it will unzip, but it exits with:

    tar: Error exit delayed from previous errors.

I'm not terribly familiar with how `tar` and zipping files work, but my guess is that this is a problem with the archive, right?

**Comment by DomT4** [comment] 2015-06-10 17:27
Yeah, It's refusing to uncompress here as well:

```
gzip: unknown compression format
gtar: Child returned status 1
gtar: Error is not recoverable: exiting now
```

The contents of the tarball are there, so it isn't just filled with empty data:

```
~> tar -tzf BibTool-2.60.tar.gz
BibTool/README
BibTool/install.tex
BibTool/COPYING
BibTool/Changes.tex
BibTool/makefile.unx
BibTool/makefile.dos
BibTool/makefile.ata
BibTool/makefile.ami
BibTool/ToDo
BibTool/THANKS
BibTool/pxfile.man
BibTool/sbuffer.man
BibTool/Perl/bibtool.pl
BibTool/Tcl/bibtool.tcl
BibTool/main.c
BibTool/crossref.c
BibTool/database.c
BibTool/entry.c
BibTool/error.c
BibTool/expand.c
BibTool/init.c
BibTool/key.c
BibTool/macros.c
BibTool/names.c
BibTool/parse.c
BibTool/print.c
BibTool/pxfile.c
BibTool/record.c
BibTool/rewrite.c
BibTool/rsc.c
BibTool/s_parse.c
BibTool/symbols.c
BibTool/stack.c
BibTool/sbuffer.c
BibTool/tex_aux.c
BibTool/tex_read.c
BibTool/type.c
BibTool/version.c
BibTool/wordlist.c
BibTool/config.h
BibTool/include/bibtool/crossref.h
BibTool/include/bibtool/database.h
BibTool/include/bibtool/bibtool.h
BibTool/include/bibtool/config.h
BibTool/include/bibtool/entry.h
BibTool/include/bibtool/error.h
BibTool/include/bibtool/expand.h
BibTool/include/bibtool/general.h
BibTool/include/bibtool/init.h
BibTool/include/bibtool/key.h
BibTool/include/bibtool/keynode.h
BibTool/include/bibtool/macros.h
BibTool/include/bibtool/names.h
BibTool/include/bibtool/parse.h
BibTool/include/bibtool/print.h
BibTool/include/bibtool/pxfile.h
BibTool/include/bibtool/regex.h
BibTool/include/bibtool/record.h
BibTool/include/bibtool/resource.h
BibTool/include/bibtool/rewrite.h
BibTool/include/bibtool/rsc.h
BibTool/include/bibtool/s_parse.h
BibTool/include/bibtool/sbuffer.h
BibTool/include/bibtool/stack.h
BibTool/include/bibtool/symbols.h
BibTool/include/bibtool/tex_aux.h
BibTool/include/bibtool/tex_read.h
BibTool/include/bibtool/type.h
BibTool/include/bibtool/version.h
BibTool/include/bibtool/wordlist.h
BibTool/lib/biblatex.rsc
BibTool/lib/braces.rsc
BibTool/lib/check_y.rsc
BibTool/lib/default.rsc
BibTool/lib/field.rsc
BibTool/lib/improve.rsc
BibTool/lib/iso2tex.rsc
BibTool/lib/month.rsc
BibTool/lib/opt.rsc
BibTool/lib/sort_fld.rsc
BibTool/lib/tex_def.rsc
BibTool/doc/bibtool.1
BibTool/doc/bibtool.tex
BibTool/doc/bibtool.bib
BibTool/doc/bibtool.ist
BibTool/doc/bibtool-doc.sty
BibTool/doc/bibtool.tex
BibTool/doc/ref_card.tex
BibTool/doc/Makefile
BibTool/doc/config.tex
BibTool/doc/c_main.tex
BibTool/doc/c_lib.tex
BibTool/doc/c.tex
BibTool/doc/c_get.pl
BibTool/doc/make_version.pl
BibTool/regex-0.12/
BibTool/regex-0.12/doc/
BibTool/regex-0.12/doc/regex.cps
BibTool/regex-0.12/doc/regex.info
BibTool/regex-0.12/doc/Makefile
BibTool/regex-0.12/doc/regex.texi
BibTool/regex-0.12/doc/xregex.texi
BibTool/regex-0.12/doc/texinfo.tex
BibTool/regex-0.12/doc/Makefile.in
BibTool/regex-0.12/doc/regex.aux
BibTool/regex-0.12/doc/include.awk
BibTool/regex-0.12/AUTHORS
BibTool/regex-0.12/README
BibTool/regex-0.12/Makefile
BibTool/regex-0.12/NEWS
BibTool/regex-0.12/INSTALL
BibTool/regex-0.12/COPYING
BibTool/regex-0.12/regex.c
BibTool/regex-0.12/configure.in
BibTool/regex-0.12/config.log
BibTool/regex-0.12/Makefile.in
BibTool/regex-0.12/config.h
BibTool/regex-0.12/configure
BibTool/regex-0.12/ChangeLog
BibTool/regex-0.12/test/
BibTool/regex-0.12/test/test.h
BibTool/regex-0.12/test/main.c
BibTool/regex-0.12/test/g++malloc.c
BibTool/regex-0.12/test/emacsmalloc.c
BibTool/regex-0.12/test/xmalloc.c
BibTool/regex-0.12/test/printchar.c
BibTool/regex-0.12/test/psx-group.c
BibTool/regex-0.12/test/Makefile
BibTool/regex-0.12/test/psx-interf.c
BibTool/regex-0.12/test/alloca.c
BibTool/regex-0.12/test/malloc-test.c
BibTool/regex-0.12/test/test.c
BibTool/regex-0.12/test/iregex.c
BibTool/regex-0.12/test/syntax.skel
BibTool/regex-0.12/test/regexcpp.sed
BibTool/regex-0.12/test/tregress.c
BibTool/regex-0.12/test/psx-basic.c
BibTool/regex-0.12/test/getpagesize.h
BibTool/regex-0.12/test/Makefile.in
BibTool/regex-0.12/test/other.c
BibTool/regex-0.12/test/psx-generic.c
BibTool/regex-0.12/test/upcase.c
BibTool/regex-0.12/test/ChangeLog
BibTool/regex-0.12/test/psx-interv.c
BibTool/regex-0.12/test/psx-extend.c
BibTool/regex-0.12/test/fileregex.c
BibTool/regex-0.12/test/bsd-interf.c
BibTool/regex-0.12/test/debugmalloc.c
BibTool/regex-0.12/regex.h
BibTool/AutoConf/config.h.in
BibTool/AutoConf/makefile.in
BibTool/AutoConf/reconfig.h.in
BibTool/BibTcl/bibtcl.bib
BibTool/BibTcl/bibtcl.ltx
BibTool/BibTcl/bibtcl.tex
BibTool/BibTcl/bibtool.c
BibTool/BibTcl/bibtool.ist
BibTool/BibTcl/Makefile.in
BibTool/BibTcl/configure
BibTool/BibTcl/configure.in
BibTool/BibTcl/dina4.sty
BibTool/BibTcl/main.tcl
BibTool/BibTcl/README
BibTool/BibTcl/version.tex
BibTool/BibTcl/Makefile
BibTool/MSDOS/link.dj
BibTool/MSDOS/link.msc
BibTool/MSDOS/link.wat
BibTool/configure
BibTool/configure.in
BibTool/install-sh
BibTool/mkdirchain
BibTool/test/BUnit.pm
BibTool/test/makefile
BibTool/test/bib/x1.bib
BibTool/test/bib/xampl.bib
BibTool/test/bib/xampl_s.bib
BibTool/test/add_field.t
BibTool/test/apply_alias.t
BibTool/test/apply_include.t
BibTool/test/apply_modify.t
BibTool/test/bibtex_env_name.t
BibTool/test/bibtex_search_path.t
BibTool/test/bibtool.t
BibTool/test/bibtoolrsc.t
BibTool/test/check_rule.t
BibTool/test/clear_ignored_words.t
BibTool/test/count_all.t
BibTool/test/count_used.t
BibTool/test/default_key.t
BibTool/test/delete_field.t
BibTool/test/expand_macros.t
BibTool/test/extract_file.t
BibTool/test/ignored_word.t
BibTool/test/input.t
BibTool/test/key_base.t
BibTool/test/key_format.t
BibTool/test/key_make_alias.t
BibTool/test/key_number_separator.t
BibTool/test/line_breaking.t
BibTool/test/macro_file.t
BibTool/test/main.t
BibTool/test/new_field_type.t
BibTool/test/new_format_type.t
BibTool/test/output_file.t
BibTool/test/pass_comments.t
BibTool/test/print.t
BibTool/test/print_align_key.t
BibTool/test/print_all_strings.t
BibTool/test/print_comma_at_end.t
BibTool/test/print_entry_types.t
BibTool/test/print_equal_right.t
BibTool/test/print_indent.t
BibTool/test/print_line_length.t
BibTool/test/print_newline.t
BibTool/test/print_parentheses.t
BibTool/test/print_terminal_comma.t
BibTool/test/print_use_tab.t
BibTool/test/quiet.t
BibTool/test/resource.t
BibTool/test/rewrite_rule.t
BibTool/test/select.t
BibTool/test/select_by_string.t
BibTool/test/select_crossrefs.t
BibTool/test/sort.t
BibTool/test/suppress_initial_newline.t
BibTool/test/symbol_type.t
BibTool/test/tex_define.t
BibTool/test/verbose.t
```

It looks like there's a duplicate file, which could be causing the issue:

```
BibTool/doc/bibtool.tex
BibTool/doc/bibtool.tex
```

**Comment by adamliter** [comment] 2015-06-10 17:30
@DomT4 Thanks! I've notified the maintainer of BibTool. As soon as the problem is fixed, I'll edit the formula, test it out, and submit a pull request.

**Comment by ge-ne** [comment] 2015-06-10 18:10
The file on CTAN has been produced on Debian with gnutar and gnuzip. It unpacks on Debian and Windows without problems. There I can also see that the file format is recognized:

    -> file BibTool-2.60.tar.gz
    BibTool-2.60.tar.gz: gzip compressed data, from Unix, last modified: Tue Jun  9 09:04:23 2015

I don't know where bib-tool-2.60.tar.gz comes from. I am distributing BibTool-2.60.tar.gz only...

**Comment by mistydemeo** [comment] 2015-06-10 18:17
`bib-tool-2.60.tar.gz` is merely the file renamed by Homebrew, since the Homebrew package is named `bib-tool`.

I can decompress this tarball using gnutar, but not bsdtar. You can reproduce this on Debian by installing bsdtar via apt-get. Since OS X ships only bsdtar, we need to rely on the tarball being extractable using it.

**Comment by DomT4** [comment] 2015-06-10 18:17
> I don't know where bib-tool-2.60.tar.gz comes from

This is just because of Homebrew naming. Our formula is called `bib-tool`, so when we download the tarball we save it as `bib-tool-2.60.tar.gz` rather than the upstream `2.60.tar.gz`. Nothing aside the naming is changed.

**Comment by ge-ne** [comment] 2015-06-10 18:43
I have tried it with bsdtar. It is in fact a problem with the duplicate files. Acording to the man pages of bsdtar the command line option q must be used to overcome this deficiency.
Thus you can repackage BibTool.tar.gz or use the q option.
I have fixed the problem and pushed to github, but will not make a new release just for this fix.

**Comment by DomT4** [comment] 2015-06-10 19:26
We'll probably have to adopt [something like this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/freeimage.rb#L3-L9) for this version, then.

**Comment by adamliter** [comment] 2015-06-10 22:24
@DomT4 I naively tried something like the following, but it's not working.

```ruby
class BibToolDownloadStrategy < CurlDownloadStrategy
  def stage
     with_system_path { safe_system 'tar', 'xqf', cached_location }
     chdir
  end
end

class BibTool < Formula
  desc "Manipulates BibTeX databases"
  homepage "http://www.gerd-neugebauer.de/software/TeX/BibTool/index.en.html"
  url "http://www.gerd-neugebauer.de/software/TeX/BibTool/BibTool-2.60.tar.gz",
    :using => BibToolDownloadStrategy
  sha256 "db84b264df7c069b5b1c8e0778dc70f4e335cd1c39d711dcd65bae02df809ad1"

  bottle do
    sha1 "d5822fd899e1238c75964b7c0763dad2f24386e7" => :yosemite
    sha1 "dcaaf50c9992f1e1812845914ab3bd4b8be521de" => :mavericks
    sha1 "e0b9efe0a08a1c02a94ddd95fdfcef8863f1ad01" => :mountain_lion
  end

  def install
    system "./configure", "--prefix=#{prefix}", "--without-kpathsea"
    system "make"
    system "make", "install"
  end

  test do
    (testpath/"test.bib").write <<-EOS.undent
      @article{Homebrew,
          title   = {Something},
          author  = {Someone},
          journal = {Something},
          volume  = {1},
          number  = {2},
          pages   = {3--4}
      }
    EOS
    system "#{bin}/bibtool", "test.bib"
  end
end
```
This throws the following error:

```
==> Verifying bib-tool-2.60.tar.gz checksum
tar xqf /Library/Caches/Homebrew/bib-tool-2.60.tar.gz
Error: Empty archive
/usr/local/Library/Homebrew/download_strategy.rb:217:in `chdir'
/usr/local/Library/Formula/bib-tool.rb:4:in `stage'
/usr/local/Library/Homebrew/resource.rb:89:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:936:in `stage'
/usr/local/Library/Homebrew/formula.rb:534:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```
I'm guessing this might have something to do with the fact if I just download the tarball and try to run the following myself, nothing happens.

    tar xqf BibTool-2.60.tar.gz

On the other hand, doing the following works just fine and unpacks the contents into a directory called BibTool.

    tar xqf BibTool-2.60.tar.gz BibTool

So is there some variable like `cached_location` that I can pass to `with_system_path` to give it the directory that it should unpack to?

**Disclaimer**: it also might be the case that something else is causing this behavior and/or that there is a better way to do this. This is just my best educated guess. Some of this is honestly over my head. I'm not too familiar with Ruby or `tar`, and I've never looked at the internals of Homebrew before.

**Comment by adamliter** [comment] 2015-06-10 22:32
Now that I say that, maybe something else is causing the error ... I just actually looked at the contents of the BibTool directory after doing

    tar xqf BibTool-2.60.tar.gz BibTool

And it turns out that it only contains the README file.

**Comment by ge-ne** [comment] 2015-06-10 22:41
> On 11 June 2015 at 00:25 Adam Liter <notifications@github.com> wrote:

[...]

> I'm guessing this might have something to do with the fact if I just download
> the tarball and try to run the following myself, nothing happens.
> tar xqf BibTool-2.60.tar.gz

To me it appears that you don't tell tar that it should gunzip the file first.
I.e. the z option is missing: tar -xqzf BibTool-2.60.tar.gz

Just my 2 Cents

Gerd

**Comment by adamliter** [comment] 2015-06-10 22:53
@ge-ne On my machine, `tar -xqzf BibTool-2.60.tar.gz` does the the same thing as `tar xqf BibTool-2.60.tar.gz`—namely, nothing.

Similarly, `tar -xqzf BibTool-2.60.tar.gz BibTool` does the same thing as `tar xqf BibTool-2.60.tar.gz BibTool`—namely, unpack only the README file into the directory called BibTool.

This seems really odd to me, given that `tar xf BibTool-2.60.tar.gz` **will** unpack the directory, but it just exits with:

    BibTool/doc/bibtool.tex: Can't create 'BibTool/doc/bibtool.tex'
    tar: Error exit delayed from previous errors.

Like I said, I'm really not familiar with `tar`, though, so maybe I'm just missing something.

**Comment by adamliter** [comment] 2015-06-10 23:14
Ah, I understand the problem. After reading the entry for `-q` a little bit closer, it makes sense. It says:

```
-q (--fast-read)
             (x and t mode only) Extract or list only the first archive entry
             that matches each pattern or filename operand. [...]
```
So `tar xqf BibTool-2.60.tar.gz BibTool` just finds the first entry that matches "BibTool", which happens to be the README.

Doing something like `tar xqf BibTool-2.60.tar.gz *` does not seem to work, and, as far as I can tell, there is no way to get bsdtar to run quietly and not throw the error, which could have been a solution since `tar xf BibTool-2.60.tar.gz` does (sort of) work.

So I'm not sure what the best solution is. Do either of you have any thoughts, @mistydemeo or @DomT4?

**Comment by adamliter** [comment] 2015-06-11 01:57
So the following works, I think. I just submitted it as a pull request. It's a bit baroque, but oh well. If anyone can think of a better way of doing this, feel free to do that instead.

```ruby
class BibToolDownloadStrategy < CurlDownloadStrategy
  def stage
     with_system_path { safe_system 'tar', 'xqf', cached_location, 'BibTool/doc/bibtool.tex' }
     with_system_path { safe_system 'tar', 'xf', cached_location, '--exclude', 'BibTool/doc/bibtool.tex' }
     chdir
  end
end
```
Doing `tar xqf BibTool-2.60.tar.gz BibTool/doc/bibtool.tex` will grab the first copy of BibTool/doc/bibtool.tex, and then doing `tar xf BibTool-2.60.tar.gz --exclude BibTool/doc/bibtool.tex` will grab everything except BibTool/doc/bibtool.tex.

**Comment by DomT4** [comment] 2015-06-11 02:17
@adamliter Nice work chasing this one around. The workaround LGTM at least, but will let Misty et al. look over it as well.

**Comment by adamliter** [comment] 2015-06-11 02:19
Sounds good. Thanks for the help and the suggestions, @DomT4!

**Comment by DomT4** [comment] 2015-06-12 15:31
Closed via https://github.com/Homebrew/homebrew/commit/bab2916f7afe8aede0ae2e188018fcb529f760f2.

**Closed by DomT4** 2015-06-12 15:31 UTC
