### ISSUE TITLE
rotrrent v0.9.4 failed to build on OS X v10.10.3 with gcc v5.1.0

### ISSUE THREAD

**Issue by paramk** [Homebrew/homebrew#40046] opened 2015-05-24 11:28 UTC
```
==> Formula
Path: /usr/local/Library/Formula/rtorrent.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4586905e12d2cfaa045f01f02576e402dc75d9cc
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.1
CLT: N/A
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: 1.8.0_25
==> ENV
HOMEBREW_CC: gcc-5
HOMEBREW_CXX: g++-5
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/libtorrent/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/pkg-config/bin:/usr/local/opt/openssl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gcc/bin

Error: rtorrent 0.9.4 did not build
Logs:
     /Users/prem/Library/Logs/Homebrew/rtorrent/01.configure
     /Users/prem/Library/Logs/Homebrew/rtorrent/01.configure.cc
     /Users/prem/Library/Logs/Homebrew/rtorrent/02.make
     /Users/prem/Library/Logs/Homebrew/rtorrent/02.make.cc
     /Users/prem/Library/Logs/Homebrew/rtorrent/config.log

```

Find below links to additional log files

1. [01.configure][1]
2. [01.configure.cc][2]
3. [02.make][3]
4. [02.make.cc][4]
5. [config.log][5]

[1]: https://gist.github.com/paramk/341b13f6a0c74a0bdd9f
[2]: https://gist.github.com/paramk/d4b5bf192a41cbd5219a
[3]: https://gist.github.com/paramk/79158c76ad3bab46273b
[4]: https://gist.github.com/paramk/9025b1ade2ee70aa1cfb
[5]: https://gist.github.com/paramk/a00883519b573cc159c1

**Comment by DomT4** [comment] 2015-05-27 01:16
Can reproduce here. Reported upstream: https://github.com/rakshasa/rtorrent/issues/297

**Comment by denji** [comment] 2015-06-01 20:12
As we know GCC5 uses by default Gnu C++11/C11.

```
LD=gcc-5
AR=gcc-ar-5
NM=gcc-nm-5
RANLIB=gcc-ranlib-5
```

You can try this, maybe will work will work, llvm-`ld` is compatible with gcc-4.9.

**Comment by DomT4** [comment] 2015-07-23 05:39
Seems to be fixed by the latest GCC-5 release.

**Closed by DomT4** 2015-07-23 05:39 UTC
Labels: upstream issue
