### ISSUE TITLE
Issue with `:mpi` dependency

### ISSUE THREAD

**Issue by dpo** [Homebrew/homebrew#46553] opened 2015-12-01 21:48 UTC
This may be related to #46461 or not, but there is another issue with the `:mpi` dependency:
```
$ brew uninstall open-mpi
Uninstalling /usr/local/Cellar/open-mpi/1.10.1_1... (783 files, 22M)
$ brew uninstall mpich
Error: No such keg: /usr/local/Cellar/mpich
$ brew install mpich
==> Downloading https://homebrew.bintray.com/bottles/mpich-3.1.4_1.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpich-3.1.4_1.mavericks.bottle.tar.gz
==> Pouring mpich-3.1.4_1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/mpich/3.1.4_1: 850 files, 16M

$ brew install -v parmetis  # a formula that depends_on :mpi
==> Installing parmetis from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/parmetis: open-mpi
==> Installing homebrew/science/parmetis dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.

  mpich: because both install mpi__ compiler wrappers

Please `brew unlink mpich` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```
So `mpich` is no longer recognized as satisfying the `:mpi` dependency.

**Comment by dpo** [comment] 2015-12-02 18:03
ps: This is independent of whether `mpich` was installed from a bottle or built from source.

**Comment by mikemcquaid** [comment] 2015-12-04 15:15
Could you try sticking some debugging code in https://github.com/Homebrew/homebrew/blob/f7f8243b6bfc4cdc835be7f24253610befc355ea/Library/Homebrew/requirements/mpi_requirement.rb#L40-L51 and see which part is failing to match.

**Comment by dpo** [comment] 2015-12-04 22:04
I had already done that, and the strange thing is that `satisfy` returns `true`. I'm trying to trace the execution with a debugger, but not familiar enough with the core of Homebrew to know what's going on. However, here's a potential clue. If I change the `:mpi` dependency to a `:build` dependency, all is well.

**Comment by UniqMartin** [comment] 2015-12-16 05:01
Can you check if the issue still persists now that an updated `open-mpi` and `mpich` bottle/formula has landed? I followed the procedure you described in the first comment, but now `mpich` (built from source) was accepted as satisfying the `:mpi` requirement without any warning or error.

**Comment by dpo** [comment] 2015-12-16 19:23
The issue persists for me. Exactly the same behavior as above.

**Comment by UniqMartin** [comment] 2015-12-17 16:42
Unfortunately, I cannot reproduce this issue on my machine (running OS X 10.11.2), when starting from a clean Homebrew installation and compiling everything from source (because I'm not in `/usr/local`).

Here are the relevant parts of my transcript ([full transcript](https://gist.github.com/UniqMartin/29c109d772fa645054c0) as a Gist):

```
$ brew uninstall open-mpi
Uninstalling /opt/brewery/tests/Cellar/open-mpi/1.10.1_1... (783 files, 22M)

$ brew uninstall mpich
Error: No such keg: /opt/brewery/tests/Cellar/mpich

$ brew install mpich
==> Using the sandbox
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
[…]
🍵   /opt/brewery/tests/Cellar/mpich/3.2: 869 files, 16M, built in 15.6 minutes

$ brew install -v parmetis
==> Installing parmetis from homebrew/science
==> Installing dependencies for homebrew/science/parmetis: sphinx-doc, cmake, metis
[…]
==> Summary
🍵   /opt/brewery/tests/Cellar/parmetis/4.0.3_3: 12 files, 22M, built in 23 seconds

$ brew test parmetis
Testing homebrew/science/parmetis
==> Using the sandbox
==> mpirun -np 4 /opt/brewery/tests/Cellar/parmetis/4.0.3_3/bin/ptest /opt/brewery/tests/Cellar/parmetis/4.0.3_3/share/p
==> Test results are in ~/Library/Logs/Homebrew/parmetis.
```

What does `ls -lF $(brew --prefix)/bin/mpi*` print?

**Comment by dpo** [comment] 2015-12-17 16:50
Hm. I'm not sure what's going on. I'm on 10.9.
```
$ ls -lF $(brew --prefix)/bin/mpi*
lrwxr-xr-x  1 dpo  admin    30B Dec 17 11:44 /usr/local/bin/mpic++@ -> ../Cellar/mpich/3.2/bin/mpic++
lrwxr-xr-x  1 dpo  admin    37B Apr 22  2015 /usr/local/bin/mpicalc@ -> ../Cellar/libgcrypt/1.6.3/bin/mpicalc
lrwxr-xr-x  1 dpo  admin    29B Dec 17 11:44 /usr/local/bin/mpicc@ -> ../Cellar/mpich/3.2/bin/mpicc
lrwxr-xr-x  1 dpo  admin    36B Dec 17 11:44 /usr/local/bin/mpichversion@ -> ../Cellar/mpich/3.2/bin/mpichversion
lrwxr-xr-x  1 dpo  admin    30B Dec 17 11:44 /usr/local/bin/mpicxx@ -> ../Cellar/mpich/3.2/bin/mpicxx
lrwxr-xr-x  1 dpo  admin    31B Dec 17 11:44 /usr/local/bin/mpiexec@ -> ../Cellar/mpich/3.2/bin/mpiexec
lrwxr-xr-x  1 dpo  admin    37B Dec 17 11:44 /usr/local/bin/mpiexec.hydra@ -> ../Cellar/mpich/3.2/bin/mpiexec.hydra
lrwxr-xr-x  1 dpo  admin    30B Dec 17 11:44 /usr/local/bin/mpif77@ -> ../Cellar/mpich/3.2/bin/mpif77
lrwxr-xr-x  1 dpo  admin    30B Dec 17 11:44 /usr/local/bin/mpif90@ -> ../Cellar/mpich/3.2/bin/mpif90
lrwxr-xr-x  1 dpo  admin    31B Dec 17 11:44 /usr/local/bin/mpifort@ -> ../Cellar/mpich/3.2/bin/mpifort
lrwxr-xr-x  1 dpo  admin    30B Dec 17 11:44 /usr/local/bin/mpirun@ -> ../Cellar/mpich/3.2/bin/mpirun
lrwxr-xr-x  1 dpo  admin    31B Dec 17 11:44 /usr/local/bin/mpivars@ -> ../Cellar/mpich/3.2/bin/mpivars
```

**Comment by UniqMartin** [comment] 2015-12-17 16:54
Does it make a difference if you add `--build-from-source` to `brew install -v parmetis`?

**Comment by dpo** [comment] 2015-12-17 17:00
Yes it does. It builds from source with only `mpich` installed.

**Comment by UniqMartin** [comment] 2015-12-17 17:40
Thanks for the confirmation! I didn't realize this earlier, but the observed behavior makes sense and is correct. The error message could be clearer and we shouldn't even try installing a conflicting formula, but that's probably about it.

If a formula is installed from a bottle, it has already been compiled against a specific MPI implementation and that happens to be the default one (`open-mpi` in this case). Since the implementations are API compatible, but not ABI compatible, simply pouring a bottle built against a different MPI implementation would create problems. In this particular example you'd most likely get an error that libraries the bottled `parmetis` was linked against are missing (because Open MPI and MPICH use different library names), but in other cases the library names might be identical and the result would most likely be a crash.

However, if a formula is installed from source, then it can be built against any MPI implementation, even one that is not provided by Homebrew, as long as it satisfies the `:mpi` requirement.

**Comment by dpo** [comment] 2015-12-17 17:58
Yes, I see. That makes sense. I can already see the bug reports pouring in at homebrew/science though ;-). Many thanks for all your help in resolving this!

**Comment by UniqMartin** [comment] 2015-12-17 18:22
> I can already see the bug reports pouring in at homebrew/science though ;-).

I hope the situation isn't too bad. Otherwise we can still create a Homebrew-specific MPI FAQ, add stuff like my explanation from above to it, and maybe also link to it from relevant error messages and caveats.

**Closed by UniqMartin** 2015-12-17 18:22 UTC
