### ISSUE TITLE
brew install node is failing with SHA1 mismatch on Mac OSX Yosemite

### ISSUE THREAD

**Issue by sandy081** [Homebrew/homebrew#36707] opened 2015-02-10 18:31 UTC
Hey,
 
I am a new user of homebrew and was trying to install node using brew. I get the following error

brew install node
==> Installing node dependency: icu4c
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/icu4c-54.1.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 244dbb217c95a79f87a35df70aca493a05c9ff39
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/icu4c-54.1.yosemite.bottle.1.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading http://download.icu-project.org/files/icu4c/54.1/icu4c-54_1-src.tgz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 8c752490bbf31cea26e20246430cee67d48abe34
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/icu4c-54.1.tgz
To retry an incomplete download, remove the file above.

**Comment by zlorkovic** [comment] 2015-02-10 18:38
Have same problem.

**Comment by DomT4** [comment] 2015-02-10 18:46
Both: Please provide your ` brew doctor ` and ` brew config ` readouts. Thanks.

**Comment by DomT4** [comment] 2015-02-10 18:47
*(Note: Anything hosted by SourceForge is broken right now. SF is down again).*

**Comment by sandy081** [comment] 2015-02-10 18:50
Hey,

Here is the requested information -

brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4a4ecc0460baec04ec895500ff11d26aa2582b16
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit sandybridge
OS X: 10.10.2-x86_64
Xcode: N/A
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_71

brew doctor
Your system is ready to brew.

**Comment by topheman** [comment] 2015-02-10 19:23
I have the same problem trying to `brew install npm`.

Error :

==> Installing node dependency: icu4c
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/icu4c-54.1.yosemite.bottle.1.tar.gz

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "icu4c"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/icu4c-54.1.yosemite.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://download.icu-project.org/files/icu4c/54.1/icu4c-54_1-src.tgz
######################################################################## 100,0%
Error: SHA1 mismatch
Expected: 8c752490bbf31cea26e20246430cee67d48abe34
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/icu4c-54.1.tgz
To retry an incomplete download, remove the file above.

`brew config`

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4a4ecc0460baec04ec895500ff11d26aa2582b16
Last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: N/A
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.7.0_67

`brew doctor`

Your system is ready to brew.

**Comment by ikorin** [comment] 2015-02-10 19:26
Similar issue here:

➜ Downloads brew install pypy
Error: pypy-2.3.1 already installed
To install this version, first `brew unlink pypy'
➜ Downloads brew upgrade pypy
==> Upgrading 1 outdated package, with result:
pypy 2.5.0
==> Upgrading pypy
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/pypy-2.5.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/pypy-2.5.0.yosemite.bottle.tar.gz
Error: SHA1 mismatch
Expected: 54b80dd6f11ba20f01223473ec195d8a8b6afc6c
Actual: a2fd3379ea944f6b2f97fb0f79b7b85cb3e14d0b
Archive: /Library/Caches/Homebrew/pypy-2.5.0.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.0-src.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pypy-2.5.0.tar.bz2
==> Downloading https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.0-osx64.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pypy--bootstrap-64.tar.bz2
==> /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/bootstrap/bin/pypy /private/tmp/pypy-MxMGsX/pypy-2.5.0-src/rpython/bin/rpython -Ojit --shared --cc clang --verbose --make-jobs 8 targe
  File "/private/tmp/pypy-MxMGsX/pypy-2.5.0-src/bootstrap/lib-python/2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "/private/tmp/pypy-MxMGsX/pypy-2.5.0-src/rpython/translator/tool/pdbplus.py", line 29, in preloop
    raise NoTTY("Cannot start the debugger when stdout is captured.")
NoTTY: Cannot start the debugger when stdout is captured.

READ THIS: http://git.io/brew-troubleshooting


➜ Downloads brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4a4ecc0460baec04ec895500ff11d26aa2582b16
Last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: N/A
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_25

**Comment by ikorin** [comment] 2015-02-10 19:29
I've tried to download the package manually:

➜ Downloads wget https://downloads.sf.net/project/machomebrew/Bottles/pypy-2.5.0.yosemite.bottle.tar.gz
--2015-02-10 11:28:57--  https://downloads.sf.net/project/machomebrew/Bottles/pypy-2.5.0.yosemite.bottle.tar.gz
Resolving downloads.sf.net... 54.230.5.216, 54.192.7.112, 54.192.7.205, ...
Connecting to downloads.sf.net|54.230.5.216|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name 'downloads.sf.net'.
To connect to downloads.sf.net insecurely, use `--no-check-certificate'.

**Comment by DomT4** [comment] 2015-02-10 19:29
Alright, the ` node ` from bottle and the ` icu4c ` from bottle *and* from source are all confirmed failures because of the Sourceforge downtime. There's not much we can do about that but wait for SF to pop back up. You're seeing the SHA failures because when SF goes down it tends to send back HTML files rather than the expected tarball, which obviously doesn't match the expected SHA.

If it's urgent, do ` brew install node --without-icu4c --build-from-source `. Otherwise, all we can do is wait it out. SF is usually back up within a few hours.

> File "/private/tmp/pypy-MxMGsX/pypy-2.5.0-src/rpython/translator/tool/pdbplus.py", line 29, in preloop
raise NoTTY("Cannot start the debugger when stdout is captured.")
NoTTY: Cannot start the debugger when stdout is captured.

This is unrelated, and potentially worth opening a new issue about. @tdsmith may know more on the PyPy failure there.

**Comment by mistydemeo** [comment] 2015-02-10 19:31
See #36707 - Sourceforge is down. It will likely be back in a few hours.

@ikorin Can you file a new issue for the pypy issue, please? Thanks!

**Comment by mistydemeo** [comment] 2015-02-10 19:31
(Rather, see #36703 - sorry)

**Closed by mistydemeo** 2015-02-10 19:31 UTC

**Comment by tdsmith** [comment] 2015-02-10 19:39
@ikorin Please include the output of `brew gist-logs pypy` with the new ticket.

**Comment by elizaschel** [comment] 2015-02-10 19:59
Having the same issue. How can we know when SF is back up?

**Comment by sandy081** [comment] 2015-02-10 20:31
@DomT4 - Thanks for the update.
Infact, brew install node --without-icu4c --build-from-source worked.

**Comment by ikorin** [comment] 2015-02-10 20:32
> @ikorin Please include the output of brew gist-logs pypy with the new ticket.

Done #36709
