### ISSUE TITLE
newt 0.52.18

### ISSUE THREAD

**Issue by isamuelson** [Homebrew/homebrew#36256] opened 2015-01-27 04:26 UTC

**Comment by mikemcquaid** [comment] 2015-01-27 08:09
Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/wiki/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged)

Thanks!

**Comment by isamuelson** [comment] 2015-01-27 17:10
i see there is an issue with this package that both the current version and the new one 0.52.18 are looking for the include folder on the system python (which is not found...)

in configure.ac 

PYTHONVERS=$(ls /usr/include/python*/Python.h 2> /dev/null | sed 's|.*\(python[[0-9]]*\.[[0-9]]*\).*|\1|g' | tr '\n' ' ')
  AC_MSG_RESULT([$PYTHONVERS])

any advice on hope to patch this file? also how to get the homebrew path for the include folder?

**Comment by isamuelson** [comment] 2015-01-27 19:13
i filed a bug on fedora to fix this. https://bugzilla.redhat.com/show_bug.cgi?id=1186486

**Comment by tdsmith** [comment] 2015-02-13 03:34
I don't think this is the cause of #30252; the problem is that newt is explicitly linking to libpython and shouldn't. Please let me know if I've misunderstood. Thanks!

**Closed by tdsmith** 2015-02-13 03:34 UTC
Labels: upstream issue
