### ISSUE TITLE
Can not install i2p due to outdated Xcode 

### ISSUE THREAD

**Issue by zagorulkinde** [Homebrew/homebrew#35982] opened 2015-01-17 19:11 UTC
gist here:
https://gist.github.com/0ca9118f28af99a13751

**Comment by zagorulkinde** [comment] 2015-01-17 19:46
And after upgrading:

Dmitrys-MBP:~ Dmitry$ brew install i2p
==> Installing i2p from privacysolutions/homebrew-i2p
==> Downloading https://github.com/PrivacySolutions/i2pd/archive/0.3.0-homebrew.
Already downloaded: /Library/Caches/Homebrew/i2p-0.3.0.tar.gz
==> Patching
==> make /usr/local/Cellar/i2p/0.3.0 install
block_d:
^
2 errors generated.
make: *** [obj/aes.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/privacysolutions/homebrew-i2p/issues

These open issues may also help:
Can not install i2p due to outdated Xcode  (https://github.com/Homebrew/homebrew/issues/35982)

**Comment by DomT4** [comment] 2015-01-19 12:19
> If reporting this issue please do so at (not Homebrew/homebrew):
https://github.com/privacysolutions/homebrew-i2p/issues

If updating Xcode doesn't work, there's nothing more obvious there that could be the problem, so I'd nudge this towards https://github.com/privacysolutions/homebrew-i2p/issues as directed instead.

**Comment by adamv** [comment] 2015-01-21 16:41
Duplicate of https://github.com/PrivacySolutions/homebrew-i2p/issues/1

**Closed by adamv** 2015-01-21 16:41 UTC

**Comment by jeroenubbink** [comment] 2015-03-20 11:57
Why is this a duplicate if the other issue is closed with a link to this one?

**Comment by mikemcquaid** [comment] 2015-03-20 11:58
It isn't.

**Comment by jeroenubbink** [comment] 2015-03-20 12:00
Hmm i see now.. Somehow i got confused by the icon at the bottom.. apologies
