### ISSUE TITLE
Luarocks does not work?

### ISSUE THREAD

**Issue by gibiansky** [Homebrew/homebrew#42889] opened 2015-08-13 06:19 UTC
I have had trouble with `luarocks` after installing the `lua` package. The trouble is documented [here](http://stackoverflow.com/questions/31671134/unable-to-install-package-using-luarocks-on-osx), and the fix is to change `@@HOMEBREW_PREFIX@@` to the output of `brew --prefix` in `brew --prefix/etc/luarocks52/config-5.2.lua`. 

My `brew doctor` output is as following, but I think it is irrelevant mostly (the one relevant bit is that I do not have a standard brew install directory):
```
Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!
Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install libyaml sqlite

Run `brew missing` for more details.
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /Users/silver/dev/homebrew/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/Users/silver/dev/homebrew/sbin:$PATH"' >> ~/.zshrc
```

**Comment by mikemcquaid** [comment] 2015-08-13 07:53
CC @DomT4 for thoughts

**Comment by DomT4** [comment] 2015-08-13 17:09
This was a temporary screw up that was caused by our problem relocating text files. Xu fixed it a week or two ago now. Essentially the fix is to do:

```
rm /usr/local/etc/luarocks52/config-5.2.lua && brew reinstall lua
```

**Comment by DomT4** [comment] 2015-08-13 22:44
Closing as fixed, but feel free to let us know if you hit any further issues. Thanks!

**Closed by DomT4** 2015-08-13 22:44 UTC
Labels: lua
