### ISSUE TITLE
devd build is broken

### ISSUE THREAD

**Issue by llimllib** [Homebrew/homebrew#50179] opened 2016-03-17 01:38 UTC
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?

### Bug reports:

Installing devd completes successfully, but the binary does not work:

```
$ brew install devd
==> Downloading https://homebrew.bintray.com/bottles/devd-0.4.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/devd-0.4.el_capitan.bottle.tar.gz
==> Pouring devd-0.4.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/devd/0.4: 5 files, 14.0M

$ devd -ol .
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x4574fe0, 0xc820654030)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/rjeczalik/notify.(*stream).Start(0xc82059cb80, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:131 +0x270
github.com/rjeczalik/notify.(*fsevents).watch(0xc820599f20, 0xc820616480, 0x2c, 0x1b00, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/rjeczalik/notify/watcher_fsevents.go:206 +0x313
github.com/rjeczalik/notify.(*fsevents).Watch(0xc820599f20, 0xc820616480, 0x2c, 0x1b0000001b00, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/rjeczalik/notify/watcher_fsevents.go:230 +0x51
go.(*struct { github.com/rjeczalik/notify.watcher; github.com/rjeczalik/notify.recursiveWatcher }).Watch(0xc820591500, 0xc820616480, 0x2c, 0xc800001b00, 0x0, 0x0)
	<autogenerated>:47 +0x7b
github.com/rjeczalik/notify.(*recursiveTree).Watch(0xc820581090, 0xc820616480, 0x2c, 0xc82059e9c0, 0xc820602944, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/rjeczalik/notify/tree_recursive.go:288 +0xc04
github.com/rjeczalik/notify.Watch(0x7fff5fbff951, 0x1, 0xc82059e9c0, 0xc820602944, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/rjeczalik/notify/notify.go:64 +0x7d
github.com/cortesi/modd/watch.Watch(0xc820602960, 0x1, 0x1, 0xbebc200, 0xc82059e960, 0x45f2280, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/cortesi/modd/watch/watch.go:301 +0x145
github.com/cortesi/devd.Route.Watch(0x0, 0x0, 0x462d9d8, 0x1, 0x5a134f0, 0xc820602720, 0xc82059e900, 0x0, 0x0, 0x0, ...)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/cortesi/devd/watch.go:19 +0x197
github.com/cortesi/devd.WatchRoutes(0xc8205957d0, 0x5a13968, 0xc82059cb00, 0x0, 0x0, 0x0, 0x5a13128, 0xc82059c7c0, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/cortesi/devd/watch.go:61 +0x1c8
github.com/cortesi/devd.(*Devd).Router(0xc820084480, 0x5a13520, 0xc82059c7c0, 0xc820595950, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/cortesi/devd/server.go:277 +0x6ac
github.com/cortesi/devd.(*Devd).Serve(0xc820084480, 0x4639a50, 0x9, 0x0, 0x0, 0x0, 0x5a13520, 0xc82059c7c0, 0xc8205efe40, 0x0, ...)
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/src/github.com/cortesi/devd/server.go:312 +0x1c8
main.main()
	/private/tmp/devd20160228-12313-1oua6n0/devd-0.4/cmd/devd/devd.go:244 +0x6ea0
```

There are no logs:

```
$ brew gist-logs devd
Error: No logs.
```

**Comment by apjanke** [comment] 2016-03-17 03:41
I can reproduce when installing from bottle on my OS X 10.9.5 box. `devd -o .` and `devd -l .` are okay, but `devd -ol .` gives me the same "go pointer to go pointer" error.

I installed the binary distribution from [their releases page](https://github.com/cortesi/devd/releases/tag/v0.4) and `devd -ol .` worked using it.

The Homebrew `go` formula has been updated since the `devd` release. I rebuilt from source using `brew install -s devd`. Same problem.

Maybe it's an issue with a library. That `github.com/rjeczalik/notify` package that's in the stack trace closest to the error has been [updated for "Go 1.6 CGO rules"](https://github.com/rjeczalik/notify/commit/c237b5bd375bb4e6a263211aba2e1b485304db2e) since we built this. I'll try bumping that resource version and see if it fixes things.

**Comment by llimllib** [comment] 2016-03-17 03:45
@apjanke: thanks for taking a look, I had the same experience with it working after installing the binary distribution from the releases page. The notify thing sounds very plausible.

**Comment by apjanke** [comment] 2016-03-17 03:47
Yep, tried it now and it seems to work. Bumping the jeczalik/notify lib dependency to the latest version fixes the crash for me. I'm putting in a PR to do so: #50181.

**Comment by apjanke** [comment] 2016-03-17 04:58
I merged the PR. If you do a `brew update && brew upgrade`, you should have a working `devd -ol .` now. Mind testing it out?

**Closed** 2016-03-17 05:00 UTC

**Comment by llimllib** [comment] 2016-03-17 12:59
Works perfectly now. Thanks for the quick fix!

**Comment by apjanke** [comment] 2016-03-17 13:19
No prob. Thanks for reporting.
