### ISSUE TITLE
brew doctor Error: No such file or directory

### ISSUE THREAD

**Issue by jfreeze** [Homebrew/homebrew#40797] opened 2015-06-16 22:25 UTC
brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 526ef67d3ce9229fd6cb91963e2afce0d32fb7ae
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.2
CLT: 7.0.0.0.1.1433655009
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/jimfreeze/.rvm/rubies/ruby-2.2.2/bin/ruby
Java: N/A

brew doctor -d
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/coreutils.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/findutils.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/cloog-ppl015.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/gmp4.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/libmpc08.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libxslt.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/mpfr2.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/autoconf.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/automake.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/bash-completion.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/freetype.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/ghostscript.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/heroku-toolbelt.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/highlight.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/imagemagick.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/jbig2dec.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/jpeg.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libevent.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libgpg-error.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libksba.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libpng.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libtiff.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libtool.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libxml2.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libyaml.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/little-cms2.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/lua.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/nmap.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/node.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/ossp-uuid.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/phantomjs.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/postgresql92.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/ppl011.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/tmux.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/tree.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/wget.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/wxmac.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
Error: No such file or directory
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `collect!'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:40:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:918:in `__check_linked_brew'
/usr/local/Library/Homebrew/cmd/doctor.rb:931:in `block in check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:930:in `select'
/usr/local/Library/Homebrew/cmd/doctor.rb:930:in `check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:1236:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1234:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1234:in `doctor'
/usr/local/Library/brew.rb:149:in `<main>'

**Comment by bitprophet** [comment] 2015-06-16 22:37
This looks like a dupe of #40781

**Comment by jfreeze** [comment] 2015-06-16 22:40
I'm happy to add this on to that, but all the suggestions under #40781 did
not fix the problem.

On Tue, Jun 16, 2015 at 4:37 PM, Jeff Forcier <notifications@github.com>
wrote:

> This looks like a dupe of #40781
> <https://github.com/Homebrew/homebrew/issues/40781>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Homebrew/homebrew/issues/40797#issuecomment-112594095>
> .
>



-- 
Dr. Jim Freeze, Ph.D.
(m) 512 949 9683

**Closed** 2015-06-16 23:09 UTC
