### ISSUE TITLE
Homebrew incorrectly flags public repository as a private one

### ISSUE THREAD

**Issue by giacecco** [Homebrew/homebrew#40487] opened 2015-06-08 10:48 UTC
See https://github.com/dinkypumpkin/homebrew-get_iplayer/issues/1 . I used this tap before and have realised of this issue while installing a new laptop. The maintainer reckons it is problem your side. I cannot attach the output of ```brew gist-logs <formula name>``` as I can't get to that stage. The output of ```brew config``` and ```brew doctor``` are [here](https://gist.github.com/giacecco/171fe6db3b5580490d52). Thanks,

G.

**Comment by xu-cheng** [comment] 2015-06-08 13:40
It's caused by incorrect use of `not` in [this line](https://github.com/Homebrew/homebrew/blob/d869e887a230832326deae08a2ba451280380a7e/Library/Homebrew/cmd/tap.rb#L88). This should be fixed after #40486 is merged.

**Comment by xu-cheng** [comment] 2015-06-08 14:15
Since #40486 is in still long way before merging. I decide to do a quick fix in 80dd62fc6fed8e9b231e7d4a836f38efa4ffc9ab.

Thanks for the report.

**Closed** 2015-06-08 14:15 UTC
Labels: bug

**Comment by giacecco** [comment] 2015-06-08 14:22
Great thanks, all sorted.
