### ISSUE TITLE
ffmpeg (re)install fails on --enable-*

### ISSUE THREAD

**Issue by shimmyshack** [Homebrew/homebrew#43075] opened 2015-08-18 21:40 UTC
#update: ffmpeg et al.  built without errors with the same configure string as I was setting in the ffmpeg.rb formula file, in a session where I had exported the same PKG_CONFIG_PATH string, (which wasn't being picked up by brew despite being an env var in the session window where I was running brew reinstall -v ffmpeg --with-......)

#update 2: for those with a similar problem, I was not aware that you can force your environmental vars to be passed to brew. I found this instruction on the [liquidsoap issues](https://github.com/drfill/homebrew-liquidsoap/issues/12) site, where the poster was having the same errors where brew is asking whether PKG_CONFIG_PATH is set and everything is fine, the OP had tried everything, and the maintainer of liquidsoap was asking whether it was brew or him!
YMMV: 

    brew install --env=std ffmpeg --with-libass etc... 

Hi

Default ffmpeg builds fine in 100seconds, but no other options will install.

    brew update
    brew doctor

all fine, but running 

    brew reinstall ffmpeg --with-*

configure flags doesn't change what is compiled into the ffmpeg binary, in fact the configure command executed by brew is identical whatever brew reinstall --with-* command is executed.

eg.
    brew reinstall -v ffmpeg --with-libass

installs nothing more than the default.

All libraries are present,

    pkg-config --list-all

contains all of them, and

    pkg-config --print-errors libass

shows no errors for example.

I changed the ffmpeg.rb script until I had convinced myself that the problem is real.

    brew gist-logs ffmpeg 

produces 
**Error: HTTP 404 Not Found (expected 201)**

Next I tried editing the formula

    brew edit ffmpeg

to explicitly push --enable-* flags into the configure command, hard coding 

    args << "--enable-libass"

inside ffmpeg.rb formula, results in errors when executing

    brew install -v ffmpeg

(./configure now has --enable-libass hard coded so no need to explicitly set --with-libass)

**Error: libass not found using pkg-config**

Changing PKG_CONFIG_PATH in my bash_profile makes no difference. My bash_profile has a script which generates a long list of the correct include locations, just to be sure, but this is not exposed to Brew's environment when building.

Can anyone throw any light on this, and it's solution please.

**Comment by tdsmith** [comment] 2015-08-19 03:59
You can see a list of options that the Homebrew formula provides by running `brew info ffmpeg`.

**Comment by shimmyshack** [comment] 2015-08-19 05:08
Yes. (They come from the Formulas directory from the file called ffmpeg.rb that I mention having to edit)

None of them were being picked up by brew.

**Comment by tdsmith** [comment] 2015-08-19 05:13
I'm not sure from your description whether this is expected behavior or not because I'm not sure exactly what changes you made. Homebrew intentionally does not pass build-related environment variables into the build environment. superenv tries to configure the build environment so that only libraries which have been declared as a dependency with `depends_on` are visible to the build.

**Comment by shimmyshack** [comment] 2015-08-19 05:29
Initially no changes were made.

Even I followed the recommendation to enable the non free libaac by running the command given at the end of a default ffmpeg install

    brew install ffmpeg

(With all the libraries ready present on my system) it failed. No extra library was added. That's definitely not expected behaviour.

I hacked the ffmpeg formula to see *why* there was no change because the output of the failed build wasn't informative. By customising the configure line manually I could see that it was libraries that couldn't be found.

This wasn't expected behaviour either as all the libraries are visible to pkgconfig and were in the pkg_config_path - indeed they were installed by brew.

So brew installs packages which are dependencies of other brew packages but brew later cannot allow those packages to be seen... I didn't think this was right at all. In the end I started to notice a trend 

PKG_CONFIG_PATH??

So I just built it myself and it worked first time, I was using brew to manage dependencies but this time for some reason no dice.

**Comment by shimmyshack** [comment] 2015-08-19 05:31
I should add I have the config.log if it would be of use.

**Comment by tdsmith** [comment] 2015-08-19 05:36
PKG_CONFIG_PATH will consist only of packages which have been declared as dependencies with a `depends_on` declaration. Packages declared as `optional` will only be included in PKG_CONFIG_PATH if --with-[package-name] is provided to `brew install` on the command line. --with options provided to `brew install` will only be processed if Homebrew understands them; options are not directly passed through to configure.

**Comment by shimmyshack** [comment] 2015-08-19 05:39
Yes I've read the code of the ffmpeg.rb file

It's why I raise this as an issue

But the options I wanted were all in the file so it's moot.

**Comment by tdsmith** [comment] 2015-08-19 05:49
Which behavior did you think was incorrect?

**Comment by shimmyshack** [comment] 2015-08-19 06:00
Ok maybe we are talking at odds.

installed "default" ffmpeg using brew

    brew install ffmpeg

As my puter has been doing this a while it has a great deal of libraries so.. all the little green ticks were there  when I ran

    brew info ffmpeg

This is the output from ( the path is from memory so excuse me if it's incorrect)

    /usr/local/Library/Formula/ffmpeg.rb 

so brew says "you have the libraries ready which ones do you want)


and yet using for instance (and from memory picking on brews own advice because of the license restrictions)

    brew reinstall ffmpeg --with-faac

Fails to install libfaac, (you can choose any library supported by brew in this manner because we know it doesn't just pass all --enable-such-and-such through but has a list in ffmpeg.rb)

So does that sound as incorrect to you as it does to me?

**Comment by tdsmith** [comment] 2015-08-19 06:44
If `brew reinstall ffmpeg --with-faac` does not build against libfaac, yes, that is a bug. It works for me, though.

Can you share the output of `brew gist-logs ffmpeg` after running `brew reinstall ffmpeg --with-faac`?

**Comment by drewlustro** [comment] 2015-08-31 23:25
I wanna throw in my hat here and note I've experienced similar recently (OS X 10.10.5).

Either `--with-faac` doesn't actually produce a `faac` enabled binary, or homebrew's notes when you type `brew info ffmpeg` don't reflect the used build options correctly.

Like, ill see a √ checkmark next to `faac`, but then homebrew will suggest that if I want faac support, i should reinstall with `--with-fdk-aac`

When `ffmpeg` is built with the gpl (and other licensing) flags turned on, does it automatically mess with the `--enable-nonfree` option?

**Comment by tdsmith** [comment] 2015-08-31 23:26
> homebrew's notes when you type brew info ffmpeg don't reflect the used build options correctly.

This is correct.

**Comment by drewlustro** [comment] 2015-08-31 23:27
@tdsmith so that's a known issue?

**Comment by tdsmith** [comment] 2015-08-31 23:28
That interface isn't intended to display what options were used for the build; it displays which possible dependencies are installed. If options were used you'd see something like this:

```
tim@rocketman$ brew info numpy
homebrew/python/numpy: stable 1.9.2 (bottled), HEAD
http://www.numpy.org
/usr/local/Cellar/numpy/1.9.2_1 (1379 files, 29M) *
  Built from source with: --with-python3
```

**Comment by drewlustro** [comment] 2015-08-31 23:30
Ah i see. Anyhow, I experienced similar difficulty as OP.

Although the struggles with ffmpeg might actually be related to `ffmpeg2theora`, which complains quite a bit and borks when transcoding AAC to Theora and then finally blames ffmpeg.

**Comment by tdsmith** [comment] 2015-08-31 23:31
Can you describe the problem you're having and how to reproduce it?

**Comment by drewlustro** [comment] 2015-08-31 23:42
My apologies. I think the issue is actually with `ffmpeg2theora`. I've since moved past the issue because I recompiled ffmpeg `--with-fdk-aac` and used it directly and that worked. Apologies for the confusion.

**Comment by tdsmith** [comment] 2015-09-01 01:34
No worries. I'll close this ticket; OP, please let us know if there's a reproducible test case for a bug involving this formula.

**Closed by tdsmith** 2015-09-01 01:34 UTC

**Comment by shimmyshack** [comment] 2015-09-01 06:29
Tim,

I'm not sure what detail I could add to my original post(s) that would
assist you further.

The issue was easily reproducible for me (and other homebrew users have had
sudden unexplained issues with other home-brew software that seem related
to the same root cause), in the end, rather than battle with homebrew's
ffmpeg,  I had to move on.

As mentioned, I simply built my own ffmpeg with the same configure line
that failed within homebrew (without altering any libraries or
dependencies), I will periodically built my own ffmpeg from now on until I
get around to testing homebrew's ffmpeg again, probably on reinstall of my
other mac.

I just don't have time to waste debugging, or indeed reporting faults,
especially if the report is minutely examined for defects without the point
ever been taken.

**Comment by brion** [comment] 2015-10-01 06:36
This is definitely biting me when trying to enable various options for ffmpeg; libraries such as lame and theora are not being found during the configure stage:

```
$ brew reinstall ffmpeg --with-lame --with-theora
==> Reinstalling ffmpeg with --with-theora
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.8.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ffmpeg-2.8.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.8 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --hos
Last 15 lines from /Users/brion/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-opencl
--enable-libx264
--enable-libmp3lame
--enable-libvo-aacenc
--enable-libxvid
--enable-libtheora
--enable-vda

ERROR: libmp3lame >= 3.98.3 not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Added Libsnappy support to FFMPEG Formula https://github.com/Homebrew/homebrew/pull/42022
```

Add --env=std and it works:

```
$ brew reinstall --env=std ffmpeg --with-lame --with-theora
==> Reinstalling ffmpeg with --with-theora
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.8.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ffmpeg-2.8.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.8 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=/usr/bin/cl
==> make install
==> Caveats
FFmpeg has been built without libfaac for licensing reasons;
libvo-aacenc is used by default.
To install with libfaac, you can:
  brew reinstall ffmpeg --with-faac

You can also use the experimental FFmpeg encoder, libfdk-aac, or
libvo_aacenc to encode AAC audio:
  ffmpeg -i input.wav -c:a aac -strict experimental output.m4a
Or:
  brew reinstall ffmpeg --with-fdk-aac
  ffmpeg -i input.wav -c:a libfdk_aac output.m4a
==> Summary
🍺  /usr/local/Cellar/ffmpeg/2.8: 210 files, 138M, built in 5.1 minutes
```

**Comment by tdsmith** [comment] 2015-10-01 06:38
If you'd like our help troubleshooting, please open a new ticket with the output of `brew gist-logs ffmpeg` after a failed build without --env=std; a log of a successful build is probably also interesting.

**Comment by tdsmith** [comment] 2015-10-01 06:40
I think that sounded more rude than I intended; by "if you'd like our help" I only meant to suggest that I don't think that you should feel obligated to track this down if it's working for you.
