### ISSUE TITLE
brew doctor: "Error: Failed to import: ruby20"

### ISSUE THREAD

**Issue by ActionScripted** [Homebrew/homebrew#38638] opened 2015-04-14 13:46 UTC
When running `brew doctor` see this:

mogwai:~ michael$ brew doctor
Error: Failed to import: ruby20
wrong number of arguments (3 for 0..1)
Your system is ready to brew.

Gist of `brew doctor`, `brew config` and `brew list` here: https://gist.github.com/ActionScripted/469af9fba5586e883597

**Comment by imkevinxu** [comment] 2015-04-14 14:18
Same issue here. I tried `brew install ruby20` and now I'm seeing this error:

```
➜  brewup
Already up-to-date.
Error: wrong number of arguments (3 for 0..1)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/requirement.rb:15:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:620:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:618:in `map'
/usr/local/Library/Homebrew/formula.rb:618:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:9:in `upgrade'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by xu-cheng** [comment] 2015-04-14 14:42
It caused by a recent homebrew-cask [commit](https://github.com/caskroom/homebrew-cask/commit/9e35a4b251353a708f39b2b8bedb6ac2f073acda). Will send a PR to fix it.

**Comment by DomT4** [comment] 2015-04-14 17:23
@xu-cheng Thanks Xu. I chased my tail around for a half hour last night trying to work out where that error was coming from.

**Comment by xu-cheng** [comment] 2015-04-14 17:54
Fixed in https://github.com/caskroom/homebrew-cask/commit/00dac547dcf6c9ca800686f99f73bb8f3098edd3

**Closed by xu-cheng** 2015-04-14 17:54 UTC
