### ISSUE TITLE
brew reinstall gcc --without-multilib error

### ISSUE THREAD

**Issue by rajathkumarmp** [Homebrew/homebrew#48212] opened 2016-01-18 16:12 UTC
I am trying to reinstall gcc again with openmp support but unable to do so.

This is the output of the command

```
Rajaths-MacBook-Pro:~ rajathkumarmp$ brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.3.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> Patching
patching file gcc/jit/Make-lang.in
Hunk #1 FAILED at 85.
1 out of 1 hunk FAILED -- saving rejects to file gcc/jit/Make-lang.in.rej
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2479 with fuzz 2 (offset 63 lines).
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

I am on OS X 10.10.5 and the home-brew 0.9.5

**Comment by dunn** [comment] 2016-01-18 18:45
Can you post the logs produced by `brew gist-logs gcc`? Thanks!

**Comment by mistydemeo** [comment] 2016-01-18 19:16
It looks like the patch is failing. Are there any local changes to the formula in your Homebrew installation?

**Comment by henningpeters** [comment] 2016-02-13 09:30
Same problem here, console output

```
$ brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.1.0/gcc-5.1.0.tar.bz2
######################################################################## 100.0%
==> Patching
patching file gcc/jit/Make-lang.in
==> ../configure --build=x86_64-apple-darwin14.5.0 --prefix=/usr/local/Cellar/gcc/5.1.0 --libdir=/usr/local/Cellar/gcc/5.1.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffi
==> make bootstrap
config.status: executing default-1 commands
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing gstdint.h commands
make: *** [bootstrap] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
brew reinstall gcc --without-multilib error (https://github.com/Homebrew/homebrew/issues/48212)
graphicsmagick fails to compile with gcc-5 in superenv (https://github.com/Homebrew/homebrew/issues/48402)
gcc failed to build on 10.6.8 (https://github.com/Homebrew/homebrew/issues/47741)
apple-gcc42 takes priority over modern gcc (https://github.com/Homebrew/homebrew/issues/41055)
gcc causes false alarms in C++ stdlib check (https://github.com/Homebrew/homebrew/issues/45218)
gcc 4.9.2 fails to produce debugging information (https://github.com/Homebrew/homebrew/issues/34976)
Object files deleted during build of gcc needed by gdb (https://github.com/Homebrew/homebrew/issues/35734)
MacOS.(gcc|clang|llvm)_version can return nil (https://github.com/Homebrew/homebrew/issues/18781)
```

And the output of ```brew gist-logs gcc```: https://gist.github.com/e9f27da39a3bb477a0c8

Unfortunately, it seems truncated, the only error I can spot is ```make: *** [bootstrap] Error 2```.

**Comment by ilovezfs** [comment] 2016-02-13 12:26
@rajathkumarmp did you figure this out?
```
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
```
is what you should see.

**Comment by henningpeters** [comment] 2016-02-13 14:42
On my system it only patches Make-lang.in, but does so successfully:

```
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.1.0/gcc-5.1.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.1.0.tar.bz2
==> Verifying gcc-5.1.0.tar.bz2 checksum
tar xf /Library/Caches/Homebrew/gcc-5.1.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
```

Where it breaks is after compiling for some time at this point:

```
config.status: executing default-1 commands
/var/folders/37/r_j2txn14ln7jkgj_g9t66c80000gn/T//ccwmCXZO.s:98:17: error: non-local symbol required in directive
        .no_dead_strip L_OBJC_Module
                       ^
make[2]: *** [NXConstStr.lo] Error 1
make[1]: *** [all-target-libobjc] Error 2
```

**Comment by ilovezfs** [comment] 2016-02-13 14:46
@henningpeters That's because you're doing 5.1.0 not 5.3.0, and you have a different issue.

**Comment by henningpeters** [comment] 2016-02-13 14:49
You are right, thanks. Testing now on 5.3.0, patch was applied successfully...

**Comment by ilovezfs** [comment] 2016-02-13 14:51
@henningpeters Excellent. Hopefully the build doesn't take 5 years :)

**Comment by henningpeters** [comment] 2016-02-13 17:45
Worked, cannot reproduce the error on osx 10.10.5, brew 0.9.5, latest recipe with gcc 5.3.0.

**Comment by dunn** [comment] 2016-02-13 19:17
Should I go ahead and close this, then?

**Comment by ilovezfs** [comment] 2016-02-14 10:43
@dunn That, or add "needs response" since @rajathkumarmp hasn't answered misty or me yet, or add "user configuration" since misty's diagnosis is almost certainly correct given that the formula hasn't changed since then and the patching current succeeds for both henningpeters and me, or both.

**Closed** 2016-02-14 11:17 UTC
