### ISSUE TITLE
Error with `fstar`: Unable to open file: prims.fst

### ISSUE THREAD

**Issue by qdwang** [Homebrew/homebrew#48646] opened 2016-01-30 15:54 UTC
After installing the `fstar` by `brew install fstar` in osx 10.11, the command `fstar.exe some.fst` will cause the error `Error: Unable to open file: prims.fst`.

**Comment by apjanke** [comment] 2016-01-30 20:50
Did you follow the instructions in the `fstar` formula's caveats? You need to set up an alias so it pulls in the F* standard library, instead of using plain `fstar.exe`.

```
==> Caveats
F* standard library is available in /usr/local/Cellar/fstar/0.9.1.1/stdlib:
- alias fstar='fstar.exe --include /usr/local/Cellar/fstar/0.9.1.1/stdlib --prims prims.fst'
```

Homebrew maintainers: maybe we should supply a `fstar` wrapper script in the formula if this is necessary for basic usage.

**Comment by beurdouche** [comment] 2016-01-31 17:33
@qdwang, did you finally managed to make it work ?
As @apjanke remarked, forcing the user to alias the executable is not the best idea.
In the next update of the formula (soon), I'll attempt to fix that.

**Comment by beurdouche** [comment] 2016-02-02 08:35
@qdwang, @apjanke,
I patched upstream, the alias will not be required anymore in the next FStar release.
I think you can close.

**Comment by apjanke** [comment] 2016-02-02 08:52
Cool, thanks!

Closing since it's clear this was expected behavior, not breakage in the Homebrew formula, and an upstream improvement is forthcoming.

**Closed by apjanke** 2016-02-02 08:52 UTC
Labels: maintainer feedback, upstream issue

**Comment by qdwang** [comment] 2016-02-04 09:05
@apjanke , @beurdouche 
Thanks! It finally works.

**Comment by beurdouche** [comment] 2016-02-04 09:08
@qdwang : I am pushing a new formula with a fix for that. The alias will not be required anymore as the compiler will search the standard library by default in `lib` (normal installations) and `stdlib` (Homebrew)
https://github.com/Homebrew/homebrew/pull/48798

**Comment by qdwang** [comment] 2016-02-04 09:19
@beurdouche Great, good job.

**Comment by qdwang** [comment] 2016-02-09 02:25
@beurdouche but then I get `Error: Unable to open file: FStar.IO.fsti`

**Comment by beurdouche** [comment] 2016-02-09 07:35
@qdwang are you up-to-date ? (v0.9.2.0)

**Comment by auduchinok** [comment] 2016-06-17 17:29
@beurdouche, I still have the problem using 0.9.2.0 installed from brew. The alias fixes problem though.
