### ISSUE TITLE
brew install mosh --HEAD fails with "Error: No such file or directory - scripts/mosh"

### ISSUE THREAD

**Issue by dbkaplun** [Homebrew/homebrew#40376] opened 2015-06-04 12:06 UTC
$ brew install mosh --HEAD
==> Installing mobile-shell dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2a-1.yosemite.bottle.1.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2a-1: 463 files, 18M
==> Installing mobile-shell
==> Cloning https://github.com/keithw/mosh.git
Updating /Library/Caches/Homebrew/mobile-shell--git
==> Checking out branch master
==> ./autogen.sh
Error: No such file or directory - scripts/mosh

**Comment by bfontaine** [comment] 2015-06-04 12:26
I can’t reproduce:

```
$ brew install mosh --HEAD
==> Cloning https://github.com/keithw/mosh.git
Updating /Library/Caches/Homebrew/mobile-shell--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/mobile-shell/HEAD --enable-completion
==> make install
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/mobile-shell/HEAD: 13 files, 956K, built in 46 seconds
```

But in any case it seems to be an upstream issue.

**Comment by DomT4** [comment] 2015-06-04 16:48
This was fixed in https://github.com/Homebrew/homebrew/commit/8bb19810b105dfad81898e71061f0047dd4b5a43. Please `brew update` and try again.

**Closed by DomT4** 2015-06-04 16:48 UTC

**Comment by dbkaplun** [comment] 2015-06-05 12:13
Confirmed, thanks!
