### ISSUE TITLE
qt5 5.5.0 errors in macdeployqt

### ISSUE THREAD

**Issue by fzwoch** [Homebrew/homebrew#42191] opened 2015-07-28 07:21 UTC
Possibly configuration error for qt5 5.5.0? Upgrading to 5.5.0 broke the "macdeployqt" application for me:

```
Log: Adding framework:
Log: Framework name "QtCore.framework" 
 Framework directory "/usr/local/Cellar/qt5/5.5.0_1/lib/" 
 Framework path "" 
 Binary directory "" 
 Binary name "" 
 Binary path "" 
 Version "" 
 Install name "/usr/local/Cellar/qt5/5.5.0_1/lib/" 
 Deployed install name "" 
 Source file Path "" 
 Framework Destination Directory (relative to bundle) "" 
 Binary Destination Directory (relative to bundle) "" 
```

This looks suspicious to me. With the official install from qt.io It looks more like this:

```
Log: Framework name "QtGui.framework" 
 Framework directory "/Users/fzwoch/Qt5.5.0/5.5/clang_64/lib/" 
 Framework path "/Users/fzwoch/Qt5.5.0/5.5/clang_64/lib/QtGui.framework" 
 Binary directory "Versions/5" 
 Binary name "QtGui" 
 Binary path "/Versions/5/QtGui" 
 Version "5" 
 Install name "/Users/fzwoch/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Versions/5/QtGui" 
 Deployed install name "@executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui" 
 Source file Path "/Users/fzwoch/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Versions/5/QtGui" 
 Framework Destination Directory (relative to bundle) "Contents/Frameworks/QtGui.framework" 
 Binary Destination Directory (relative to bundle) "Contents/Frameworks/QtGui.framework/Versions/5" 
```

There are several of these observations. Further down they lead to wrong/invalid otool commands:

```
Log: Using install_name_tool:
Log:  in "client.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui"
Log:  change reference "/usr/local/Cellar/qt5/5.5.0_1/lib/"
Log:  to ""
```

Which finally results in many of these errors:

```
ERROR: no file at ""
```

I'm not sure whether this is a bug or did I a miss an additional configuration step?

**Comment by DomT4** [comment] 2015-07-28 12:04
Please `brew update && brew reinstall qt5`, Apologies.

**Comment by fzwoch** [comment] 2015-07-28 12:39
That didn't help. The issue is still present. Also I don't think this is a pkg-config .pc issue what I'm facing here. Qt and qmake are operating as expected. Compilation and running of code works perfectly fine.

It is the next step - modifying the application for deploying onto other machines without installing Qt that fails. The Qt application macdeployqt usually does the job for us here. But for some reason it fails with the homebrew provided formula install. It looks like it cannot detect its own library and framework directories where it is installed.

The qt.io stock install of 5.5.0 however does not show this behaviour. That one works perfectly fine. So its either a misconfiguration on my side - in that case I'm sorry, but I appreciate any hints on how to fix it. Or it is a bug in the homebrew formula or bottle(?) that is being installed.

**Comment by DomT4** [comment] 2015-07-28 12:48
> Also I don't think this is a pkg-config .pc issue what I'm facing here.

**Comment by beemaster** [comment] 2015-07-30 10:50
I can confirm this problem, OS X 10.10.5, macdeployqt is broken. The reason for that might be "-no-rpath" in qt5.rb. From my point of view, qt5.rb is very (and probably unnecessary) complicated.
Should be enough just to use "./configure -nomake examples -nomake tests -opensource -confirm-license"

**Comment by DomT4** [comment] 2015-07-30 15:58
Justification for each option is listed in #42217, for the curious.

**Comment by aurelien-rainone** [comment] 2015-08-17 10:13
Having had some problems with macdeployqt myself, and found a way to fix them with some post-build scripting, i decided to write a python script that should work for any projects (at least it works with mine :smiley: )
Check it out [https://github.com/aurelien-rainone/macdeployqtfix](https://github.com/aurelien-rainone/macdeployqtfix)

**Comment by UniqMartin** [comment] 2015-10-18 14:10
@fzwoch Please `brew update && brew upgrade qt5` and report back if that solves your issue. Qt 5.5.1 just landed in Homebrew; it contains a number of upstream fixes to `macdeployqt` since 5.5.0.

**Comment by msphair** [comment] 2015-10-18 15:46
@UniqMartin Same issues on our project still with 5.5.1

**Comment by fzwoch** [comment] 2015-10-18 15:56
Same here.

```
Log:  change reference "/usr/local/Cellar/qt5/5.5.1/lib/"
Log:  to ""
ERROR: no file at ""
```

So I can see it correctly is configured to use the new 5.5.1 but it fails nonetheless. I havent't tried the retail 5.5.1 package but since 5.5.0 is working just fine I suspect it is how things are build that may cause things to fail. Like some default prefix path..

**Comment by UniqMartin** [comment] 2015-10-18 16:07
@msphair @fzwoch I was afraid this would be the outcome. Thanks for the confirmation! Is any of the affected projects public and with build documentation or a build script? Preferably something that isn't huge and has lots of dependencies, but still requires `macdeployqt`. I'd like to test locally, as I'm currently trying to find the root cause of this failure.

**Comment by msphair** [comment] 2015-10-18 16:17
came up with this quickly. tested it with 5.5.0 io (works) and 5.5.1 brew (fails)

`test.pro`
```
#-------------------------------------------------
#
# Project created by QtCreator 2015-06-24T19:18:41
#
#-------------------------------------------------


TEMPLATE = app
CONFIG -= embed_manifest_exe
TARGET = "test"
DEPENDPATH += .
INCLUDEPATH += .
QT += sql
QT += network
QT += xml
QT += widgets
QT += printsupport

QMAKE_POST_LINK += "rm -rf test.app/Contents/Resources/qt.conf test.app/Contents/PlugIns/ && "
QMAKE_POST_LINK += "/usr/local/Cellar/qt5/5.5.1/bin/macdeployqt test.app"

SOURCES += main.cpp
```

`main.cpp`
```
#include <QCoreApplication>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    return 0;
}
```

**Comment by msphair** [comment] 2015-10-18 16:19
which means i don't think it's macdeployqt? because i'm using the brew macdeployqt on the io built bundle and it works

**Comment by UniqMartin** [comment] 2015-10-18 17:53
@msphair Thanks, that helped! I could see the failure, found the issue, and now have a solution to the problem. I'll work on bringing the fix to Homebrew.

**Comment by msphair** [comment] 2015-10-18 17:54
@UniqMartin what did the problem end up being? and what was the solution?

**Comment by UniqMartin** [comment] 2015-10-18 18:47
The problem is that the Qt build system produces broken binaries and frameworks on OS X for a build that does not need to be relocatable (`-no-rpath` configure argument), i.e., lives in a fixed location like `/usr/local`. Homebrew fixes the library dependencies after `make install`. The structure created thus is legal, but not what `macdeployqt` expects to find. That's why it fails. The official build is relocatable (and built with the `-rpath` configure argument), so it doesn't exhibit this problem, but creates other problems for Homebrew.

The solution is to fix the Qt build system to make it do “The Right Thing”. At least what is right in my opinion. We'll see if upstream agrees or cares.

**Closed** 2015-11-08 18:39 UTC

**Comment by UniqMartin** [comment] 2015-11-08 18:51
This should have been resolved in the latest update to the `qt5` formula. Please give it another try with `brew update` followed by `brew upgrade qt5`.

**Comment by fzwoch** [comment] 2015-11-08 20:20
Works for me. Thanks a lot for figuring it out fixing!

**Comment by tfar** [comment] 2016-04-15 14:19
@UniqMartin Was this solved upstream or only with the homebrew recipe? I've found https://bugreports.qt.io/browse/QTBUG-47868 in the upstream bugtracker.

**Comment by UniqMartin** [comment] 2016-04-15 14:32
@tfar I'm not sure whether this was fixed upstream or not. The Qt 5.6.0 we currently ship in Homebrew is basically unpatched, so the only difference is that our `qt5` formula is built with a fixed path (`-no-rpath`; this means all binaries and frameworks link to each other with an absolute path; if you copy it into a different location, things break) whereas the upstream binaries are relocatable (built with `-rpath`, the default; this means all binaries and frameworks link to each other with relative paths; if you copy everything to a new location, things should continue to work).

The issue that was raised and fixed here is not immediately related. It had something to do with our processing of the binaries after they are built (we were not processing frameworks correctly).
