### ISSUE TITLE
brew cask install caffeine -- curl: (7) Failed to connect to download.lightheadsw.com port 80: Operation timed out

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#36881] opened 2015-02-17 02:42 UTC
when running `brew cask install caffeine` getting this msg:
```    
==> Downloading http://download.lightheadsw.com/download.php?software=caffeine

curl: (7) Failed to connect to download.lightheadsw.com port 80: Operation timed out
Error: Download failed on Cask 'caffeine' with message: Download failed: http://download.lightheadsw.com/download.php?software=caffeine    ```

**Comment by adamv** [comment] 2015-02-17 03:09
Duplicate of #36878.

**Closed by adamv** 2015-02-17 03:09 UTC
