### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by nicolasmassouh** [Homebrew/homebrew#43551] opened 2015-09-03 12:49 UTC
I can't update homebrew. 

this is my log 

Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:226:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'

Someone there a reply ? 

kind regards

**Comment by bfontaine** [comment] 2015-09-03 13:27
Please run `brew update` again.

Closing as a duplicate of #42553.

**Closed by bfontaine** 2015-09-03 13:27 UTC
