### ISSUE TITLE
audit: `brew audit` should look for duplicate prefix in paths

### ISSUE THREAD

**Issue by dholm** [Homebrew/homebrew#43872] opened 2015-09-13 12:42 UTC
Two formulas that I have installed put files in `#{prefix}/#{prefix}/some/path`.  `brew audit` should check for the presence of this after a formula has been installed and generate an error.

The two formulas are:

 - cppcheck 1.70
   `/usr/local/Cellar/cppcheck/1.70/usr/local/Cellar/cppcheck/1.70/cfg/avr.cfg`
   `/usr/local/Cellar/cppcheck/1.70/usr/local/Cellar/cppcheck/1.70/cfg/cppcheck-cfg.rng`
   `/usr/local/Cellar/cppcheck/1.70/usr/local/Cellar/cppcheck/1.70/cfg/gnu.cfg`
   [..]

 - radare2 0.9.9
   `/usr/local/Cellar/radare2/0.9.9_1/usr/local/Cellar/radare2/0.9.9_1/lib/radare2/0.9.9/lang_duktape.dylib`
   `/usr/local/Cellar/radare2/0.9.9_1/usr/local/Cellar/radare2/0.9.9_1/lib/radare2/0.9.9/lang_lua.dylib`
   [..]

I detected this while working on fixing an unrelated bug in the radare2 formula.  A simple way of scanning ones Homebrew cellar for this is to run `find $(brew --prefix)/Cellar | egrep 'Cellar.+Cellar'`.

**Comment by DomT4** [comment] 2015-09-13 14:06
Fixed in the former in https://github.com/Homebrew/homebrew/pull/43875. Couldn't reproduce the latter, how did you build that?

**Comment by dholm** [comment] 2015-09-13 15:37
@DomT4 I noticed it while fixing #43856 so probably it was a temporary issue in my locally modified formula.

**Closed** 2015-12-07 04:14 UTC
