### ISSUE TITLE
Ran brew update, brew upgrade, brew doctor. Was told to report this bug:

### ISSUE THREAD

**Issue by mikelane** [Homebrew/homebrew#42554] opened 2015-08-06 14:52 UTC
```Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'```

**Comment by mikemcquaid** [comment] 2015-08-06 14:53
Duplicate of https://github.com/Homebrew/homebrew/issues/42553. Please rerun `brew update` and it should go away.

**Closed** 2015-08-06 14:54 UTC
