### ISSUE TITLE
GTK+3 (v3.18.0) Failed to Upgrade/Build on OS X v10.11.0 'El Capitan'  

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew#44537] opened 2015-10-02 18:18 UTC
[Here](https://gist.github.com/RandomDSdevel/9550d654940b03b3c506)'s the Gist, but I'll warn you ahead of time that it doesn't include anything from `~/Library/Logs/Homebrew/gtk+3` because I didn't find anything there when I looked for it.  Also, I haven't yet performed the El Capitan permissions fix prescribed by `brew doctor -vd` (see `doctor.out` in the Gist) so I'll try that and see if it works.  Either way, I'll let you guys know what happens.

**Comment by DomT4** [comment] 2015-10-02 18:20
It can't write to `/usr/local`, which is the problem. Try the recommended:

```
sudo chown -R $(whoami):admin /usr/local && brew prune
```

Should sort the issue out fix both `doctor` warnings.

**Comment by RandomDSdevel** [comment] 2015-10-02 18:24
OK, I just did the permissions fix and the pruning, and I _still_ get the _same error_ when trying to build the new version of GTK+.

**Comment by DomT4** [comment] 2015-10-02 18:28
Can you generate a new log? Thanks

**Comment by RandomDSdevel** [comment] 2015-10-02 18:47
OK, I've overwritten [the Gist](https://gist.github.com/RandomDSdevel/9550d654940b03b3c506) with new copies of the log files for you to look at.  One strange thing I noticed, though, is that `brew config` listed my Command Line Tools version as 'N/A' even though I _swear_ I installed them for Xcode v7.0.  Maybe updating to Xcode v7.0.1 undid or invalidated that?  I'll go check for a new CLT installer package at Apple Developer Connection just in case.

**Comment by RandomDSdevel** [comment] 2015-10-02 18:50
Oh, doh!  I did the CLT install before I upgraded to El Capitan!  I don't see a new GUI CLT installer package for 10.11, though, so I guess I'll just have to run `xcode-select --install` instead.

**Comment by RandomDSdevel** [comment] 2015-10-02 18:58
OK, running `xcode-select --install` didn't help matters like I though it would.  I'm starting to think that this _might_ be an upstream bug.  Perhaps I should go look up that way…

**Comment by DomT4** [comment] 2015-10-02 18:59
This is the error from the readout, so it might be our problem, but this passed our CI barely 5 hours ago and I'm not sure what could have broken in that time.

```
==> Downloading https://download.gnome.org/sources/gtk+/3.18/gtk+-3.18.0.tar.xz
Already downloaded: /Library/Caches/Homebrew/gtk+3-3.18.0.tar.xz
==> Verifying gtk+3-3.18.0.tar.xz checksum
==> Patching
patching file testsuite/gtk/Makefile.in
Hunk #4 FAILED at 1140.
1 out of 5 hunks FAILED -- saving rejects to file testsuite/gtk/Makefile.in.rej
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
ErrorDuringExecution: Failure while executing: /usr/bin/patch -g 0 -f -p1
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

CC @ tschoonj

**Comment by DomT4** [comment] 2015-10-02 19:00
CC @tschoonj

**Comment by RandomDSdevel** [comment] 2015-10-02 19:08
Well, _that's_ weird…I wonder what could be going wrong?

**Comment by RandomDSdevel** [comment] 2015-10-02 19:18
Bump @tschoonj.

**Comment by tschoonj** [comment] 2015-10-02 19:25
Strange indeed. I remember seeing something like this before with `:DATA` patches that was fixed by putting the patch in an external file. Could you try doing that?

**Comment by RandomDSdevel** [comment] 2015-10-02 19:30
How would I accomplish that?  Do I have to file a bug upstream for this?

**Comment by RandomDSdevel** [comment] 2015-10-02 19:33
@tschoonj:  Is that my job or @DomT4's?  And, if it's my job, how would I do it?  Does it require filing a bug upstream, or can it be fixed within Homebrew?

**Comment by DomT4** [comment] 2015-10-02 19:38
Give me a sec to see if I can reproduce locally. Looking into it.

**Comment by RandomDSdevel** [comment] 2015-10-02 20:01
@DomT4:  Got anything yet?

**Comment by DomT4** [comment] 2015-10-02 20:04
Patch does fail here. Just going to nudge it into the patches repo we keep & try using that.

**Comment by RandomDSdevel** [comment] 2015-10-02 20:08
You mean [Homebrew/patches](https://github.com/Homebrew/patches)?  Does that mean I'll have to tap that repo in order to get things to work on my end once you've figured out how to fix it from yours, or would GTK+'s formula just fetch the patch for me?

**Comment by DomT4** [comment] 2015-10-02 20:10
You wouldn't need to touch that repo. The patch would be included in-formula as a `patch do` block and fetched & applied automatically after untar.

**Comment by DomT4** [comment] 2015-10-02 20:11
@tschoonj Can we use this diff instead? It seems to be what upstream have committed: https://git.gnome.org/browse/gtk+/diff/?id=5bb9c1891ced2699bfc9d92acd8adf7b6167de26&id2=f7e0deb7cb22870846ebd9f37085163fc9499bce

**Comment by tschoonj** [comment] 2015-10-02 20:14
Yes sure. I disabled the test in the Makefile.am initially but they fixed the code in that commit later

Op 2 okt. 2015 om 21:11 heeft Dominyk Tiller <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@tschoonj<https://github.com/tschoonj> Can we use this diff instead? It seems to be what upstream have committed: https://git.gnome.org/browse/gtk+/diff/?id=5bb9c1891ced2699bfc9d92acd8adf7b6167de26&id2=f7e0deb7cb22870846ebd9f37085163fc9499bce

**Comment by RandomDSdevel** [comment] 2015-10-02 20:15
@DomT4:  Awesome!  So I just have to run `brew update` again when you guys have squared everything away.

**Comment by DomT4** [comment] 2015-10-02 20:15
Cool. Just checking locally to make sure there are no problems, but the shorter a diff we have to apply the less chance there is of trouble generally.

>  So I just have to run brew update again when you guys have squared everything away.

Yeah. I'll ping you here when it's fixed. Shouldn't be long.

**Comment by RandomDSdevel** [comment] 2015-10-02 20:16
Great, thanks!

**Comment by DomT4** [comment] 2015-10-02 20:29
Should be fixed by https://github.com/Homebrew/homebrew/commit/9cda892b8fcf053e8e265e0c58de3722688a22b8.

`brew update && brew upgrade gtk+3` and you should be good again. Thanks for the report on this!

**Comment by RandomDSdevel** [comment] 2015-10-02 20:31
@DomT4:  You're very welcome!

**Closed** 2015-10-02 20:30 UTC
Labels: user configuration
