### ISSUE TITLE
brew cask install burn -- curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#36880] opened 2015-02-17 02:40 UTC
trying `brew cask install burn` - getting:

```    
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'burn' with message: Download failed: http://downloads.sourceforge.net/project/burn-osx/Burn/2.5.1/burn251.zip    ```

**Comment by adamv** [comment] 2015-02-17 03:09
Duplicate of #36878.

**Closed by adamv** 2015-02-17 03:09 UTC
