### ISSUE TITLE
Brew install of Zathura fails on make install of GTK+3 on MacOS 10.6.8

### ISSUE THREAD

**Issue by scottbaron** [Homebrew/homebrew#40439] opened 2015-06-05 20:38 UTC
How do I fix this.  This is a byproduct of my attempt to install Zathura. A command line pdf viewer. 
➜  ~  brew install gtk+3
==> Downloading https://download.gnome.org/sources/gtk+/3.16/gtk+-3.16.3.tar.xz
Already downloaded: /Library/Caches/Homebrew/gtk+3-3.16.3.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gtk+3/3.16.3 --disable-glibtest --enable-
==> make install
gtksettings.c:910: Warning: Gtk: unexpected annotation: element-type
Command '['/private/tmp/gtk+320150605-27418-r2pocx/gtk+-3.16.3/gtk/tmp-introspectxeWlKT/Gtk-3.0', '--introspect-dump=/private/tmp/gtk+320150605-27418-r2pocx/gtk+-3.16.3/gtk/tmp-introspectxeWlKT/functions.txt,/private/tmp/gtk+320150605-27418-r2pocx/gtk+-3.16.3/gtk/tmp-introspectxeWlKT/dump.xml']' returned non-zero exit status -11
make[2]: *** [Gtk-3.0.gir] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

**Comment by jacknagel** [comment] 2015-06-05 20:41
Duplicate of https://github.com/Homebrew/homebrew/issues/40438; please don't open multiple issues for the same item, thanks.

**Closed by jacknagel** 2015-06-05 20:41 UTC

**Comment by scottbaron** [comment] 2015-06-05 20:49
I know a reply was unnecessary, but thank you for for bringing this to my attention. I see you all over the forums, providing an abundance of assistance. So much appreciation to you and the team.  A service that we cannot put a price tag on.
