### ISSUE TITLE
'brew info --json' doesn't properly reflect built-as-bottle state

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew#47912] opened 2016-01-10 05:48 UTC
Steps to reproduce:

I install Gimp with `brew reinstall gimp --build-bottle`

To make sure I did it right, I `brew bottle gimp`; it works.

Then, `brew info gimp --json=v1 | jq .[0].installed[0].built_as_bottle` outputs `null`.

**Comment by ilovezfs** [comment] 2016-01-10 07:13
This was caused by a "race" between two commits.
bash-3.2$ git log -n1 --format=%ai 33442291229d692fbdf05c3f4c03878fc64ea759
2012-08-15 22:08:40 -0500
bash-3.2$ git log -n1 --format=%ci 33442291229d692fbdf05c3f4c03878fc64ea759
2012-09-17 20:01:37 -0500
bash-3.2$ git log -n1 --format=%ai 8837423a5a9643cf1b2e824c9a31cc72a78c516b
2012-08-25 11:31:57 -0700
bash-3.2$ git log -n1 --format=%ci 8837423a5a9643cf1b2e824c9a31cc72a78c516b
2012-08-25 11:52:37 -0700

"built_bottle" was renamed "built_as_bottle" after the date 33442291229d692fbdf05c3f4c03878fc64ea759 was authored but before the date it was committed, so the corresponding name change did not make it to the new additions to formula.rb.

In any case, the diff that fixes this is, as follows:
```
diff --git a/Library/Homebrew/formula.rb b/Library/Homebrew/formula.rb
index 65f8c33..7abcc0b 100644
--- a/Library/Homebrew/formula.rb
+++ b/Library/Homebrew/formula.rb
@@ -1287,7 +1287,7 @@ class Formula
       hsh["installed"] << {
         "version" => keg.version.to_s,
         "used_options" => tab.used_options.as_flags,
-        "built_as_bottle" => tab.built_bottle,
+        "built_as_bottle" => tab.built_as_bottle,
         "poured_from_bottle" => tab.poured_from_bottle
       }
     end
```
I'll open a PR.

**Comment by glyph** [comment] 2016-01-10 11:37
@ilovezfs thanks for tracking this down!

**Closed** 2016-01-12 09:43 UTC
