### ISSUE TITLE
brew info on pinned formula fails if the formulas has been upgraded manually

### ISSUE THREAD

**Issue by mcdado** [Homebrew/homebrew#46044] opened 2015-11-16 15:47 UTC
Say I pinned `ffmpeg` when it was 2.8, but then I run `brew upgrade ffmpeg` when 2.8.2 was available. The package would be upgraded, but now running `$ brew info ffmpeg` returns this:

```
Error: /usr/local/Cellar/ffmpeg/2.8 is not a directory
```

or this:
```
$ brew  info --debug ffmpeg
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/ffmpeg.rb
Error: /usr/local/Cellar/ffmpeg/2.8 is not a directory
/usr/local/Library/Homebrew/keg.rb:99:in `initialize'
/usr/local/Library/Homebrew/formula_pin.rb:38:in `new'
/usr/local/Library/Homebrew/formula_pin.rb:38:in `pinned_version'
/usr/local/Library/Homebrew/formula.rb:941:in `pinned_version'
/usr/local/Library/Homebrew/cmd/info.rb:109:in `info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:35:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:146:in `<main>'
```

I guess it's some sort of cached reference?

**Comment by dunn** [comment] 2015-11-17 03:14
Hrm, I can't replicate this.  I tried with Ghostscript; have you seen it with any formula other than ffmpeg?

**Comment by mcdado** [comment] 2015-11-17 06:13
Could as well be that it was pinned with an older version of brew and now it is fixed? Or maybe just non-bottles?

No I didn't experience it other times.

**Comment by xu-cheng** [comment] 2015-11-17 06:23
> Error: /usr/local/Cellar/ffmpeg/2.8 is not a directory

Can you check this path? It should be a directory. If not, you may want to remove that file.

**Comment by mcdado** [comment] 2015-11-17 07:21
It doesn't exist anymore, because after the upgrade now there's only a directory called 2.8.2

**Comment by xu-cheng** [comment] 2015-11-18 07:53
I suspect the symlink `/usr/local/Library/PinnedKegs/ffmpeg` on your system is broken. You can try to remove it.

**Comment by mcdado** [comment] 2015-11-18 08:03
That is definitely the case, and I deleted it before creating the issue. :)
I was hoping that sharing about this would lead to the discovery of some bug in homebrew.

**Comment by xu-cheng** [comment] 2015-11-18 08:20
I think this is a one time issue as I cannot reproduce it locally. Close this for now. Thanks for the report.

**Closed by xu-cheng** 2015-11-18 08:20 UTC
