### ISSUE TITLE
smlnj fails to build on OS X 10.11.3

### ISSUE THREAD

**Issue by wolverian** [Homebrew/homebrew#49524] opened 2016-02-25 15:31 UTC
The bottle for this formula works, but I can't build the formula without using the bottle. The error is:

~~~
config/install.sh: Installation complete.
Error: No such file or directory - /private/tmp/smlnj20160225-17436-x4a0tz/config
~~~

The error happens after the formula is complete, in some cleanup code inside Homebrew. I suspect this weird bit of code in the formula causes something to go very wrong:

~~~ruby
    # Build in place
    root = prefix/"SMLNJ_HOME"
    cd ".."
    root.install "config"
    cd root
~~~

I tried to run `brew gist-logs smlnj`, but got an error:

~~~
$ brew gist-logs smlnj
Error: HTTP 404 Not Found (expected 201)
~~~

Why I'm trying to build the formula: I'm trying to upgrade the formula to smlnj's newest version. I encountered this problem after doing the upgrade edit in the formula, and then realized it happens with the current version too.

**Comment by bfontaine** [comment] 2016-02-25 17:15
The issue is that the build directory is moved under the prefix but at the end of the installation we try to find the usual metafiles (e.g. `README`/`LICENSE`) in the build directory. It doesn’t exist anymore (because we moved it), hence the failure.

**Comment by DomT4** [comment] 2016-03-25 20:43
Closing in favour of #49530.

**Closed by DomT4** 2016-03-25 20:43 UTC
