### ISSUE TITLE
Bottle macvim

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew#42962] opened 2015-08-15 01:05 UTC
It would be nice for `macvim` to be bottled. Why isn't it bottled? There's a reference [here](https://github.com/Homebrew/homebrew/issues/33319#issuecomment-59647256) to Python issues.

> We don't have bottles for them yet due to still working out some potential Python issues.

**Comment by DomT4** [comment] 2015-08-15 02:35
See https://github.com/Homebrew/homebrew/commit/fb0842e6fedbaa3cb38887f8e0ace24066a50453.

Because the dep is `depends_on :python => :recommended` we built it against the default formula to fulfil that requirement, which is the Homebrew Python formula.

This means that whenever someone attempts to use the MacVim bottle, because it was built against Homebrewed Python that becomes a dependency:

```
==> Installing dependencies for macvim: sqlite, openssl, python
```

Understandably, people get a little worried when they go to upgrade MacVim and [suddenly find](https://github.com/Homebrew/homebrew/issues/41588) they have to install Homebrew's Python, which isn't a small dependency.

Whether using the system Python remains an issue is something you'd need to ask Tim about. The dancing inside the formula may make it impractical to tie it to a specific Python one way or another.

**Comment by cc941201** [comment] 2015-08-15 03:50
You can use `brew cask` to install MacVim.

**Comment by DomT4** [comment] 2015-08-15 03:57
It depends which OS X version you're using how up-to-date that package is though. Anything below Yosemite is currently capped at `7.4-73`.

**Comment by sjackman** [comment] 2015-08-15 04:47
Thanks for the explanation, Dominyk.

**Comment by tdsmith** [comment] 2015-08-15 05:42
You know, I guess we could build it against system Python and rewrite the linkage in post_install.

**Comment by DomT4** [comment] 2015-08-15 15:19
We could always make it `:optional` as well, although that may be really unpopular given how long it has been the default option.

**Comment by mikemcquaid** [comment] 2015-08-15 16:38
I'm leaning towards thinking the "bottles always install the `default_formula` for a requirement" was a bad idea and we should just stop doing that. On the flip side though I'm thinking the Python situation is stupid and untenable (despite @tdsmith's amazing work) in that we seem to have 50% who are very opinionated about why Homebrew should always/should never use the system Python.

**Comment by tdsmith** [comment] 2015-08-15 17:05
We can't *just* stop; in general the same dependencies we built against do need to be installed. We'd have to let clients how know dependencies were satisfied by the test-bot. (Maybe add a `system` attibute to the Requirement?) The :python dependency is still used more places than it's needed, but since macvim embeds the interpreter (instead of providing an extension module) this one kinda matters.

**Comment by mikemcquaid** [comment] 2015-08-15 17:21
I guess my point was: Python was the only package that this case was added to fix and I'm not sure it's fixing more problems than it's causing. Longer-term I still think it would be a better user experience for everyone and provide significantly more work for maintainers if we just decide that people have to use either the system or Homebrew Python consistently e.g by moving the Homebrew Python to dupes and treating it like Clang in the  LLVM formula (i.e. we don't actually support using it within Homebrew itself but if you want to do so outside: go mad).

**Comment by tdsmith** [comment] 2015-08-15 17:41
But if we build a bottle with e.g. a :fortran requirement we really do need the user to install gcc to use the bottle even if they have ifort installed; it's not Python-specific.

**Comment by DomT4** [comment] 2015-08-15 17:51
I'd almost rather go the other way entirely and enforce Homebrew's Python as a variable we actually have control over. If Apple hadn't added Python 2.7.10 as part of 10.10.5's bumps, we'd still be fielding plenty of complaints about problems in the earlier Pythons.

Either way, I do suspect we're going to get forced into picking one or the other. Either support system default requirements, or move the system to bottles being built against system Python or Homebrew Python by default but from-source installations just using whatever happens to be in the `$PATH`, etc.

**Comment by mikemcquaid** [comment] 2015-08-15 18:54
> But if we build a bottle with e.g. a :fortran requirement we really do need the user to install gcc to use the bottle even if they have ifort installed; it's not Python-specific.

If it links against it: yes. If it doesn't: it should be defined as `:build`.

I don't think the problem is Python-specific but it's with Python that we hear by far the most complaints.

> I'd almost rather go the other way entirely and enforce Homebrew's Python as a variable we actually have control over. If Apple hadn't added Python 2.7.10 as part of 10.10.5's bumps, we'd still be fielding plenty of complaints about problems in the earlier Pythons.

This logic applies to pretty much any system duplicate and it's more an idealogical thing; are we responsible for maintaining a higher-level of security than Apple when it comes to packages they install? I don't think we are and I think doing so is busywork that many users don't care about us doing.

**Comment by tdsmith** [comment] 2015-08-15 19:07
Yes, gfortran dynamically links to some math libraries that gcc installs and there's no support for doing it statically.

Python is used in three different ways and the differences between the use cases are important:
* Libraries and bindings: it's a bug in the library build system if it matters which python is used to build it
* Applications: this is what you're describing, Mike; it shouldn't matter which python is used, modulo recently mooted concerns about SSL APIs, but it does matter that we either keep the same python around or rewrite shebangs
* Embedded interpreters: this is how vim uses python; it matters which Python is used because that sets up the default module search path and people get annoyed when they can't use a module in vim which they just pip-installed

(Applications like ansible that support discovering non-required modules in their environment bleed into the third case.)

**Comment by DomT4** [comment] 2015-08-16 00:14
> This logic applies to pretty much any system duplicate

I don't think it does, really. I agree how much we should duplicate the system is solidly ideological, but there's very little in the core that we actively dupe Apple on & has security related issues. Primarily, OpenSSL, Python, cURL & to a lesser extent Ruby.

Nobody's suggesting we start easily permitting users to link Clang over the system or using our Perl for Homebrew formulae or unkegging our `curl`, etc. We're not contemplating a vast expansion of forcibly duplicating the system here, just how to handle the Python situation going forwards.

> I don't think we are and I think doing so is busywork that many users don't care about us doing.

I'm not sure how the discussion ended up here, but in general, however much users don't give a crap I do believe we have a responsibility to best security practices. IMO, people are allowed to be annoyed if they use a package manager and that package manager knows some behaviour is potentially insecure but does it anyway.

My point about us being able to control the variables wasn't particularly SSL/TLS related in this case. I used it as the most recent example of broader complaints but there are situations where the system Python doesn't have a recent enough `setuptools` and we have to vendor one into that formula's Cellar. There are places where we have to vendor `pip` because the system just doesn't ship it, and so on.

It's not like using the system Python is all happy-days & no frantic dancing. Tucking away Homebrew's Python in a little corner and refusing to use it isn't going to be a panacea either. The answer to your immediate concerns would seem to be to train the `default_formula` mechanism to take system paths as well as formula paths, so we can build bottles against the system Python, if that would work.

**Comment by mikemcquaid** [comment] 2015-08-16 15:27
The problem is on stuff like Macvim we have two choices: pick system/Homebrew Python and build against that or not offer a binary package. There's not really another way around this without implementing another feature which would further complicate our dependency logic.

Honestly it's tempting to just push people towards the Cask instead.

**Comment by DomT4** [comment] 2015-08-20 02:13
Closing this one out. The skinny on the actual question here is that MacVim is unlikely to be bottled in the near future unless we do some Python hackery or make Python `optional` in MacVim. If anyone wants to take a run at the former, feel free.

I think all the maintainers are well aware enough of the Python issues in these niche situations that we don't need to keep this issue open indefinitely to remind us.

**Closed by DomT4** 2015-08-20 02:13 UTC
