### ISSUE TITLE
unitialized constand Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by Spiral90210** [Homebrew/homebrew#42601] opened 2015-08-07 10:19 UTC
It asked me to report this bug, I think I was on a2373af9 previously.

I ran brew doctor, which suggested an update update.
I ran said update, and got an error.
I ran update again, and it updated from the same version to itself?
brew doctor reports healthy.

Following is terminal output:

====================================
```
C02M31YWFD59:~ me$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.

C02M31YWFD59:~ me$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

C02M31YWFD59:~ me$ brew update
Updated Homebrew from 5cd762f5 to 5cd762f5.
==> New Formulae
homebrew/versions/antlr3

C02M31YWFD59:~ me$ brew doctor
Your system is ready to brew.
```

**Comment by bfontaine** [comment] 2015-08-07 10:22
Closing as a duplicate of #42553.

**Closed by bfontaine** 2015-08-07 10:22 UTC
