### ISSUE TITLE
Git package broken in 10.11 El Capitan

### ISSUE THREAD

**Issue by nrbrook** [Homebrew/homebrew#40519] opened 2015-06-09 11:31 UTC
While I managed to fix most issues I was initially seeing in El Capitan by installing the latest command line tools, running `brew update`, `brew doctor` and fixing the warnings, I can't reinstall git (which I was attempting to do to fix a different issue).

```
$ brew reinstall git
==> Reinstalling git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.4.3.tar.xz
Already downloaded: /Library/Caches/Homebrew/git-2.4.3.tar.xz
==> make prefix=/usr/local/Cellar/git/2.4.3 sysconfdir=/usr/local/etc CC=clang C
./git-compat-util.h:219:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [ll-merge.o] Error 1
```

**Comment by DomT4** [comment] 2015-06-09 11:37
We don't support `El Capitan` at this point. What build options are you using?

**Comment by mohibeyki** [comment] 2015-06-09 11:50
I have the same issue, and I'm not using any build options, what options should I use?

**Comment by DomT4** [comment] 2015-06-09 11:53
You both have the 10.11 CLT installed? Can someone do `mdfind ssl.h | grep include`? Does `/usr/include` exist for you both?

**Comment by npinon** [comment] 2015-06-09 11:56
Yes it exist : 

```
mdfind ssl.h | grep include
/usr/local/Cellar/openssl/1.0.1j/include/openssl/ssl.h
/usr/local/Cellar/openssl/1.0.2/include/openssl/ssl.h
/usr/local/Cellar/openssl/1.0.2a-1/include/openssl/ssl.h
/usr/local/Cellar/openssl/1.0.1f/include/openssl/ssl.h
/usr/local/Cellar/openssl/1.0.1h/include/openssl/ssl.h
/usr/local/Cellar/openssl/1.0.1i/include/openssl/ssl.h
```

I don't have the same issue : 

```
brew reinstall git
==> Reinstalling git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.4.3.tar.xz
Already downloaded: /Library/Caches/Homebrew/git-2.4.3.tar.xz
==> make prefix=/usr/local/Cellar/git/2.4.3 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= install
./git-compat-util.h:100:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^
1 error generated.
make: *** [ll-merge.o] Error 1
```

**Comment by mikemcquaid** [comment] 2015-06-09 11:58
To be honest if you're already running El Capitan you should be submitting pull requests to fix these type of issues yourselves.

**Comment by DomT4** [comment] 2015-06-09 11:59
> Yes it exist :

It only exists via Homebrew there - None of those are system directories. You can use a Homebrew OpenSSL by doing `brew install git --with-brewed-openssl`. Let me know if that works. I'm curious to know if 10.11 kills OpenSSL though - Does `/usr/bin/openssl` exist?

> #include <unistd.h>

This *should* exist if `/usr/include` exists.

**Comment by mohibeyki** [comment] 2015-06-09 12:13
Well, using `--with-brewed-openssl` worked as it should have :)
and `/usr/bing/openssl exists`
@mikemcquaid unfortunately I'm not an expert in brew, and I feel ashamed because it feels like we should have :(

**Comment by DomT4** [comment] 2015-06-09 12:24
> and /usr/bin/openssl exists

The headers and libraries should exist somewhere on the system then - Either within `Xcode` or the CLT. If they exist in `Xcode` they'll be tucked inside `/path/to/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/openssl` or similar. Are you all using Xcode 7?

**Comment by mikemcquaid** [comment] 2015-06-09 12:31
Run `/usr/bin/openssl -v` and see what it says.

**Comment by npinon** [comment] 2015-06-09 12:33
Openssl isn't the problem. El capitan seems to have a bug in the make phase.

```
brew reinstall git --with-brewed-openssl
==> Reinstalling git with --with-brewed-openssl
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.4.3.tar.xz
Already downloaded: /Library/Caches/Homebrew/git-2.4.3.tar.xz
==> make prefix=/usr/local/Cellar/git/2.4.3 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= install
make: *** [hex.o] Error 1
1 error generated.
make: *** [list-objects.o] Error 1
1 error generated.
make: *** [line-log.o] Error 1
```

**Comment by nrbrook** [comment] 2015-06-09 12:41
Yes I've seen those errors too, before I installed `Command_Line_Tools_OS_X_10.11_for_Xcode_7_beta.dmg` I think. `brew install git --with-brewed-openssl` fixed the fit installation for me too

**Comment by mohibeyki** [comment] 2015-06-09 12:42
I have XCode 6.3.2 and that is probably the problems since there is no MacOSX10.11.sdk in XCode directory (10.10 & 10.9 exists)
I thought having the new CLT tools would mean that these problems shouldn't happen
Using `openssl version -a`
```
OpenSSL 0.9.8zf 19 Mar 2015
built on: May  9 2015
platform: darwin64-x86_64-llvm
options:  bn(64,64) md2(int) rc4(ptr,char) des(idx,cisc,16,int) blowfish(idx)
compiler: -arch x86_64 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -O3 -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DMD32_REG_T=int -DOPENSSL_NO_IDEA -DOPENSSL_PIC -DOPENSSL_THREADS -DZLIB -mmacosx-version-min=10.6
OPENSSLDIR: "/System/Library/OpenSSL"
```

**Comment by nrbrook** [comment] 2015-06-09 12:43
Perhaps `sudo xcode-select -switch /Applications/Xcode-Beta.app` with Xcode 7 beta would fix it?

**Comment by DomT4** [comment] 2015-06-09 12:51
> El capitan seems to have a bug in the make phase.

Need more details here. `brew gist-logs git` should show them.

> I have XCode 6.3.2 and that is probably the problems since there is no MacOSX10.11.sdk in XCode directory 

If you're using the unstable OS X you should be using the unstable Xcode as well.

**Comment by npinon** [comment] 2015-06-09 12:59
Command Line Tools (OS X 10.10) for Xcode 7 beta && sudo xcode-select -switch /Applications/Xcode-beta.app
resolved the issue.

It works fine now

**Comment by epogue** [comment] 2015-06-09 15:25
@npinon: Thanks! Fixed it for me as well.

**Comment by RoXeon** [comment] 2015-06-09 16:11
@npinon @npinon How is that even possible since there is no openssl in XCode 7 beta/MacOSX10.11.sdk? Can someone confirm that XCode 7 beta contains "Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/openssl" folder?

**Comment by alexwhen** [comment] 2015-06-09 17:15
same problem

**Comment by mikemcquaid** [comment] 2015-06-09 18:05
Everyone running 10.11 will have the same problem.

**Comment by mikemcquaid** [comment] 2015-06-09 18:06
It's almost as if you're running a developers-only OS beta released less than 24h ago.

**Comment by mistydemeo** [comment] 2015-06-09 18:10
If you're experiencing an issue, and installing Xcode 7 and running `xcode-select` does not fix the issue, please provide the logs from `brew gist-logs git`. We can't diagnose anything further without logs. Thanks!

**Comment by DomT4** [comment] 2015-06-09 18:14
@Homebrew/owners @bfontaine When do we want to add basic recognition of the new OS X? Names, symbols, Xcode version, etc? We waited till 10 Aug last year.

**Comment by mistydemeo** [comment] 2015-06-09 18:30
Given that users are installing it already, we should probably add the basics required to support it now, with the caveat that it's definitely unsupported and may not work.

**Comment by lloeki** [comment] 2015-06-09 18:47
Re @RoXeon:

```
~> ls /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/openssl | wc -l 
      71
~> ls /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/openssl
ls: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/openssl: No such file or directory
```

Re @mistydemeo: https://gist.github.com/anonymous/4c693e3c46bf3030078b

> with the caveat that it's definitely unsupported and may not work.

Purely as courtesy, shouldn't (at least) `brew doctor` warn about being run on a yet unknown system?

**Comment by epogue** [comment] 2015-06-09 18:47
Spoke too soon. @npinon's advice helped me with some packages, but `brew install git` is failing. Here are the logs from my system: https://gist.github.com/anonymous/e06a7ee90875513f46ec

**Comment by npinon** [comment] 2015-06-09 18:57
@epogue use 
```
brew install git --with-brewed-openssl
```

**Comment by bentruyman** [comment] 2015-06-09 19:00
@npinon That worked for me. Thanks.

**Comment by RnbWd** [comment] 2015-06-09 19:15
I can confirm this works for me too: 

```bash
brew install git --with-brewed-openssl
```

thanks!

**Comment by mistydemeo** [comment] 2015-06-09 19:16
Can someone experiencing this try:

```
brew install https://gist.githubusercontent.com/mistydemeo/1395c9d5f537c5428d84/raw/685dad5a04cd76d13d0c87966857f48f48aca3ff/git.rb
```

**Comment by lloeki** [comment] 2015-06-09 19:19
@mistydemeo tried, works for me.

**Comment by mistydemeo** [comment] 2015-06-09 19:23
PR in #40532.

**Comment by RnbWd** [comment] 2015-06-09 19:27
@mistydemeo tried your formula as well:

```bash
brew install https://gist.githubusercontent.com/mistydemeo/1395c9d5f537c5428d84/raw/685dad5a04cd76d13d0c87966857f48f48aca3ff/git.rb
```
It worked!

**Comment by mistydemeo** [comment] 2015-06-09 20:23
Merged that branch; this should be fixed now.

**Closed** 2015-06-09 20:25 UTC
Labels: 10.11

**Comment by yurikoles** [comment] 2015-06-09 21:00
I can say even more, the brew itself is broken, because it fails to link apps. Jus try to do a fresh install or clean prefix, not just upgrade and use old brew.

**Comment by tdsmith** [comment] 2015-06-09 21:10
Please open a new issue if you continue to have problems with this or other packages after upgrading.

**Comment by DomT4** [comment] 2015-06-09 22:52
Something interesting. There is no `include/openssl` folder in the 10.11 Xcode SDK, but there is `lib/libcrypto.tbd` and `lib/libssl.tbd`. There's also `lib/sshcrypto/libcrypto.tdb`.

**Comment by mistydemeo** [comment] 2015-06-10 05:07
The `.tbd` files are a new feature in the 10.11 SDKs, I believe. The actual libraries are located in `/usr/lib` as expected; like with Xcode, the CLT doesn't install any openssl headers.

**Comment by DomT4** [comment] 2015-06-11 03:19
@mistydemeo Something interesting has apparently happened with `ssh` on 10.11 - I wonder if Apple are planning to ditch OpenSSL completely relatively soon if they're already dropping the headers, combined with [this](https://twitter.com/Kryptoblog/status/608594170786250752)?

**Comment by mistydemeo** [comment] 2015-06-11 03:31
ssh has its own libcrypto (`/usr/lib/sshcrypto/libcrypto.dylib`) and the headers aren't included, so I assume that's not intended for public use at any point.

I know Apple has marked their openssl headers as deprecated, but hopefully they intend to provide more than one OS's worth of notice for removal. The actual libraries probably aren't going away for some time.

**Comment by mistydemeo** [comment] 2015-06-11 03:31
Interesting though!

**Comment by DomT4** [comment] 2015-06-11 03:49
Thanks! Will be interesting to see what Apple's plans are long-term on this, especially with OpenSSL removing support for the 0.9.8 branch in December (Although there's nothing stopping Apple continuing to support the branch themselves).
