### ISSUE TITLE
<gnu-sed --with-default-names> fails to build on 10.9.5

### ISSUE THREAD

**Issue by ttecon** [Homebrew/homebrew#35730] opened 2015-01-10 19:04 UTC
https://gist.github.com/anonymous/2dad2b3f5674e54496d0

```
$ brew install gnu-sed --with-default-names
==> Downloading http://ftpmirror.gnu.org/sed/sed-4.2.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gnu-sed-4.2.2.tar.bz2
==> Patching
==> ./configure --prefix=/usr/local/Cellar/gnu-sed/4.2.2
==> make install
install

Making install in lib
make[1]: *** No rule to make target `install'.  Stop.
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting
```

**Comment by ttecon** [comment] 2015-01-10 19:35
Note: Brew doctor mentions broken symlinks but pruning these doesn't help. I recently reinstalled homebrew and tried to reinstall my formulas. All the formulas that failed resulted in broken symlinks. I already tried to prune and reinstalled but same problems.

**Comment by jacknagel** [comment] 2015-01-10 22:33
Closing as an effective duplicate of #35731.

**Closed by jacknagel** 2015-01-10 22:33 UTC
