### ISSUE TITLE
Brew install subversion error

### ISSUE THREAD

**Issue by dxh1011** [Homebrew/homebrew#36301] opened 2015-01-28 03:48 UTC
When I try to run
brew install --universal --with-java
subversion==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-
Already downloaded: /Library/Caches/Homebrew/subversion-1.8.11.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion--serf-1.3.8.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.8.11/li
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.8.11 --with-zlib=/usr --
==> make
  "_apr_uri_parse", referenced from:
      _main in svnrdump.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [subversion/svnrdump/svnrdump] Error 1

READ THIS: http://git.io/brew-troubleshooting

anybody could help me?

**Comment by mistydemeo** [comment] 2015-01-28 03:53
> READ THIS: http://git.io/brew-troubleshooting

Please read this and post all of the requested diagnostics, thanks!

**Comment by DomT4** [comment] 2015-01-28 03:57
The last time something very similar to this cropped up, It occurred because for some reason a ` universal ` subversion install wasn't triggering a ` universal ` brewed-apr install. The workaround was ` brew install apr --universal ` *before* building subversion. Still trying to work out why it's not automatically pulling in a universal ` apr ` at times. This comment is of course wildly irrelevant if the user has the CLT installed, in which case, apologies.

**Comment by bryonbean** [comment] 2015-02-01 02:06
Having a similar problem: 
https://gist.github.com/8ee16f1f234e4ba340b8

webptadmins-MacBook-Pro-7:~ bryonbean$ brew install --universal --with-java subversion
==> Downloading http://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.8.11.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion-1.8.11.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
==> Downloading https://serf.googlecode.com/svn/src_releases/serf-1.3.8.tar.bz2
Already downloaded: /Library/Caches/Homebrew/subversion--serf-1.3.8.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.8.11/libexec/serf GSSAPI=/usr CC=/usr/bin/c
    env.ParseConfig('$APU --ldflags --includes --link-ld --libs')
  File "/usr/local/Cellar/scons/2.3.4/libexec/scons-local/SCons/Environment.py", line 1579:
    return function(self, self.backtick(command))
  File "/usr/local/Cellar/scons/2.3.4/libexec/scons-local/SCons/Environment.py", line 597:
    raise OSError("'%s' exited %d" % (command, status))

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Brew install subversion error (https://github.com/Homebrew/homebrew/issues/36301)
Subversion fails on 10.10 --with-python (https://github.com/Homebrew/homebrew/issues/34119)

**Comment by DomT4** [comment] 2015-02-01 02:10
Can you try the same thing?

` brew install apr --universal ` and then ` subversion --universal --with-java `.

**Comment by bryonbean** [comment] 2015-02-01 02:30
Yeah, sorry, I tried that earlier and forgot to mention it.

webptadmins-MacBook-Pro-7:~ bryonbean$ brew install apr --universal
Warning: apr-1.5.1 already installed

**Comment by DomT4** [comment] 2015-02-01 12:58
If you do ` brew info apr ` does it confirm you got the ` universal ` build?

**Comment by bryonbean** [comment] 2015-02-01 18:19
It appears that way, yes...

webptadmins-MacBook-Pro-7:~ bryonbean$ brew info apr
apr: stable 1.5.1 (bottled)
https://apr.apache.org/

This formula is keg-only.
Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple's CLT package contains apr.

/usr/local/Cellar/apr/1.5.1 (54 files, 1.4M)
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/apr.rb
==> Options
--universal
	Build a universal binary

**Comment by DomT4** [comment] 2015-02-01 18:34
If it was ` Poured from bottle ` then it isn't a universal build. Homebrew doesn't bottle the universal builds, as it's a custom build option.

Try ` brew remove apr apr-util ` and then ` brew install apr-util --universal ` and then try the SVN build again.

**Comment by bryonbean** [comment] 2015-02-01 18:43
Dominyk, that worked, I nearly have it installed (some issue with JavaHL). A sincere thanks for your help!

**Comment by DomT4** [comment] 2015-02-01 18:54
Awesome. Glad you've got it working okay! :+1:.

I'm still not sure why the ` universal ` build of ` svn ` isn't triggering a ` universal ` build of ` apr ` automatically, but at least doing so manually fixes the problem consistently.

**Comment by DomT4** [comment] 2015-02-01 21:21
Reproduced the initial reported problem here:

```
Undefined symbols for architecture i386:
  "_apr_uri_parse", referenced from:
      _main in svnrdump.o
ld: symbol(s) not found for architecture i386
```

That should be fixed by doing ` brew install apr-util --universal `. Working on fixing wider issues around the requirement not tagging in universal options automatically ASAP.

**Comment by dxh1011** [comment] 2015-02-02 03:08
Thank you very much, DomT4, that worked.

**Closed** 2015-02-02 03:08 UTC
