### ISSUE TITLE
NaCL fails to install on 10.9.4

### ISSUE THREAD

**Issue by thefiddler** [Homebrew/homebrew#30702] opened 2014-07-07 06:49 UTC
I am trying to install nacl via `brew install nacl -v` and I am getting the following error:
```
$ brew install nacl -v
==> Downloading http://hyperelliptic.org/nacl/nacl-20110221.tar.bz2
Already downloaded: /Library/Caches/Homebrew/nacl-20110221.tar.bz2
==> Verifying nacl-20110221.tar.bz2 checksum
tar xf /Library/Caches/Homebrew/nacl-20110221.tar.bz2
==> ./do
Warning: tried to install empty array to /usr/local/Cellar/nacl/20110221/include
Error: build/myrmbp/include/amd64/randombytes.h does not exist
```
This is running on a regular rmbp installation. One thing I notice is that the error refers to a hostname that is different than my real hostname (`myrmbp` instead of `my-rmbp`) - not sure if this makes a difference.

Build log here: https://gist.github.com/anonymous/2509437d0f3c61163d50

Any ideas?

**Comment by adamv** [comment] 2015-03-04 04:35
I cannot reproduce a build failure with this config:

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: git@github.com:adamv/homebrew.git
HEAD: 7656218af1593feca6c98aa563744cd871b2a8f4
Last commit: 2 hours ago
HOMEBREW_PREFIX: /Users/adamv/.hb
HOMEBREW_CELLAR: /Users/adamv/homebrew/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.9.5-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/adamv/.hb/bin/python => /Users/adamv/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_05
```

**Comment by DomT4** [comment] 2016-03-26 00:55
Can't reproduce here, and there's not much we can do with the information provided to help. If this is still an issue and there's any information you can provide to help us narrow down the circumstances we can look at this again, but closing for now as it seems to have gone dead.

Have opened https://github.com/Homebrew/homebrew/pull/50429 to make debugging in future a bit easier if necessary.

**Closed by DomT4** 2016-03-26 00:55 UTC
Labels: help wanted
