### ISSUE TITLE
`brew update` is (again) repeating the "Already up-to-date notice".

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew#49893] opened 2016-03-09 03:24 UTC
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I only have one tap, but `brew update` tells me twice that I'm already up-to-date.
```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Already up-to-date.
```
 I don't know how long it's been doing this, but it can't be more than two or three weeks.  (I usually just do `git pull`).

**Comment by chdiza** [comment] 2016-03-09 03:25
This seems like a repeat of #48469.

**Comment by UniqMartin** [comment] 2016-03-09 04:44
Do you happen to have `HOMEBREW_VERBOSE` set in your environment or are you passing either `--verbose` or `-v` to `brew update`? If so, all but the last `Already up-to-date.` is coming directly from `git` (its output is not supressed in verbose mode) and only the last one is coming from Homebrew (indistinguishable from the former due to identical wording).

The number of the former directly correlates with the number of Git repositories that are being updated (for most users this means Homebrew itself plus all taps).

**Comment by chdiza** [comment] 2016-03-09 04:52
I do have `HOMEBREW_VERBOSE` set, as I have for years.  Other than #48469, this behavior is unprecedented.

Also, the one tap that I have is not even a git repo.  It's a collection of local formulas; there is no `.git` dir in it anywhere.  There is only one git repo in my entire on-machine HB universe, namely, `HOMEBREW_REPOSITORY`.

**Comment by UniqMartin** [comment] 2016-03-09 05:12
Recently, there have been changes to the reporting side of `brew update` and I guess they have reintroduced this behavior. I think if you have verbose output enabled, then you actually want to see the output from both `git` and Homebrew, so this duplicated output is somewhat inevitable. Suppressing it on the Homebrew side as was done in #48469 doesn't make much sense (to me), as there will still be multiple instances of this line for those users who have Git-based taps installed.

Is this additional line actually an issue if you take into account the amounts of text that will otherwise be output in verbose mode for a typical run of `brew update`? The issue is purely cosmetic and doesn't even affect 99% of our users, who use Homebrew in its default non-verbose mode.

> Also, the one tap that I have is not even a git repo. It's a collection of local formulas; there is no .git dir in it anywhere.

That's why I wrote “for most users”. :wink:

**Comment by chdiza** [comment] 2016-03-09 06:46
> I think if you have verbose output enabled, then you actually want to see the output from both git and Homebrew,

Not *that* particular piece of output.  And it's not inevitable, it was fixed once before.

Note that, as in #48649, *the tap is irrelevant*.  After I obliterate my tap with  `brew untap $(brew tap)`, if I run `brew update` I still get two "Already.." messages.  So the second instance of the message is not the result of trying to update a tap.  It's just a needless echo.

If one DOES have taps tapped ("real" ones, git repos), then the problem is still there.  E.g., after tapping homebrew/x11:
```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Already up-to-date.
```
A simple fix like last time ought to eliminate the last line.  (That's the only one that's pointless.)  Users with `HOMEBREW_VERBOSE` set, whether they have tapped taps or not, should not have to see the redundant line.

**Comment by UniqMartin** [comment] 2016-03-09 07:25
> Not *that* particular piece of output. And it's not inevitable, it was fixed once before.

Let me be clear: I think I understand your issue with this behavior perfectly well, but I disagree that it's something worth fixing, because it's not broken. The duplication in the output only happens under very specific circumstances: (1) there are no updates, and (2) verbose output is enabled, and (3) the user has no taps (that are Git repositories). In all other instances the two lines you'd like to see merged mean two different things: the former reflects the status of a particular Git repository while the latter is related to *all* of Homebrew. Ideally, the output from your comment would look something like this:

```
==> Updating Git repository /use/local
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.

==> Updating Git repository /usr/local/Library/Taps/homebrew/homebrew-x11
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.

==> Summarizing Homebrew update
Already up-to-date.
```

I hope this helps to illustrate my point. Adding those headings would also make the verbose output much more useful, as it's currently almost impossible to tell which repository certain parts of the output refer to.

**Comment by chdiza** [comment] 2016-03-09 19:08
> The duplication in the output only happens under very specific circumstances:

It happens under (1) and (2) by themselves, (3) is irrelevant.  This is in effect what I reported in my previous post.  Far from being a freak circumstance, it happens iff verbose mode is on but there are no updates.

Anyway, I'd be perfectly happy if the *final* instance of the message---the one that apparently means "all updating-related tasks done"---said something other than "Already up-to-date".    Maybe "Homebrew update complete", or something.  Really, anything other than a message which misleadingly suggests that a `git pull` that never happened did happen.

**Comment by UniqMartin** [comment] 2016-03-09 19:58
> (3) is irrelevant.

Sorry to disagree, but it is relevant. If you read my other comment carefully (and I didn't fail to express myself too badly), while the phrase is identical, it's meaning is not. If there is more than one (remote) Git repository contributing to a Homebrew installation, then the final `Already up-to-date.` refers to Homebrew as a whole while all the other `Already up-to-date.` instances refer to individual Git repositories (that together form a specific Homebrew installation). That said, I totally understand that because of the identical wording the impression left is a different one.

Do the headings that I'm proposing in #49905—a refined version of the output snippet from <https://github.com/Homebrew/homebrew/issues/49893#issuecomment-194150998>—make the situation clearer and acceptable to you? I.e. do you think the headings are sufficient to get across what I tried to spell out above (in my first paragraph) and would make the repetition acceptable, because it is put into context? I'd appreciate a comment about this on #49905, that deals with two issues in verbose mode: (a) deparallelization to avoid output intermingling and (b) adding headings, to make it clearer to what repositories/operations certain outputs belongs to. Thanks!

**Comment by ilovezfs** [comment] 2016-03-13 13:17
@UniqMartin Did non-verbose brew update used to print "Already up-to-date" or is that new behavior?

**Comment by mikemcquaid** [comment] 2016-03-13 16:04
@ilovezfs It's existing behaviour.

**Comment by DomT4** [comment] 2016-03-14 03:15
Let's shuffle discussion over to the PR so it's not ongoing in dual locations: #49905

**Closed by DomT4** 2016-03-14 03:15 UTC
