### ISSUE TITLE
Failed `brew update` on El Capitan (OS X 10.11) Beta

### ISSUE THREAD

**Issue by ngocphamm** [Homebrew/homebrew#41665] opened 2015-07-13 15:54 UTC
I know it's beta, and I shouldn't complain if anything's wrong, but it was good last night and earlier this morning. Then now I have the following output. (My `brewu` is an alias to `brew update && brew outdated`)

```
~ ❯❯❯  brewu                                                                                        
error: unable to unlink old '.gitignore' (Permission denied)                                          
Error: Failure while executing: git pull --quiet origin refs/heads/master:refs/remotes/origin/master
```

Running the command again will get me to this
```
~ ❯❯❯  brewu                                                                                        
Stashing your changes:                                                                                
 M Library/Homebrew/cmd/doctor.rb                                                                     
 D Library/Homebrew/test/.gitignore                                                                   
error: unable to unlink old '.gitignore' (Permission denied)                                         
Error: Failure while executing: git pull --quiet origin refs/heads/master:refs/remotes/origin/master  
```

If anyone is running El Capitan, can you please confirm whether this is my issue or it's universal for homebrew under the beta OS? Thank you guys!

**EDIT:**
I don't know which `.gitignore` file the first run referring to, but the one under `Library/Homebrew/test` has `-rw-------` permissions, and I'm on the same admin user created since the start of the OS (2 years a go, I think).

**Comment by omega** [comment] 2015-07-13 16:38
I get a similar problem, but for me it also fails to unlink the old `README.md` for some reason :/ After the unsuccessful attempt there are a lot of new files and modified files as well

**Comment by omega** [comment] 2015-07-13 16:46
Running `brew doctor` told me that `/usr/local` was not writable by my user. `sudo chown $(USER):admin /usr/local` fixed that, and now `brew update` works again. Dunno if it would be worthwhile for `brew update` to also contain that check maybe?

**Comment by omega** [comment] 2015-07-13 16:47
So to be clear, this is probably not a 10.11 issue, but rather an "upgrade OS X"-issue, as that resets permissions on `/usr/local`

**Comment by ngocphamm** [comment] 2015-07-13 16:56
Yeah probably, @omega. The `chown` also fixed mine. Thanks for the quick response!

**Comment by aclissold** [comment] 2015-07-23 00:17
If there are issues when updating OS X, shouldn't brew be updated to anticipate this?

**Comment by tdsmith** [comment] 2015-07-23 00:34
What do you suggest?

**Comment by aclissold** [comment] 2015-07-23 03:12
Hmmm! I guess a permissions error like this one could technically happen for any reason and there's no way of telling if it was actually from an update or not. So maybe just a more helpful error message after `error: unable to unlink old '.gitignore' (Permission denied)`? Something to the effect of, "if you recently updated your installation of OS X, the permissions on /usr/local might have been reset and you may have to run sudo chown $USER:admin /usr/local" or whatever. Or a yes/no prompt to perform the fix automatically. Or is that too destructive of an action to recommend when there's no way of knowing if it's the right solution?

Also, I'm noticing that this issue and #41690 are duplicates, and similar to #41150 which is closed yet being tracked in #40837. Maybe #41150 should still be open?

**Comment by tdsmith** [comment] 2015-07-23 03:34
Thanks for thinking about it and for linking these issues together; I agree that doing something more proactive about permissions problems makes sense, especially if we're about to see a big pulse of affected users. `update` isn't interactive and we should probably keep it that way but we ought to be able to detect this and print something more helpful.

**Comment by DomT4** [comment] 2015-07-23 03:39
We don't store the information that someone has recently updated their OS X version anywhere. Regularly telling everyone on 10.11 to `sudo chown -R $(whoami):admin HOMEBREW_PREFIX` regardless of whether they have a problem or not is fairly bleh.

We could check ownership, but if your Homebrew is outside of `/usr/local` in a user directory or similar if doesn't necessarily have to use admin rights AFAIK. Likewise not everything in the `HOMEBREW_PREFIX` needs the same set of access permissions.

This is going to be kind of tricky to iron out what we can detect that is the same across every user but doesn't lob the warning at people needlessly :/.

**Comment by tdsmith** [comment] 2015-07-23 03:41
If git fails, we can try writing a probe file to HOMEBREW_PREFIX, and if it fails with a permissions error, we can print advice.

**Comment by DomT4** [comment] 2015-07-23 03:41
Unless the problem just impacts one of two already existing files, rather than the whole directory?

**Comment by omega** [comment] 2015-07-23 04:53
Catching this error would have been as simple as checking for write access to the homebrew prefix. It won't catch everything, but I think homebrew would always need  write access there? Brew doctor checks for it at least

**Comment by bbiao** [comment] 2015-07-23 07:37
I have checked the /usr/local permissions on 10.10, it is owned by user root and group admin. So use the command

sudo chown root:admin /usr/local

will fix the problem.

**Comment by DomT4** [comment] 2015-07-23 14:02
`/usr/local` itself should be owned by `$(whoami):admin`, *not* root.

**Comment by kommen** [comment] 2015-07-27 12:20
JFYI, as I had the same issue after upgrading to 10.11, I filed a radar: http://openradar.appspot.com/21891797

[For what it's worth, I have had good experiences getting OS X migration/upgrade issues fixed by Apple rather quickly by filing the appropriate radars and pointing to github issues/stackoverflow threads/etc.]

**Comment by kommen** [comment] 2015-08-12 07:49
Got a reply on my radar from Apple:

> This issue behaves as intended based on the following:
This is expected. 
El Capitan expects /usr/local to have the specific permissions it sets during installation.
We are now closing this bug report.

This looks like after upgrading to 10.11 everyones `/usr/local` owner will be reset to `root:wheel`

**Comment by mikemcquaid** [comment] 2015-08-12 08:10
Thanks @kommen that's good to know; we'll need to work out how to best handle that.

**Comment by XMap** [comment] 2015-08-12 08:52
@mikemcquaid @kommen  I have install php56 success . on OS X 10.11 .

By . Brew install libxml2   & brew link libxml2 .
First of all . you need set /usr/local to  $(whoami):admin

And  .Download the XCode 7 Beta .
Rename it to Xcode

**Comment by kommen** [comment] 2015-08-14 12:12
One more follow up: I asked if Apple thinks that changing it back to `$(whoami):admin` after upgrading to 10.11 would cause unexpected system behavior. Got this as a reply:

> El Capitan doesn't place any system files in /usr/local, but it does set permissions on the /usr/local directory itself during upgrade, and may do so at other times.

Doesn't really answer my question, but for me this sounds like a "don't do that". But maybe I'm just misinterpreting that.

**Comment by mikemcquaid** [comment] 2015-08-14 13:23
> Doesn't really answer my question, but for me this sounds like a "don't do that". But maybe I'm just misinterpreting that.

I don't know if it's as strong as that but it's definitely a "this will happen some times and you should probably try and handle that".

**Comment by DomT4** [comment] 2015-08-14 16:03
I think @tdsmith is still working on a message to combat this in #42048.

**Comment by djKooks** [comment] 2015-08-21 14:21
Hello,
I'm facing similar problem when using 'brew update'

error: The following untracked working tree files would be overwritten by merge:
	Library/Formula/pdf2svg.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

I tried sudo chown $(USER):admin /usr/local but it doesn't help.
Do somebody know about other way to solve?

**Comment by djKooks** [comment] 2015-08-21 14:31
'brew doctor' shows error like this.

Error: Failed to import: scantailor
version '{"0.9.11"=>Formulary::FormulaNamespace52be542c7b6258a69ad870249f7fd402::Scantailor::Version}' should be a string

**Comment by DomT4** [comment] 2015-08-21 15:38
^ Try `cd $(brew --prefix) && git fetch && git reset --hard origin/master`.

**Comment by djKooks** [comment] 2015-08-23 12:44
@DomT4 I got it. It works~Thanks.

**Comment by sshaw** [comment] 2015-09-04 23:08
In my case the change to `/usr/local`'s permissions was caused by GnuPG installer.

**Comment by sshaw** [comment] 2015-09-04 23:09
And after running `brew update`:

```
...
Library/Homebrew/test/test_language_module_requirement.rb already exists, no checkout
Library/Homebrew/test/test_migrator.rb already exists, no checkout
Library/Homebrew/test/test_mpi_requirement.rb already exists, no checkout
Library/Homebrew/test/test_sandbox.rb already exists, no checkout
Library/Homebrew/test/test_x11_requirement.rb already exists, no checkout
Library/Homebrew/test/testball_bottle.rb already exists, no checkout
Library/Homebrew/utils/fork.rb already exists, no checkout
Library/Homebrew/utils/git.rb already exists, no checkout
Could not restore untracked files from stash
Error: Failure while executing: git stash pop --quiet
```

**Comment by DomT4** [comment] 2015-09-04 23:13
> In my case the change to /usr/local's owner was caused by GnuPG's installer.

Are you referring to GPGTools? If so, [known issue](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/doctor.rb#L86-L103). The two don't really play nicely.

**Comment by sshaw** [comment] 2015-09-04 23:22
> Are you referring to GPGTools? If so, known issue. It doesn't really play nicely with Homebrew.

Negative. It was [GnuPG for OS X](http://sourceforge.net/p/gpgosx/docu/Download/), running 10.9.5.

**Comment by DomT4** [comment] 2015-09-04 23:28
Hmm. Maybe we need to warn about that as well if it borks permissions :confused:. Just out of curiosity, is there a reason to use GnuPG for OS X rather than `brew install gpg2` or `brew install homebrew/versions/gpg21`?

**Comment by sshaw** [comment] 2015-09-04 23:44
> Just out of curiosity, is there a reason to use GnuPG for OS X rather than brew install gpg2 or brew install homebrew/versions/gpg21?

No reason. For some things it does not occur to me that Homebrew may have a formula. For others I check and there's none.

**Comment by DomT4** [comment] 2015-09-05 02:03
Ah, okay. Just wondered if there was something we could improve there. I'll check out the permissions issue, but you can fix it by doing the standard:

```
sudo chown -R $(whoami) /usr/local
```

**Comment by loybert** [comment] 2015-09-10 17:52
Thx @DomT4 :+1:

**Comment by spaquet** [comment] 2015-09-18 18:20
@DomT4 +1

**Comment by diegorv** [comment] 2015-09-19 14:43
@DomT4 :+1:

**Comment by nreilly** [comment] 2015-09-20 03:57
According to https://developer.apple.com/library/prerelease/mac/releasenotes/General/rn-osx-10.11/

>System file permissions are automatically protected, and updated, during Software Updates. The Repair Permissions function is no longer necessary.

It seems this would need to be corrected after every sw update.

**Comment by DomT4** [comment] 2015-09-20 17:33
There's now a document for this [here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md) which the Troubleshooting page points at. Hopefully clears up future confusion/problems/etc. We'll be adding a `brew doctor`/etc warning soon as well.

**Comment by donaldallen** [comment] 2015-09-23 18:41
@DomT4 Thanks for the documentation. I already had /usr/local, brew installed, and did the suggested chown change, but to no avail. Still had brew doctor / brew update hang. I ended up having to uninstall brew using the script you provide in the FAQ, reinstalled, and now everything is fine and dandy.

**Comment by say2joe** [comment] 2015-09-23 21:28
Did not work: sudo chown -R $(whoami):staff /usr/local
Worked: sudo chown -R $(whoami):admin /usr/local

**Comment by cwahlfeldt** [comment] 2015-09-30 23:02
Just updated to the official release of el capitan today. brew keeps giving me this error. `sudo chown -R $(whoami):admin /usr/local` is not working for me.

**Comment by DomT4** [comment] 2015-10-01 02:22
@cwahlfeldt Can you `/bin/ls -lhO /usr` and provide the readout there? Thanks!

**Comment by bswinnerton** [comment] 2015-10-01 02:41
Could this have anything to do with El Capitan's new ["System Integrity Protection"](http://arstechnica.com/apple/2015/09/os-x-10-11-el-capitan-the-ars-technica-review/8/#h1)?

**Comment by DomT4** [comment] 2015-10-01 02:43
^ [Yes](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md)

**Comment by bswinnerton** [comment] 2015-10-01 02:44
Ah, I missed that. Thanks @DomT4!

_steps back into the shadows_

**Comment by dexterddit** [comment] 2015-10-01 04:45
Yup that the ownership was the issue . Works fine again . Thanks

**Comment by cwahlfeldt** [comment] 2015-10-01 14:13
Wasnt working yesterday but is working fine now. Thanks Ya'll. I just used `sudo chown -R $(whoami):admin /usr/local` and it magically worked.

**Comment by pchaganti** [comment] 2015-10-01 14:46
Yep. Works super with the chown :+1:

**Comment by chaseholland** [comment] 2015-10-01 18:22
Had to run `brew doctor` after the chown, but it works now for me, as well. :+1:

**Comment by tmkasun** [comment] 2015-10-01 19:56
For me 
`xcode-select --install`
Fixed the problem

**Comment by marcoslhc** [comment] 2015-10-01 22:36
`sudo chown -R $(whoami):admin /usr/local` is a must, but also helps re installing ruby via RVM

**Comment by mutech** [comment] 2015-10-03 11:23
Probably this discussion had been on the table many a times in the past, but looking at the opinionated response of Apple:

I find it a bad idea to use a directory like /usr/local which is by old conventions used to install local software to be shared by users and about all other Unix systems controlled by root and to impose the requirement that it's owned by a or "the" user.

If I understand the rationale behind it right, this is done because first a lot of software packages (brew formulae) expect /usr/local/ and it "would be too hard" to fix them all. That's the reason why we have /usr/local. The reason why we don't install packages as root is less clear to me, but what I remember is that using root is not much more secure but much less convenient. I disagree, but maybe not too much.

Until now, I found that acceptable, even though a bit ugly. But since now each and every user has to fix permissions, I think it's time to get it right. Getting it right means, in my opinion, to make software packages location independent, which most of them should be out of the box (thanks to autoconfigure & friends). Brew formulae should define a flag indicating whether a package is location independent. If a home-brew installation uses a different location, search should not report location dependent packages and their dependencies (unless given some option). That would allow for a smooth transition. Once there is no reason to enforce the /usr/local prefix, it should be possible for users to decide whether they want to use a traditional UNIX setup (keeping /usr/local but root owned) or install software in a non-controlled location like /opt/homebrew, where it can be owned by anybody. 

What do you guys think about that?

**Comment by CodeGnome** [comment] 2015-10-03 13:24
I haven't run into any problems yet personally, but if the tree needs to be chowned by the admin group, then it seems likely that the tree will need `chmod -R g+w "$(brew --prefix)"` as well. Otherwise, it seems that after upgrading, files are r-x for admin, but files and directories lack write permissions for the group.

This seems like it might be particularly important on a system where `brew --prefix` is shared or managed by more than one user. YMMV.

**Comment by hinok** [comment] 2015-10-04 00:47
In my case, permission was only changed for `/usr/local`, not for all files inside `/usr/local`.
Recursive option in chown/chmod can be quite dangerous if someone has installed eg. mysql from its official package (it creates `_mysql` user and sets permissions for some files).

Check your permissions inside `/usr/local` and maybe only this one will fix. In my case, it helped.
```
sudo chown $(whoami):admin /usr/local
```

**Comment by DomT4** [comment] 2015-10-04 00:52
> Recursive option (-R) in chown/chmod can be quite dangerous if someone has installed eg. mysql from its official package (it creates _mysql user and sets permissions for some files).

We're working towards a command users can run that will only `chown` files known to belong to Homebrew, which will ease those concerns in future, presuming it proves relatively feasible.

**Comment by DomT4** [comment] 2015-10-04 13:50
Going to close this one for now since there's now a warning thrown by `brew` & there's a few of these threads floating around.

Please feel free to open a new issue on permission errors if the recommended `brew doctor` steps fail to fix any issues you see. Thanks!

**Closed by DomT4** 2015-10-04 13:50 UTC
Labels: 10.11
