### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by lorddaedra** [Homebrew/homebrew#42594] opened 2015-08-07 06:25 UTC
brew update (10.11 public beta)
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

I tried again and it works... Submitting this because of "Please report this bug:" message

**Comment by bfontaine** [comment] 2015-08-07 06:32
Closed as a duplicate of #42553.

**Closed by bfontaine** 2015-08-07 06:32 UTC
