### ISSUE TITLE
unable to upgrade postgis without upgrading postgresql

### ISSUE THREAD

**Issue by EconGeo** [Homebrew/homebrew#35165] opened 2014-12-21 09:32 UTC
I am trying to upgrade postgresql without upgrading my version postgresql.  I have tried this

```$ brew install postgis --ignore-dependencies
==> Downloading http://download.osgeo.org/postgis/source/postgis-2.1.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/postgis-2.1.4.tar.gz
Error: No such file or directory - /usr/local/Cellar/postgresql/9.4.0```

but the ```postgis``` formula looks for only the most recent version of postgresql via the updated ```postgresql``` formula.  If I run ```brew install postgis``` without the ``--ignore-dependencies`` flag, the formula automatically starts installing postgresql 9.4.0.  I don't think postgis should automatically be installing newer versions of postgresql without a specific user request to do so.  Going through a major upgrade from 9.3.5 to 9.4.0 is a  hassle and I think a lot of database users would like to choose when to go through a major upgrade.  For example, some people may still be running 9.1, but would like the ability to install the latest postgis.  Any guidance on how I can accomplish this without upgrading postgresql?

**Comment by jacknagel** [comment] 2015-01-05 04:13
Closing per the workarounds posted. Otherwise, this is working as intended. We don't support not upgrading dependencies when updating dependents.

**Closed by jacknagel** 2015-01-05 04:13 UTC

**Comment by EconGeo** [comment] 2015-01-09 00:46
doing the checkout that @matallo  recommended doesn't work.  Homebrew complains about not knowing what to do with Xcode 6.1.1.   Trying the switch method doesn't work either, as postgresql complains about not being able to find libraries linked to by postgis.2.1.so such as cgal.  Any other ideas or is there a good way to move my data over to 9.4.  What a nightmare.  I again have to reiterate that postgis formula should check if postgresql is installed, not update postgresql automatically to the newest version.  Upgrading to a major release of a server is not the same as updating other types of software.
