### ISSUE TITLE
Latest Homebrew release can't install ruby and mysql

### ISSUE THREAD

**Issue by manueljordan** [Homebrew/homebrew#47546] opened 2015-12-31 01:19 UTC
I am working on Mac 10.8.5

I have worked with Homebrew since two years ago without any problem. 

And I have now two problems as follows:

I run twice `brew doctor`

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.
```

When I want install ruby I always get:

```
….
curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/openssl-1.0.2e.tar.gz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/312f6228/openssl/fix-Apple-clang-version-detection.patch
######################################################################## 100.0%
==> Patching
patching file crypto/aes/asm/aesni-mb-x86_64.pl
patching file crypto/aes/asm/aesni-sha1-x86_64.pl
patching file crypto/aes/asm/aesni-sha256-x86_64.pl
patching file crypto/bn/asm/rsaz-x86_64.pl
patching file crypto/bn/asm/x86_64-mont.pl
patching file crypto/bn/asm/x86_64-mont5.pl
patching file crypto/ec/asm/ecp_nistz256-x86_64.pl
patching file crypto/modes/asm/aesni-gcm-x86_64.pl
patching file crypto/modes/asm/ghash-x86_64.pl
patching file crypto/sha/asm/sha1-mb-x86_64.pl
patching file crypto/sha/asm/sha1-x86_64.pl
patching file crypto/sha/asm/sha256-mb-x86_64.pl
patching file crypto/sha/asm/sha512-x86_64.pl
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2e --openssldir=/usr/local/etc/openssl no-ssl2 zlib-dynamic shared enable-cms darwin64-x86_64-cc enable-ec_nistp_64_gcc_1
==> make depend
^[[5~==> make
Last 15 lines from /Users/manueljordan/Library/Logs/Homebrew/openssl/03.make:
x86_64-mont.s:966:2: error: invalid instruction mnemonic 'adcxq'
 adcxq %rax,%r12
 ^~~~~
x86_64-mont.s:967:2: error: invalid instruction mnemonic 'adoxq'
 adoxq %r15,%r13
 ^~~~~
x86_64-mont.s:972:2: error: invalid instruction mnemonic 'adcxq'
 adcxq %rax,%r13
 ^~~~~
x86_64-mont.s:973:2: error: invalid instruction mnemonic 'adoxq'
 adoxq %rbp,%r15
 ^~~~~
make[2]: *** [x86_64-mont.o] Error 1
make[1]: *** [subdirs] Error 1
make: *** [build_crypto] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
openssl: full path to openssl in post_install https://github.com/Homebrew/homebrew/pull/47536
openssl failed to build on 10.9 https://github.com/Homebrew/homebrew/issues/46053
openssl: add 'enable-ssl-trace' option https://github.com/Homebrew/homebrew/pull/45250
wine dependency openssl/1.0.2d https://github.com/Homebrew/homebrew/issues/43752
```

When I want install mysql, I always get:

```
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.4.1: 1,980 files, 30.3M, built in 3 minutes 33 seconds
==> Installing mysql dependency: boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "boost"
Download failed: https://downloads.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2
```

* I have deleted each formula
* I have uninstalled and installed again Homebrew (December 30 2015)

And the same problems persist, all the output data shown above is after the re installation.

What is wrong?

**Comment by mistydemeo** [comment] 2015-12-31 01:31
Regarding your second problem, the site that hosts boost is currently down for maintenance: https://twitter.com/sfnet_ops/status/682370691396571138

Regarding your first problem, have you tried following Homebrew's instruction to update your Command Line Tools?

**Comment by manueljordan** [comment] 2015-12-31 02:29
Thanks by the clarification about the second problem.

About the first: 
I have `Software  OS X 10.8.5 (12F2560)`
It is Mountain Lion according with:

* https://es.wikipedia.org/wiki/OS_X#Versi.C3.B3n_10.8:_.C2.ABMountain_Lion.C2.BB

Now I am on `https://developer.apple.com/downloads/` and with the search for `Command Line Tools`, the latest updated release for my OS version is April 2014 (see the image)

![commandlinetools](https://cloud.githubusercontent.com/assets/2552795/12060328/3aca0484-af3b-11e5-8f77-0592c0e56eb5.png)

So I am not able to do a new update. Since my OS is old.

Futhermore the note says:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

```

it from `brew doctor`:

```


Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.
```
I only have installed Xcode through  `https://developer.apple.com/downloads`

If exists other way to give data. Please indicate me.

Thank you.

**Comment by DomT4** [comment] 2016-01-03 17:07
What does `/usr/bin/curl -I -v https://www.openssl.org/source/openssl-1.0.2e.tar.gz` return?

**Comment by manueljordan** [comment] 2016-01-03 19:09
Hello

I have the following:

```
Manuels-MacBook-Pro:~ manueljordan$ /usr/bin/curl -I -v https://www.openssl.org/source/openssl-1.0.2e.tar.gz
* About to connect() to www.openssl.org port 443 (#0)
*   Trying 194.97.150.234...
* connected
* Connected to www.openssl.org (194.97.150.234) port 443 (#0)
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to www.openssl.org:443
* Closing connection #0
curl: (35) Unknown SSL protocol error in connection to www.openssl.org:443
Manuels-MacBook-Pro:~ manueljordan$
```

Thank you.

**Comment by DomT4** [comment] 2016-01-03 19:18
Thanks, that's useful.

Do you have Homebrew's `curl` installed/can you install Homebrew's `curl` and then try `/usr/local/opt/curl/bin/curl -I -v https://www.openssl.org/source/openssl-1.0.2e.tar.gz`?

**Comment by manueljordan** [comment] 2016-01-03 19:26
Hello 

I just _reinstalled_ Homebrew:

```
Manuels-MacBook-Pro:~ manueljordan$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown manueljordan /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 3929, done.
remote: Compressing objects: 100% (3771/3771), done.
remote: Total 3929 (delta 32), reused 2291 (delta 20), pack-reused 0
Receiving objects: 100% (3929/3929), 3.42 MiB | 95.00 KiB/s, done.
Resolving deltas: 100% (32/32), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at 9e9067e config: split conditional
==> Installation successful!
==> Next steps
Run `brew help` to get started
Manuels-MacBook-Pro:~ manueljordan$
```

brew doctor

```
Manuels-MacBook-Pro:~ manueljordan$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.
Manuels-MacBook-Pro:~ manueljordan$
```
About install curl.

```
Manuels-MacBook-Pro:~ manueljordan$ brew install curl
==> Installing dependencies for curl: pkg-config
==> Installing curl dependency: pkg-config
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.29 --disable-host-tool --with-internal-glib --with-pc-path=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgco
==> make
==> make check
==> make install
🍺  /usr/local/Cellar/pkg-config/0.29: 10 files, 664.6K, built in 1 minute 1 second
==> Installing curl
==> Downloading https://github.com/bagder/curl/releases/download/curl-7_46_0/curl-7.46.0.tar.bz2
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/569041/f114ec62-98cb-11e5-9249-f9f1db07c07b.bz2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAISTNZFOVBIJ
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/curl/7.46.0 --with-darwinssl --without-libssh2 --without-libidn --without-libmetalink --without-gssapi --without-li
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/curl/lib
    CPPFLAGS: -I/usr/local/opt/curl/include


zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/curl/7.46.0: 359 files, 2.5M, built in 57 seconds
Manuels-MacBook-Pro:~ manueljordan$
```

About your command:

```
Manuels-MacBook-Pro:~ manueljordan$ /usr/local/opt/curl/bin/curl -I -v https://www.openssl.org/source/openssl-1.0.2e.tar.gz
*   Trying 194.97.150.234...
*   Trying 2001:608:c00:180::1:ea...
* Immediate connect fail for 2001:608:c00:180::1:ea: No route to host
* Connected to www.openssl.org (194.97.150.234) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.openssl.org
* Server certificate: GlobalSign Domain Validation CA - SHA256 - G2
* Server certificate: GlobalSign Root CA
> HEAD /source/openssl-1.0.2e.tar.gz HTTP/1.1
> Host: www.openssl.org
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Sun, 03 Jan 2016 19:25:49 GMT
Date: Sun, 03 Jan 2016 19:25:49 GMT
< Server: Apache/2.4.7 (Ubuntu)
Server: Apache/2.4.7 (Ubuntu)
< Strict-Transport-Security: max-age=31536000; includeSubDomains
Strict-Transport-Security: max-age=31536000; includeSubDomains
< Last-Modified: Thu, 03 Dec 2015 18:03:11 GMT
Last-Modified: Thu, 03 Dec 2015 18:03:11 GMT
< ETag: "50356b-52602343e558b"
ETag: "50356b-52602343e558b"
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Length: 5256555
Content-Length: 5256555
< Content-Type: application/x-gzip
Content-Type: application/x-gzip

<
* Connection #0 to host www.openssl.org left intact
Manuels-MacBook-Pro:~ manueljordan$
```

I really appreciate your quick support.

**Comment by DomT4** [comment] 2016-01-03 19:59
Thanks. Give me an hour or so, going to poke around a VM to flesh out a hunch.

**Comment by DomT4** [comment] 2016-01-03 21:02
https://github.com/Homebrew/homebrew/pull/47646

Essentially, needing Homebrew's `curl` on 10.8 and below is likely to become a thing.

It looks like OpenSSL's server (Along with a bunch of GNOME ones now) rejects anything below TLSv1.1 and Mountain Lion's curl is capped at talking SSLv3 in handshake and TLSv1.0 for connection.

**Comment by DomT4** [comment] 2016-01-03 21:04
As for the build error, I thought that was fixed by https://github.com/Homebrew/homebrew/blob/master/Library/Formula/openssl.rb#L25-L34. Hmm.

**Comment by manueljordan** [comment] 2016-01-04 15:17
Hello DomT4

Thanks a lot by your valuable support. I did the following:

```
Manuels-MacBook-Pro:~ manueljordan$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.
```
And

```
Manuels-MacBook-Pro:~ manueljordan$ brew update
Updated Homebrew from 9e9067eb to 9b0114ae.
==> New Formulae
gpa
==> Updated Formulae
abcde                         exiftool                      libdvdcss                     pandoc                        pngcrush                      zopfli
amdatu-bootstrap              iso-codes                     mkvtoolnix                    pandoc-citeproc               sound-touch
==> Renamed Formulae
offline-imap -> offlineimap
Manuels-MacBook-Pro:~ manueljordan$ brew list
curl		pkg-config
Manuels-MacBook-Pro:~ manueljordan$ brew upgrade curl
Error: curl 7.46.0 already installed
Manuels-MacBook-Pro:~ manueljordan$
```

About `brew install ruby` I have the following error:

```
Manuels-MacBook-Pro:~ manueljordan$ brew install ruby
==> Installing dependencies for ruby: readline, libyaml, makedepend, openssl
==> Installing ruby dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.mountain_lion.bottle.tar.gz
######################################################################## 100.0%
==> Pouring readline-6.3.8.mountain_lion.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.


Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 40 files, 2M
==> Installing ruby dependency: libyaml
==> Downloading https://homebrew.bintray.com/bottles/libyaml-0.1.6_1.mountain_lion.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libyaml-0.1.6_1.mountain_lion.bottle.tar.gz
🍺  /usr/local/Cellar/libyaml/0.1.6_1: 7 files, 328.0K
==> Installing ruby dependency: makedepend
==> Downloading https://homebrew.bintray.com/bottles/makedepend-1.0.5.mountain_lion.bottle.tar.gz
######################################################################## 100.0%
==> Pouring makedepend-1.0.5.mountain_lion.bottle.tar.gz
🍺  /usr/local/Cellar/makedepend/1.0.5: 7 files, 71.8K
==> Installing ruby dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2e.tar.gz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/312f6228/openssl/fix-Apple-clang-version-detection.patch
######################################################################## 100.0%
==> Patching
patching file crypto/aes/asm/aesni-mb-x86_64.pl
patching file crypto/aes/asm/aesni-sha1-x86_64.pl
patching file crypto/aes/asm/aesni-sha256-x86_64.pl
patching file crypto/bn/asm/rsaz-x86_64.pl
patching file crypto/bn/asm/x86_64-mont.pl
patching file crypto/bn/asm/x86_64-mont5.pl
patching file crypto/ec/asm/ecp_nistz256-x86_64.pl
patching file crypto/modes/asm/aesni-gcm-x86_64.pl
patching file crypto/modes/asm/ghash-x86_64.pl
patching file crypto/sha/asm/sha1-mb-x86_64.pl
patching file crypto/sha/asm/sha1-x86_64.pl
patching file crypto/sha/asm/sha256-mb-x86_64.pl
patching file crypto/sha/asm/sha512-x86_64.pl
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2e --openssldir=/usr/local/etc/openssl no-ssl2 zlib-dynamic shared enable-cms darwin64-x86_64-cc enable-ec_nistp_64_gcc_1
==> make depend
==> make
Last 15 lines from /Users/manueljordan/Library/Logs/Homebrew/openssl/03.make:
x86_64-mont.s:966:2: error: invalid instruction mnemonic 'adcxq'
 adcxq %rax,%r12
 ^~~~~
x86_64-mont.s:967:2: error: invalid instruction mnemonic 'adoxq'
 adoxq %r15,%r13
 ^~~~~
x86_64-mont.s:972:2: error: invalid instruction mnemonic 'adcxq'
 adcxq %rax,%r13
 ^~~~~
x86_64-mont.s:973:2: error: invalid instruction mnemonic 'adoxq'
 adoxq %rbp,%r15
 ^~~~~
make[2]: *** [x86_64-mont.o] Error 1
make[1]: *** [subdirs] Error 1
make: *** [build_crypto] Error 1

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
openssl: fix headers for universal build https://github.com/Homebrew/homebrew/pull/47652
openssl: load zlib from an explicit path https://github.com/Homebrew/homebrew/pull/47650
openssl: add 'enable-ssl-trace' option https://github.com/Homebrew/homebrew/pull/45250
Manuels-MacBook-Pro:~ manueljordan$ ~
```

I have no idea what is wrong.

I don't know if 

```
These open issues may also help:
openssl: fix headers for universal build https://github.com/Homebrew/homebrew/pull/47652
openssl: load zlib from an explicit path https://github.com/Homebrew/homebrew/pull/47650
openssl: add 'enable-ssl-trace' option https://github.com/Homebrew/homebrew/pull/45250
```
Have some clues...

BTW: Some months ago, I have tried to install through Homebrew `wine`. I had some problems about its installation process (a lot of `make` and finally an error - I don't remember the error) and therefore I have uninstalled. Even with that (uninstallation) all remain working fine: Git, Ruby, MySQL (about formulas installed) I don't know if exists some weird relation. 

But since I did `brew update` and `upgrades` for ruby I am with this problem. 

Take your time in resolve this. Really I enjoy work with `Homebrew` :)

**Comment by DomT4** [comment] 2016-01-06 22:52
@manueljordan Can you provide a full `brew gist-logs openssl` there? Thanks. I suspect it's related to the outdated CLT warning, but will make it easier to check with a full debug log.

**Comment by manueljordan** [comment] 2016-01-11 13:28
@DomT4 

Seems something extra is needed it.

```
Manuels-MacBook-Pro:~ manueljordan$ brew gist-logs openssl
https://gist.github.com/e061d8479ef3e8dee122
Manuels-MacBook-Pro:~ manueljordan$
```

**Comment by udaykadaboina** [comment] 2016-01-20 20:45
:+1: Great this worked for me! :)

**Comment by ql** [comment] 2016-02-02 11:15
after brew update the problem is still here for me: https://gist.github.com/ae179fd863cfb58be029

**Comment by DomT4** [comment] 2016-02-02 16:09
This is still interesting:

> Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.

That's appearing for everyone who still has the OpenSSL problem. I suspect I can't directly link it because of the way Apple guards their download server but please ensure you've downloaded & installed this CLT package on OS X 10.8.x -

<img width="735" alt="screen shot 2016-02-02 at 16 09 06" src="https://cloud.githubusercontent.com/assets/6998367/12755451/5ce97a94-c9c7-11e5-8b27-f07d8734c3bc.png">

**Comment by DomT4** [comment] 2016-03-20 03:39
After some pretty extensive local testing over the last few weeks I was only able to reproduce this _prior_ to installing the updated Command Line Tools package either from the Apple Developer website or inside Xcode.app's `Preferences => Downloads` window.

Please ensure you've done that if you're having problems and ding me and I'll reopen, but I haven't been able to reproduce at all with the updated CLT.

**Closed by DomT4** 2016-03-20 03:39 UTC
Labels: 10.8

**Comment by danmoore2205** [comment] 2016-03-29 13:09
thanks @DomT4 for the info, this fixed my problems on Mountain Lion. *hat tip*
