### ISSUE TITLE
possibly sourceforge has manipulated boost  SHA256 mismatch

### ISSUE THREAD

**Issue by mgaldzic** [Homebrew/homebrew#41801] opened 2015-07-17 00:42 UTC
On attempting install boost --build-from-source

I see the following error - sounds like sourceforge has manipulated boost

Error: SHA256 mismatch
Expected: fdfc204fc33ec79c99b9a74944c3e54bd78be4f7f15e260c0e2700a36dc7d3e5
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/boost-1.58.0.tar.bz2

Not sure where to report this, trying here. Maybe someone here understands how brew works and can direct this to the proper place. Pretty sure the fix is to download boost from a better source
 like http://www.boost.org/users/history/version_1_58_0.html

**Comment by tdsmith** [comment] 2015-07-17 00:45
Thanks for reporting. Sourceforge is returning HTML instead of tarballs because they're in disaster recovery mode; this is frustrating but not sinister. Closing as duplicate of #41778.

**Closed by tdsmith** 2015-07-17 00:45 UTC

**Comment by polidore** [comment] 2015-07-17 12:58
thanks
