### ISSUE TITLE
broken ffmpeg build with openjpeg

### ISSUE THREAD

**Issue by dericed** [Homebrew/homebrew#42450] opened 2015-08-04 13:53 UTC
The openjpeg formula was upgraded from 1.5.1 to 1.5.2. ffmpeg doesn't seem to support this version, so if I run `brew install ffmpeg --with-openjpeg` then I get a broken ffmpeg. 
```
ffmpeg 
dyld: Library not loaded: /usr/local/lib/libopenjpeg.1.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
Trace/BPT trap: 5
```

Is there a way to have ffmpeg use the non-current openjpeg lib?

**Comment by mistydemeo** [comment] 2015-08-04 14:41
Looks like the dylib version changed, possibly not on purpose. It installs:

```
/usr/local/lib/libopenjpeg.1.5.2.dylib
/usr/local/lib/libopenjpeg.5.dylib
/usr/local/lib/libopenjpeg.dylib
```

**Comment by mistydemeo** [comment] 2015-08-04 15:02
Actually, it looks like `5` is the corect soversion: https://github.com/uclouvain/openjpeg/blob/openjpeg-1.5/CMakeLists.txt#L38-L48

```cmake
# Because autotools does not support X.Y notation for SOVERSION, we have to use
# two numerorations, one for the openjpeg version and one for openjpeg soversion
# version | soversion
#   1.0   |  0
#   1.1   |  1
#   1.2   |  2
#   1.3   |  3
#   1.4   |  4
#   1.5   |  5
#   1.5.1 |  5
#   2.0   |  6
```

I wonder why yours is `.1.dylib`?

**Comment by dunn** [comment] 2015-08-04 15:24
I can't reproduce this.  Did you reinstall ffmpeg after upgrading to the new version of openjpeg?

**Comment by dericed** [comment] 2015-08-04 16:39
I just ran `brew uninstall` on both openjpeg and ffmpeg, then `brew update`. Then tried to reinstall with `brew install ffmpeg --with-openjpeg`. Errors again:

```
ffmpeg --with-openjpeg
==> Installing ffmpeg dependency: openjpeg
==> Downloading https://homebrew.bintray.com/bottles/openjpeg-1.5.2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openjpeg-1.5.2.yosemite.bottle.tar.gz
==> Pouring openjpeg-1.5.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/openjpeg/1.5.2: 22 files, 432K
==> Installing ffmpeg
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ffmpeg-2.7.2.tar.bz2
Package libopenjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libopenjpeg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libopenjpeg' found
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.7.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --enable-o
==> make install
==> Caveats
FFmpeg has been built without libfaac for licensing reasons;
libvo-aacenc is used by default.
To install with libfaac, you can:
  brew reinstall ffmpeg --with-faac

You can also use the experimental FFmpeg encoder, libfdk-aac, or
libvo_aacenc to encode AAC audio:
  ffmpeg -i input.wav -c:a aac -strict experimental output.m4a
Or:
  brew reinstall ffmpeg --with-fdk-aac
  ffmpeg -i input.wav -c:a libfdk_aac output.m4a
==> Summary
🍺  /usr/local/Cellar/ffmpeg/2.7.2: 207 files, 43M, built in 5.4 minutes
```

So I think I fresh reinstall works, but I have multiple computers with broken ffmpegs after running a `brew update && brew upgrade```.

**Comment by dunn** [comment] 2015-08-04 16:53
I think the problem is that the pkg-config file is named `libopenjpeg1.pc` instead of `libopenjpeg.pc`.  @mistydemeo, should we tweak the ffmpeg formula, or is this more likely a mistake on the openjpeg side?

**Comment by dunn** [comment] 2015-08-04 16:56
The pkg-config file for openjpeg 2.1.0 is called `libopenjp2.pc`, so leaving this one named `libopenjpeg.pc` wouldn't have caused any sort of conflict.

**Comment by mistydemeo** [comment] 2015-08-04 17:00
I think the problem isn't the .pc file but the dylib name. Looking at the bottles, 1.5.1 *did* ship `/usr/local/lib/libopenjpeg.1.dylib`, not `libopenjpeg.5.dylib`. Judging from the CMakeLists.txt, 5 *may* have been intended but wasn't what was built.

**Comment by dunn** [comment] 2015-08-04 17:14
The ffmpeg issue is occurring here, though, where it tries to use pkg-config to pull the openjpeg cflags: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ffmpeg.rb#L123.  The previous version had `libopenjpeg.pc` symlinked to `libopenjpeg1.pc`, but now with 1.5.2 we just have `libopenjpeg1.pc` and no symlink.

**Comment by axfelix** [comment] 2015-08-04 21:00
FYI, just hit this on a 10.6 machine:


Archives-Computer:~ charlott$ brew install ffmpeg
==> Installing dependencies for ffmpeg: texi2html, yasm, x264, lame, libv
==> Installing ffmpeg dependency: texi2html
==> Downloading http://download.savannah.gnu.org/releases/texi2html/texi2html-1.
==> Downloading from http://mirror.csclub.uwaterloo.ca/nongnu//texi2html/texi2ht
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/texi2html/1.82 --mandir=/usr/local/Ce
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software in versions before Mountain Lion.
==> Summary
/usr/local/Cellar/texi2html/1.82: 108 files, 2.4M, built in 18 seconds
==> Installing ffmpeg dependency: yasm
==> Downloading http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/yasm/1.3.0
==> make install
/usr/local/Cellar/yasm/1.3.0: 44 files, 3.5M, built in 30 seconds
==> Installing ffmpeg dependency: x264
==> Cloning https://git.videolan.org/git/x264.git
Cloning into '/Library/Caches/Homebrew/x264--git'...
Checking connectivity... done.
==> Checking out revision c8a773ebfca148ef04f5a60d42cbd7336af0baf6
==> ./configure --prefix=/usr/local/Cellar/x264/r2533 --enable-shared --enable-s
==> make install
/usr/local/Cellar/x264/r2533: 9 files, 3.4M, built in 54 seconds
==> Installing ffmpeg dependency: lame
==> Downloading https://downloads.sourceforge.net/sourceforge/lame/lame-3.99.5.t
==> Downloading from http://superb-dca2.dl.sourceforge.net/project/lame/lame/3.9
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/lame/3.99.5 --enable-nasm
==> make install
/usr/local/Cellar/lame/3.99.5: 25 files, 2.2M, built in 28 seconds
==> Installing ffmpeg dependency: libvo-aacenc
==> Downloading https://downloads.sourceforge.net/project/opencore-amr/vo-aacenc
==> Downloading from http://iweb.dl.sourceforge.net/project/opencore-amr/vo-aace
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libvo-aacenc/0.1.3
==> make install
/usr/local/Cellar/libvo-aacenc/0.1.3: 15 files, 332K, built in 20 seconds
==> Installing ffmpeg dependency: xvid
==> Downloading https://fossies.org/unix/privat/xvidcore-1.3.4.tar.gz
==> Downloading from https://fossies.org/linux/misc/xvidcore-1.3.4.tar.gz
######################################################################## 100.0%
==> ./configure --disable-assembly --prefix=/usr/local/Cellar/xvid/1.3.4
==> make
==> make install
/usr/local/Cellar/xvid/1.3.4: 9 files, 1.3M, built in 45 seconds
==> Installing ffmpeg
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.7.2 --enable-shared --enable
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
broken ffmpeg build with openjpeg https://github.com/Homebrew/homebrew/issues/42450

**Comment by dunn** [comment] 2015-08-04 21:21
@axfelix I'm not sure if this is the same issue; could you post `brew gist-logs ffmpeg`?

**Comment by axfelix** [comment] 2015-08-04 21:27
oh, you're right, looks like an openCL issue. sorry about that. https://gist.github.com/anonymous/8b87fc1803666be9eb3a

**Comment by mistydemeo** [comment] 2015-08-04 23:44
@axfelix, your ffmpeg issue should be fixed in a2373af9c153d68511778b446387024e1f3caa8f

**Comment by mjbshaw** [comment] 2015-08-07 01:14
I just hit this exact same issue. I'm on OS X 10.10. I uninstalled openjpeg and ffmpeg and reinstalled them (brew uninstall ... And then brew install ...) and that seems to have fixed the issue.

I'd provide more details, but I'm typing this on my phone so can't right now. I just wanted to say there is more than one person with the issue before I forget about it.

**Comment by mjbshaw** [comment] 2015-08-07 14:47
Now that I'm at a computer, here are more details from me.

Illustration of the issue and details:
```
$ brew update
Already up-to-date.
$ brew upgrade
$ ffmpeg
dyld: Library not loaded: /usr/local/lib/libopenjpeg.1.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
[1]    64991 trace trap  ffmpeg
$ ls /usr/local/lib | grep openjpeg
libopenjpeg.1.5.2.dylib
libopenjpeg.5.dylib
libopenjpeg.dylib
openjpeg-1.5
openjpeg-2.1
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    gcc
$ brew gist-logs ffmpeg
couldn't understand kern.osversion `14.4.0'
https://gist.github.com/2715cac5cc292c32b8e3
```

Just uninstalling ffmpeg and reinstalling it works (no need to reinstall openjpeg):
```
$ brew uninstall ffmpeg
Uninstalling /usr/local/Cellar/ffmpeg/2.7.2... (238 files, 48M)
ffmpeg 2.5.4, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.6_1, 2.7.1 are still installed.
Remove them all with `brew uninstall --force ffmpeg`.
$ brew install ffmpeg --with-libquvi --with-theora --with-speex --with-rtmpdump --with-openssl --with-libcaca --with-frei0r --with-libbluray --with-faac --with-fdk-aac --with-ffplay --with-openjpeg --with-freetype --with-libvpx --with-schroedinger --with-tools --with-libvorbis --with-libass --with-opus --with-x265 --with-webp --with-opencore-amr --with-libvidstab --with-libssh
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ffmpeg-2.7.2.tar.bz2
Package libopenjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libopenjpeg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libopenjpeg' found
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.7.2 --enable-shared --enable
==> make install
==> make alltools
🍺  /usr/local/Cellar/ffmpeg/2.7.2: 239 files, 48M, built in 2.6 minutes
$ ffmpeg
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.7.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libfaac --enable-libass --enable-ffplay --enable-libssh --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-openssl --enable-libopus --enable-frei0r --enable-libcaca --enable-libquvi --enable-libvidstab --enable-libx265 --enable-libwebp --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags= --enable-nonfree --enable-vda
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by dunn** [comment] 2015-08-13 17:03
OK, I believe this will be fixed if you upgrade openjpeg; but let me know if you have further issues!

**Closed** 2015-08-13 17:03 UTC
