### ISSUE TITLE
hashcat dependency (unar) installation problem

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew#36877] opened 2015-02-17 02:35 UTC
when running `brew cask install hashcat` getting this:

```    
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
unar ... Error: Command failed to execute!

==> Failed command:
["#<Pathname:/usr/local/bin/brew>", "install", "unar"]

==> Output of failed command:
==> Downloading https://theunarchiver.googlecode.com/files/unar1.8.1_src.zip
Already downloaded: /Library/Caches/Homebrew/unar-1.8.1.zip
==> xcodebuild -project ./XADMaster/XADMaster.xcodeproj -target XADMaster SYMROOT=../ -configuration Release
	CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/clients.o libxad/clients.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/all.o libxad/all.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/emulation.o libxad/unix/emulation.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /tmp/unar-QB2wIc/The\ Unarchiver/XADMaster.build/Release/XADMaster.build/Objects-normal/x86_64/init.o libxad/unix/init.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)    ```

what should I do?

**Comment by adamv** [comment] 2015-02-17 03:09
Duplicate of #36878.

**Closed by adamv** 2015-02-17 03:09 UTC
