### ISSUE TITLE
ImageMagick can't convert PDF with density set

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew#36762] opened 2015-02-12 17:33 UTC
After a recent brew update, I can't seem to convert PDFs with `convert` anymore, when I set `-density`.

This works:
```
$ convert input.pdf output.png
```

This fails:
```
$ convert -density 600 input.pdf output.png
convert: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r600x600"  "-sOutputFile=/var/tmp/magick-475988numpV09h7Fl%d" "-f/var/tmp/magick-47598i67DEU4vj4sh" "-f/var/tmp/magick-475980zG_8mnJ52tT"' (-1) @ error/delegate.c/ExternalDelegateCommand/461.
convert: no images defined `output.png' @ error/convert.c/ConvertImageCommand/3210.
```

I already tried `brew reinstall ghostscript` and `brew reinstall imagemagick --with-ghostscript`.

```
$ brew --version
0.9.5
$ convert --version
Version: ImageMagick 6.9.0-3 Q16 x86_64 2015-02-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg lcms ltdl lzma png tiff xml zlib
$ gs --version
9.15
```

`brew doctor` lists nothing specific except for the usual Tcl/Tk stuff:

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a
```

**Comment by asparagui** [comment] 2015-02-23 04:04
Could you verify with a different process that the problem is in the homebrew version of these libraries, rather than an upstream regression?

**Comment by slhck** [comment] 2015-02-23 09:03
@asparagui For some reason, it works again. I suspect some failure when loading the Ghostscript libraries, but I can't verify it. So let's close this for now.

**Comment by gexly** [comment] 2015-03-31 15:28
Having the same problem when adding "-density 300" before the input filename.
convert -density 300 input.pdf -resize 2000x2000 output.png

convert: Postscript delegate failed `/home/...input.pdf': QmkS.cache @ error/pdf.c/ReadPDFImage/638.
convert: missing an image filename `/home/...output.png' @ error/convert.c/ConvertImageCommand/2940.

**Comment by tdsmith** [comment] 2015-04-01 06:02
I'm not sure whether this is the same problem; the error message is different. Can we see `brew doctor`, `brew config`, and `brew info imagemagick`? I think you will have to ask the Imagemagick developers for help understanding this problem and for advice re whether you or we can fix something.

**Comment by gexly** [comment] 2015-04-01 10:16
Sorry please close this issue it was old ImageMagick version problem.

**Closed** 2015-04-01 10:16 UTC
