### ISSUE TITLE
idutils formula broken; leaves behind undeletable directory

### ISSUE THREAD

**Issue by multi-io** [Homebrew/homebrew#47549] opened 2015-12-31 03:47 UTC
"brew install idutils" runs for a long time, then (during "make install") fails and leaves behind a directory in /tmp/ named something like idutils20151231-56082-1j8wb0x, containing a seemingly endless sequence of subdirectories /tmp/idutils20151231-56082-1j8wb0x/idutils-4.6/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/confdir-14B---/....  The directory is undeletable ("File name too long", or "No space left on device" (which isn't true), or "Directory not empty", depending on what you try). :-(

**Comment by ilovezfs** [comment] 2015-12-31 05:42
I cannot reproduce this issue. I tried on 10.8 and on 10.11.

```
brew gist-logs idutils
```
and paste the gist url.

Also,

```
brew tap homebrew/bundle
brew bundle dump
```

And then pastebin or gist the output file named 'Brewfile'. Maybe it will shed some light.

**Comment by ilovezfs** [comment] 2015-12-31 06:51
This is some sort of upstream bug with your particular setup (possibly your libc).

The problem is created by a program that configure compiles and runs. I don't know why it messes up in your case and fails to remove the directories. I can re-create the situation by compiling a modified version of it and running that.

```
bash-3.2$ #prerequisite
bash-3.2$ brew install xz
Warning: xz-5.2.2 already installed
bash-3.2$ mkdir -p /tmp/idutils20151231-56082-1j8wb0x/idutils-4.6
bash-3.2$ cd /tmp/idutils20151231-56082-1j8wb0x/idutils-4.6
bash-3.2$ &>/dev/null curl -OL http://ftpmirror.gnu.org/idutils/idutils-4.6.tar.xz
bash-3.2$ unxz idutils-4.6.tar.xz 
bash-3.2$ tar xf idutils-4.6.tar 
bash-3.2$ cd idutils-4.6
bash-3.2$ &>/dev/null curl -OL https://gist.githubusercontent.com/ilovezfs/c28360bce0e93339a674/raw/28d62a21e860ca255808609c92d5053828743706/getcwd_abort_bug.c
bash-3.2$ clang -o getcwd_abort_bug getcwd_abort_bug.c 
bash-3.2$ &>/dev/null ./getcwd_abort_bug
bash-3.2$ for i in {1..256} ; do &>/dev/null cd confdir-14B--- ; done
bash-3.2$ pwd | wc -c
    3907
bash-3.2$ for i in {1..256} ; do &>/dev/null cd confdir-14B--- ; done
bash-3.2$ pwd | wc -c
    5107
bash-3.2$ for i in {1..256} ; do &>/dev/null cd confdir-14B--- ; done
bash-3.2$ pwd | wc -c
    5107
bash-3.2$ ls
bash-3.2$ cd ..
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
bash-3.2$ #But it worked
bash-3.2$ pwd | wc -c
    5110
bash-3.2$ for i in {1..256} ; do &>/dev/null rmdir confdir-14B--- ; &>/dev/null cd .. ; done
bash-3.2$ pwd | wc -c
    1252
bash-3.2$ for i in {1..256} ; do &>/dev/null rmdir confdir-14B--- ; &>/dev/null cd .. ; done
bash-3.2$ pwd | wc -c
       2
bash-3.2$ rm -rf /tmp/idutils20151231-56082-1j8wb0x/idutils-4.6
bash-3.2$
```

**Comment by DomT4** [comment] 2015-12-31 09:41
It's an El Capitan bug which may possibly be fixed in certain configurations already. Same thing happened in various other GNU formulae: #45273, etc. Have filed #47553 to fix it.

In the nested directory you can run something like the script [here](https://lists.gnu.org/archive/html/bug-tar/2015-10/msg00017.html) to purge it directory by directory.

**Closed** 2015-12-31 09:50 UTC
