### ISSUE TITLE
Concurrent builds?

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew#43887] opened 2015-09-13 20:26 UTC
I probably missed the issue about this already, but I didn't
find anything...

Anyways, why doesn't homebrew support concurrent builds?
I always get a bit confused when something like
"Another process is already using xz" pops up, because
I'm fairly certain that binaries don't have single-process
locks.

It's mostly a convenience thing, I guess. If I'm on an
installation binge it would be much easier to keep things
straight because I don't have to delay for xz/cmake 
to open up. Not sure how widely this would be used
otherwise, unless possibly for parallel builds of
dependencies, like opam? Or if not that,would some
kind of queue mechanism be possible? Like "Another
process is already using xz, but I can run that command
as soon as it opens up.

**Comment by xu-cheng** [comment] 2015-09-14 06:42
Homebrew supports parallel multiple formulae as long as their dependencies tree don't intersect with each other. Sorry but there is little we can do here.

**Comment by DomT4** [comment] 2015-09-14 14:14
Closing per Xu's comment.

**Closed by DomT4** 2015-09-14 14:14 UTC
Labels: features

**Comment by aw1621107** [comment] 2015-09-14 14:38
...I don't think I'm understanding something. Can homebrew only run one instance of a particular binary at a time?

**Comment by tdsmith** [comment] 2015-09-14 14:42
The limitation is that multiple builds shouldn't try to update the same package in the Cellar simultaneously, which is hard to choreograph.

Builds often run on many cores and we risk oversubscribing resources if we allow multiple builds to run at once.

The value proposition isn't clear and it would be a lot of work.

**Comment by aw1621107** [comment] 2015-09-14 15:29
I didn't think that'd be an issue if homebrew were just using binaries most of the time, but fair enough. Sorry for wasting you time

**Comment by bfontaine** [comment] 2015-09-14 20:53
@aw1621107 Imagine you wanted to install two formulae at the same time, A and B. Both have a dependency on C. If you start each installation in two separate threads both will try to install C at the same time and some weird things might happen. The issue is not that the `xz` binary will be *used* simultaneously in two threads but that it might be *installed* at the same time by both formulae.

**Comment by aw1621107** [comment] 2015-09-15 17:05
@bfontaine That makes sense. So can homebrew not tell between a dependency needing to be installed vs. a dependency that will only get used?
