### ISSUE TITLE
binutils failed to build on 10.6.8

### ISSUE THREAD

**Issue by conib** [Homebrew/homebrew#38014] opened 2015-03-24 04:01 UTC
Hello everyone ...

In 02.Make in the gist-logs posted at
    https://gist.github.com/087dab4aa87054f9aa06
show at line 2676 that ld failed with an undefined symbol "_wcsncasecmp".

I googled and discovered that Stefan Schmidt determined that this is a problem with wcsncasecmp being undefined up to Mac OS X 10.7:
    http://lists.gnu.org/archive/html/bug-binutils/2014-12/msg00189.html

A few weeks later Nick Clifton posted
    http://lists.gnu.org/archive/html/bug-binutils/2015-02/msg00190.html
that he'd generated a patch
   http://lists.gnu.org/archive/html/bug-binutils/2015-02/txtWj3lXH7GAF.txt
to repair this issue.

I'd like to edit the formula myself but I just don't know enough yet about configure and patches.

Please help!  Any pointers would be appreciated.

-- Constance

**Comment by tdsmith** [comment] 2015-03-24 07:24
Thanks for researching the bug!

There's some advice here on opening a pull request: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

and here's some advice on adding patches to Homebrew formulas: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#patches

If you have any questions I'd happy to help either here or on IRC.

**Comment by conib** [comment] 2015-03-24 09:43
Hey, thanks for the fast response and the links, much appreciated.

Now I "just" need to get up to speed on this stuff.

[Heh, heh.  "If" I have any questions.]
;-)
First noob question:
(And BTW thanks in advance for your patience)
In Nick's post
https://sourceware.org/ml/binutils/2015-02/msg00341.html
(Nick is replying to Stefan's message which confirmed that the patch worked for him)
where Nick says "I have now check the patch in along with this changelog info", and then posts some changelog stuff, does this all mean that Nick has implemented and checked-in a fix for this issue?
(And so we can assume that the next release of binutils will actually contain the towlower workaround Nick's patch implements?)

-- Constance

**Comment by conib** [comment] 2015-03-25 20:41
Okay, at this point I've edited my local copy of the binutils formulae and done a successful brew install with it.

I then restored the original binutils formulae version and ran a "brew audit --strict" on it to see what issues it had originally.  Nothing earth-shaking, but I wanted a baseline.

Then I tried to find info on the "brew tests" command but was unsuccessful.  What is it supposed to do, exactly?

I went ahead and ran it  (what the heck) but at first crack it abended with an error complaining about a RubyGems requirement.

So I take it that "brew tests" installs some sort of test suite?  Or ...?

**Comment by andistern** [comment] 2015-05-14 22:55
Hi,
just added thees for lines to formula ( just to save everybody else's time )
```python 
 patch :p1 do
    url "http://lists.gnu.org/archive/html/bug-binutils/2015-02/txtWj3lXH7GAF.txt"
    sha256 "9f1b04776bd94d2cf2d61f26d03cb7c22560d5ab43b9c2e76c8818b97186af1c"
 end
```
```brew tests``` kind of worked after a ```rvm reset``` and showed some differences caused by
```
    assert_equal MacOS.default_compiler, tab.cxxstdlib.compiler
``` 
on my Machine (  osx/10.6.8/i386 ). You might want to look at ```test_tab.rb```

**Comment by andistern** [comment] 2015-08-18 16:21
![Uploading Bildschirmfoto 2015-08-18 um 18.14.48.png…]()

**Comment by andistern** [comment] 2015-08-18 16:26
![bildschirmfoto 2015-08-18 um 18 14 48](https://cloud.githubusercontent.com/assets/1109617/9335730/022d2850-45d6-11e5-9fd4-7712f3f2594d.png)
and change the 4 lines above to wherever the file resides
```
  HOME = ENV["HOME"]
  def patches
	  { :p1 => "file://#{HOME}/src/Homebrew/patches/binutils--patch-V2.txt" }
  end
```

**Comment by lskatz** [comment] 2015-09-01 18:55
Could you all be more specific on how to patch this?  I am getting this error which leads me to this issues page.


    [lkatz@monolith0 .linuxbrew]$ brew reinstall binutils
    ==> Reinstalling binutils
    ==> Downloading http://ftpmirror.gnu.org/binutils/binutils-2.25.1.tar.gz
    Already downloaded: /home/lkatz/.cache/Homebrew/binutils-2.25.1.tar.gz
    ==> ./configure  --with-sysroot=/ --prefix=/home/lkatz/.linuxbrew/Cellar/binutils/2.25.1 --infodir=/hom
    checking for C compiler default output file name... a.out
    checking whether the C compiler works... configure: error: in `/tmp/binutils20150901-45830-csjdd8/binutils-2.25.1':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details.

    READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

    These open issues may also help:
    binutils failed to build on 10.6.8 https://github.com/Homebrew/homebrew/issues/38014

**Comment by mistydemeo** [comment] 2015-09-01 20:15
Adapted the patch to the current stable release of binutils; works for me on 10.6. Let me know if you have any more issues!

**Comment by mistydemeo** [comment] 2015-09-01 20:16
@lskatz Your issue looks unrelated. If you're using binutils, please report that at [linuxbrew](https://github.com/Homebrew/linuxbrew).

**Closed** 2015-09-01 20:16 UTC
Labels: 10.6

**Comment by lskatz** [comment] 2015-09-01 20:24
Thank you.  Issue submitted here: https://github.com/Homebrew/linuxbrew/issues/529
