### ISSUE TITLE
llvm 3.6.1 failure with python llvmlite install.

### ISSUE THREAD

**Issue by defjaf** [Homebrew/homebrew#41320] opened 2015-07-03 11:14 UTC
When I try to install (via pip) the latest version of the python package [llvmlite 0.6.0](https://github.com/numba/llvmlite) with homebrew llvm 3.6.1, after setting `LLVM_CONFIG=/usr/local/Cellar/llvm/3.6.1/bin/llvm-config` I get the following error:

        initfini.cpp:9:10: fatal error: 'llvm/Config/config.h' file not found
        #include "llvm/Config/config.h"

It appears that `/usr/local/Cellar/llvm/3.6.1/include/llvm/Config/llvm-config.h` exists, but not `config.h`. This can be fixed with a soft link in that Cellar directory, but I don't know if this an error in the homebrew installation/formula for llvm, or the initfini.cpp in the llvmlite python package (this error is [reported there](https://github.com/numba/llvmlite/issues/76), too.)

**Comment by DomT4** [comment] 2015-07-03 11:59
It exists in the `llvm36` formula in Versions:

```
/usr/local/Cellar/llvm36/3.6.1/lib/llvm-3.6/include/clang/Config/config.h
/usr/local/Cellar/llvm36/3.6.1/lib/llvm-3.6/include/llvm/Config/config.h
/usr/local/Cellar/llvm36/3.6.1/lib/llvm-3.6/include/llvm/Config/llvm-config.h
/usr/local/Cellar/llvm36/3.6.1/lib/llvm-3.6/include/polly/Config/config.h
```

The differences between LLVM36 in Versions and the LLVM in core are:

* Python bindings are built by default
* Clang is built by default
* The build still uses `configure` rather than CMake.

One of those variables is likely to be the difference.

**Comment by pitrou** [comment] 2015-07-04 13:34
I'm almost 100% sure this is due to cmake vs. configure.

**Comment by DomT4** [comment] 2015-07-04 13:38
CC @tamird

**Comment by tamird** [comment] 2015-07-05 16:05
OK, I've got to the bottom of this. TL;DR: use `llvm-config.h`; `config.h` is never supposed to be present in LLVM distributions.

Specifically https://github.com/llvm-mirror/llvm/commit/90c29494121e3a4cefb5cae5d272178bbc49d3a9#diff-b67911656ef5d18c4ae36cb6741b7965R30 added an intentional deletion of `config.h` at distribution time. Since LLVM has pretty much abandoned non-cmake builds, it's probably just a bug that `config.h` survives to the end of the build.

I would close this issue; https://github.com/numba/llvmlite/issues/76 should be fixed appropriately.

**Comment by pitrou** [comment] 2015-07-06 12:44
The issue is now fixed in the llvmlite repo.

**Comment by DomT4** [comment] 2015-07-06 12:48
@pitrou Any timetable on cutting a new release? No pressure; we can backport the fix otherwise, but I don't want to tee up a backport PR here if there's a release imminent.

**Comment by pitrou** [comment] 2015-07-06 12:49
We usually sync llvmlite and numba releases, so probably a month and a half from now. Thought if there are other bugs we could cut a release earlier.

**Comment by DomT4** [comment] 2015-07-06 13:00
Cool. Will backport that shortly then. Thanks for the quick fix!

**Comment by DomT4** [comment] 2015-07-06 13:08
Oh, It's not something we package. Alright, off I go to drink more :coffee: and actually wake up my brain. Closing as fixed upstream.

**Closed by DomT4** 2015-07-06 13:08 UTC
