### ISSUE TITLE
pango-1.36.8 failed to build on 10.10.3 (14D136)

### ISSUE THREAD

**Issue by themsay** [Homebrew/homebrew#40853] opened 2015-06-18 10:41 UTC
https://gist.github.com/b993db679b606702efea

**Comment by bernatfp** [comment] 2015-06-18 11:39
Can't build pango either.

https://gist.github.com/1c2f2df1ccd13b9d6579

**Comment by DomT4** [comment] 2015-06-18 17:01
@themsay Yours' seems to be a simple case that it can't find Cairo. Please ensure you're up-to-date with `brew update` and then `brew install cairo` - Try again afterwards. You may need to `brew upgrade` as well, we made some major GTK+ changes yesterday.

@bernatfp Your error is a little unusual. `make` isn't terribly verbose about what's going wrong there. You have a lot of `doctor` warnings that could be contributing though. I'd recommend dealing with as many of those as you can, particularly:

* https://gist.github.com/anonymous/1c2f2df1ccd13b9d6579#file-doctor-out-L39-L41
* https://gist.github.com/anonymous/1c2f2df1ccd13b9d6579#file-doctor-out-L73-L91
* https://gist.github.com/anonymous/1c2f2df1ccd13b9d6579#file-doctor-out-L120-L122

**Comment by themsay** [comment] 2015-06-18 18:46
@DomT4 <code>brew install cairo</code> return Warning: cairo-1.14.2_1 already installed and <code>brew upgrade cairo</code> also return Error: cairo 1.14.2_1 already installed.

**Comment by themsay** [comment] 2015-06-18 19:08
I sort the issue by simply running:

<code>brew uninstall cairo</code>

then

<code>brew update && brew upgrade --all</code>

it automatically install pango and cairo successfully.

**Comment by DomT4** [comment] 2015-06-18 19:39
^ :+1:. `--all` is no longer a thing by the way. It was reverted.

**Comment by tko** [comment] 2015-06-19 07:07
The error in @bernatfp case seems to be something wrong with python:
```
/bin/sh: /usr/local/Cellar/gobject-introspection/1.44.0/bin/g-ir-scanner: /usr/bin/python: bad interpreter: No such file or directory
```
https://gist.github.com/anonymous/1c2f2df1ccd13b9d6579#file-02-make-L140

I got the same error because of /usr/local/opt/python/bin/python but I suspect that's because I've uninstalled the brew python because it was messing other things up. Missing /usr/bin/python seems bad.

**Comment by bernatfp** [comment] 2015-06-19 15:03
@tko that's probably the issue. I created a symlink and that fixed the problem:

```
ln -s /usr/bin/python2.7 /usr/bin/python
```

Thanks @themsay @tko

**Comment by juanfal** [comment] 2015-06-21 12:32
Hi, everything works (cairo and the rest) but pango doesn't install

After doctoring brew (no issues left), cleaning up, uninstalling cairo, and then installing it again, and then pango, again the same errors linking:

    brew install pango
    ==> Downloading https://download.gnome.org/sources/pango/1.36/pango-1.36.8.tar.xz
    Already downloaded: /Library/Caches/Homebrew/pango-1.36.8.tar.xz
    ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/pango/1.36.8_1 --enable-man --with-html-dir=/usr/local/Cellar/pango/1.36.8
    ==> make
    libtool: link: ( cd ".libs" && rm -f "libpangoft2-1.0.la" && ln -s "../libpangoft2-1.0.la" "libpangoft2-1.0.la" )
    make[3]: *** [all-recursive] Error 1
    make[2]: *** [all] Error 2
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2
    couldn't understand kern.osversion `14.3.0'

    READ THIS: https://git.io/brew-troubleshooting

    These open issues may also help:
    HTTPS to HTTP redirect in `pango` formula (https://github.com/Homebrew/homebrew/issues/40915)

**Comment by TheLinuxNinja** [comment] 2015-06-29 10:04
ditto @juanfal 
I followed your steps and arrived at the same place. pango will not re-install after having uninstalled cairo and pango. My issue is with jigdo requiring pango. doctor just warns me that pango isn't installed.

This issue should be re-opened and not closed.

**Comment by DomT4** [comment] 2015-06-29 18:39
Will need `brew gist-logs` from you both.

**Comment by moovchris** [comment] 2015-06-29 21:37
I had this same issue, did a brew `install -v pango` and saw `Library not loaded: /usr/local/lib/libgio-2.0.0.dylib`. I reinstalled glib, then pango installed fine.

**Comment by pleaseshutup** [comment] 2015-06-30 04:20
Had the same issue as juanfal. I ended up doing brew install -vd pango and then jumping into the shell. Find the pango install files in /private/etc/
do a make and found a permissions error. 

I think this was left around from foolishly installing as root before.
Clean up the files in /Users/yourname/.cache and then brew install pango successfully

**Comment by juanfal** [comment] 2015-06-30 08:18
No luck here. After

    rm -rf ~/.cache/
    brew install -v pango

gave me this sad end:

    libtool: link: (cd ".libs" && rm -f "libpangoft2-1.0.dylib" && ln -s "libpangoft2-1.0.0.dylib" "libpangoft2-1.0.dylib")
    libtool: link: ( cd ".libs" && rm -f "libpangoft2-1.0.la" && ln -s "../libpangoft2-1.0.la" "libpangoft2-1.0.la" )
    make[3]: *** [all-recursive] Error 1
    make[2]: *** [all] Error 2
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2
    couldn't understand kern.osversion `14.3.0'
    ==> Formula
    Path: /usr/local/Library/Formula/pango.rb
    ==> Configuration
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew.git
    HEAD: 7d33150156980fa13b3f93db87b127b784b0f61a
    Last commit: 4 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    CPU: quad-core 64-bit broadwell
    OS X: 10.10.3-x86_64
    Xcode: 6.3.2
    CLT: 6.3.2.0.1.1431401888
    couldn't understand kern.osversion `14.3.0'
    GCC-4.2: build 5666
    Clang: 6.1 build 602
    X11: 2.7.7 => /opt/X11
    System Ruby: 2.0.0-p481
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
    Java: 1.6.0_65
    ==> ENV
    HOMEBREW_CC: clang
    HOMEBREW_CXX: clang++
    MAKEFLAGS: -j4
    CMAKE_PREFIX_PATH: /usr/local/opt/gettext:/usr/local/opt/libffi:/usr/local/opt/icu4c:/usr/local
    CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
    PKG_CONFIG_PATH: /usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/pixman/lib/pkgconfig:/usr/local/opt/cairo/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/gobject-introspection/lib/pkgconfig:/usr/local/opt/harfbuzz/lib/pkgconfig
    PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
    ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
    PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/xz/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/gettext/bin:/usr/local/opt/glib/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/cairo/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/gobject-introspection/bin:/usr/local/opt/harfbuzz/bin:/usr/bin:/bin:/usr/sbin:/sbin

    Error: pango 1.36.8 did not build
    Logs:
         /Users/juanfc/Library/Logs/Homebrew/pango/01.configure
         /Users/juanfc/Library/Logs/Homebrew/pango/01.configure.cc
         /Users/juanfc/Library/Logs/Homebrew/pango/02.make
         /Users/juanfc/Library/Logs/Homebrew/pango/02.make.cc
         /Users/juanfc/Library/Logs/Homebrew/pango/config.log

    These open issues may also help:
    Pango install fail on 10.11 (https://github.com/Homebrew/homebrew/issues/41086)
    pango-1.36.8 failed to build on 10.10.3 (14D136) (https://github.com/Homebrew/homebrew/issues/40853)

**Comment by DomT4** [comment] 2015-06-30 08:24
`brew gist-logs pango` are necessary from everyone still having an issue. It contains the whole build logs and a deeper level of detail than the end of the build log.

**Comment by juanfal** [comment] 2015-06-30 08:42
Sorry, you did say that already.  Here's mine:

    $ brew gist-logs pango
    couldn't understand kern.osversion `14.3.0'
    https://gist.github.com/59c2c48e695a12fc5355

**Comment by DomT4** [comment] 2015-06-30 09:32
@tdsmith Is [this line](https://gist.github.com/anonymous/59c2c48e695a12fc5355#file-02-make-L140) anything we can fix here? Has popped up a few times, and seems to be the failure.

It does reproduce locally when built from source: `/usr/local/bin/g-ir-scanner: bad interpreter: /usr/local/opt/python/bin/python: no such file or directory`, but doesn't reproduce with the bottle. I can't immediately spot which formulae is leaking a direct Python dependency/etc, but haven't checked out build logs yet.

**Comment by tdsmith** [comment] 2015-06-30 14:37
That script belongs to gobject-introspection, so it's probably doing some clever Python detection we should disable.

**Comment by tdsmith** [comment] 2015-06-30 14:45
I can't get the gobject-introspection formula to write a shebang containing anything other than `/usr/bin/python`. The `:python` dependency was removed April 10 in c6731ddd0. If a fresh source build gives you a different shebang, try setting `ENV["PYTHON"] = "/usr/bin/python"` in the formula and see if that resolves it.

**Comment by mcmancini** [comment] 2015-07-03 17:56
Hi all, I have been having the same Pango problem on 10.10.3 and 10.10.4.  Setting ENV=/usr/bin/python did not correct the problem (and I do not have brew's python 2 or 3 installed).  I also have a clean brew doctor.  The brew -v flag on Pango hinted that gobject-introspection was finding a mach-o binary, but not the correct type (or something to that effect).  I found that installing the universal binary version of gobject-introspection allowed Pango to install correctly without drama.

**Comment by DomT4** [comment] 2015-07-04 00:08
Oddly, I could reproduce this last night again, but I've just sat down to try and resolve it and now I can't reproduce it at all. Can everyone who is still having this problem do:

```
brew update && brew upgrade
brew rm gobject-introspection
brew install pango
```

Anyone still having the problem after that, please provide a fresh `brew gist-logs pango`, Thanks!

**Comment by mcmancini** [comment] 2015-07-04 03:43
I removed gobject-introspection (and pango) and tried installing pango: I ran into the same error as before (gist at https://gist.github.com/anonymous/6490d992b74349acfbca).

Installing gobject-introspection –universal and then installing pango (no flags) repeatably works on my system.

**Comment by juanfal** [comment] 2015-07-04 09:22
Oh! thanks

    brew update && brew upgrade
    brew rm gobject-introspection
    brew install pango

worked for me:

    $ …
    $ brew install pango
    ==> Installing pango dependency: gobject-introspection
    ==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.44.0.yosemite.bottle.2.tar.gz
    ######################################################################## 100,0%
    ==> Pouring gobject-introspection-1.44.0.yosemite.bottle.2.tar.gz
    🍺  /usr/local/Cellar/gobject-introspection/1.44.0: 196 files, 10M
    ==> Installing pango
    ==> Downloading https://download.gnome.org/sources/pango/1.36/pango-1.36.8.tar.xz
    Already downloaded: /Library/Caches/Homebrew/pango-1.36.8.tar.xz
    ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/pango/1.36.8_1 --enable-man --with-html-dir=/usr/local/Cellar/pango/1.36.8_1/share/doc -
    ==> make
    ==> make install
    🍺  /usr/local/Cellar/pango/1.36.8_1: 126 files, 4,7M, built in 39 seconds

**Comment by BloodBrother** [comment] 2015-07-07 13:52
Hey guys,
I've tried @DomT4 's solution but to no avail...
Here's the gist, as requested.

https://gist.github.com/anonymous/4c147dd8b858d22e2120

Thanks for you help you all.

**Comment by peking2** [comment] 2015-07-15 06:12
tried all above, but still not working

https://gist.github.com/ca6d7cfb66be43cd9543

thanks

**Comment by nicolag** [comment] 2015-07-17 05:39
Hey DomT4,

I've tried your solutions but doesn't seem like working for me, still couldn't install:
```
$ brew install pango
==> Downloading https://download.gnome.org/sources/pango/1.36/pango-1.36.8.tar.x
Already downloaded: /Library/Caches/Homebrew/pango-1.36.8.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/pango/1.36.8_1
==> make
make[4]: *** [Pango-1.0.gir] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
pango-1.36.8 failed to build on 10.10.3 (14D136) (https://github.com/Homebrew/homebrew/issues/40853)
```

 here is the gist-logs, any ideas?
```
$ brew gist-logs pango
https://gist.github.com/623f3e5c16284e51a087
```
look forward to your solutions, thx

**Comment by nicolag** [comment] 2015-07-17 06:17
btw, here's the brew doctor
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libjpeg.8.dylib
    /usr/local/lib/libpixman-1.0.dylib
    /usr/local/lib/libpng.3.dylib
    /usr/local/lib/libpng12.0.dylib
    /usr/local/lib/libpng14.14.dylib
    /usr/local/lib/libpng15.15.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/jconfig.h
    /usr/local/include/jerror.h
    /usr/local/include/jmorecfg.h
    /usr/local/include/jpeglib.h
    /usr/local/include/libpng12/png.h
    /usr/local/include/libpng12/pngconf.h
    /usr/local/include/libpng14/png.h
    /usr/local/include/libpng14/pngconf.h
    /usr/local/include/libpng15/png.h
    /usr/local/include/libpng15/pngconf.h
    /usr/local/include/libpng15/pnglibconf.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libcairo-gobject.la
    /usr/local/lib/libcairo-script-interpreter.la
    /usr/local/lib/libcairo.la
    /usr/local/lib/libfpm_helper.la
    /usr/local/lib/libjpeg.la
    /usr/local/lib/libpixman-1.la
    /usr/local/lib/libpng12.la
    /usr/local/lib/libpng14.la
    /usr/local/lib/libpng15.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/libpng12.pc
    /usr/local/lib/pkgconfig/libpng14.pc
    /usr/local/lib/pkgconfig/libpng15.pc
    /usr/local/lib/pkgconfig/pixman-1.pc
    /usr/local/lib/pkgconfig/xsp-2.pc
    /usr/local/lib/pkgconfig/xsp-4.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfpm_helper.a
    /usr/local/lib/libjpeg.a
    /usr/local/lib/libpixman-1.a
    /usr/local/lib/libpng12.a
    /usr/local/lib/libpng14.a
    /usr/local/lib/libpng15.a
```

**Comment by nicolag** [comment] 2015-07-17 13:37
brew doctor is clean except for You should `brew install` the missing dependencies:
brew install pango

**Comment by nicolag** [comment] 2015-07-17 17:04
Anyone able to solve this?

**Comment by DomT4** [comment] 2015-07-17 17:36
I'm still looking into it, but trying to fix something I can no longer reproduce on two machines is difficult.

Your error is a little different though @nicolag:

```
dyld: Library not loaded: /usr/local/lib/libpixman-1.0.dylib
  Referenced from: /usr/local/lib/libcairo.2.dylib
  Reason: image not found
```

You should be able to fix that by doing `brew reinstall pixman`?

**Comment by nicolag** [comment] 2015-07-17 19:13
@DomT4, it works! You're awesome, thanks so much.

**Comment by nicolag** [comment] 2015-07-17 19:20
Hey Dominyk,

It works, tons of thanks, you really solve my nightmare.

Best,
Nicola Guo | www.nicoladesign.ca <http://nicoladesign.ca> | 647-963-8866

============================================================
****This e-mail and any attachments may contain confidential and privileged
information. If you are not the intended recipient, please notify the
sender immediately by return an e-mail, delete this e-mail and destroy any
copies. Any dissemination or use of these information by any person rather
than the intended recipient is unauthorized and may be illegal.

**Comment by DomT4** [comment] 2015-07-17 19:27
Happy to help!

**Comment by TheLinuxNinja** [comment] 2015-07-20 18:48
I had the same pixman issue, reinstalled it, but pango is still broken.
Also tried removing gobject-introspection by:
brew uninstall --force gobject-introspection
then brew upgrade again. Same results.

if I run:
brew gist-logs pango

I get:

Error: HTTP 404 Not Found (expected 201)

**Comment by TheLinuxNinja** [comment] 2015-07-20 19:02
After gathering the logs and trying to do a gist post, I found an error pointing me to fontconfig.
I 'brew reinstall fontconfig' and am now able to do 'brew upgrade' which successfully installed pango.

Now that I've reached the bottom of the rabbit hole, I hope this helps someone.

**Comment by BloodBrother** [comment] 2015-07-20 19:51
@TheLinuxNinja Thanks, dude. This worked for me too. A good day to you all.

**Comment by DomT4** [comment] 2015-10-09 04:12
Presuming this is resolved for everyone at this point, since we've merged a couple version updates since. Please do let us know if anyone is still hitting this error though.

**Closed by DomT4** 2015-10-09 04:12 UTC
