### ISSUE TITLE
uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by Screak42** [Homebrew/homebrew#42600] opened 2015-08-07 09:59 UTC
OSX 10.10.4 (14E46
3.5 GHz Intel Core i7 iMac

10:56 [USER]@[MACHINEID]:~$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'

**Comment by bfontaine** [comment] 2015-08-07 10:09
Closing as a duplicate of #42553.

**Closed by bfontaine** 2015-08-07 10:09 UTC
