### ISSUE TITLE
OpenSSL and OS X 10.3: certificate verify failed

### ISSUE THREAD

**Issue by lloeki** [Homebrew/homebrew#38507] opened 2015-04-10 07:18 UTC
Some certificate validations [fail with ruby](https://github.com/rails-assets/rails-assets/issues/239), but it seems to be more far reaching. This affects both homebrew's ruby (bottled) and custom-built ruby, and possibly anything using homebrew's OpenSSL.

There seems to be a problem either with the certificate dump process or the keychain certificate store has some issues to begin with. Diagnosing the issue is quite muddled due to various moving parts and order things were done (installing openssl/building ruby/generating cert.pem/upgrading to 10.10.3).

Hard to tell if homebrew is or is not – partially or totally – in cause or can take mitigation steps, but please see investigations late in the aforementioned issue.

**Comment by lloeki** [comment] 2015-04-10 07:24
I confirmed that as soon as an install or upgrade of openssl is done post 10.3 via homebrew, `cert.pem` will be (re)generated and things blow up from there.

**Comment by lloeki** [comment] 2015-04-10 07:24
Possible ties with #38226.

**Comment by lloeki** [comment] 2015-04-10 07:28
Steps to reproduce:

```
# upgrade to OS X 10.3, then
brew uninstall openssl
brew install openssl ruby
/usr/local/bin/ruby -e 'require "net/http"; require "uri"; Net::HTTP.get(URI("https://google.com"))'
```

**Comment by mikemcquaid** [comment] 2015-04-10 07:31
Duplicate of https://github.com/Homebrew/homebrew/issues/38491.

**Closed by mikemcquaid** 2015-04-10 07:31 UTC

**Comment by lloeki** [comment] 2015-04-10 07:35
Well, sorry for the noise. Missed it in a search, plus it's already cross-referenced, how could I miss that :sob:.

**Comment by mikemcquaid** [comment] 2015-04-10 07:37
No worries!
