### ISSUE TITLE
llvm failed to build on 10.10.3

### ISSUE THREAD

**Issue by mantognini** [Homebrew/homebrew#39865] opened 2015-05-18 06:14 UTC
Hi,

The relevant gist-logs are here: https://gist.github.com/mantognini/0f3b81ced6ce6dcf134d

This is a different issue than #39621 mostly because it's not a compilation issue but a linker issue: a lot of symbols are not found. For examples, [L112-122](https://gist.github.com/mantognini/0f3b81ced6ce6dcf134d#file-02-make-L112-L122), [L182-264](https://gist.github.com/mantognini/0f3b81ced6ce6dcf134d#file-02-make-L182-L264), ...

The build command was `brew install llvm --with-clang --with-lld --with-lldb --with-rtti --without-assertions`.

Let me know if I can provide more information.

**Comment by xu-cheng** [comment] 2015-05-18 07:55
cc @DomT4 @tamird

**Comment by tamird** [comment] 2015-05-18 11:54
Whoa, even `brew install llvm --with-lld` fails this way.

**Comment by DomT4** [comment] 2015-05-18 16:14
I'm starting to think we should either strip the Homebrew/homebrew LLVM formula down to nothing but the core LLVM and Clang elements and leave the fuller non-cmaked one in Versions, or revert the CMake changes.

A lot of this seems like things that need to be kicked upstream for at least advice and potential fixes. We're hitting a steady level of LLVM issues that we have no immediate solution for since switching to CMake; the problem of course being complicated by switching to CMake also resolving a few build issues. Either way, big chunks of the LLVM formula no longer work evidently.

**Comment by tamird** [comment] 2015-05-18 16:18
I think that's a bit of a knee-jerk. Most of the LLVM formula works, and there's no clear indication of what the root cause of the `lld`/`lldb` troubles is.

LLVM as a whole is moving away from non-cmake builds, so reverting to make is a Bad Idea.

Honestly, this particular issue looks to me like a problem with `lld` being half-baked in 3.6 - `brew install llvm --HEAD --with-lld` works fine. I can't speak to the `lldb` issues.

**Comment by DomT4** [comment] 2015-05-18 16:21
I have a bigger preference towards pulling out the broken elements than I do a full revert. We can remove elements temporarily that are broken, report the issues upstream, add notes to those issues in the formula and re-add the bits that work to the `head` section. Either way, I don't think we can just leave chunks of the formula broken.

**Comment by tamird** [comment] 2015-05-18 18:15
So this actually turns out to be another shared libraries-related failure (and it does occur with `--HEAD`; I was wrong earlier). This patch fixes the issue:
```diff
diff --git a/Library/Formula/llvm.rb b/Library/Formula/llvm.rb
index f257ddd..b458973 100644
--- a/Library/Formula/llvm.rb
+++ b/Library/Formula/llvm.rb
@@ -67,7 +67,7 @@ class Llvm < Formula
   option "with-lldb", "Build LLDB debugger"
   option "with-rtti", "Build with C++ RTTI"
   option "with-python", "Build Python bindings against Homebrew Python"
-  option "without-shared", "Don't build LLVM shared libraries"
+  option "with-shared", "Build LLVM shared libraries"
   option "without-assertions", "Speeds up LLVM, but provides less debug information"
 
   deprecated_option "rtti" => "with-rtti"
```

Perhaps we should apply that patch and stop shipping the dylibs? upstream clearly does not maintain this path very well at all.

**Comment by DomT4** [comment] 2015-05-18 18:22
We'll need to run it past @jacknagel given his previous regression comments. Also think we should remove LLDB as an option for now given #39621 and people are going to keep trying to invoke that option.

**Comment by xu-cheng** [comment] 2015-05-18 18:29
> Also think we should remove LLDB as an option for now given #39621 and people are going to keep trying to invoke that option.

:sob: For me, lldb built against homebrew Python is the only reason I use llvm formula

**Comment by tamird** [comment] 2015-05-18 18:30
Let's keep the LLDB discussion in #39621. 

As for this issue: fixing LLD to work with shared libraries is fairly trivial, but requires patching LLD's source, which depends on #31508.

**Closed** 2015-05-19 00:43 UTC
