### ISSUE TITLE
New launchctl interface in 10.10

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/homebrew#33259] opened 2014-10-17 06:15 UTC
If you take a look at `man launchctl` on 10.10, you'll see that there is a bunch of new functionality, and `load` and `unload` are now considered "legacy subcommands" in favor of `bootstrap`, `enable`, and `kickstart` or some combination thereof.

We may want to adjust our launchctl caveats accordingly.

**Comment by simonpie** [comment] 2015-02-09 04:08
I would like to add on the previous comment,

One has to use the service label as specified in the plist with the verbs enable and kickstart.  Here is a sequence that worked for me for a basic command :

    sudo launchctl bootstrap system /Library/LaunchDaemons/ipupdate.plist
    sudo launchctl enable system/RapportIP
    sudo launchctl kickstart -kp system/RapportIP

Where RapportIP is the label in the plist for that job, the name that would appear if one were to write `launchctl list.  Without the enable line, my job would not launch.

**Comment by huitseeker** [comment] 2015-02-16 16:59
@simonpie That's usually solved by doing calling `launchtl bootstrap -w`

**Comment by simonpie** [comment] 2015-02-16 17:08
@hultseeker,

This is definitely not documented on my yosemite machine.  The `-w` flag is only addressed in the legacy subcommands subsection.  But, may I inquire, what is this supposed to solve ?

**Comment by ming13** [comment] 2015-03-24 12:19
FYI `launchd` was [probably rewritten](http://www.newosxbook.com/articles/8-10.10.html).

**Comment by dsorresso** [comment] 2015-04-16 01:02
FYI...

`$ launchctl help
Usage: launchctl <subcommand> ... | help [subcommand]
Many subcommands take a target specifier that refers to a domain or service
within that domain. The available specifier forms are:

system/[service-name]
Targets the system-wide domain or service within. Root privileges are required
to make modifications.

user/<uid>/[service-name]
Targets the user domain or service within. A process running as the target user
may make modifications. Root may modify any user's domain. User domains do not
exist on iOS.

gui/<uid>/[service-name]
Targets the GUI domain or service within. Each GUI domain is associated with a
user domain, and a process running as the owner of that user domain may make
modifications. Root may modify any GUI domain. GUI domains do not exist on iOS.

session/<asid>/[service-name]
Targets a session domain or service within. A process running within the target
security audit session may make modifications. Root may modify any session
domain.

pid/<pid>/[service-name]
Targets a process domain or service within. Only the process which owns the
domain may modify it. Even root may not do so.

When using a legacy subcommand which manipulates a domain, the target domain is
inferred from the current execution context. When run as root (whether it is
via a root shell or sudo(1)), the target domain is assumed to be the
system-wide domain. When run from a normal user's shell, the target is assumed
to be the per-user domain for that current user.`

Most interesting to this discussion are the `system` and `user` domain types. If the legacy subcommands still work for you it's totally fine to keep using them. But the new subcommands require a lot less guess-work in terms of the context you want to manipulate. (Ask anyone who wanted to load or unload a job in another user's session in Mavericks and earlier, for example.)

The "system-wide" domain is comprised mainly of stuff from `/System/Library/LaunchDaemons`. There is one `user` and `gui` domain per logged-in user on the system, both comprised mainly of stuff from `/System/Library/LaunchAgents` as described in the `launchd.plist(5)` man page under the `LimitLoadToSessionType` key.

**Comment by DomT4** [comment] 2015-04-16 01:08
The new language is a nightmare. Since the old language still works, I've been pretty content sticking to it until Apple force us elsewhere. It's considerably less complex and confusing than the new language. 'Tis the reason I haven't pushed any PRs to "update" the language yet. Up to someone else if they want to climb into that maze :smile_cat:

**Comment by dsorresso** [comment] 2015-04-16 01:21
I'd file a bug against Apple asking for either better documentation or convenient shortcuts for the new subcommands. Stuff like `load`, `unload`, etc. attempted to guess which context you wanted to target, but it got into weird and unexpected territory in a few edge cases. 

Maybe the new subcommands could be made to recognize shortcuts based on the environment (i.e. if you're running as user 501, target the named thing in user 501's context).

**Comment by eddiezane** [comment] 2015-04-16 21:39
I have a feeling things are still going to change. Commands like `unbootstrap` return
> Command is not yet implemented.

I maintain a [gem](https://github.com/eddiezane/lunchy) that wraps launchctl and have been putting off making it compliant with the new commands. Hoping that the next set of changes they ship include better explanations.

**Comment by tadelv** [comment] 2015-07-08 12:27
How are you gentlemen,
Are there any open pull requests for this issue?

**Comment by mikemcquaid** [comment] 2015-07-08 12:54
@tadelv Not yet. We'd welcome one, though!

**Comment by tadelv** [comment] 2015-07-10 12:13
I see. I have been playing around with launchctl on 10.10 and 10.11. Yosemite version has missing functionality for unbootstrap as mentioned by @eddiezane, while "El Capitan" has another subcommand called bootout for this which actually works.

the domains are split by session types:
system is the root domain (sudo, etc, no gui access (at least shouldn't be))
user/uid is the users background domain, no gui access 
gui/uid is the users login session (gui access)
pid/pid is the session for the pid you specify - haven't really looked into this one.

So in short:
if you want a system wide daemon (for servers, etc) use sudo launchctl bootstrap system /Library/LaunchDaemons/my.awesome.plist
if you want a server that will activate for each of your logins (ssh, telnet, console), user launchctl bootstrap user/uid /Library/LaunchAgents/my.awesome.agent.plist
if you want to start a gui (Aqua) program, use launchctl bootstrap gui/uid /Library/LaunchAgents/my.awesome.agent.plist

@mikemcquaid I'm not sure what is there to be fixed actually... :) I looked at caveats.rb but couldn't really understand it after 2mins of reading.

**Comment by mikemcquaid** [comment] 2015-07-10 13:46
> @mikemcquaid I'm not sure what is there to be fixed actually... :) I looked at caveats.rb but couldn't really understand it after 2mins of reading.

Basically just the stuff that's being printed about `launchctl` in `caveats.rb` may need to be updated depending on the OS X version.

**Comment by dsorresso** [comment] 2015-07-10 17:00
> system is the root domain (sudo, etc, no gui access (at least shouldn't be))

Yes, the WindowServer will deny any attempt to draw to the screen if you're a daemon running in the system session.

> user/uid is the users background domain, no gui access 

Correct. Notably, these domains can exist even when a user is not logged in. This is why you might see processes running as a certain user despite that user not being logged in at either the GUI console or via SSH.

> gui/uid is the users login session (gui access)

Yep, and importantly, these domains gets torn down when the user logs out, so any services in them will be terminated.

> pid/pid is the session for the pid you specify - haven't really looked into this one.

This primarily relates to XPC services. By default, when an app embeds XPC services (or links against a framework that embeds them), they are scoped such that they are only accessible by that process. So each process gets its own private instance of XPC services. That is the collection of services that the `pid` specifier lets you examine.

In the implementation before Yosemite, examining these domains was a pretty big pain in the ass and completely different from how you'd examine other launchd services. Now it's all unified under one syntax, so examining an XPC service is exactly like examining a launchd job. They are represented by the same data structure.

> So in short:
> if you want a system wide daemon (for servers, etc) use

> `sudo launchctl bootstrap system /Library/LaunchDaemons/my.awesome.plist`

It's worth noting here that, in the `load` and `unload` commands, `sudo` to implies that you wanted the thing to load in the system domain. The new subcommands are explicit because the `sudo(1)` behavior made things very confusing if the user was logged into the GUI as root (or had `su(1)`ed to root), since the root user would have its own GUI session that the user might want to manipulate. There wasn't really a good story around this behavior.

Also, it's much, much easier to get something loaded into another user's domain with the new explicit syntax, something that was always a royal pain for anyone writing an installer. You can use `sudo(1)` and then target the user domain you want. All that's required is proper privileges; you don't have to much with the bootstrap port or the `LAUNCHD_SOCKET` environment variable.

> I might also have misread/generally missed something. Please correct me if I'm wrong :)

You're pretty much correct. If something in unclear in the documentation, I encourage you to file a bug asking for clearer documentation and/or examples.

**Comment by Tonyliu2ca** [comment] 2015-07-19 05:54
Before 10.10, at least I can tell, all the launchd plist file domains are distinguished by where the file saved, i.e. all defined in /Library/LaunchDaemons are system daemons, ~/Library/LaunchAgents are user agents and wherever in who's user home, it belongs to that user's domain (user/$uid) launchd agent. This' clear and confirmed by plist file location.

In 10.10, it looks like not based on file locations, but can be assigned whatever admin wants. for example, admin can assign /Library/LaunchDaemons/my.awesome.plist to be system bootstrap and later on, make it user one, even more, it can be made to be different based on user ID probably. files saved in same location, can be system domain, user or gui domains and no one can tell. on the other hand, before a network AD user login, who knows who will log onto which computer, and we cannot tell the user ID before a user login, so how do we assign a plist for that user domain (user/$uid or gui/$uid)?
it is confuse.

**Comment by jfindlay** [comment] 2016-03-22 01:54
Sorry for all the references :embarrassed:.  I forgot I had had that in the commit message.

**Comment by mikemcquaid** [comment] 2016-04-02 16:09
10.11 has come around and this still isn't a problem for us using the existing caveats so: closing.

**Closed by mikemcquaid** 2016-04-02 16:09 UTC
Labels: 10.10
