### ISSUE TITLE
Space in path of XCode causes build error.

### ISSUE THREAD

**Issue by jokester** [Homebrew/homebrew#40361] opened 2015-06-04 02:10 UTC
Hello

I find that a space in path of XCode can cause build error, like in https://gist.github.com/jokester/8451ba450202150d0f3a#file-brew-install-macvim-verbose-L11-L13 .

It seems `sh` are receiving space-delimited substrings as its arguments.

Just confirmed this error can be avoided by removing space from path of XCode. Still it may be better to correctly handle space in the path.

**Comment by mistydemeo** [comment] 2015-06-04 02:27
I don't think this error is caused by Homebrew; the command that failed is actually from within the macvim makefile, and the flags causing this aren't being passed by Homebrew. Can you build Macvim outside Homebrew? Might be better to report this to them.

**Comment by jacknagel** [comment] 2015-06-09 02:47
This is definitely a problem that needs to be addressed upstream, so closing.

**Closed by jacknagel** 2015-06-09 02:47 UTC
Labels: upstream issue
