### ISSUE TITLE
pinentry ignores backspace

### ISSUE THREAD

**Issue by proski** [Homebrew/homebrew#40335] opened 2015-06-03 02:27 UTC
pinentry (the curses version) ignores backspace. The backspace key sends code 0x7f both in iTerm and in Terminal.app. Ctrl-H works, but it's not intuitive. Users may have trouble fixing errors in the password.

**Comment by jacknagel** [comment] 2015-06-03 02:51
Sounds like something that should be reported to the pinentry authors rather than Homebrew?

**Comment by chdiza** [comment] 2015-06-06 15:11
Is this problem still occurring in the newly-released `pinentry 0.9.4`?

0.9.3 was full of little problems, if the gnupg-dev mailing list is any indication.

**Comment by jacknagel** [comment] 2015-06-16 03:03
This still happens on 0.9.4.

**Comment by chdiza** [comment] 2015-06-16 04:38
I can confirm.  Has anyone reported it upstream?

As another data point, I noticed there is no backspace problem with their newly-included `pinentry-tty`. 

(Homebrew doesn't enable that in the formula; unconnected with the present issue, I'm thinking about making a PR to add it).

**Comment by chdiza** [comment] 2015-06-16 04:43
Well this is weird.  I can confirm the bug also on the curses mode of `pinentry-mac`, which has embedded `pinentry 0.8.1`.  I have a hard time believing that backspacing is broken on pinentry on OSX since that far back.  I could swear I've used it myself within the last couple of years.  Perhaps Yosemite broke something.

**Comment by chdiza** [comment] 2015-06-18 13:47
Ping.

If nobody has reported it yet, I will, but I don't want to issue a duplicate report.

**Comment by mikemcquaid** [comment] 2015-06-18 17:33
@chdiza That'd be great, thanks!

**Comment by chdiza** [comment] 2015-06-20 02:51
[Done](https://bugs.gnupg.org/gnupg/issue2020).

**Comment by chdiza** [comment] 2015-06-23 18:45
OK, after lots of pain, this has been fixed in [upstream's git repo](http://git.gnupg.org/cgi-bin/gitweb.cgi?p=pinentry.git;a=commit;h=6ce1d0c0d4106c359eee65d7cf27d522d3f8b72a).  It is not yet in a release.  I also asked if they'd cut a release quickly to help out OSX users.

Turns out, backspace (what's labeled "delete" on Mac keyboarads near their northeast corners) has NEVER worked in pinentry on OSX.

In the meantime, you can just use Ctrl-h instead of backspace/delete.

Maintainers: we can also (untested but should work) apply the patch, and then remove it at next release.  Shall I make a PR now, or wait to see if they cut a release tomorrow?

```diff
diff --git a/pinentry/pinentry-curses.c b/pinentry/pinentry-curses.c
index 235435a..784c770 100644
--- a/pinentry/pinentry-curses.c
+++ b/pinentry/pinentry-curses.c
@@ -705,7 +705,11 @@ dialog_input (dialog_t diag, int alt, int chr)
   switch (chr)
     {
     case KEY_BACKSPACE:
-    case 'h' - 'a' + 1: /* control-h.  */
+      /* control-h.  */
+    case 'h' - 'a' + 1:
+      /* ASCII DEL.  What Mac OS X apparently emits when the "delete"
+	 (backspace) key is pressed.  */
+    case 127:
       if (diag->pin_len > 0)
 	{
 	  diag->pin_len--;
```

Also, be aware that when the next release lands we're going to have to add another `--disable-FOO` flag.  That's because there is forthcoming some kind of "emacs" version of `pinentry`, and at least right now, their HEAD won't build on OSX without disabling it.  I'll take care of all this when the release lands.

**Comment by proski** [comment] 2015-06-23 19:46
Thank you for fixing that bug! I confirm that Delete on the native keyboard and Backspace on an external USB keyboard erase the preceding character. To compile pinentry, I checked it out from `git://git.gnupg.org/pinentry.git` I had to use `brew link --force gettext` before autogen.sh as suggested somewhere on StackExchange to avoid unexpanded macros. For whatever reason, I cannot post comments on the GnuPG bugtracker, so please feel free to repost my gratitude and my test results there :)

**Closed** 2015-06-24 02:43 UTC
Labels: upstream issue
