### ISSUE TITLE
Can't install LLVM; selected compiler could not find or parse C++ library headers

### ISSUE THREAD

**Issue by cat-j** [Homebrew/homebrew#38179] opened 2015-03-29 15:14 UTC
`Mac-2:test_app mac$ brew install llvm`
`==> Downloading http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz`
`######################################################################## 100.0%`
`==> Patching`
`patching file Makefile.rules`
`==> ./configure --prefix=/usr/local/Cellar/llvm/3.5.1 --enable-optimized --disab`
`checking whether we are using the GNU C++ compiler... no`
`checking whether clang++ accepts -g... no`
`checking how to run the C preprocessor... clang -E`
`checking whether clang works... no`
`configure: error: Selected compiler could not find or parse C++ standard library headers.  Rerun with CC=c-compiler CXX=c++-compiler ./configure ...`

How do I run the command with the compilers mentioned in the error message?

**Comment by jacknagel** [comment] 2015-03-29 15:44
Please follow the instructions at https://git.io/brew-troubleshooting when opening a new issue.

Though based on this and other issues you've opened, there appears to be a more general problem with the compilers on your system, so you should focus on that rather than opening new issues for different formulae.

**Comment by cat-j** [comment] 2015-03-29 16:18
I figured something was wrong with my configuration, but I don't know how to fix it and I can't find any help online. A lot of guides on how to set up LLVM and other tools assume the user already knows which directory everything should be in and has compiled things before and they don't link to any resources for people with less experience. I don't even know how to get started with this.

**Comment by jacknagel** [comment] 2015-04-30 00:59
Closing as a dupe of #38155; ultimately they have the same root cause.

**Closed by jacknagel** 2015-04-30 00:59 UTC
Labels: user configuration
