### ISSUE TITLE
openssl 1.0.2g fails to build on 10.6.8

### ISSUE THREAD

**Issue by frickler01** [Homebrew/homebrew#49814] opened 2016-03-06 09:30 UTC
It breaks during compilation with
```
gcc-4.2 -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -c  -o sha1-x86_64.o sha1-x86_64.s
sha1-x86_64.s:1243:missing or invalid immediate expression `0b00011011' taken as 0
sha1-x86_64.s:1243:suffix or operands invalid for `pshufd'
sha1-x86_64.s:1245:missing or invalid immediate expression `0b00011011' taken as 0
sha1-x86_64.s:1245:suffix or operands invalid for `pshufd'
sha1-x86_64.s:1395:missing or invalid immediate expression `0b00011011' taken as 0
sha1-x86_64.s:1395:suffix or operands invalid for `pshufd'
sha1-x86_64.s:1396:missing or invalid immediate expression `0b00011011' taken as 0
sha1-x86_64.s:1396:suffix or operands invalid for `pshufd'
make[2]: *** [sha1-x86_64.o] Error 1
make[1]: *** [subdirs] Error 1
make: *** [build_crypto] Error 1
```
See the [gist-log](https://gist.github.com/5de7aa4f00f09b477729) for details. This is from my ~~messed up~~ carefully set up regular machine, but the deviations don't affect the outcome. Same results on freshly installed OS without changes to homebrew defaults.

This has already been discussed [upstream](https://groups.google.com/forum/?_escaped_fragment_=topic/mailing.openssl.dev/gYxZkC4F08o#!topic/mailing.openssl.dev/gYxZkC4F08o) but having a 10.6 option to get the correct patch would be nice.

I tried to [patch](https://github.com/akamai/openssl/commit/c4af68c317c025c7d0c4f0495b8115d6426a25be.patch) in what they claimed to be working by adding
```
  if MacOS.version <= :lion
    patch do
      url "https://github.com/akamai/openssl/commit/c4af68c317c025c7d0c4f0495b8115d6426a25be.patch"
      sha256 "03bb853487e52005f264923f61f2fd74b74396b54bd1742fdf3cec33d7b2cb36"
    end
  end
```
to the formula, but that gave me `Hunk #1 FAILED at 192`. I probably missed some important detail.

### On a slightly different topic
Since I'm presumably stuck with 10.6.8 for an indefinite amount of time, use brewed software on a daily basis and have a mostly unused rig standing around, I could offer a testing and bottling machine to let `homebrew` support 10.6 again. Of course I'd throw in some time for maintenance of formulas. If that's of any interest. I'd need some pointers how to set it up properly though.

**Comment by ilovezfs** [comment] 2016-03-06 18:12
@frickler01 The MacPorts doppelgängers have fixed this:
https://trac.macports.org/ticket/50771
https://github.com/openssl/openssl/pull/792
https://github.com/neverpanic/openssl/commit/89c89c60953aa8dae34a777d6010829b9f1a742f

I reproduced the issue, and verified that the patch allows the brew formula to build on 10.6.8

Add this to your openssl.rb:
```
diff --git a/Library/Formula/openssl.rb b/Library/Formula/openssl.rb
index e8a0389..8386fe0 100644
--- a/Library/Formula/openssl.rb
+++ b/Library/Formula/openssl.rb
@@ -22,6 +22,11 @@ class Openssl < Formula
 
   depends_on "makedepend" => :build
 
+  patch do
+    url "https://github.com/neverpanic/openssl/commit/89c89c60953aa8dae34a777d6010829b9f1a742f.diff"
+    sha256 "4dcd647966840c6ccc6c9da2711ac4e9f504d016846f5b830a8a309a4996b343"
+  end
+
   def arch_args
     {
       :x86_64 => %w[darwin64-x86_64-cc enable-ec_nistp_64_gcc_128],

```

**Comment by ilovezfs** [comment] 2016-03-06 18:31
@frickler01 you should now be able to do
```
brew pull 49827
```
if you don't want to edit the rb manually.
(https://github.com/Homebrew/homebrew/pull/49827)

**Comment by neverpanic** [comment] 2016-03-06 20:40
@ilovezfs I think this should be fixed in a different way; the crypto/perlasm/x86_64-xlate.pl post-processes whatever crypto/aes/asm/aesni-sha1-x86_64.pl writes to stdout, and has previously replaced the offending `0bsomething` constant with a different representation.

Instead, we should either revert the commit that broke this (openssl/openssl@fd7dc20), or revert and apply the alternative suggestion from akamai/openssl@c4af68c.

If you link the commit from my fork of openssl, does that mean I can no longer delete the forked repo without breaking your formula? I usually regularly delete forks with no open pull requests and no active development from my github account.

**Comment by frickler01** [comment] 2016-03-06 23:18
@neverpanic +1 for using the upstream patch. How exactly does this work in homebrew?

**Comment by ilovezfs** [comment] 2016-03-07 00:05
@neverpanic Breaking the formula would be the right thing to have happen because presumably at that point you're deleting it because it's been superseded by an upstream commit or an alternative fix, which should be used in the formula instead. When a longer term patch is needed and there is no upstream commit or stable url, the patch can be inlined in the formula or added to the https://github.com/Homebrew/patches/ repository.


@frickler01 You're confused, I think. There is no upstream patch yet. That's the point of the comment in the pull request:
https://github.com/Homebrew/homebrew/pull/49827/files#diff-5f8300a99f5c14b861dfa8eff2905a16R25

How does it work? By using a `patch do` block to apply the diff from the commit just like every other `patch do` block in brew. The underlying magic is that GitHub lets you append ".diff" to any commit to format it as a raw git diff: https://github.com/blog/967-github-secrets

**Comment by frickler01** [comment] 2016-03-07 00:51
@ilovezfs I'm sorry, I meant revert the breaking commit. That was sort of upstream for me. Therefore the question: How do you revert a single commit out of the repo in homebrew? The point is that the basis for overriding that commit will stay in the official branch for good.

**Comment by ilovezfs** [comment] 2016-03-07 01:37
@frickler01 I refreshed the PR. Take a look ;)

@neverpanic Better?
https://github.com/Homebrew/homebrew/pull/49827/files
https://github.com/Homebrew/patches/pull/11/files

**Comment by frickler01** [comment] 2016-03-07 07:59
@ilovezfs Ah I see, its that easy. :)

**Comment by mikemcquaid** [comment] 2016-03-07 08:27
> Since I'm presumably stuck with 10.6.8 for an indefinite amount of time, use brewed software on a daily basis and have a mostly unused rig standing around, I could offer a testing and bottling machine to let homebrew support 10.6 again. Of course I'd throw in some time for maintenance of formulas. If that's of any interest. I'd need some pointers how to set it up properly though.

Unfortunately it's not just about having a testing/bottling machine but about the balance of users vs. effort. Just to give you a heads up as I suspect you'll be disappointed: at some point in the relatively near future we are going to officially drop 10.6 support so Homebrew will refuse to work there, unfortunately. We just don't have the resources to adequately support old versions.

**Comment by frickler01** [comment] 2016-03-07 08:36
I already thought so... Well then I'll have to fork some kind of SL-brew from that point and see how far I make it. @ilovezfs are you in? ;)

**Comment by mikemcquaid** [comment] 2016-03-07 08:39
@frickler01 Likely https://github.com/mistydemeo/tigerbrew#tigerbrew is your best fit for this.

**Comment by frickler01** [comment] 2016-03-07 08:57
I'm aware of tigerbrew, I just thought it's mainly focused on PPC builds. I'll look into it.

**Closed** 2016-03-07 11:21 UTC

**Comment by neverpanic** [comment] 2016-03-07 17:25
@ilovezfs Yes, much better. Note that the git copy of the MacPorts ports tree that you referenced in the commit message is currently temporary and subject to force-pushes and history rewriting until further notice, so the reference will likely break in a few days.
