### ISSUE TITLE
Xcode CLT 6.3 libc++ headers #include missing debug header, causing build failures

### ISSUE THREAD

**Issue by pyed** [Homebrew/homebrew#38514] opened 2015-04-10 13:39 UTC
I'm trying to build libtorrent-rasterbar from source:
```shell
brew install libtorrent-rasterbar --with-geoip --with-python --build-from-source
```

the error happened while building the boost library, here's the huge log file 'b2' from ~/Library/Logs/Homebrew/boost/02.b2
https://gist.github.com/pyed/593ade6f4a7d5035e0cc

brew doctor is fine, 

brew config
```shell
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: dc612ee11e870ccc7cda08edebfe9f0fcae9c47b
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: N/A
CLT: 6.3.0.0.1.1428348375
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: N/A
```

**Comment by pyed** [comment] 2015-04-10 14:44
with bottled boost can't build too 

```shell
 ~  brew install libtorrent-rasterbar --with-geoip --with-python
==> Installing dependencies for libtorrent-rasterbar: boost, boost-python
==> Installing libtorrent-rasterbar dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.57.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring boost-1.57.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.57.0: 10572 files, 439M
==> Installing libtorrent-rasterbar dependency: boost-python
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2
######################################################################## 100.0%
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.57.0 --libdir=/usr/local/Cellar/boost-python/1.57.0/lib --with-librari
==> ./b2 --build-dir=build-python --stagedir=stage-python python=2.7 --prefix=/usr/local/Cellar/boost-python/1.57.0 --libdir=/usr/l
...skipped <pbuild-python/boost/bin.v2/libs/python/build/darwin-4.2.1/release>libboost_python.dylib for lack of <pbuild-python/boost/bin.v2/libs/python/build/darwin-4.2.1/release>numeric.o...
...skipped <pstage-python/lib>libboost_python.dylib for lack of <pbuild-python/boost/bin.v2/libs/python/build/darwin-4.2.1/release>libboost_python.dylib...
...failed updating 108 targets...
...skipped 10 targets...
...updated 25 targets...
```

**Comment by mistydemeo** [comment] 2015-04-10 17:14
The error:

> /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found

I think this may be a header bug in the new CLT; `#include <__debug>` was conditional on `__LIBCPP_DEBUG` in the previous version.

**Comment by DomT4** [comment] 2015-04-10 18:02
@mistydemeo Does this need kicking to Apple?

**Comment by mistydemeo** [comment] 2015-04-10 18:06
Yes, I'll file an rdar.

**Comment by DomT4** [comment] 2015-04-10 18:07
Okay, cool. Thanks. Bit of a bumpy 10.10.3 release so far.

**Comment by mistydemeo** [comment] 2015-04-10 20:56
http://openradar.appspot.com/radar?id=6405426379751424

**Comment by mistydemeo** [comment] 2015-04-10 20:57
Filed an rdar and mirrored to openradar, since this is of interest to other people.

**Comment by MindTooth** [comment] 2015-04-11 13:42
Can confirm this with flac as well :-(

**Comment by nigelm** [comment] 2015-04-11 16:28
Workround, posted on http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

#### The Fix

    echo '#define _LIBCPP_ASSERT(x, m) ((void)0)' | sudo tee -a /Library/Developer/CommandLineTools/usr/include/c++/v1/__debug > /dev/null

#### Cleanup

    sudo rm /Library/Developer/CommandLineTools/usr/include/c++/v1/__debug

**Comment by ssbanerje** [comment] 2015-04-12 16:56
This might be the same problem as in #38501 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65733

**Comment by UniqMartin** [comment] 2015-04-12 22:38
From what I can tell, the issue arises only with Command Line Tools 6.3 (CLT; this one is missing the `__debug` header file), but not with Xcode 6.3 (this one ships with the `__debug` header file). Thus, the issue title is slightly misleading and it would be great to change it.

To be more specific, these are the two standard locations that contain `libc++` headers:
* CLT: `/Library/Developer/CommandLineTools/usr/include/c++/v1` – lacks `__debug`
* Xcode: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1` – contains `__debug`

All other locations with C++ header files belong to the now deprecated, but still supported `libstdc++` from GCC 4.2.1.

(Sorry, but I'm pretty sure #38501 is not related.)

**Comment by fmonserrat** [comment] 2015-04-15 00:22
I think this is the same issue I'm facing with:
brew install gecode

/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.

**Comment by tdsmith** [comment] 2015-04-15 22:25
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` will work around this issue if you have full Xcode installed.

**Comment by tdsmith** [comment] 2015-04-15 23:24
I tried to hack around it by providing an empty \_\_debug header but e.g. `<string>` references a _LIBCPP_ASSERT macro unconditionally, so this doesn't work: https://github.com/Homebrew/homebrew/compare/master...tdsmith:clt6.3-workaround

**Comment by UniqMartin** [comment] 2015-04-16 22:58
I think the cleanest solution would be to wait for Apple to fix this in the CLT and in the meantime tell people to install and use Xcode. (Certainly not a lightweight workaround.)

If one really wants to avoid Xcode and still provide a workaround, @tdsmith's general approach looks reasonable to me. Why not take the full `__debug` header file from Xcode instead of providing an empty one? Or one could take it directly from the [LLVM Subversion repository](http://reviews.llvm.org/diffusion/L/browse/libcxx/tags/RELEASE_360/final/include/__debug) (the one from LLVM 3.6 that Xcode 6.3 is based on).

**Comment by jwuwork** [comment] 2015-04-17 01:54
I noticed you guys are having the same issue I had a few days ago, so here's the fix:

http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3/29576048#29576048

Hope this helps.

**Comment by tdsmith** [comment] 2015-04-17 06:11
> Or one could take it directly from the LLVM Subversion repository (the one from LLVM 3.6 that Xcode 6.3 is based on).

Nice. Opened #38735 for discussion.

**Comment by mitar** [comment] 2015-04-19 20:30
`nmap` has the same issue.

**Comment by DomT4** [comment] 2015-04-22 02:20
Apple just landed an Xcode and CLT update for 10.10. Should be available in MAS now.

**Comment by mitar** [comment] 2015-04-22 03:05
And does the update fix the missing file?

**Comment by DomT4** [comment] 2015-04-22 03:06
I'll let you know in about... 3GB time :wink:

**Comment by UniqMartin** [comment] 2015-04-22 03:26
Yes, it does. The new version (6.3.1.0.1.1429149539, to be precise) of the stand-alone Command Line Tools now includes the `__debug` header that went missing in the previous iteration (6.3.0.0.1.1428348375). All other changes in the package seem to be exclusively Swift-related.

**Comment by slhck** [comment] 2015-04-22 19:51
I can confirm this is working for me as well after today's CLI tools update.

**Closed** 2015-04-23 08:25 UTC
