### ISSUE TITLE
Git bash completion not based on the best available

### ISSUE THREAD

**Issue by asbjornu** [Homebrew/homebrew#43089] opened 2015-08-19 12:35 UTC
The [current bash completion recipe](/homebrew/blob/master/Library/Formula/bash-completion.rb) is based on [this](https://bash-completion.alioth.debian.org/) instead of [this](/git/git/blob/master/contrib/completion/git-completion.bash). The latter supports completion of branches and such which the former doesn't. 

I'm clueless on how to create a brew recipe, so I'm wondering if it would be possible for someone to create a recipe for the `git-completion.bash` script? It may be a challenge that the `git-completion.bash` script resides in the enormous [Git](/git/git) repository and all we want is that single file? I dunno. Any pointers and help would be highly appreciated.

**Comment by bfontaine** [comment] 2015-08-19 12:49
I’m confused. The formula you linked to is for Bash completion, it has nothing to do with Git. Use `brew install git` to get the latest `git` as well as the official completion script.

**Comment by asbjornu** [comment] 2015-08-19 13:35
I'm the one that is confused, obviously. I already have the latest version of Git. Where do I find the `git-completion.bash` script?

**Comment by bfontaine** [comment] 2015-08-19 13:45
It should be in `$(brew --prefix)/etc/bash_completion.d/git-completion.bash`.

**Comment by DomT4** [comment] 2015-08-20 02:02
Closing per the above. Unless you chose to build `git --without-completions` those will exist.

**Closed by DomT4** 2015-08-20 02:02 UTC

**Comment by asbjornu** [comment] 2015-08-20 06:53
@bfontaine Indeed it is. But as with `$(brew --prefix)/etc/bash_completion`, it is installed without an executable flag. Is that as intended or a bug I should create a separate issue for?

**Comment by bfontaine** [comment] 2015-08-24 13:13
@asbjornu completion scripts must be sourced, not executed. So no, it’s not a bug.

**Comment by asbjornu** [comment] 2015-08-24 13:28
@bfontaine I see. Thanks!
