### ISSUE TITLE
build swftools and zlib not found

### ISSUE THREAD

**Issue by sbellan61** [Homebrew/homebrew#39648] opened 2015-05-11 19:12 UTC
I'm trying to install swftools on my Mac OS 10.10.2.

I've successfully installed zlib with

brew tap homebrew/dupes
brew install zlib

and installed the other swftools dependencies (jpeglib, freetype). But when I do ./configure, I get

ERROR:
You need zlib to compile swftools

Yet, it seems the zlib install was successful:

brew list zlib
/usr/local/Cellar/zlib/1.2.8/include/ (2 files)
/usr/local/Cellar/zlib/1.2.8/lib/libz.1.2.8.dylib
/usr/local/Cellar/zlib/1.2.8/lib/pkgconfig/zlib.pc
/usr/local/Cellar/zlib/1.2.8/lib/ (3 other files)
/usr/local/Cellar/zlib/1.2.8/share/man/man3/zlib.3

So it seems like the swftools configuration just isn't finding zlib--but I have no idea how to help it. Help appreciated!

**Comment by DomT4** [comment] 2015-05-11 19:33
You already have `zlib` installed on OS X, Apple install it by default. Homebrew Dupes' `zlib` is `keg_only` to not ram into the system version and potentially break things, which is why `swftools` won't be finding that particular `zlib`.

Are you trying to compile `swftools` using Homebrew or outside of Homebrew?

**Comment by sbellan61** [comment] 2015-05-11 19:51
Thanks Dominyk. I had been trying to install it outside of homebrew. However, just now I tried it with homebrew and got the same problem as shown below--as you can see it refers me to this issue :)

Any more guidance would be much appreciated

stevebemacbook3:swftools-0.9.2 sbellan$ brew install swftools
==> Downloading http://www.swftools.org/swftools-0.9.2.tar.gz
######################################################################## 100.0%
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/swftools/0.9.2
==> make
2015-05-11 14:49:22 -0500

make

make: *** No targets specified and no makefile found.  Stop.
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
build swftools and zlib not found (https://github.com/Homebrew/homebrew/issues/39648)

**Comment by DomT4** [comment] 2015-05-11 19:53
Can you do a full `brew gist-logs swftools`? It'll show much more detail.

**Comment by sbellan61** [comment] 2015-05-11 20:15
All it shows is this:

stevebemacbook3:~ sbellan$ brew gist-logs swftools
https://gist.github.com/fb852c6c1cbf3f2738b3
stevebemacbook3:~ sbellan$

**Comment by sbellan61** [comment] 2015-05-11 20:16
Ah, I see that the URL has the info you’re probably looking for.

**Comment by DomT4** [comment] 2015-05-11 20:24
The mountain of `brew doctor` warnings are worth following up on. Fairly sure those are the cause of your pain here, and any other problems you hit during `brew` compiles.

This should fix your immediate issue:
* `rm /usr/local/lib/libz.1.2.8.dylib`
* `rm /usr/local/include/zlib.h`
* `rm /usr/local/lib/pkgconfig/zlib.pc`
* `rm /usr/local/lib/libz.a`

I also recommend:

* `brew update`
* ```sudo chown -R `whoami` /usr/local/share/man```
* `brew cleanup && brew prune`
* Update your CLT & Xcode packages
* Ensure `xcodeselect` points to an Xcode or CLT path that exists

**Comment by sbellan61** [comment] 2015-05-11 20:33
I removed those four files and did the first 3 commands you recommended. Then tried

brew install swftools

Still have the same problem. I’m not sue how to do your last 2 recommendations, any further guidance on those (though it sounds like you don’t think they’re directly relevant)? I really help your continued support on this Dominyk.

Steve

**Comment by DomT4** [comment] 2015-05-11 20:45
Does it give a different failure, or another one? You can see more detail by tacking `--verbose` onto your `brew install` instruction. If you have `zlib` installed via MacPorts you may need to remove it there as well, since your compile is checking the MacPorts include paths as well.

The last one may actually be directly relevant, depending on where it's trying to pull the files from. What does `xcode-select -p` say? And where do you have Xcode installed on your system? If you don't know the latter, `mdfind xcode | grep Xcode.app` is usually a decent bet for finding it.

**Comment by sbellan61** [comment] 2015-05-11 21:04
All 3 queries below. Yes, I forgot I had used macports to install a bunch of stuff a few years back. Didn’t realize there was any macports/homebrew interaction that could cause conflict. I tried uninstalling zlib with macports and it said I’ll have to uninstall a few other packages first. I also thought maybe I should just install swftools with macports instead of homebrew then, but that didn’t work either. Everything copied below with each item separated by a blank line.

sudo port uninstall zlib
Password:
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
--->  Unable to uninstall zlib @1.2.3_3, the following ports depend on it:
--->  	gdal @1.6.2_0
--->  	libgeotiff @1.2.5_1
--->  	libpng @1.2.40_0
--->  	tiff @3.9.1_0+macosx
Error: port uninstall failed: Please uninstall the ports that depend on zlib first.

sudo port install swftools
sudo port install swftools
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
Warning: xcodebuild exists but failed to execute
Warning: Xcode does not appear to be installed; most ports will likely fail to build.
Warning: Xcode does not appear to be installed; most ports will likely fail to build.
--->  Configuring jpeg
Error: Failed to configure jpeg, consult /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_jpeg/jpeg/work/jpeg-9/config.log
Error: org.macports.configure for port jpeg returned: configure failure: command execution failed
Please see the log file for port jpeg for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_jpeg/jpeg/main.log
Error: Unable to upgrade port: 1
Error: Unable to execute port: upgrade jpeg failed
bash-3.2$ port selfupdate
port selfupdate
--->  Updating MacPorts base sources using rsync
Error: Error synchronizing MacPorts sources: command execution failed
Please run `port -v selfupdate' for details.
Error: /opt/local/bin/port: port selfupdate failed: Error synchronizing MacPorts sources: command execution failed

bash-3.2$ xcode-select -p 
/Library/Developer/CommandLineTools

bash-3.2$ mdfind xcode | grep Xcode.app
mdfind xcode | grep Xcode.app
/Developer/Applications/Xcode.app
/Applications/Xcode.appdownload
/Previous Systems.localized/2010-09-13_0726/Developer/Applications/Xcode.app

bash-3.2$ brew install swftools --verbose
==> Downloading http://www.swftools.org/swftools-0.9.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/swftools-0.9.2.tar.gz
==> Verifying swftools-0.9.2.tar.gz checksum
tar xf /Library/Caches/Homebrew/swftools-0.9.2.tar.gz
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/swftools/0.9.2
checking build system type... i386-apple-darwin14.1.0
checking host system type... i386-apple-darwin14.1.0
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking whether gcc supports lazy variable declaration... yes
checking how to run the C preprocessor... clang -E
checking for ranlib... ranlib
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for gzip... gzip
checking for target system... 
checking for sin in -lm... yes
checking for deflate in -lz... no

ERROR:
You need zlib to compile swftools

==> make
make: *** No targets specified and no makefile found.  Stop.
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Formula
Path: /usr/local/Library/Formula/swftools.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: fd40341f8cbd79913e3a845856d104f38c99c92b
Last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.10.2-x86_64
Xcode: 6.0 => /Developer/Applications/Xcode.app/Contents/Developer
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
MacPorts/Fink: /opt/local/bin/port
X11: 2.1.5 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_65
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin

Error: swftools 0.9.2 did not build
Logs:
     /Users/sbellan/Library/Logs/Homebrew/swftools/01.configure
     /Users/sbellan/Library/Logs/Homebrew/swftools/01.configure.cc
     /Users/sbellan/Library/Logs/Homebrew/swftools/02.make
     /Users/sbellan/Library/Logs/Homebrew/swftools/config.log

These open issues may also help:
build swftools and zlib not found (https://github.com/Homebrew/homebrew/issues/39648)

**Comment by DomT4** [comment] 2015-05-11 21:35
Alright, we need to deal with the Xcode problem evidently. Let's try ` xcodebuild -version ` for a start, and then ` ls -1 /Developer/`.

**Comment by sbellan61** [comment] 2015-05-12 00:01
hmm, I get this 

bash-3.2$ xcodebuild -version
xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Should I uninstall Xcode completely and reinstall it? Maybe this has to do with me upgrading to Yosemite after installing Xcode and it not being updated appropriately?

If so, are these the best uninstall instructions:

http://macsecurity.net/view/66/ <http://macsecurity.net/view/66/>

**Comment by DomT4** [comment] 2015-05-12 00:34
I wouldn't recommend MacKeeper. As far as I'm aware, the `/Developer` directory isn't used any more, I thought that got phased out. Could be wrong. Apparently `/Developer/Library/uninstall-developer-folder` exists, so if it does go in there and use whatever scripts Apple has provided to remove whatever version of Xcode is lingering there.

You also have a partial download of a newer Xcode in `/Applications/Xcode.appdownload` which is worth just doing ` rm -rf /Applications/Xcode.appdownload ` on. After dealing with both of those, try the `brew install swftools` again and see what happens. The CommandLineTools should be enough to install most formulae, so I suspect your old/rogue Xcode install is the core problem.

**Comment by jacknagel** [comment] 2015-05-21 01:42
Closing since I don't think there is anything actionable here.

**Closed by jacknagel** 2015-05-21 01:42 UTC
Labels: user configuration
