### ISSUE TITLE
mongodb doesn't build on 10.11

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#40955] opened 2015-06-21 23:53 UTC
https://gist.github.com/anonymous/335036395941eb391ff7

**Comment by amw** [comment] 2015-06-22 12:11
Reported and fixed upstream. Use `brew install mongodb --devel`.

See https://jira.mongodb.org/browse/SERVER-17728

**Comment by mikemcquaid** [comment] 2015-06-22 12:44
@yurikoles Please do a bit more research before filing 10.11 issues e.g. see if you can reproduce outside Homebrew, submit issues and patches upstream and submit pull requests to fix things. We know a lot of things will be broken right now; only the first developer preview has been released and if you're running the developer preview you should aim to be filing detailed bug reports in relevant locations. Thanks!

**Comment by DomT4** [comment] 2015-06-22 14:32
Since there's a fix upstream already, moving this to triage in #40837. It's possible we'd consider passing `--disable-warnings-as-errors` to Scons for >= 10.11 - If someone wants to tee up a PR we'd review it.

**Closed by DomT4** 2015-06-22 14:32 UTC
Labels: 10.11

**Comment by amw** [comment] 2015-07-30 23:50
This fix has been back-ported to 3.0 branch in 3.0.5 which is now available in Homebrew without the `--devel` flag. You can mark this issue as fixed in #40837 .

**Comment by DomT4** [comment] 2015-07-31 00:01
Thanks, Updated the list!
