### ISSUE TITLE
ant-contrib not installing to ant lib folder

### ISSUE THREAD

**Issue by atrauzzi** [Homebrew/homebrew#41469] opened 2015-07-07 21:58 UTC
Just recently attempting to put together a build script in ant that uses ant-contrib.  Installed using homebrew.

Ant seems unable to locate the contrib jar.  See this stackoverflow answer for more details: http://stackoverflow.com/questions/31277698/how-to-abstract-ant-contrib-cross-platform/31277896#31277896

**Comment by atrauzzi** [comment] 2015-07-07 21:59
Solution here might be to ensure ant-contrib gets installed to the correct directory.  Otherwise, there isn't much of a point in offering it as part of homebrew.

**Comment by DomT4** [comment] 2015-07-07 22:14
You can see the discussion about inclusion, which includes placement discussion, in #27878.

We could look at adding caveats to the `ant-contrib` formula with a link to the http://ant-contrib.sourceforge.net/#install page which documents how to use the jar from a separate location.

**Comment by atrauzzi** [comment] 2015-07-08 03:57
That doesn't quite make sense unfortunately, especially considering this defines ant as a dependency.  Your suggestions obviates using homebrew to manage the package as I would be better off just statically adding it to my project.
When I install ant-contrib using apt-get on Debian, it gets installed somewhere that ant can resolve it and is "ready to go out of the box".  This is the behaviour you want to target.

Otherwise, you're effectively telling people to use homebrew to install something and then go to a web page, to download or copy and place it in their projects and ignore the one homebrew installed.  Consider for a moment that based on your suggestion, I'd have to write several lines of ugly detection in my build scripts.  Worse still, because I wouldn't just be detecting when people are on OSX, I'd also have to detect whether they were using homebrew, etc...

Ideally you would just place it where the homebrew-installed ant expects to see jar files.  Again, because the package depends on ant, the answer is clear here.

**Comment by DomT4** [comment] 2015-07-08 04:07
> Otherwise, you're effectively telling people to use homebrew to install something and then go to a web page, to download or copy and place it in their projects and ignore the one homebrew installed.

I wasn't. The part I was alluding to was:

> Keep ant-contrib-0.3.jar in a separate location. You now have to tell Ant explicitly where to find it (say in /usr/share/java/lib):

It's unusual that if this issue is so troublesome as you describe it but we haven't had a report on it before.

I have no particular objection to vendoring it directly into `ant` as an `option` aside it isn't an official Apache project and it could mislead people, but will let the rest of @Homebrew/owners discuss it given Mike/Adam made the original decision.

The choice is either the status quo or having it vendored optionally into the `ant` formula. We're not going to make it so it is its own formula but still installs directly into the `ant` directory; we've had all sorts of trouble with that dance before.

**Comment by atrauzzi** [comment] 2015-07-08 04:21
It's definitely troublesome, and I'd wager that people don't know where to advocate, assume everyone uses OSX or just end up statically bundling it into their projects.  Can't always depend on an audience to self-select ;)

If ant is defined as a dependency, why is installing directly to ant a problem?  This is the behaviour with apt-get and works beautifully.

**Comment by mikemcquaid** [comment] 2015-07-08 13:03
Can you provide a reproducible test-case to demonstrate the problem? We aren't `apt-get` so it's not just as simple as doing things the same way they do.

**Comment by atrauzzi** [comment] 2015-07-08 13:45
Just have this at the top of your ant script:

```
<project>
    <taskdef resource="net/sf/antcontrib/antcontrib.properties"/>
</project>
```

On Ubuntu, this works once you install the ant-contrib package.  And yeah, while I know you're not apt-get, most everyone brands you as the desperately needed equivalent on OSX. ;)

Again, there is a strong case to be made for removing this package from homebrew if it's not going to be integrated with the system.  That more or less makes the integration incomplete and people won't be able to use it without having their build scripts take a dependency on homebrew conventions.

Which won't end well when the build scripts run on a remote build server running linux.

The only way around this problem right now is to download and copy the ant-contrib.jar into the project and reference it directly via:

```
	<taskdef resource="net/sf/antcontrib/antlib.xml">
		<classpath>
			<pathelement location="bin/ant-contrib.jar" />
		</classpath>
	</taskdef>
```

**Comment by mikemcquaid** [comment] 2015-07-08 13:47
> Here's a "complete" ant build.xml you can use:

Sorry, please can you let me know where I should write that file, what command I should run, etc.

**Comment by atrauzzi** [comment] 2015-07-08 13:59
Just toss it anywhere and run `ant build.xml`.  It has no sideffects, so should be safe.  It'll just attempt to resolve the .jar via normal ant conventions and error out.

Then, if you want, put a copy of `ant-contrib.jar` in a `bin` directory and replace the `taskdef` with the 2nd snippet, it should pick it up statically.

**Comment by mikemcquaid** [comment] 2015-07-08 14:33
Ok, thanks. Where do you/ant consider to be the correct directory?

**Comment by atrauzzi** [comment] 2015-07-08 14:54
That's actually a good question.  I'm not entirely certain on that one, although the

**Comment by DomT4** [comment] 2015-07-15 20:22
Closed via #41514.

**Closed by DomT4** 2015-07-15 20:22 UTC

**Comment by rleigh-dundee** [comment] 2015-08-03 08:52
Is this really fixed, because I find I'm getting

```
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antcontrib.properties. It could not be found.
```

with the latest homebrew.

**Comment by mikemcquaid** [comment] 2015-08-03 09:38
@rleigh-dundee If it isn't: please provide a reproducible test case and, ideally, a PR.

**Comment by rleigh-dundee** [comment] 2015-08-03 10:51
The testcase is pretty much what @atrauzzi described:

```
cat build.xml
<project name="test">
  <taskdef resource="net/sf/antcontrib/antcontrib.properties"/>
  <taskdef resource="net/sf/antcontrib/antlib.xml"/>
</project>
% ant
Buildfile: /private/tmp/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antcontrib.properties. It could not be found.
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

BUILD SUCCESSFUL
Total time: 0 seconds
```

**Comment by mikemcquaid** [comment] 2015-08-03 10:58
Works here. Try to `brew reinstall ant ant-contrib && brew test ant-contrib`

**Comment by rleigh-dundee** [comment] 2015-08-03 11:02
Hmm, you're right.  I'd already reinstalled ant, must have been something with ant-contrib.  Sorry for the noise.
