### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by Neung07** [Homebrew/homebrew#42736] opened 2015-08-10 09:04 UTC

**Comment by black-snow** [comment] 2015-08-10 09:35
got this, too
brew doctor is fine

**Comment by bfontaine** [comment] 2015-08-10 11:25
Closed as a duplicate of #42553.

**Closed by bfontaine** 2015-08-10 11:25 UTC

**Comment by bfontaine** [comment] 2015-08-10 11:26
@black-snow No, the error comes from the fact that `brew update` updates its own code. The error appears only on one `brew update`, after the second one it’s fine. We have fixed the issue since, so it shouldn’t appear anymore.
