### ISSUE TITLE
Disable by default downloading source from insecure URLs

### ISSUE THREAD

**Issue by dgouldin** [Homebrew/homebrew#36711] opened 2015-02-10 20:54 UTC
When SF's cert busted today, I found homebrew falling back to installing from source :+1: and using non-tls urls to do so :-1:. Can allowing source from an insecure url be an override rather than the default? I'd rather users have to load that gun themselves.

**Comment by jacknagel** [comment] 2015-02-10 21:02
If you can point at specific packages, we can switch the URL to use https, if it's available. There is an ongoing effort to do this across all formulae.

Requiring an explicit opt-in would be a backwards-incompatible change, though.

**Comment by jdunck** [comment] 2015-02-10 21:04
It's a bug to insecurely install software.  Is there a backwards-compatibility concern for bugfixes?

**Comment by jacknagel** [comment] 2015-02-10 21:10
>It's a bug to insecurely install software.

That's a pretty unfair way to frame the issue. Many packages simply do not have any other available download source.

>Is there a backwards-compatibility concern for bugfixes?

If they change external behavior in a user-visible way, yes.

**Comment by dgouldin** [comment] 2015-02-10 21:10
[makedepend](http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2) for one

**Comment by tdsmith** [comment] 2015-02-10 21:18
Note that all downloads in formulas have checksums in the formula; you'd have to execute a sha1 collision attack to successfully MITM a Homebrew download. We'll be happy to take pull requests for individual packages that we can switch to https URLs.

**Comment by jdunck** [comment] 2015-02-10 21:19
I do appreciate that there are packages with no authoritative secure download.  Perhaps a version could be put out with a warning, and the following version could require a flag to proceed.

It would be good for the ecosystem for homebrew to apply pressure on packages to offer secure downloads.

**Comment by jdunck** [comment] 2015-02-10 21:20
@tdsmith or gain GH credentials for a user whose pull you'd trust.

**Comment by DomT4** [comment] 2015-02-10 22:11
> When SF's cert busted today, 

Sourceforge fairly frequently redirects to mirrors that aren't guarded by TLS. It's a little unfair to hold up SF as a standard that should be met without highlighting that small nit.

The SSL/TLS situation is something that is being improved. Where upstream SSL/TLS links are available, they should be switched as new PRs are submitted. SSL link auditing is something ` brew audit ` actually does for a host of popular links. It'd be awesome if Homebrew had the power to convince upstreams to adopt strong TLS protection for their websites and particularly download links, but alas.

It's not a bug to use an insecure download link when that is all upstream offer, and I think making blocking that capability the default would be a massive regression in usability for Homebrew. Not against an option, but I think making it the default is asking for misery.

> or gain GH credentials for a user whose pull you'd trust.

This wouldn't work, unless you also compromised the test bot. The Bot checks the given SHA itself, and will raise a fatal testing error if it detects a mismatch. So likely the PR would have to come from a compromised maintainer *and* be verified by a compromised test bot for it to be accepted. It's not as simple as just compromising an account of a regular contributor or someone trusted.

**Comment by tdsmith** [comment] 2015-02-10 22:11
Well, sure, and they'd have to have a good explanation for changing the hash and they'd have to MITM our build bot in a UK data center as well (not impossible, it's true) or else it would complain about the PR and complain again after it was pulled and eventually we'd get complaints from users. To be sure, I think the concern is good and we want to do what we can to make attacks difficult. I also think we're unlikely to require a `--allow-unverified-transit` option or similar because the UX cost/security benefit ratio doesn't seem very favorable. Hopefully Let's Encrypt will help a lot when it launches this summer. Going to close this for now; happy to have conversations about secure practices on the mailing list if you have proposals!

**Closed by tdsmith** 2015-02-10 22:11 UTC
