### ISSUE TITLE
Xcode 7.1 requires SDK 10.11 even when on OSX 10.10

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew#46362] opened 2015-11-25 18:06 UTC
I'm experiencing this issue on 10.10.5 after just updating to Xcode 7.1

```
CMake Error at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:3 (project)


CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Configuring incomplete, errors occurred!
```

Perhaps this is the problem:
If one is on 10.10 then they should have a 10.10 SDK installed. But Xcode 7.1 installs a 10.11 SDK. You can see that by invoking: 
```
🍎 Test:Desktop blah$ ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.11.sdk/
 ```

**Comment by DomT4** [comment] 2015-11-25 18:15
This is a known issue that Apple won't fix. You need to install the CLT package on 10.10 if you want to use the Xcode 7 releases.

**Comment by luzpaz** [comment] 2015-11-25 18:21
I installed CLT 7.1 I get the same error

**Comment by DomT4** [comment] 2015-11-25 18:21
What are you trying to compile and where from?

**Comment by luzpaz** [comment] 2015-11-25 18:24
I created a tap http://github.com/scribusproject/homebrew-scribus
that I've been using for some time now. When I upgraded to Xcode 7.1 I started getting this problem. 

```
$ brew tap scribusproject/homebrew-scribus
$ brew install --HEAD scribus --verbose
```

**Comment by UniqMartin** [comment] 2015-11-25 21:36
> If one is on 10.10 then they should have a 10.10 SDK installed. But Xcode 7.1 installs a 10.11 SDK.

I think this is a common misconception. It might have been like that in the past, but nowadays Apple recommends to always build against the most recent SDK. And if you have to target an older OS X (e.g., because that's what you are using), you are supposed to set the deployment target accordingly. Everything in the SDK (in theory at least) is properly tagged as to when something was introduced, so you should get the right compiler warnings/errors if you try to use something that was introduced in a newer OS X than you are targeting with your build.

That said, I'm not sure if the software you are trying to compile is misbehaving (haven't looked at the code in your tap) or if Homebrew is doing the wrong thing here. (Hope the information I provided helps you to get closer to the root cause of your issue.)

**Comment by luzpaz** [comment] 2015-11-30 20:59
Looks like passing  ```-DCMAKE_OSX_DEPLOYMENT_TARGET=#{MacOS.version}``` to Cmake fixed it

I get this output though:

CMake Warning at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake:97 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but the matching SDK does not exist
  at:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk"

  Instead using SDK:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk".
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
  CMakeLists.txt:42 (PROJECT)

**Comment by UniqMartin** [comment] 2015-11-30 21:36
It's only a warning, so you can simply ignore it. If it bothers you, the warning can be eliminated by explicitly setting both the deployment target and the sysroot (SDK). To implement the strategy apparently recommended by Apple, you would additionally pass `-DCMAKE_OSX_SYSROOT=/path/to/latest/sdk` to your CMake invocation where `/path/to/latest/sdk` is the output of `xcrun --show-sdk-path` (on a system with Xcode) or simply `/` (on a CLT-only system). At least that's what has been working fine for me with various CMake and Xcode releases for a non-Homebrew project.

**Comment by mistydemeo** [comment] 2015-11-30 22:20
I'll take a look at updating our build flags to fix this.

**Comment by luzpaz** [comment] 2015-12-02 13:41
Thanks @mistydemeo !

**Comment by mikemcquaid** [comment] 2015-12-04 15:02
Given what @UniqMartin has said I don't believe this is an actual issue but would definitely welcome a PR from @mistydemeo to make it nicer.

**Closed by mikemcquaid** 2015-12-04 15:02 UTC
