### ISSUE TITLE
Issue with zsh & iTerm2 & homebrew on 10.11 OS X

### ISSUE THREAD

**Issue by brianjking** [Homebrew/homebrew#44997] opened 2015-10-15 15:35 UTC
Whenever I open a new tab or window in iTerm 2 I'm seeing this notice:

```
Last login: Thu Oct 15 09:58:06 on ttys005
/Users/brianjking/.zshenv:1: command not found: brew
```
The contents are as follows:
```
cat /Users/brianjking/.zshenv
export PATH="$(brew --prefix)/bin:$PATH"
```

Any tips?

**Comment by bfontaine** [comment] 2015-10-15 15:40
Which OS X version do you have? Is `/usr/local/bin` in your `$PATH`?

**Comment by brianjking** [comment] 2015-10-15 15:52
@bfontaine 

```export PATH="$
/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brianjking/Library/Android/sdk"```

**Comment by bfontaine** [comment] 2015-10-15 21:56
@brianjking if Homebrew is installed in `/usr/local` (this is the default) you don’t have to `export PATH="$(brew --prefix)/bin:$PATH"` because `brew --prefix` *is* `/usr/local` and `/usr/local/bin` is already in your `PATH`.
I guess that for some reason `/usr/local/bin` is not in your `PATH` when you call `brew --prefix` because `brew` is in `/usr/local/bin`. Try adding `echo $PATH` just before the line where you call `brew --prefix` and see if `/usr/local/bin` is in it.

**Comment by cdl** [comment] 2015-10-15 22:20
@bfontaine Am also getting this issue. Below is the output of `echo $PATH` right before using `brew --prefix`.

`/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by apjanke** [comment] 2015-10-16 06:40
Dupe of robbyrussell/oh-my-zsh#4497.

Long story short: in El Capitan, the `path_helper` call, which adds `/usr/local/bin` to the `$PATH`, got [moved from `/etc/zshenv` to `/etc/zprofile`](http://www.zsh.org/mla/users/2015/msg00727.html), so `/usr/local/bin` is no longer on the path when `.zshenv` gets run. Move that code to `.zprofile` or `.zshrc`, or if you really have to, add something to `~/.zshenv` to add `/usr/local/bin` to the path before doing that call.

**Comment by apjanke** [comment] 2015-10-19 13:44
brianjking confirmed on the OMZ issue that moving the code to `~/.zshrc` fixed it. Does that work for you too, @cdl?

**Comment by cdl** [comment] 2015-10-19 15:31
@apjanke Yup, fixes the issue for me, but unfortunately one of my editor plugins [requires it in `~/.zshenv`](https://github.com/SublimeLinter/SublimeLinter-jshint#linter-installation). Will reach out and see if they can change this.

Thanks for the help!

**Comment by apjanke** [comment] 2015-10-19 16:21
Ah, I see. It makes sense that `.zshrc` wouldn't work for them, because that's for interactive shells. Tricky.

In your case, you could work around it by getting the `brew` location on the path before you attempt to call it. (Which ends up being a little redundant or chicken-and-egg, but it'd work.) (And I'm doing appending here to reduce the risk of messing with a path provided by a parent process.) So you could do this in your `.zshenv`

```
PATH=$PATH:/usr/local/bin
PATH="$PATH:$(brew --prefix)/bin"
```

To get it to work in the general case, you would also need to put `PATH="$(brew --prefix)/bin:$PATH"` in your `~/.zshrc`, because the `/etc/zshrc` `path_helper` call *resets* the path instead of adding to it. Since it already includes `/usr/local/bin`, you'd probably be fine without it unless you're running Homebrew from a nonstandard location. But it's something to be aware of.

Or you could [configure `paths` in Sublime Text](http://sublimelinter.readthedocs.org/en/latest/troubleshooting.html#adding-to-the-paths-setting).

**Comment by cdl** [comment] 2015-10-27 20:08
@apjanke Sorry for the late reply, just wanted to follow up and say thanks for the help! I tried originally configuring `paths` in Sublime Text as you suggested, but it ended up not really working correctly. So, the former tactic of modifying `.zshenv` to manually append `/usr/local/bin` and `$(brew --prefix)/bin` to my PATH worked.

Thanks again for the help!

**Closed** 2015-10-29 14:02 UTC
Labels: user configuration
