### ISSUE TITLE
MacVim fails to build (OS X 10.10.3)

### ISSUE THREAD

**Issue by dimitriye98** [Homebrew/homebrew#40206] opened 2015-05-30 05:21 UTC
[redundant error message removed by @tdsmith]

As far as I can tell, no-one has had the issue before.

**Comment by mistydemeo** [comment] 2015-05-30 05:36
Please provide the output of `brew gist-logs macvim`. Thanks!

**Comment by dimitriye98** [comment] 2015-05-30 22:12
https://gist.github.com/63490e178399c856fee2

**Comment by tdsmith** [comment] 2015-05-31 00:59
The problem is that `lm` is appearing in your link flags instead of `-lm`. Do you have any unusual versions of e.g. sed, awk, grep, etc installed or maybe environment variables that e.g. always colorize things?

**Comment by dimitriye98** [comment] 2015-05-31 08:43
Not that I know of. I mean, I colorize `ls` output, but that shouldn't affect it. My .bashprofile is these four lines:

```bash
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export EDITOR=nano
export HOMEBREW_GITHUB_API_TOKEN=d2569be4fe460628177dd8416086d008530bd5b3
```

**Comment by lieuwex** [comment] 2015-05-31 16:35
I have a slightly different error: https://gist.github.com/anonymous/023a419b88a0c619d1bd

**Comment by tdsmith** [comment] 2015-05-31 16:59
@lieuwex Did something happen to your system Python installation? Does `/System/Library/Frameworks/Python.framework/Versions/2.7/Python` exist?

**Comment by tdsmith** [comment] 2015-05-31 17:17
@dimitriye98 Can you add `-d` to your `brew install` command and then, after `configure` finishes and while `make` is running, hit ctrl+c, choose "shell" from the debug menu, and copy `src/auto/config.log` somewhere and then gist it?

**Comment by lieuwex** [comment] 2015-05-31 17:20
@tdsmith Thank you! Indeed `/System/Library/Frameworks/Python.framework/Versions/2.7/Python` did not exist, `/System/Library/Frameworks/Python.framework/Versions/{2.7,Current}` were pointing to  `/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7`, I manually changed it to  `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7` and it seems to be working now. I have python installed with `--override-system-python`. I guess this is out of scope for this issue, should I create a new issue for this problem?

**Comment by tdsmith** [comment] 2015-05-31 17:25
Glad it's working. --override-system-python no longer has an effect and we (strongly!) recommend leaving anything in /System intact. I don't think we'll make changes to Homebrew to support that configuration but I'd be happy to talk about ways to achieve what you need.

**Comment by tdsmith** [comment] 2015-05-31 17:26
-- though if you use the stable path in your symlinks through /usr/local/opt, e.g. `/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7`, your configuration will be a little less fragile.

**Comment by lieuwex** [comment] 2015-05-31 18:43
@tdsmith Thanks for the tip! Everything works so I don't really have anything that I need right now. I have no idea why it broke in the first place since I didn't touched the files manually beforehand.

**Comment by dimitriye98** [comment] 2015-05-31 20:48
Gisted config.log: https://gist.github.com/36b1a32014ee7663f0a1

**Comment by tdsmith** [comment] 2015-05-31 21:06
Well, `LIBS` is being mis-set by configure: https://gist.github.com/dimitriye98/36b1a32014ee7663f0a1#file-config-log-L8002

I have `LIBS='-lm  -lncurses -liconv -framework Cocoa'`; that extra dollar sign is causing trouble.

**Comment by tdsmith** [comment] 2015-05-31 21:10
What do you have for `/bin/sh --version`? I have 'GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)'; if you have something else I wonder if it's confusing configure.

**Comment by manuvo** [comment] 2015-06-09 15:38
I have same problem. What do i do ?

**Comment by tdsmith** [comment] 2015-06-09 16:32
Please be more specific about the problem you're having and provide supporting logs.

**Comment by manuvo** [comment] 2015-06-10 17:00
https://gist.github.com/0d435d75a8f99cd06f31 thanks!

**Comment by manuvo** [comment] 2015-06-10 17:02
brew install macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/Snapshot-76.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-76.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tc
==> make
          ^
1 error generated.
make[1]: *** [objects/if_python.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
macvim: disable ruby integration on 10.6 (https://github.com/Homebrew/homebrew/pull/40255)
MacVim fails to build (OS X 10.10.3) (https://github.com/Homebrew/homebrew/issues/40206)
macvim failed to build on 10.6.8 (https://github.com/Homebrew/homebrew/issues/38047)

**Comment by tdsmith** [comment] 2015-06-11 07:42
That problem is unrelated. You can probably work around it by including `/Library/Frameworks/Python.framework/Versions/2.7/bin` in your PATH instead of `/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS`; you need to make sure `python-config` matches `python`.

**Comment by periperipea** [comment] 2015-08-18 08:23
I logged a similar issue (the lm/-lm oddity) and was rirected to this thread.  tdsmith's comments had me check:

    LIBS='$-lm -lncurses -liconv -framework Cocoa'; 
and

    /bin/sh --version
    /bin/sh: 0: Illegal option --

Not what I expected!  In my case, the problem was that I installed dash, and linked sh to dash, rather than bash.  For the purpose of this build, I swapped it out for bash:

    $ sudo rm /bin/sh
    $ sudo ln -s /bin/bash /bin/sh
    $ ls -lh /bin/bash /bin/sh
    lrwxr-xr-x  1 root  wheel    19B Aug 18 16:19 /bin/bash -> /usr/local/bin/bash
    lrwxr-xr-x  1 root  wheel     9B Aug 18 16:18 /bin/sh -> /bin/bash

With this arrangement, it builds as expected:

    $ brew install vim
    ==> Downloading https://mirrors.kernel.org/debian/pool/main/v/vim/vim_7.4.712.orig.tar.gz
    Already downloaded: /Library/Caches/Homebrew/vim-7.4.712.tar.gz
    ==> ./configure --prefix=/usr/local --mandir=/usr/local/Cellar/vim/7.4.712_1/share/man --enable-
    multibyte --with-tlib=ncurses --enable-cscope --with-features=huge --with-compiledby=Homebrew 
    --enable-perlinterp --enable-pythoninterp --enable-rubyinterp --enable-gui=no --
    ==> make
    ==> make install prefix=/usr/local/Cellar/vim/7.4.712_1 STRIP=true
    🍺  /usr/local/Cellar/vim/7.4.712_1: 1606 files, 26M, built in 37 seconds

I hope this helps someone!

**Comment by wuzer** [comment] 2015-08-29 12:57
https://gist.github.com/7e6b9aa6d18237d0ee32  -----log

**Comment by plough** [comment] 2015-09-21 03:59
I've got this problem on my macbook: 
configure: error: cannot run C compiled programs.
https://gist.github.com/anonymous/36525791160f4964eae8 ------log

I can use gcc to compile 'hello world' C programs, and run it. So I guess there's nothing to do with gcc. Can you help me?

**Comment by DomT4** [comment] 2015-09-21 04:18
@plough As the `brew doctor` output hints, please install the Command Line Tools & try again.

**Comment by plough** [comment] 2015-09-21 05:00
@DomT4 It works. Thank you very much!

**Comment by xiaosworld** [comment] 2015-09-22 03:18
I've got a problem when I install the macvim with the command:
"brew install macvim --with-cscope --with-lua":
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/macvim20150922-17767-15kcb3q/macvim-snapshot-77/src':

configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

the log:  
https://gist.github.com/anonymous/51426834768daf60e1ed

I don't know what's wrong :-(

**Comment by DomT4** [comment] 2015-09-22 03:27
@xiaosworld Tim's the expert but I'd try removing `Canopy_64bit` from your `$PATH` temporarily. The `config` files there have the potential to cause trouble in fairly major ways during compile. You can also `sudo chown -R $(whoami):admin /usr/local` to fix the permission errors at the top of `brew doctor`.

**Comment by xiaosworld** [comment] 2015-09-22 04:56
@DomT4 It works! Thanks a lot!

**Comment by lehnerwhite** [comment] 2015-09-22 20:34
I have been trying different things to get my macvim installation to compile, but I haven't been able to find the trick. I checked the command line tools for Xcode and made sure i have gcc. Does anyone have any other ideas?

brew install macvim --with-cscope --with-lua --HEAD
==> Cloning https://github.com/macvim-dev/macvim.git
Updating /Library/Caches/Homebrew/macvim--git
==> Checking out branch master
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rub
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/macvim20150922-2682-grqm9k/src':
configure: error: C compiler cannot create executables

**Comment by lehnerwhite** [comment] 2015-09-22 20:34
https://gist.github.com/anonymous/393692ddf39c14fcbece

**Comment by DomT4** [comment] 2015-09-22 20:36
@lehnerwhite Remove `anaconda` from your `$PATH` temporarily.

**Comment by pank7** [comment] 2015-09-25 03:48
Hi kind guys, I have a similar problem here.

* `gist-logs`: https://gist.github.com/anonymous/eb6e6b143cc1df48b657
* I've gone through all the comments above.
* I'm pretty sure I have the command line tools installed.
* When I execute `xcode-select --install` it tells me the software I need is not in appstore.

Thanks in advance!

**Comment by shobhitg** [comment] 2015-11-06 19:57
https://gist.github.com/6298984d78d96e5f62f9

**Comment by shobhitg** [comment] 2015-11-06 20:01
Update: Removed `anaconda` from `$PATH`, and the install worked.

**Comment by ashishbhutani** [comment] 2015-11-18 10:07
Hi
I am facing the problem too in installing macvim.
Gist: https://gist.github.com/anonymous/167af4501eabe70976ed

**Comment by chdiza** [comment] 2015-11-18 18:24
@ashishbhutani You appear to be running Xcode 5 on El Capitan.  That's bound to be a problem.  El Cap requires Xcode 7. (You can see at the bottom of the gist that `brew doctor` tells you to install a newer Xcode).

**Closed** 2015-12-07 04:31 UTC
Labels: user configuration
