### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by idrinkyourcoffee** [Homebrew/homebrew#42595] opened 2015-08-07 06:38 UTC
An automated message from `brew update` requested that I file this bug report.  Here is the shell session in which the error occurred.

```ShellSession
$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
$ brew doctor
Your system is ready to brew.
$ brew update
Already up-to-date.
```
Thanks.  Homebrew is awesome!!!

**Comment by bfontaine** [comment] 2015-08-07 06:41
Closing as a duplicate of #42553, and thank you for the kind words :smile:

**Closed by bfontaine** 2015-08-07 06:41 UTC
