### ISSUE TITLE
idris failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42669] opened 2015-08-09 03:12 UTC
https://gist.github.com/927ade8ef2421dde5037

```
[38 of 98] Compiling Idris.Core.Binary ( src/Idris/Core/Binary.hs, dist/dist-sandbox-b7102fdd/build/Idris/Core/Binary.o )

src/Idris/Core/Binary.hs:309:10:
    Duplicate instance declarations:
      instance Binary T.Text
        -- Defined at src/Idris/Core/Binary.hs:309:10
      instance Binary T.Text -- Defined in ‘Data.Text’
Failed to install idris-0.9.18
cabal: Error: some packages failed to install:
idris-0.9.18 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by DomT4** [comment] 2015-08-09 03:18
@apjanke Our policy on stuff that's not "Help can't find OpenSSL on 10.11" or obviously caused by Homebrew is more or less "Should be reported upstream".

If you could report what you report here upstream as well and give us a bug report to keep an eye on it's likely to make everyone's lives easier than trying to keep tabs on an increasingly large amount of formula issues in the core. Thanks!

If only ~50 or so formulae are having issues on a pre-production system it could be a lot worse to be honest :smile_cat:.

**Comment by apjanke** [comment] 2015-08-09 03:58
I'm see if I can put together an upstream bug report for this and other build failures that aren't lib or Homebrew-specific.

50's not bad. Unfortunately the failure list I have is 226 long.

**Comment by apjanke** [comment] 2015-08-09 07:33
I'm sorry; I'm a little confused. For failing formulae that look like upstream problems on 10.11, do you want an upstream bug report *instead of* an individual formula failure report in the Homebrew repo, or *in addition to*?

**Comment by mikemcquaid** [comment] 2015-08-09 08:46
> I'm sorry; I'm a little confused. For failing formulae that look like upstream problems on 10.11, do you want an upstream bug report instead of an individual formula failure report in the Homebrew repo, or in addition to?

Instead, ideally, as well as commenting in the main #40837 tracking issue.

**Comment by mikemcquaid** [comment] 2015-08-09 08:46
Just to say: we do appreciate these it's just that the vast majority are upstream issues rather than Homebrew ones.

**Comment by DomT4** [comment] 2015-08-09 11:48
> 50's not bad. Unfortunately the failure list I have is 226 long.

Just FWIW, the core ships 3176 formula, so that's still ~7% failing, not all of which are 10.11 exclusive issues. I'm fairly relaxed about failure on a pre-production release at this point - If last year is anything to go by there's a good 60+ days yet before release.

Essentially the problem with these sorts of reports is that there's not much we alone can do. We're not in the position in terms of human-power & time to explore all the codebases involved and come up with fixes before upstream does. It's great to know what's failing and we appreciate the reports, but we can get fixes done and merged a lot quicker by notifying upstreams.

**Comment by apjanke** [comment] 2015-08-09 18:20
Gotcha.

I'll switch to just making new issues for things that look like problems in Homebrew code or formulae themselves, and tracking upstream build issues under that main tracking issue.

**Comment by DomT4** [comment] 2015-08-11 18:13
Moving to tracking in #40837.

**Closed by DomT4** 2015-08-11 18:13 UTC
Labels: 10.11
