### ISSUE TITLE
Error: Failure while executing: git stash pop --quiet

### ISSUE THREAD

**Issue by keevee09** [Homebrew/homebrew#42488] opened 2015-08-05 07:22 UTC
On running `brew update` I received the above error. I then ran `brew doctor` and received another error.
I include here the console output from the two commands:

`tony@Macintosh:~$ brew update`
`Stashing your changes:`
 `M Library/Formula/boost-python.rb`
 `M Library/Formula/boost.rb`
`?? Library/Formula/cantera.rb`
`?? Library/Formula/gromacs.rb`
`?? Library/Formula/openfst.rb`
`?? Library/Formula/opengrm-ngram.rb`
`?? Library/Formula/pdftoipe.rb`
`?? Library/Formula/sundials.rb`
`Error: Failure while executing: git stash pop --quiet`
`tony@Macintosh:~$ brew doctor`
`Please note that these warnings are just used to help the Homebrew maintainers`
`with debugging if you file an issue. If everything you use Homebrew for is`
`working fine: please don't worry and just ignore them. Thanks!`

`Warning: Unbrewed dylibs were found in /usr/local/lib.`
`If you didn't put them there on purpose they could cause problems when`
`building Homebrew formulae, and may need to be deleted.`

`Unexpected dylibs:`
`    /usr/local/lib/libaspell.15.1.4.dylib`
`    /usr/local/lib/libpspell.15.1.4.dylib`
`    /usr/local/lib/libtcl8.6.dylib`
`    /usr/local/lib/libtk8.6.dylib`

`Warning: Unbrewed header files were found in /usr/local/include.
`If you didn't put them there on purpose they could cause problems when
`building Homebrew formulae, and may need to be deleted.

`Unexpected header files:`
`    /usr/local/include/aspell.h`
`    /usr/local/include/fakemysql.h`
`    /usr/local/include/fakepq.h`
`    /usr/local/include/fakesql.h`
`    /usr/local/include/itcl.h`
`    /usr/local/include/itcl2TclOO.h`
`    /usr/local/include/itclDecls.h`
`    /usr/local/include/itclInt.h`
`    /usr/local/include/itclIntDecls.h`
`    /usr/local/include/itclMigrate2TclCore.h`
`    /usr/local/include/itclTclIntStubsFcn.h`
`    /usr/local/include/mysqlStubs.h`
`    /usr/local/include/odbcStubs.h`
`    /usr/local/include/pqStubs.h`
`    /usr/local/include/pspell/pspell.h`
`    /usr/local/include/tcl.h`
`    /usr/local/include/tclDecls.h`
`    /usr/local/include/tclOO.h`
`    /usr/local/include/tclOODecls.h`
`    /usr/local/include/tclPlatDecls.h`
`    /usr/local/include/tclThread.h`
`    /usr/local/include/tclTomMath.h`
`    /usr/local/include/tclTomMathDecls.h`
`    /usr/local/include/tdbc.h`
`    /usr/local/include/tdbcDecls.h`
`    /usr/local/include/tdbcInt.h`
`    /usr/local/include/tk.h`
`    /usr/local/include/tkDecls.h`
`    /usr/local/include/tkPlatDecls.h`

`Warning: Unbrewed .la files were found in /usr/local/lib.`
`If you didn't put them there on purpose they could cause problems when`
`building Homebrew formulae, and may need to be deleted.`

`Unexpected .la files:`
`    /usr/local/lib/libaspell.la`
`    /usr/local/lib/libpspell.la`

`Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.`
`If you didn't put them there on purpose they could cause problems when`
`building Homebrew formulae, and may need to be deleted.`

`Unexpected .pc files:`
`    /usr/local/lib/pkgconfig/opencv3.pc`
`    /usr/local/lib/pkgconfig/tcl.pc`
`    /usr/local/lib/pkgconfig/tk.pc`

`Warning: Unbrewed static libraries were found in /usr/local/lib.`
`If you didn't put them there on purpose they could cause problems when`
`building Homebrew formulae, and may need to be deleted.`

`Unexpected static libraries:`
`    /usr/local/lib/libtclstub8.6.a`
`    /usr/local/lib/libtkstub8.6.a`
`Error: /usr/local/Library/Formula/boost-python.rb:31: syntax error, unexpected <<, expecting keyword_end`
`<<<<<<< Updated upstream`
`  ^`
`/usr/local/Library/Formula/boost-python.rb:48: syntax error, unexpected ===, expecting keyword_end`
`=======`
`   ^`
`Please report this bug:`
`    https://git.io/brew-troubleshooting`
`/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'`
`/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'`
`/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'`
`/usr/local/Library/Homebrew/formulary.rb:69:in `klass'`
`/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'`
`/usr/local/Library/Homebrew/formulary.rb:174:in `factory'`
`/usr/local/Library/Homebrew/formulary.rb:190:in `from_rack'`
`/usr/local/Library/Homebrew/formula.rb:801:in `block in installed'`
`/usr/local/Library/Homebrew/formula.rb:799:in `map'`
`/usr/local/Library/Homebrew/formula.rb:799:in `installed'`
`/usr/local/Library/Homebrew/cmd/doctor.rb:1006:in `check_missing_deps'`
`/usr/local/Library/Homebrew/cmd/doctor.rb:1268:in `block in doctor'`
`/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `each'`
`/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `doctor'`
`/usr/local/Library/brew.rb:127:in `<main>'`
`tony@Macintosh:~$ `

**Comment by mikemcquaid** [comment] 2015-08-05 07:26
@keevee09 At some point you had modified `boost` and `boost-python`. If you wish to keep your changes you need to use Git to commit them after resolving the merge conflict. If you do not please run `git reset --hard origin/master`

**Comment by keevee09** [comment] 2015-08-05 07:40
@mikemcquaid thanks. Correct. I installed modified boost and boost-python a couple of weeks ago (earlier versions compatible with Caffe).

**Comment by mikemcquaid** [comment] 2015-08-05 07:48
That's the cause of your issues, I'm afraid.

**Comment by DomT4** [comment] 2015-08-08 06:06
Closing per Mike's comment. If you need earlier versions of formulae rather than editing local files I'd probably suggest either supporting them in your own tap or submitting them to Homebrew/versions.

**Closed by DomT4** 2015-08-08 06:06 UTC
Labels: user configuration
