### ISSUE TITLE
Installing executables to sbin is confusing if sbin isn't in PATH

### ISSUE THREAD

**Issue by wmbutler** [Homebrew/homebrew#38767] opened 2015-04-17 21:18 UTC
I know this has something to do with `sbin` and I've seen workarounds, but I think it would make a lot of sense for this script to be written properly so it works the first time. Is anybody interested in making the fix?

`brew install mtr`

**Comment by tdsmith** [comment] 2015-04-18 04:46
The formula is written properly but we can nag about configuration.

**Comment by tdsmith** [comment] 2015-04-18 05:25
Closing as duplicate of #37040.

**Closed by tdsmith** 2015-04-18 05:25 UTC
