### ISSUE TITLE
Phantomjs 2.0 fails to install on 10.11

### ISSUE THREAD

**Issue by enilsen16** [Homebrew/homebrew#42249] opened 2015-07-29 18:47 UTC
```
~ brew install phantomjs
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://github.com/ariya/phantomjs/archive/2.0.0.tar.gz
==> Downloading from https://codeload.github.com/ariya/phantomjs/tar.gz/2.0.0
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/mikemcquaid/db645f7cbeec4f3b1b2e/raw/e664ecc5c259344d5a73a84b52e472bf8ad3733e/phantomjs-yosemite.patch
######################################################################## 100.0%
==> Patching
patching file src/qt/qtbase/src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm
patch unexpectedly ends in middle of line
==> ./build.sh --confirm --jobs 8 --qt-config -openssl-linked
OpenSSL disabled.
OpenSSL support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /private/tmp/phantomjs20150729-52735-158fllc/phantomjs-2.0.0/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /private/tmp/phantomjs20150729-52735-158fllc/phantomjs-2.0.0/src/qt/qtbase/configure to continue.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
phantomjs: homepage fixed https://github.com/Homebrew/homebrew/pull/41623
Phantomjs fails to build on 10.6 https://github.com/Homebrew/homebrew/issues/38916
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by dunn** [comment] 2015-07-29 18:53
Could you post `brew gist-logs phantomjs`, please?

**Comment by enilsen16** [comment] 2015-07-29 19:00
Output from `brew gist-logs phantomjs`: https://gist.github.com/anonymous/10400b68b4d7ef15d104

**Comment by mikemcquaid** [comment] 2015-07-29 19:07
This will be the internal Qt failing to compile.

**Comment by enilsen16** [comment] 2015-07-29 19:11
So it's just an unfortunate error message? 

I'll try installing Qt with this patch - `https://github.com/thoughtbot/capybara-webkit/issues/815`

**Comment by mikemcquaid** [comment] 2015-08-01 13:39
@enilsen16 So, it's failing to find OpenSSL because we ask for it to be linked in but the actual fix will require upstream PhantomJS changes (and likely a new release).

**Comment by evadne** [comment] 2015-08-23 11:34
As a workaround, this seems to work: `npm install phantom phantomjs -g`

**Comment by flooie** [comment] 2015-08-25 17:56
@evadne your advice worked for me thanks

**Comment by nikz** [comment] 2015-09-02 17:08
@mikemcquaid is there anything we (I) can do to help out here? Sounds like this potentially requires moving parts from other projects, in which case I'll be patient :)

**Comment by mikemcquaid** [comment] 2015-09-02 17:13
@nikz If you can get it building locally and submit a PR once it's working that'd be :sparkles:

**Comment by nikz** [comment] 2015-09-02 17:19
@mikemcquaid at risk of being a bit cheeky (ok, a lot cheeky) could you point me to where you'd start?



I'm a total newb, tend to just bash at this stuff until it seems to work. But I'm keen to help! 








On Wednesday, 2 Sep 2015 at 18:13, Mike McQuaid <notifications@github.com>, wrote:

@nikz If you can get it building locally and submit a PR once it's working that'd be

**Comment by nikz** [comment] 2015-09-03 11:26
If you add the patch suggested by @enilsen16, then qt builds, but not the included qt for Phantom JS (I'm guessing).

I'll take a closer look at the recipe and see if I can't add that patch to the included qt.

**Comment by mikemcquaid** [comment] 2015-09-13 11:56
@Vitallium Any chance we'll see a new PhantomJS 2 release any time soon? Thanks!

**Comment by Vitallium** [comment] 2015-09-13 11:59
@mikemcquaid hi, yes. We're working on 2.0.1 release. Coming release will work on OS X smoothly. Unfortunately, we don't have any ETA on it (there are 2 blocking issues for this release).

**Comment by mikemcquaid** [comment] 2015-09-13 11:59
@Vitallium np, thanks, good to know!

**Comment by jcoyne** [comment] 2015-09-21 16:14
I'm getting the same error on osx 10.10.5
running this command: 
```
brew install phantomjs --HEAD
==> Cloning https://github.com/ariya/phantomjs.git
Cloning into '/Library/Caches/Homebrew/phantomjs--git'...
remote: Counting objects: 27176, done.
remote: Compressing objects: 100% (19331/19331), done.
remote: Total 27176 (delta 8130), reused 21349 (delta 7238), pack-reused 0
Receiving objects: 100% (27176/27176), 93.74 MiB | 431.00 KiB/s, done.
Resolving deltas: 100% (8130/8130), done.
Checking connectivity... done.
Checking out files: 100% (25492/25492), done.
==> Checking out branch master
==> ./build.sh --confirm --jobs 4 --qt-config -openssl-linked
OpenSSL disabled.
OpenSSL support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /private/tmp/phantomjs20150921-27100-r1jikw/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /private/tmp/phantomjs20150921-27100-r1jikw/src/qt/qtbase/configure to continue.

```

**Comment by DomT4** [comment] 2015-09-21 16:58
@jcoyne I presume you've upgraded to Xcode 7?

**Comment by jcoyne** [comment] 2015-09-21 18:33
@DomT4 yes
```
$ xcodebuild -version
Xcode 7.0
Build version 7A220
```

**Comment by DomT4** [comment] 2015-09-21 18:40
That's the issue. Phantom (Or rather the internal Qt) glues itself to `sysroot` to find things for compile. In this case, `sysroot` is likely to be blank because Xcode 7 did not ship the 10.10 SDK for an unknown reason, and it won't fallback on checking the contents of `/usr`.

You *could* try installing the Command Line Tools package, but I'm not sure it'll do the job in this situation given the `qt` build system.

**Comment by ywen** [comment] 2015-10-01 21:59
Can we do anything about it?

**Comment by maxnordlund** [comment] 2015-10-03 13:27
The tracking issue upstream is https://github.com/ariya/phantomjs/issues/12902 Not sure when it will be released though.

**Comment by lasg125** [comment] 2015-10-04 04:22
@evadne your advice works!

**Comment by zykadelic** [comment] 2015-10-12 11:56
@evadne +1 for npm workaround

**Comment by maxnordlund** [comment] 2015-10-12 12:17
@zykadelic @lasg125 and @evadne that doesn't solve the problem of compiling version 2.0 on El Capitan, since it reverts back to 1.9.8. I've to say -1 for that tip here (but very useful if you just want _something_)

**Comment by zykadelic** [comment] 2015-10-12 12:38
@maxnordlund It is indeed not a proper fix, but it helped me proceed

**Comment by vihuvac** [comment] 2015-10-17 01:50
I got a similar problem at installing ```phantomjs``` in Mac OS X El Capitan. I get the following error:
```
phantomjs: OS X Yosemite or older is required.
Error: An unsatisfied requirement failed this build.
```

I cannot even install older ```phatomjs``` versions.

**Comment by DomT4** [comment] 2015-10-18 17:12
> I cannot even install older phatomjs versions.

Older `phantomjs` versions are likely to have even more problems. Even if you work around the OpenSSL problem with Qt linkage, which is possible, you hit the problem that the 10.11 SDK removed several elements which Qt uses and will run into that half way through compile or so.

I'd be tempted to switch to the static binary supplied upstream for El Capitan until there's a compatible source build, but that dies at run for me :cry::

```
[1]    34971 killed     /Users/xyz/Downloads/phantomjs-2.0.0-macosx/bin/phantomjs
```

**Comment by vihuvac** [comment] 2015-10-18 19:03
I got install it via ```nam```:

```npm install -g phantomjs ```

My current version installed is:

```
phantomjs -v

1.9.8
```

I hope it helps!

**Comment by route** [comment] 2015-10-27 09:09
@vihuvac same for me for any version:
```
brew install phantomjs
phantomjs: OS X Yosemite or older is required.
Error: An unsatisfied requirement failed this build.
```

**Comment by Vitallium** [comment] 2015-10-27 09:12
Hey guys, I pushed 2.0.1 preview version with El Capitan support - https://github.com/Vitallium/phantomjs/releases/tag/2.0.1
We solved issues with OpenSSL with new XCode 7 and UPX.

**Comment by route** [comment] 2015-10-27 09:16
@Vitallium Wow thanks for information! I also would like to try it with latest capybara/poltergeist.

**Comment by rrooding** [comment] 2015-10-27 09:47
Cool, works right for me!

**Comment by 907th** [comment] 2015-10-27 11:43
@Vitallium Good news! How soon 2.0.1 will be released?

**Comment by GeoffreyBooth** [comment] 2015-10-27 18:33
@Vitallium and others, is there a way to install one of the binaries from https://github.com/Vitallium/phantomjs/releases/tag/2.0.1 via Homebrew?

**Comment by ywen** [comment] 2015-10-27 18:52
@GeoffreyBooth Well since this is a temporary solution, and all you have to do is to copy one single phantoms file to `/usr/local/bin`. Homebrew does't really help that much here

**Comment by mikemcquaid** [comment] 2015-10-27 21:41
@Vitallium Any chance to push that tag on the main repo? If so I'm happy to build a release.

**Comment by praveenperera** [comment] 2015-10-30 08:01
@Vitallium your fork works great, thanks!

**Comment by Vitallium** [comment] 2015-10-30 08:02
@mikemcquaid I could try, but I can't guarantee. We publish official releases only there.

**Comment by mikemcquaid** [comment] 2015-10-30 21:19
> @mikemcquaid I could try, but I can't guarantee. We publish official releases only there.
> @praveenperera it's not a fork. Treat it as an official preview version.

@Vitallium can you clarify your current position in PhantomJS? Are you the maintainer and person who will be creating new releases or a contributor to a project that relies on Ariya to commit your work? I just ask so we can decide how to move forward with this for Homebrew. Thanks!

**Comment by jeffwesson** [comment] 2015-11-05 23:19
@evadne +1 for the workaround, thanks!

**Comment by iilei** [comment] 2015-11-06 19:39
Thanks @Vitallium

**Comment by route** [comment] 2015-11-07 11:59
@Vitallium works for me but shows 2.0.0 though and I tried to run poltergeist test suit and it still shows issues for attachments which is regression introduced in PhantomJS 2.0 right? Is that going to be fixed in 2.0.1 or no?

**Comment by Vitallium** [comment] 2015-11-07 16:47
@mikemcquaid well, it's hard to say. Some of our core contributors are not active atm. So I have to be more initiative in the project. Usually Ariya (@ariya) creates all releases and their notes. I just do builds.
@route yes, fix for `uploadFile` is not included yet, but definitely will be in 2.0.1 release.

**Comment by mikemcquaid** [comment] 2015-11-07 19:54
> @mikemcquaid well, it's hard to say. Some of our core contributors are not active atm. So I have to be more initiative in the project. Usually Ariya (@ariya) creates all releases and their notes. I just do builds.

Ok, cool, thanks. I think we'll wait for an "official" release then (which, between us, I think you should be permitted to make).

**Comment by GeoffreyBooth** [comment] 2015-11-08 22:22
@Vitallium is there a pull request for the `uploadFile` fix? Is there some way for me to make an El Capitan build of PhantomJS with the `uploadFile` fix?

Or is 2.0.1 coming soon? It's been [promised since January](https://github.com/ariya/phantomjs/issues/12902), I'm starting to lose hope.

**Comment by lifecoderua** [comment] 2015-11-10 18:14
@evadne +1 for the solution, thank you.
Binary from official site is broken at the moment.

**Comment by saintmac** [comment] 2015-11-10 19:49
@Vitallium thanks for the build! I couldn't get 1.9.8 or 2.0.0 to work on El Capitan but your build works great so far

**Comment by route** [comment] 2015-11-11 08:38
@saintmac 1.9.8 works good btw, you can just download it from https://bitbucket.org/ariya/phantomjs/downloads

**Comment by route** [comment] 2015-11-11 08:39
@mikemcquaid may be we can allow at least 1.9.8 for homebrew? since it works good

**Comment by mikemcquaid** [comment] 2015-11-11 09:17
> @mikemcquaid may be we can allow at least 1.9.8 for homebrew? since it works good

We already do. It doesn't compile from source on El Capitan.

**Comment by XerxesNoble** [comment] 2015-11-14 19:57
@evadne +1

**Comment by imedvedko** [comment] 2015-11-26 18:15
@Vitallium, can you send a patch for 2.0.0 with fix? It can be added to the build script.

**Comment by route** [comment] 2015-11-26 18:23
I think you guys can lock issue since nothing anyone can do except waiting :)

**Comment by agoldis** [comment] 2015-12-01 12:49
Thanks @Vitallium! 
https://github.com/Vitallium/phantomjs/releases/tag/2.0.1 works smoothly on El Capitan

**Comment by mikemcquaid** [comment] 2015-12-03 11:12
I've asked if upstream can release @Vitallium's version: https://github.com/ariya/phantomjs/issues/13783

**Comment by michelegera** [comment] 2015-12-03 11:14
Thanks @mikemcquaid!

**Comment by SimonChong** [comment] 2015-12-15 12:36
When I install the 2.0.1 tag and I run PhantomJS in El Capitan I get:

dyld: Library not loaded … Reason: Image not loaded

Any ideas how I could fix it?

**Comment by mikemcquaid** [comment] 2015-12-18 15:21
@SimonChong That's not a Homebrew issue.

**Comment by alan707** [comment] 2016-01-02 04:13
@evadne +1

**Comment by tofagerl** [comment] 2016-01-04 08:12
How do I install the 2.0.1 version? I tried using NPM syntax, i.e. brew install phantomjs@2.0.1, but that was no go.

**Comment by kfix** [comment] 2016-01-08 00:01
2.0.1 will never be released, the target for 10.11 support is PhantomJS 2.1: ariya/phantomjs#12970

**Comment by mikemcquaid** [comment] 2016-01-08 08:11
@kfix I think I may just ship 2.0.1 as-is.

**Comment by mikemcquaid** [comment] 2016-01-09 11:12
I tried, failed: https://github.com/Homebrew/homebrew/pull/47835. Anyone else: feel free to pick that up and we'll consider merging 2.0.1.

**Comment by geoffwalmsley** [comment] 2016-01-10 00:25
Install fails:

brew install phantomjs

phantomjs: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.


C'mon guys - this is pretty basic stuff

**Comment by jcoyne** [comment] 2016-01-10 01:57
@geoffwalmsley that's rude and not helpful

**Comment by geoffwalmsley** [comment] 2016-01-10 02:15
@jcoyne is there an expectation that brew will not keep pace with major os releases as the error I posted seems to suggest?

**Comment by jcoyne** [comment] 2016-01-10 02:39
@geoffwalmsley Sorry, I'm not a maintainer, I don't know the answer to that. I was just here to report the error I saw.

**Comment by dunn** [comment] 2016-01-10 02:56
May be a good time to remind everyone of our code of conduct: https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md

> is there an expectation that brew will not keep pace with major os releases as the error I posted seems to suggest?

As the error message says, PhantomJS 2.0 doesn't build on El Capitan due to an _upstream_ incompatibility.  It's not because we're dragging our feet on supporting 10.11, and it's why we're looking for ways to release 2.0.1 as soon as possible: https://github.com/Homebrew/homebrew/issues/42249#issuecomment-170226164

**Comment by DomT4** [comment] 2016-01-10 05:00
I can't write that error message to be any *more* obvious; It's an *upstream* issue, not a Homebrew one. We can't magically wave a wand here and "make it work". As we've said, someone can feel free to pick up on where Mike's PR was left and we'll review it.

Can we please keep this Issue on point. If you have solutions we more than welcome them.

**Comment by mikemcquaid** [comment] 2016-01-10 12:20
@geoffwalmsley Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Closed** 2016-01-10 12:24 UTC
Labels: 10.11, upstream issue

**Comment by dunn** [comment] 2016-01-10 16:34
2.0.1 is now available through Homebrew, thank you all for your patience!

**Comment by nikz** [comment] 2016-01-10 16:48
Yay! Thanks everyone! :smile:

**Comment by brunowego** [comment] 2016-01-11 12:28
:+1:

**Comment by bmishkin** [comment] 2016-01-11 16:00
:+1:  working great, thanks team

**Comment by erictheise** [comment] 2016-01-14 19:01
I'm seeing
```
$ phantomjs --version
2.0.0
```
after installing 2.0.1. Thanks everyone for your work on this.

**Comment by dunn** [comment] 2016-01-14 19:06
@erictheise that's just the version-strings not being updated in the fork we're temporarily using: https://github.com/Vitallium/phantomjs/blob/master/src/consts.h#L35-L38

**Comment by zvilich** [comment] 2016-01-19 10:58
when i do:
brew install phantomjs
I still receive :
phantomjs: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

OS version 10.11.2

**Comment by DomT4** [comment] 2016-01-19 10:59
@zvilich I suspect you need to `brew update`.

**Comment by zvilich** [comment] 2016-01-19 11:04
:+1: working great, thanks DomT4

**Comment by EFF** [comment] 2016-01-21 16:46
YES well done on this one guys !

**Comment by mneumark** [comment] 2016-01-25 15:06
Just letting everyone know that phantomjs 2.1 was officially released last night! So just doing a normal update/upgrade will fix this problem officially.

**Comment by AnalyzePlatypus** [comment] 2016-04-10 08:36
**brew install phantomjs** works flawlessly now. No problems on El Capitan 10.11.4
