### ISSUE TITLE
irssi seems to be broken

### ISSUE THREAD

**Issue by scbunn** [Homebrew/homebrew#37601] opened 2015-03-11 16:30 UTC
something doesn't seem right here.

```bash
$ brew install irssi
==> Downloading https://homebrew.bintray.com/bottles/irssi-0.8.17_2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/irssi-0.8.17_2.yosemite.bottle.tar.gz
==> Pouring irssi-0.8.17_2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/irssi/0.8.17_2: 278 files, 4.3M
$ irssi
$ which irssi
/usr/local/bin/irssi
$ /usr/local/Cellar/
cd /usr/local/Cellar/
$ ls
bash/       cscope/     gdbm/       git/        htop-osx/   kdiff3/     libffi/     macvim/     mysql/      parallel/   pkg-config/ python3/    readline/   sqlite/     tree/       watch/      xz/         zsh/
brew-cask/  emacs/      gettext/    glib/       irssi/      libevent/   libyaml/    mercurial/  openssl/    pcre/       python/     qt/         saltstack/  tmux/       vim/        wget/       zeromq/
$ cd irssi/
$ ls
0.8.17_2/
$ cd 0.8.17_2/
$ ls
AUTHORS               ChangeLog             NEWS                  TODO                  include/              share/
COPYING               INSTALL_RECEIPT.json  README.md             bin/                  lib/
$ cd bin
$ ls
botti* irssi*
$ ./irssi
$
```

**Comment by DomT4** [comment] 2015-03-11 19:40
Are you saying Irssi doesn't launch for you?

No problems here with the same bottle. Can you provide a ` brew doctor ` and ` brew config ` to see if they have any useful hints?

**Comment by scbunn** [comment] 2015-03-11 19:46
Yes.  Sorry if that wasn't clear.  When I try and launch irssi nothing happens.

brew doctor
```bash
user@host (exit:0 |lwp:236) (~)
[22500][~]$ brew doctor
Your system is ready to brew.
```

brew config
```bash 
user@host (exit:0 |lwp:236) (~)
[22501][~]$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 29a67cdedf95a8c83a39ee4cb8a420503c46b5ff
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.2-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_11
user@host (exit:0 |lwp:236) (~)
[22502][~]$```

**Comment by DomT4** [comment] 2015-03-11 20:15
No worries, just wanted to confirm.

Config and Doctor both look fine. Can you try ` brew remove glib openssl irssi && brew install irssi ` please? The ` brew install irssi ` will automatically pull in the ` glib ` and ` openssl ` bottles for you. Just wondering if one of the deps has wandered off or something.

**Comment by scbunn** [comment] 2015-03-11 21:37
Sure, I can do that.  I actually blew away homebrew altogether today and still have the same issue, but here is the results of removing irssi, glib, and openssl and trying to install again.

```bash
user@host (exit:0 |lwp:231) (~)
[22516][~]$ brew remove glib openssl irssi
Uninstalling /usr/local/Cellar/glib/2.42.2...
Uninstalling /usr/local/Cellar/openssl/1.0.2...
Uninstalling /usr/local/Cellar/irssi/0.8.17_2...
user@host (exit:0 |lwp:231) (~)
[22517][~]$ brew install irssi
==> Installing dependencies for irssi: glib, openssl
==> Installing irssi dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.42.2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/glib-2.42.2.yosemite.bottle.tar.gz
==> Pouring glib-2.42.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.42.2: 410 files,  17M
==> Installing irssi dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2.yosemite.bottle.tar.gz
==> Pouring openssl-1.0.2.yosemite.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2: 459 files,  18M
==> Installing irssi
==> Downloading https://homebrew.bintray.com/bottles/irssi-0.8.17_2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/irssi-0.8.17_2.yosemite.bottle.tar.gz
==> Pouring irssi-0.8.17_2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/irssi/0.8.17_2: 278 files, 4.3M
user@host (exit:0 |lwp:231) (~)
[22518][~]$ irssi
user@host (exit:0 |lwp:231) (~)
[22519][~]$
```

**Comment by DomT4** [comment] 2015-03-11 21:46
Very odd. Can you try ` brew remove irssi && brew install irssi --build-from-source ` to see if the from-source build produces the same failure-to-launch on your machine?

**Comment by scbunn** [comment] 2015-03-11 21:55
Liftoff, building from source works.  Not sure why the pre-package binary does not.

**Comment by DomT4** [comment] 2015-03-11 21:56
Ah. @mikemcquaid Worth generating new bottles here maybe?

**Comment by scbunn** [comment] 2015-03-11 22:10
not sure if its related or not, but the build form source version doesn't seem to have /script functionality.

**Comment by tdsmith** [comment] 2015-03-12 00:31
Do you have any files in `~/.irssi/`?

**Comment by scbunn** [comment] 2015-03-12 00:45
Hit @tdsmith I do have a setup in .irssi; however, I have tried removing this directory (and my settings there) and it had no affect (either in the pre-compiled binary not running or /script not being a command).

BTW, Thanks @DomT4 for showing me how to force brew to install from source, I was wondering how to do that.

**Comment by DomT4** [comment] 2015-03-12 00:46
> for showing me how to force brew to install from source, I was wondering how to do that.

No worries! ` -fs ` should work as well, if you don't want to type out the whole ` --build-from-source `.

**Comment by mikemcquaid** [comment] 2015-03-12 10:19
Pushed a new bottle in e8b792e674e5e740677640b1452fa42bee394ecd in case that helps.

**Comment by scbunn** [comment] 2015-03-12 16:53
@mikemcquaid thanks for the new bottle; unfortunately, it also does not work (launching irssi results in nothing).  

When I try and build from source I can see that perl is not included in the modules which is the reason that /script doesn't exist.  I suspect I have issues with perl on my system (because I also have issues running parallel from homebrew because of perl permissions) but I'm not even sure where to start to determine if anything is wrong with perl.

**Comment by DomT4** [comment] 2015-03-12 20:07
Default compile instructs for ` configure ` include: ` --with-perl=yes --with-perl-lib=/usr/local/Cellar/irssi/0.8.17_2/lib/perl5/site_perl `, so they should be being linked.

An ` otool -L $(brew --prefix irssi)/bin/* | grep perl ` should reveal:

```
	/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib (compatibility version 5.18.0, current version 5.18.2)
	/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib (compatibility version 5.18.0, current version 5.18.2)
```

Do you see either of those things in either the bottle build or the ` -fs ` build on your machine?

**Comment by tomnewton** [comment] 2015-04-29 18:26
When I try to install irssi on Yeosemite I get: 
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied - /usr/local/lib/perl5/site_perl/darwin-thread-multi-2level
Error: Permission denied - /usr/local/lib/perl5/site_perl/darwin-thread-multi-2level

**Comment by DomT4** [comment] 2015-04-29 22:21
> Permission denied - /usr/local/lib/perl5/site_perl/darwin-thread-multi-2level

Usually fixed by ``` sudo chown -R `whoami` /usr/local ```

**Comment by tomnewton** [comment] 2015-04-30 10:01
Thanks @DomT4

**Comment by jacknagel** [comment] 2015-05-09 03:54
Are there any action items here, or can this be closed?

**Comment by DomT4** [comment] 2015-05-09 20:28
As far as I can tell, this is a `user configuration` error. I can't reproduce the problem, despite trying on a couple of different machines, and nobody else has reported the issue.

Suspect OP has/had some problems with the Perl setup on their system for whatever reason, but there's not much we can do about that sadly beside advising OP to reinstall OS X or something similar.

**Closed** 2015-05-09 21:39 UTC

**Comment by jonasbn** [comment] 2015-05-12 06:53
I am sorry I did not speak up earlier, I experienced this issue too, but settled for monitoring the bug and the proposed fix of changing permissions worked for me. Anyway the conclusion by @DomT4 is probably correct, but IMHO the issue might resurface, since the permissions on the Perl libraries are not under the control of the irssi installation.

**Comment by solocshaw** [comment] 2015-07-26 13:18
I have an issue similar to @tomnewton's. When trying to run irssi i get:

    dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gettext/lib/libintl.8.dylib
      Referenced from: /usr/local/bin/irssi
      Reason: no suitable image found.  Did find:
	    /usr/local/lib/libintl.8.dylib: mach-o, but wrong architecture
    Trace/BPT trap: 5

**Comment by dunn** [comment] 2015-07-26 14:54
@solocshaw that's a slightly different issue, but `brew reinstall irssi` should fix it.
