### ISSUE TITLE
OpenSSL linking issues due to removal of keg_only status

### ISSUE THREAD

**Issue by reaperhulk** [Homebrew/homebrew#41613] opened 2015-07-12 00:05 UTC
The homebrew OpenSSL recipe is no longer keg only (as of https://github.com/Homebrew/homebrew/commit/9ca3c054c070cc825870a6fc0fc5c5a22f7d8559#diff-5f8300a99f5c14b861dfa8eff2905a16) due to El Capitan no longer shipping headers.

Unfortunately, this leads to some major problems with projects (outside homebrew) that attempt to compile against OpenSSL without having the homebrew prefix added. Specifically, a project that links against OpenSSL and uses clang will see the homebrew OpenSSL headers due to the clang search path order:
```
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
```

However, when it links the clang library search path order is:
```
Library search paths:
	/usr/lib
	/usr/local/lib
Framework search paths:
	/Library/Frameworks/
	/System/Library/Frameworks/
```

So the binary compiles using the headers for 1.0.2d but links against 0.9.8. This problem typically manifests as a Symbol Not Found error at runtime.

This problem can be worked around by passing the appropriate LDFLAGS or CFLAGS but appears to represent a significant regression from the previous behavior. Is there any better workaround or is this expected?

**Comment by DomT4** [comment] 2015-07-12 00:19
Clang will add the headers from `/usr/local/include` but prioritises the libs in `/usr/lib` regardless of `$PATH` priority? :eyes:.

I presume you've found this issue outside of Python as well?

**Comment by reaperhulk** [comment] 2015-07-12 00:21
@DomT4 yeah you can replicate that info on your own Mac to make sure I'm not crazy. Run `clang -Xlinker -v /dev/null` to see the linker paths and `clang -x c -v -E /dev/null` to see the include paths.

**Comment by reaperhulk** [comment] 2015-07-12 00:44
@DomT4 it's possible I slightly misunderstood your question. I added `/usr/local` to the front of `$PATH` and that does indeed cause it to search `/usr/local/lib` first.

**Comment by DomT4** [comment] 2015-07-12 00:48
It's fairly amazing this is intended behaviour; deliberately mixing `/usr/local/include` with `/usr/lib` is asking for chaos whenever the same thing exists in both locations.

Confirmed though. We'll need to look into this to see if it permanently reproduces in every situation, and if there's any mitigation routes available that aren't extremely drastic.

CC @Homebrew/owners

**Comment by tdsmith** [comment] 2015-07-12 01:55
I also hadn't appreciated that the include and linker search paths were different.

Since it will be necessary to add linker flags for developers to use Homebrew's openssl correctly (even on El Capitan!) I think it makes sense to re-keg openssl.

**Comment by tdsmith** [comment] 2015-07-12 02:27
The main obstacle to making openssl keg-only again is that the install_name of libssl.dylib became `/usr/local/lib/libssl.dylib` when we made it a normal formula. That means that anything built (bottled by us, or built from source by users) against openssl in the last couple of days will break unless it is rebuilt against an openssl with a kegged install_name. For safety, that means revisioning everything with an openssl dependency, which is a big undertaking.

**Comment by DomT4** [comment] 2015-07-12 03:40
> For safety, that means revisioning everything with an openssl dependency, which is a big undertaking.

I think we're probably fine to handle this on a case-by-case basis initially, unless we get pounded with issues. The stuff we merged in the last couple days can get revisions, but beyond that given it's the weekend the impact may be fairly low.

**Comment by mikemcquaid** [comment] 2015-07-12 06:59
@reaperhulk What version of OS X are you on?

**Comment by reaperhulk** [comment] 2015-07-12 14:05
@mikemcquaid I'm on 10.10.4 running the latest (non-beta) Xcode CLI tools

**Comment by DomT4** [comment] 2015-07-13 19:56
Closed via https://github.com/Homebrew/homebrew/commit/2e191b19b8eccfbc031c224892bda140b1b38e7b.

**Closed by DomT4** 2015-07-13 19:56 UTC
