### ISSUE TITLE
Homebrew Truck Factor

### ISSUE THREAD

**Issue by gavelino** [Homebrew/homebrew#43038] opened 2015-08-17 19:01 UTC
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Homebrew** and obtained a value of **2**.  For this value we did not consider the files in **Library/Formula** folder. 

The developers responsible for this TF are:

Jack Nagel - author of 72% of the files
Max Howell - author of 18% of the files

To validate our results, we would like to ask **Homebrew** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Homebrew**?

(b) Do you agree that **Homebrew** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Homebrew** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by bfontaine** [comment] 2015-08-17 22:00
Interestingly both these developers have already left the project and we’re still here :smile:

**Comment by scpeters** [comment] 2015-08-17 22:49
I don't know how you define authorship, but over 300 people have committed to files in the `Libray/Homebrew` folder, and 20 people have 10 commits or more.

~~~
git log /usr/local/Library/Homebrew | grep ^Author | sort | uniq -c | sort
git log /usr/local/Library/Homebrew | grep ^Author | sort | uniq -c | sort | wc -l
~~~

Homebrew has a very large community. Maybe your analysis is missing some of these contributors and maintainers?

**Comment by bfontaine** [comment] 2015-08-17 22:52
@scpeters Please read the preprint: https://peerj.com/preprints/1233/

**Comment by scpeters** [comment] 2015-08-17 23:01
From the preprint: "Basically, the weights of each variable assume that FA (file authorship) is by far the strongest predictor of file authorship." So basically people who created files in a repository are the only people counted by this metric.

That's probably why they excluded the `Library/Formula` folder, since lots of people created files there.

I just don't think `File Creator` is sufficient as a single metric. Why not look at the number of maintainers who are allowed to merge pull requests?

**Comment by DomT4** [comment] 2015-08-17 23:33
Thanks for this issue! We were discussing Homebrew's truck/bus/etc factor the other week, which I think was actually triggered by your work here. It's interesting trying to work out a project like Homebrew's truck factor as as you point out the "core" logic that drives everything is a different "area" of contribution than the formulae themselves, but neither would function as intended without the other.

> (a) Do you agree that the listed developers are the main developers of Homebrew?
> (b) Do you agree that Homebrew will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

They aren't. Max's last commit was almost two years ago now and he has largely stepped away from Homebrew entirely; the codebase has changed very significantly in the period since. Not to take anything away from Max of course, we wouldn't be having this discussion without him, but he's no longer actively involved.

Jack departed the development team last month. You can't walk far in Homebrew without finding significant chunks of Jack's work as you note with the TF and he was a massive contributor, particularly to core code. As huge as Jack's participation was though, Homebrew hasn't fallen apart in the month and a bit he's been gone and it won't going forwards.

My thoughts on the dev team is that whilst we all have our niches and those niches could suffer temporarily if that developer departed, the project would be fine. As a team we actively work on ensuring nobody is indispensable and everyone can cover the whole spectrum of work in maintaining Homebrew.

Personally, If I won the lottery and never had to worry about making ends meet or being comfortable in life I'd sit around contributing to FOSS projects from my own little island somewhere surrounded by loved ones & a few thousand dogs.

> c) Does Homebrew have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

There is some documentation on being a Homebrew maintainer and plans to improve that are in the pipeline, but I think one of our strengths is that we have a very active team chat where we can reach each other throughout the day and discuss issues that come up.

It allows us to keep everyone in the loop about changes and means we don't leave developers behind too much wondering what's going on and why x fixes y and z, etc. The team chat has proved to be an extremely valuable asset. It's difficult to document everything to do with a project of this size, so in many ways a more dynamic learning environment is more relevant day-to-day.

**Comment by tdsmith** [comment] 2015-08-18 01:54
Well, here's my perspective, speaking only for myself; I've been a maintainer for about a year (I joined after Max had left).

(a) Do you agree that the listed developers are the main developers of Homebrew?

I agree that Max and Jack made many essential contributions to Homebrew's core and deserve credit for them. I would guess that Jack understands Homebrew's core better than anyone else does.

(b) Do you agree that Homebrew will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

Not necessarily in trouble, no. Jack's resignation means that some of our architectural problems will not be resolved in the short-to-medium term, which is a loss, but I don't think it's challenged the viability of the project.

(c) Does Homebrew have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

I think the viability of the project depends on the velocity of pull requests to add and update formulas more than it depends on the number of developers working on the core code, which deserves improvements but more or less works. We have a handful of other maintainers and a large body of contributors who are interested in Homebrew's future and I think that community energy and the solid foundation to which Jack and Max contributed will sustain the project despite the loss of their effort and expertise.

**Comment by bfontaine** [comment] 2015-08-18 07:51
Here is my personal point of view. Note that I’ve been a maintainer for only a few months but I contributed to Homebrew before.

> (a) Do you agree that the listed developers are the main developers of Homebrew?

They once were, but Max left two years ago and Jack did it one month ago. Max created the project and thus created a lot of files, but since his departure a lot of things have changed in the code base. Jack was the main core contributor when he was here IMO. We lost a great expertise but the project is not doomed in any way.

> (b) Do you agree that Homebrew will be in trouble if the listed developers leave the project

No, as you can see.

> (e.g., if they win in the lottery, to be less morbid)

Like @DomT4, I too would probably contribute a lot more to Homebrew and OSS projects if I won the lottery. I’d love to be able to work on Homebrew full-time. :smile: 

> (c) Does Homebrew have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Documentation is something we’ve thought a lot about recently; but more for new contributors than existing maintainers. We share a lot of knowledge inside the team and always ensure we don’t have SPOFs, i.e. one part of the Homebrew project that would die if one of us were hit by a truck.

**Comment by mikemcquaid** [comment] 2015-08-18 10:09
> (a) Do you agree that the listed developers are the main developers of Homebrew?

I don't think Max has been for a while (as mentioned previously).
 
> (b) Do you agree that Homebrew will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

Jack left recently but the majority of his changes were reviewed such that I don't think it's crippling to the project that he has left. Both Jack and Max's contributions tailed off before they left so we already had picked up some of the slack of running the project. 

> (c) Does Homebrew have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

We don't have detailed documentation but we have a large user base of skilled, regular contributors.

**Comment by DomT4** [comment] 2015-08-25 17:21
Going to close this one out. Seems like everyone who wanted to comment has done so. If there's anything you want to follow-up on @gavelino we're very happy to continue the conversation, I hope the responses here are useful to you.

**Closed by DomT4** 2015-08-25 17:21 UTC

**Comment by gavelino** [comment] 2015-08-25 17:25
Ok @DomT4,

thank everyone. I really appreciate the answers.
