### ISSUE TITLE
Warnings from git when using `brew log foo`

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew#48251] opened 2016-01-19 14:47 UTC
$ brew log lua
    Warning: The git repository is a shallow clone therefore the filtering may be incorrect.
    Use `git fetch --unshallow` to get the full repository.

`brew log` itself still works, but I wonder if it would make sense to squelch this error–rather than let `git` suggest to users that they pull down the full repository.

**Comment by bfontaine** [comment] 2016-01-19 15:27
This warning comes from us; not from `git`. The issue is that if you have a shallow repository the log might not be complete.

**Comment by telemachus** [comment] 2016-01-19 16:34
> This warning comes from us; not from `git`.

@bfontaine Oh. Then I'm even more confused. As far as I know, I never asked for a shallow repo. I just run `brew up`. Is it normal or not normal to have a shallow repository if using `brew` normally? The error message could probably be clearer, in any case.

**Comment by bfontaine** [comment] 2016-01-19 16:58
I agree we should make this clearer. When you tap a repository it does a shallow clone by default.

**Comment by telemachus** [comment] 2016-01-19 17:25
@bfontaine So does that mean that by default the `brew log` command is liable to error? Not a huge deal if so. I just want to make sure that I'm following what the warning is trying to tell me.

**Comment by bfontaine** [comment] 2016-01-19 21:56
@telemachus Yep. Well technically that’s not an error but more something that you should be aware of.

**Comment by DomT4** [comment] 2016-02-13 03:08
Closing here, but open to documentation improvements on our defaulting to shallow clones for taps.

**Closed by DomT4** 2016-02-13 03:08 UTC
