### ISSUE TITLE
no memcached support in most recent MySQL brew port

### ISSUE THREAD

**Issue by GETandSELECT** [Homebrew/homebrew#42935] opened 2015-08-14 12:00 UTC
see http://stackoverflow.com/questions/31407630/os-x-and-brew-install-innodb-mysql-memcached-plugin-for-nosql

innodb_memcached_config.sql not available https://dev.mysql.com/doc/refman/5.6/en/innodb-memcached-internals.html

**Comment by mikemcquaid** [comment] 2015-08-14 20:33
Can you provide more details about this and what you're expecting?

**Comment by jeffjohnson9046** [comment] 2015-09-09 18:47
I ran into this same issue yesterday:

### Steps to Reproduce
1. Uninstall existing MySQL installation: ```brew uninstall mysql```
2. Make sure ```homebrew``` is up to date: ```brew update```
3. Verify that the ```libevent``` dependency is installed: ```brew install libevent``` returns ```Warning: libevent-2.0.22``` already installed
4. Attempt to install MySQL, including the ```memcached``` plugin:  ```brew install --with-memcached mysql```

**NOTE:** The ```brew install --enable-memcached mysql``` also produces the same result as described in **Actual Result** below, but the output on the console indicates that ```--enable-memcached``` has been deprecated and replaced with ```--with-memcached```.

### Expected/Desired Result
MySQL is installed with the components necessary to install and configure the MySQL memcached plugin.

### Actual Result
Observe the following result after executing ```brew install --with-memcached mysql```:
```
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.26.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-5.6.26.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql/5.6.26 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DMYSQL_DATADIR=/usr/local/var/mysql -DINSTALL_INCLUDEDIR=i
==> make
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libstrings.a(longlong2str.c.o) has no symbols
/usr/bin/ranlib libstrings.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libstrings.a(longlong2str.c.o) has no symbols
[ 10%] Built target strings
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
mysql-sandbox 3.1.0 https://github.com/Homebrew/homebrew/pull/43389
mydumper: MySQL Data Dumper and Loader https://github.com/Homebrew/homebrew/pull/43139
percona-toolkit does not depend on MySQL https://github.com/Homebrew/homebrew/pull/41595
MySQL not woking with --datadir option https://github.com/Homebrew/homebrew/issues/41160
mysql-proxy 0.8.5 failed to build with mysql-connector-c 6.1.6 https://github.com/Homebrew/homebrew/issues/41263
no memcached support in most recent MySQL brew port https://github.com/Homebrew/homebrew/issues/42935
mysql-connector-c++ cannot build with mariadb  https://github.com/Homebrew/homebrew/issues/34578
mysql failed to build on 10.10 https://github.com/Homebrew/homebrew/issues/33448
Packages with --with-mysql option not satisfied by mariadb https://github.com/Homebrew/homebrew/issues/32973
```

### Additional Notes
* ```homebrew``` version information:  ```0.9.5 (git revision 2f227e; last commit 2015-09-09)```
* OS information (from ```sw_vers```):
```
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```
* I followed a couple of the links cited in the output above (which led me here), and this link seems to be the most relevant:  https://github.com/Homebrew/homebrew/issues/33448
* At one point, the ```--enable-memcached``` used to work:  http://adamthedeveloper.blogspot.com/2013/03/install-mysql-56-with-memcached-plugin.html

### Work-Around
To work around this problem and test MySQL w/the memcached plugin, I created an Ubuntu VM using Vagrant.  Installing MySQL and setting up the MySQL memcached plugin on a Vagrant VM worked fine.

**Comment by rlunar** [comment] 2015-10-29 16:42
Still broken on Yosemite 10.10.5 build 14F1021

$ brew install mysql --with-memcached                                                                                                           
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.27.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-5.6.27.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql/5.6.27 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DMYSQL_DATADIR=/usr/local/var/my
==> make
Last 15 lines from /Users/rluna/Library/Logs/Homebrew/mysql/02.make:
[ 10%] Building C object strings/CMakeFiles/strings.dir/my_strchr.c.o
cd /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings && /usr/local/Library/ENV/4.3/clang  -DDISABLE_MYSQL_THREAD_H -DHAVE_CONFIG_H -Wall -Wextra -Wformat-security -Wvla -Wwrite-strings -Wdeclaration-after-statement -O3 -g -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -I/tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/include    -o CMakeFiles/strings.dir/my_strchr.c.o   -c /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings/my_strchr.c
[ 10%] Building C object strings/CMakeFiles/strings.dir/strcont.c.o
cd /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings && /usr/local/Library/ENV/4.3/clang  -DDISABLE_MYSQL_THREAD_H -DHAVE_CONFIG_H -Wall -Wextra -Wformat-security -Wvla -Wwrite-strings -Wdeclaration-after-statement -O3 -g -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -I/tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/include    -o CMakeFiles/strings.dir/strcont.c.o   -c /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings/strcont.c
[ 10%] Building C object strings/CMakeFiles/strings.dir/strappend.c.o
cd /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings && /usr/local/Library/ENV/4.3/clang  -DDISABLE_MYSQL_THREAD_H -DHAVE_CONFIG_H -Wall -Wextra -Wformat-security -Wvla -Wwrite-strings -Wdeclaration-after-statement -O3 -g -fno-omit-frame-pointer -fno-strict-aliasing -DDBUG_OFF -I/tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/include    -o CMakeFiles/strings.dir/strappend.c.o   -c /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings/strappend.c
[ 10%] Linking C static library libstrings.a
cd /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/strings.dir/cmake_clean_target.cmake
cd /tmp/mysql20151029-57545-1mzcblf/mysql-5.6.27/strings && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/strings.dir/link.txt --verbose=1
/usr/bin/ar cq libstrings.a  CMakeFiles/strings.dir/bchange.c.o CMakeFiles/strings.dir/bmove_upp.c.o CMakeFiles/strings.dir/ctype-big5.c.o CMakeFiles/strings.dir/ctype-bin.c.o CMakeFiles/strings.dir/ctype-cp932.c.o CMakeFiles/strings.dir/ctype-czech.c.o CMakeFiles/strings.dir/ctype-euc_kr.c.o CMakeFiles/strings.dir/ctype-eucjpms.c.o CMakeFiles/strings.dir/ctype-extra.c.o CMakeFiles/strings.dir/ctype-gb2312.c.o CMakeFiles/strings.dir/ctype-gbk.c.o CMakeFiles/strings.dir/ctype-latin1.c.o CMakeFiles/strings.dir/ctype-mb.c.o CMakeFiles/strings.dir/ctype-simple.c.o CMakeFiles/strings.dir/ctype-sjis.c.o CMakeFiles/strings.dir/ctype-tis620.c.o CMakeFiles/strings.dir/ctype-uca.c.o CMakeFiles/strings.dir/ctype-ucs2.c.o CMakeFiles/strings.dir/ctype-ujis.c.o CMakeFiles/strings.dir/ctype-utf8.c.o CMakeFiles/strings.dir/ctype-win1250ch.c.o CMakeFiles/strings.dir/ctype.c.o CMakeFiles/strings.dir/decimal.c.o CMakeFiles/strings.dir/dtoa.c.o CMakeFiles/strings.dir/int2str.c.o CMakeFiles/strings.dir/is_prefix.c.o CMakeFiles/strings.dir/llstr.c.o CMakeFiles/strings.dir/longlong2str.c.o CMakeFiles/strings.dir/my_strtoll10.c.o CMakeFiles/strings.dir/my_vsnprintf.c.o CMakeFiles/strings.dir/str2int.c.o CMakeFiles/strings.dir/str_alloc.c.o CMakeFiles/strings.dir/strcend.c.o CMakeFiles/strings.dir/strend.c.o CMakeFiles/strings.dir/strfill.c.o CMakeFiles/strings.dir/strmake.c.o CMakeFiles/strings.dir/strmov.c.o CMakeFiles/strings.dir/strnmov.c.o CMakeFiles/strings.dir/strxmov.c.o CMakeFiles/strings.dir/strxnmov.c.o CMakeFiles/strings.dir/xml.c.o CMakeFiles/strings.dir/my_strchr.c.o CMakeFiles/strings.dir/strcont.c.o CMakeFiles/strings.dir/strappend.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libstrings.a(longlong2str.c.o) has no symbols
/usr/bin/ranlib libstrings.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libstrings.a(longlong2str.c.o) has no symbols
[ 10%] Built target strings
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
MySQL 5.7.9 https://github.com/Homebrew/homebrew/issues/45368
mysql: Add patches for memcached build failure https://github.com/Homebrew/homebrew/pull/44650
mydumper: MySQL Data Dumper and Loader https://github.com/Homebrew/homebrew/pull/43139
percona-toolkit does not depend on MySQL https://github.com/Homebrew/homebrew/pull/41595
MySQL not woking with --datadir option https://github.com/Homebrew/homebrew/issues/41160
no memcached support in most recent MySQL brew port https://github.com/Homebrew/homebrew/issues/42935
mysql-proxy 0.8.5 failed to build with mysql-connector-c 6.1.6 https://github.com/Homebrew/homebrew/issues/41263
mysql-connector-c++ cannot build with mariadb  https://github.com/Homebrew/homebrew/issues/34578
mysql failed to build on 10.10 https://github.com/Homebrew/homebrew/issues/33448
Packages with --with-mysql option not satisfied by mariadb https://github.com/Homebrew/homebrew/issues/32973
FAIL: 1

**Comment by smartinsightsfromdata** [comment] 2016-03-10 17:40
Not sure who has closed this.  Problem exist (same as documented by @rlunar ) with `mysql 5.7.11`.

As I saw a reference to Boost 1.60 used instead of 1.60, I re-installed boost 1.59, deleted 1.60 and tried again to  install `brew install  mysql --with-memcached`.

Same result as above, again.

**Closed** 2016-03-13 16:28 UTC
Labels: upstream issue
