### ISSUE TITLE
Error building gengetopt

### ISSUE THREAD

**Issue by darker0n** [Homebrew/homebrew#38781] opened 2015-04-18 05:44 UTC
I tried brew update and brew doctor. This is my console:

    darker0n@MacBook-Pro-Pasha ~> brew install zmap
    ==> Installing dependencies for zmap: gengetopt, byacc, libdnet
    ==> Installing zmap dependency: gengetopt
    ==> Downloading http://ftpmirror.gnu.org/gengetopt/gengetopt-2.22.6.tar.gz
    Already downloaded: /Library/Caches/Homebrew/gengetopt-2.22.6.tar.gz
    ==> ./configure --prefix=/usr/local/Cellar/gengetopt/2.22.6 --mandir=/usr/local/
    ==> make install
    make[4]: *** [header.lo] Error 1
    make[3]: *** [install] Error 2
    make[2]: *** [install-recursive] Error 1
    make[1]: *** [install] Error 2
    make: *** [install-recursive] Error 1

    READ THIS: https://git.io/brew-troubleshooting

And this is my brew doctor log:

    darker0n@MacBook-Pro-Pasha ~> brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: Python is installed at /Library/Frameworks/Python.framework

    Homebrew only supports building against the System-provided Python or a
    brewed Python. In particular, Pythons installed to /Library can interfere
    with other software installs.

    Warning: Homebrew's sbin was not found in your PATH but you have installed
    formulae that put executables in /usr/local/sbin.
    Consider setting the PATH for example like so
       echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by tdsmith** [comment] 2015-04-18 07:28
Can you post `brew gist-logs gengetopt`, please?

**Comment by darker0n** [comment] 2015-04-18 11:10
https://gist.github.com/8c79c6468b081cad7ba3

**Comment by jacknagel** [comment] 2015-04-18 16:34
```
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
```

Dupe of https://github.com/Homebrew/homebrew/issues/38514

**Closed by jacknagel** 2015-04-18 16:34 UTC

**Comment by darker0n** [comment] 2015-04-18 18:29
I'm updated xCode and all works fine. Thanks for your answers :smile:
