### ISSUE TITLE
Poppler fails to install with Qt5 optional bindings

### ISSUE THREAD

**Issue by skalee** [Homebrew/homebrew#44150] opened 2015-09-19 22:06 UTC
Following fails ([logs in gist](https://gist.github.com/anonymous/03d1b54cf313eef1075e)):

    brew install poppler --with-qt5

However this one surprisingly succeeds ([logs in gist](https://gist.github.com/anonymous/410676aff5ad19926d5f)):

    brew install poppler --with-qt --with-qt5

Thanks for your attention (and hopefully fixes, or maybe caveats entry is enough?). Pretty odd, isn't it?

**Comment by skalee** [comment] 2015-09-19 22:20
Though I don't see `poppler-qt5.h` anywhere neither `/usr/local/Cellar/poppler/0.35.0/include/poppler/qt5` whereas `poppler-qt4.h` is present in `/usr/local/Cellar/poppler/0.35.0/include/poppler/qt4`…

**Comment by skalee** [comment] 2015-09-19 23:49
1. Only the most recent Poppler versions: 0.35.0 and 0.36.0 are affected.
2. Installation succeeds for Poppler 0.34.0.
3. As far as I understand the logs, the problem is related to tests run after compilation.

**Comment by DomT4** [comment] 2015-09-20 00:20
The problem is `qt5`. It has ridiculously broken `pkg-config` files, which `poppler` uses during compile. Poppler is a victim rather than a suspect in this breakage, sadly.

**Comment by skalee** [comment] 2015-09-20 00:21
My previous comment was invalid. Poppler 0.34.0 does not detect Qt5 and disables the corresponding wrapper, even though `----enable-poppler-qt5` was passed:

```
checking for POPPLER_QT5... yes
checking for POPPLER_QT5_TEST... yes
checking for moc... moc
checking for Qt5 moc... no
checking for moc-qt5... no
checking for Qt5 moc-qt5... checking for qtchooser... no
…
Building poppler with support for:
  qt5 wrapper:        no
```

On the other hand, Poppler 0.35.0 detects Qt correctly, it just fails to brew:
```
checking for POPPLER_QT4... no
checking for POPPLER_QT5... yes
checking for POPPLER_QT5_TEST... yes
checking for moc... moc
checking for Qt5 moc... moc
…
Building poppler with support for:
  qt5 wrapper:        yes
```

**Comment by skalee** [comment] 2015-09-20 00:28
@DomT4 Thanks a lot.

**Comment by DomT4** [comment] 2015-09-20 00:32
Sadly the quite broken Qt5 situation is known. In an ideal world I'd like to revert to the version prior to `5.3.0` but we've discovered that people prefer a quite broken up-to-date `qt5` over a prior-version-but-functioning-completely `qt5`. Qt 5.5.1 seems likely to land soon, which should fix most of the issues we've been seeing, hopefully.

**Comment by ult1m8** [comment] 2015-09-22 13:52
Whats the status on this?  Is there a successful way forward (with Qt5 and poppler)?  Or do we just hope and pray the 5.5.1 resolves issues?

**Comment by DomT4** [comment] 2015-09-27 16:41
We're working on applying a patch to fix this, but it needs to be submitted upstream and Qt's patch submission process isn't the easiest in the world.

**Comment by ult1m8** [comment] 2015-09-28 00:06
DomT4, I would *love* to see that patch once done.  My teams project is currently updating from Qt4 to Qt5.5 and require poppler.

**Comment by UniqMartin** [comment] 2015-09-28 20:18
Support for building the Qt 5 bindings should be restored once #44410 gets committed, which should happen very soon.

Note though, that it's not possible to build the `poppler` formula with bindings for both Qt 4 and Qt 5 at the same time. Currently, options `--with-qt` and `--with-qt5` are mutually exclusive, but the formula silently ignores `--with-qt5` if `--with-qt` is also given. Would it be better to abort the build with an error if both options are specified? (Personally, I think this should be the case and will be less confusing.)

**Closed** 2015-09-28 21:20 UTC
Labels: upstream issue

**Comment by DomT4** [comment] 2015-09-28 21:22
`brew update && brew upgrade qt5` and this'll work again as expected. If someone wants to open a PR to be more explicit about only supporting one `qt` option we'll review it; we prefer non-fatal `ohai` warnings rather than raising though.
