### ISSUE TITLE
llvm 3.6.1 fails due to lldb_codesign: no identity found

### ISSUE THREAD

**Issue by mjbshaw** [Homebrew/homebrew#40359] opened 2015-06-04 00:59 UTC
Updating to the latest llvm (3.6.1) fails. `brew upgrade llvm` errors out with the message ``couldn't understand kern.osversion `14.3.0'``, but the logs show the actual error is `lldb_codesign: no identity found`.

Note that I'm building with the options `--with-lld, --with-clang, --with-lldb` (presumably it's the `--with-lldb` option that's causing the failure, but I haven't tried to narrow down the issue because building takes forever and burns up my laptop; I can do more target testing if needed, though).

[gist of the issue can be found here](https://gist.github.com/anonymous/920533dffaaa4ce1e3b5).

**Comment by mjbshaw** [comment] 2015-06-04 01:02
This might be a dupe of #39621, but I'm not 100% sure, so I'm logging it as a separate issue here.

**Comment by DomT4** [comment] 2015-06-04 16:51
Yeah, technically it's a dupe of existing issues. IMO this needs to go upstream, since I can't see there's anything we can do if there's an expectation of code-signing there.

CC @xu-cheng @tamird for prior discussions.

**Comment by tamird** [comment] 2015-06-04 16:53
+1 dupe

**Comment by luzpaz** [comment] 2015-06-12 12:18
+1 dupe

**Comment by DomT4** [comment] 2015-06-12 14:48
Closing this in favour of #39621.

**Closed by DomT4** 2015-06-12 14:48 UTC
Labels: upstream issue
