### ISSUE TITLE
nmap failed to build on 10.10.3 (14D131)

### ISSUE THREAD

**Issue by sethvargo** [Homebrew/homebrew#38500] opened 2015-04-10 00:23 UTC
https://gist.github.com/007dc61054f3f5185291

**Comment by mistydemeo** [comment] 2015-04-10 17:15
Same bug as #38514 - the issue is from the `iterator` C++ header in the new CLT. Closing as a dupe, let's keep discussion in one place!

**Closed by mistydemeo** 2015-04-10 17:15 UTC

**Comment by sethvargo** [comment] 2015-04-10 17:59
Cool sorry! I searched for nmap, but didn't see 38514. Will track that :smile:
