### ISSUE TITLE
cmake reports: CMake Error: Could not find CMAKE_ROOT !!!

### ISSUE THREAD

**Issue by xpol** [Homebrew/homebrew#35888] opened 2015-01-15 02:12 UTC
after `brew install cmake` installed cmake-3.1 on my OS X 10.10.

Running cmake will report error:

````
CMake Error: Could not find CMAKE_ROOT !!!
````

**Comment by mistydemeo** [comment] 2015-01-15 02:14
Can you please provide the output of `brew config` and `brew doctor`? What is the output of `which cmake`?

In addition, please follow the rest of the [troubleshooting guide](http://git.io/brew-troubleshooting). Thanks!

**Comment by snarke** [comment] 2015-01-21 19:53
Same problem..

brew config:
`$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit core2
OS X: 10.6.8-i386
Xcode: 3.2.6
CLT: N/A
GCC-4.0: build 5494
GCC-4.2: build 5666
LLVM-GCC: build 2335
Clang: 1.7 build 77
X11: 2.3.6 => /usr/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/snarke/.rvm/rubies/ruby-2.1.3/bin/ruby
`


brew doctor:
`Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /Library/usr/bin/freetype-config
  /Library/usr/bin/uuid-config
`


$ which cmake
/Library/usr/bin/cmake

**Comment by snarke** [comment] 2015-01-21 20:10
Error message itself is 

```Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
cmake reports: CMake Error: Could not find CMAKE_ROOT !!! (https://github.com/Homebrew/homebrew/issues/35888)
cmake builds fail on CLT-only with --env=std (https://github.com/Homebrew/homebrew/issues/29101)
```

**Comment by snarke** [comment] 2015-01-21 20:55
Huh. My apologies. It's NOT the same problem. It _used_ to be the "CMAKE_ROOT" not found problem, but after weeding out all the stuff `brew doctor` chastised me for, it changed. But since brew was still reporting the open issues links, I didn't realize they weren't as relevant any more. 

It's also saying `See also "/tmp/cmake-JwdsqM/cmake-3.1.0/CMakeFiles/CMakeError.log".` except that there is no such file. There's not even a "/tmp/cmake-JwdsqM" directory. So I'm not sure how to figure out what the problem is with the initial run. Hmmmmm.....

**Comment by xpol** [comment] 2015-01-22 00:35
I just can't reproduce this problem  after setting CMAKE_ROOT manually once, even I removed the CMAKE_ROOT in .bash_profile.

**Comment by ahmeier** [comment] 2015-01-25 14:21
I have exactly the same problem. Xcode and CLT are updated. running 10.10.1. My gist-log:
https://gist.github.com/8ca0cac911da4ac08480

Strange problem.

**Comment by jacknagel** [comment] 2015-02-13 02:44
Closing since the original issue in this thread can't be reliably reproduced. If your issue is not related to CMAKE_ROOT, then you need to open a new issue.

**Closed by jacknagel** 2015-02-13 02:44 UTC
Labels: needs response

**Comment by shepardo** [comment] 2015-02-26 21:51
I get the sample problem in Linux Open SUSE 12 x64, when installing from source cmake 3.1.3, over cmake 2.8.2. The problem was solved after removing some residuals of the old cmake (like /usr/bin) _and_ rebooting.

**Comment by melvincabatuan** [comment] 2015-03-21 19:46
$ ls
Auxiliary CMakeCPackOptions.cmake cmake_uninstall.cmake CTestCustom.cmake DartConfiguration.tcl Modules Tests
bin CMakeFiles CPackConfig.cmake CTestScript.cmake install_manifest.txt Source Utilities
CMakeCache.txt cmake_install.cmake CPackSourceConfig.cmake CTestTestfile.cmake Makefile Testing
$ rm CMakeCache.txt 
$ cmake --version
cmake version 3.2.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by algr** [comment] 2016-02-05 18:45
I get the sample problem in Ubuntu 13.06 armv7, but accompanied by a segfault, and not under strace:
```
# cmake --version
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/local/bin
Segmentation fault
# strace -o temp.out cmake --version
cmake version 3.5.0-rc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
so I wonder if this is an uninitialized data issue?

**Comment by mikemcquaid** [comment] 2016-02-05 20:16
We don't support Linux, this is Homebrew for OS X.
