### ISSUE TITLE
Mutt and Tin conflict

### ISSUE THREAD

**Issue by orbifx** [Homebrew/homebrew#43861] opened 2015-09-12 18:00 UTC
Can't install `mutt` and `tin` because they both install `mmdf.5` and `mbox.5`.

```
# brew install tin
Error: Cannot install tin because conflicting formulae are installed.
  mutt: because both install mmdf.5 and mbox.5 man pages
Please `brew unlink mutt` before continuing.
```

**Comment by DomT4** [comment] 2015-09-12 20:48
It blocks you because otherwise you'd run into linking failures trying to link two of the same-named file onto the same location. This is the intended behaviour.

You can `brew unlink mutt` and then install `tin`, and then `unlink` and `link` each one as necessary/desired, if you're looking for a way around this.

**Comment by dunn** [comment] 2015-09-12 22:36
You can also unlink mutt, install tin, then `brew link --overwrite mutt` which will overwrite conflicting tin symlinks with the mutt ones. (You can do it the other way around if you'd prefer the tin manpages to be linked.)

**Comment by DomT4** [comment] 2015-09-13 00:41
Presuming resolved by the above two responses, but let us know if you have any further questions here. Happy to help!

**Closed by DomT4** 2015-09-13 00:41 UTC

**Comment by orbifx** [comment] 2016-01-09 15:19
I didn't try it in the end, but it seems like a valid solution.
