### ISSUE TITLE
Build of coreutils --HEAD fails

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew#40962] opened 2015-06-22 04:41 UTC
```
./bootstrap: Error: 'makeinfo' version == 4.8 is too old
./bootstrap:        'makeinfo' version >= 4.13 is required
./bootstrap: See README-prereq for how to get the prerequisite programs
```
full log: https://gist.github.com/fc2038050bc8e961b0de

My suggestion is to create --head for texinfo formulae

**Comment by mikemcquaid** [comment] 2015-06-22 09:11
> My suggestion is to create --head for texinfo formulae

Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jacknagel** [comment] 2015-06-22 14:08
Why would adding head to texinfo solve the problem? It's currently packaging version 5.2, while the error is complaining about version 4.8 (this is the version that Apple packages currently).

I can't reproduce this. Can you try `brew reinstall texinfo` first?

**Comment by DomT4** [comment] 2015-06-27 18:47
Presuming resolved.

**Closed by DomT4** 2015-06-27 18:47 UTC
Labels: 10.11, needs response, user configuration
