### ISSUE TITLE
node and icu4c Yosemite bottles have different C++ standard libraries

### ISSUE THREAD

**Issue by MerelyAPseudonym** [Homebrew/homebrew#36681] opened 2015-02-09 18:34 UTC
(Either that, or there's a misleading warning)

```none
joshuatilles@MBP0206 ~> brew install node
==> Installing node dependency: icu4c
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/icu4c-54.1.
Already downloaded: /Library/Caches/Homebrew/icu4c-54.1.yosemite.bottle.1.tar.gz
==> Pouring icu4c-54.1.yosemite.bottle.1.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

OS X provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
🍺  /usr/local/Cellar/icu4c/54.1: 242 files, 65M
==> Installing node
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/node-0.12.0
Already downloaded: /Library/Caches/Homebrew/node-0.12.0.yosemite.bottle.tar.gz
==> Pouring node-0.12.0.yosemite.bottle.tar.gz
Warning: node dependency icu4c was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
==> Caveats
If you update npm itself, do NOT use the npm update command.
The upstream-recommended way to update npm is:
  npm install -g npm@latest

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/0.12.0: 2196 files, 26M
joshuatilles@MBP0206 ~>
```

I'd expect that if I'm letting Homebrew handle the dependencies of a formula for me, it shouldn't do anything that it has to warn me about.

**Comment by DomT4** [comment] 2015-02-09 18:55
This is a known thing. I haven't found any issues with the setup in weeks of testing, so I don't think it's a big deal FWIW. It's not a misleading warning as such, It's a warning that something may go wrong, not that it will go wrong :).

I think it's a ` cxx11 ` warning, which is probably relatively easy to fix - But given the fix will require people to build ` icu4c ` from source rather than from a bottle, I didn't really want to push something like that unless it proves necessary.

Mike, Jack, Tim or any of the maintainers may look at this differently from me.

**Comment by jacknagel** [comment] 2015-02-09 19:10
So the issue is that the node executable links against libstdc++ because of an archaic deployment target setting.

It would be cool if node would link against libc++, but that will require someone to convince upstream.

**Comment by lowski** [comment] 2015-02-10 07:39
There is an issue when you use Titanium. It doesn't work after upgrade. I had to go back to v 0.10.36.

**Comment by DomT4** [comment] 2015-02-10 13:05
How are Node upstream dealing with this, given they also use ` icu4c `, and from 0.12 have the feature turned on for English? It'd be good to have some communication from the Node team about these things.

**Comment by DomT4** [comment] 2015-02-10 18:49
I'll partially revert what we committed earlier this week in regards to ` icu4c ` in a PR imminently, add some caveats to warn of the issues, and file an upstream report with Node to request they stop building against frustratingly outdated deployment targets. Right now, you can actually build the latest version without ` icu4c ` just by doing ` brew install node --without-icu4c `.

**Comment by DomT4** [comment] 2015-02-11 18:32
Closed by 2bfa1000b66d021da073b75e51c3f93423ddeea2.

**Closed** 2015-02-12 06:08 UTC
Labels: libc++, upstream issue

**Comment by engineapp** [comment] 2015-02-23 17:23
@lowski What is the best way to install 0.10.36 using brew?

**Comment by lowski** [comment] 2015-02-23 17:27
@engineapp to be honest I don't know. What I did I just cd to Homebrew directory and revert node.js formula to this [commit](https://github.com/Homebrew/homebrew/blob/06b10bc64605ece33b56d2607a1480cf8177fd8f/Library/Formula/node.rb)

**Comment by DomT4** [comment] 2015-02-23 20:46
Try not to revert Homebrew's git repo. That has caused all sorts of trouble before now. There's a Node 0.10.x waiting to be merged in Homebrew/Versions, which you can tap and use.

**Comment by engineapp** [comment] 2015-02-23 21:37
Great thanks.

**Comment by DomT4** [comment] 2015-02-23 21:38
Give me like... 25 minutes minutes and I'll merge the Node010 in Versions, then you'll be able to do ` brew tap homebrew/versions && brew install node010 `.
