### ISSUE TITLE
ruby failed to install with permission error

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/homebrew#47439] opened 2015-12-28 02:35 UTC
gist-logs
https://gist.github.com/anonymous/78079f2adc94030e3d32

The error is because it is trying to install the common headers to a wrong location

Last 15 lines from /Users/yuhuang/Library/Logs/Homebrew/ruby/03.make:
installing common headers:    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Users/yuhuang/.homebrew/Cellar/ruby/2.3.0/include/ruby-2.3.0
/private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Users (Errno::EACCES)
        from /private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:250:in `fu_mkdir'
        from /private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:227:in `block (2 levels) in mkdir_p'
        from /private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:225:in `reverse_each'
        from /private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:225:in `block in mkdir_p'
        from /private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:211:in `each'
        from /private/tmp/ruby20151228-5074-1gfrvku/ruby-2.3.0/lib/fileutils.rb:211:in `mkdir_p'
        from ./tool/rbinstall.rb:191:in `makedirs'
        from ./tool/rbinstall.rb:304:in `prepare'
        from ./tool/rbinstall.rb:513:in `block in <main>'
        from ./tool/rbinstall.rb:801:in `block in <main>'
        from ./tool/rbinstall.rb:798:in `each'
        from ./tool/rbinstall.rb:798:in `<main>'
make: *** [do-install-nodoc] Error 1

It is not installed within the homebrew directory.

**Comment by DomT4** [comment] 2015-12-28 17:31
Heh, I've seen this reported in a bunch of places already. It is believed to be a Ruby problem, rather than anything specific to the way we or anyone else packages it. `rbenv` had the same issue reported a couple days back: https://github.com/rbenv/rbenv/issues/844

I'll peek upstream and see if it's on the Ruby bugtracker yet.

**Comment by DomT4** [comment] 2015-12-28 19:14
Has been reported upstream: https://bugs.ruby-lang.org/issues/11881

I can't reproduce locally. It installs in the right place. Mildly frustrating because without being able to reproduce it's difficult to test potential fixes. Do you have `SDK` variables set in your `env`?

**Comment by mistydemeo** [comment] 2015-12-28 19:21
@DomT4 We export SDKROOT on Xcode-only configurations.

**Comment by DomT4** [comment] 2015-12-28 19:23
@mistydemeo Ah, I knew that but didn't notice OP here was running an Xcode-only system. Doh. Can we unset `SDKROOT` in the formula without breaking it as a workaround for the upstream issue?

**Comment by mistydemeo** [comment] 2015-12-28 19:46
It looks like the upstream commit that caused that is quite small; we could probably just include a patch to remove it until it gets fixed?

**Comment by mistydemeo** [comment] 2015-12-28 23:18
Should be fixed now.

**Closed** 2015-12-28 23:19 UTC
Labels: upstream issue
