### ISSUE TITLE
404 Not Found on HBase and Hive

### ISSUE THREAD

**Issue by D-vindicator** [Homebrew/homebrew#44485] opened 2015-10-01 02:57 UTC
Please update the url of these two softwares.

**Comment by bfontaine** [comment] 2015-10-02 10:40
Would you mind making a pull-request? This should help and I’m happy to answer any question you might have: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by Moisan** [comment] 2015-10-02 21:44
I could reproduce the 404 Not Found error for HBase, which was due to the new latest release, [pull request 44511](https://github.com/Homebrew/homebrew/pull/44511) should fix that. However I could not reproduce it for Hive.

**Comment by DomT4** [comment] 2015-10-04 14:24
There's no newer release for `hive` on the upstream website or Apache mirrors. Presuming that's a local issue which usually self-resolves after a few hours. Please `brew update` and try again on that.

**Closed by DomT4** 2015-10-04 14:24 UTC
