### ISSUE TITLE
Can not install Homebrew because can not load CA certificate file.

### ISSUE THREAD

**Issue by lostatseajoshua** [Homebrew/homebrew#44636] opened 2015-10-05 19:10 UTC
In terminal when I type in the command:
 ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

It begins the download of hombrew but it always fails here:
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/homebrew/': SSL: can't load CA certificate file /absolute/path/to/cacert.pem
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1

I then try to run the install again and it home-brew is installed but it is not. When I try to use any brew command it says command not found. If I try to uninstall home-brew it says homebrew not found

**Comment by DomT4** [comment] 2015-10-05 19:23
> SSL: can't load CA certificate file /absolute/path/to/cacert.pem

That message is being thrown from `curl`, I believe. Are you setting an environmental variable for the CA cert somewhere? Try `env | grep cacert`.

**Comment by lostatseajoshua** [comment] 2015-10-05 19:30
I am not sure what a environmental variable is. I ran grep cacert and nothing happens and when I run env it just displays a list of information. Sorry I feel clueless on these errors. Do I have to create a CA cert? Where does it come from? I have tired google and not look on this error or what it even is.

**Comment by DomT4** [comment] 2015-10-05 19:35
`env` prints out a full list of everything loaded into the environment. Includes your `$PATH`, `$SHELL`, any variable you've exported, etc. You shouldn't be seeing this error at all. The error message suggests that somewhere the default example path for a CA certificate from `curl` is being passed when it shouldn't be.

Make sure you ran the `env | grep cacert` command whole, not both separately. 

Do you have a `.bashrc` or `.zshrc` or `.bash_profile` in your `$HOME` directory?

**Comment by lostatseajoshua** [comment] 2015-10-05 19:42
Well I think the problem is I don't have a cert to clone from git I always use ssh. Where do I setup a cert to clone from git? I tired to make a .pem file and run git config --system http.sslCAInfo /path/to/file/Certificates.pem but it throws could not lock config file.

**Comment by apjanke** [comment] 2015-10-09 01:50
You shouldn't need to do any cert-related configuration for this to work. OS X ships with CA certificates already installed, and the system `curl` set up to respect them. (It's not done with PEM files in newer versions; since 10.9, [`curl` is linked to Apple's Secure Transport framework](http://curl.haxx.se/mail/archive-2013-10/0036.html) and gets its CA certs from the system keychain.)

This looks like it might be a problem with the git configuration file, and not environment variables. Since Mavericks, `curl` doesn't seem to respect the `$CURL_CA_BUNDLE` environment variable. And I can't induce this error on Mavericks at all. But on El Capitan, I can reproduce this issue by adding the following section to `~/.gitconfig`.

```
[http]
        sslVerify = true
        sslCAinfo = /absolute/path/to/cacert.pem
```

This reproduces the exact error message when running `git` (which I believe is calling out to `curl` or `libcurl` behind the scenes, like DomT4 suggests, and is passing `--cacert` or its equivalent).

```
$ git clone https://github.com/homebrew/homebrew.git
Cloning into 'homebrew'...
fatal: unable to access 'https://github.com/homebrew/homebrew.git/': SSL: can't load CA certificate file /absolute/path/to/cacert.pem
```

That seems consistent with the OS X curl changes for [10.9](http://curl.haxx.se/mail/archive-2013-10/0036.html) and [10.10](http://curl.haxx.se/mail/archive-2014-10/0053.html).

So, check your `~/.gitconfig` for that `sslCAInfo` line and correct or remove it. Maybe it got edited at some point when you were setting up a `git` connection to a different server?

**Comment by DomT4** [comment] 2015-10-19 16:47
Closing as dead. Will reopen or let another maintainer reopen if we get a reply here.

**Closed by DomT4** 2015-10-19 16:47 UTC
Labels: user configuration
