### ISSUE TITLE
Python openssl issue

### ISSUE THREAD

**Issue by michaeljs1990** [Homebrew/homebrew#41215] opened 2015-06-30 17:38 UTC
https://github.com/Homebrew/homebrew/issues/14497 looks like it may possibly be related to this issue. Right now when i am trying to connect to docker with docker-py I keep getting an ssl cert error. 
```
msg: SSLError(SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),),)
```
This is using python 2.7.10 as installed through brew. If I then install python 2.7.10 via python.org using the exact same pip packages installed when i was using python brew it works. This is also using the same version of openssl as i replaced the default osx version with one i installed through brew 1.0.2c. Any possible idea why this could be happening. 

I encountered this when working on https://github.com/ansible/ansible-modules-core/pull/1639

**Comment by tdsmith** [comment] 2015-06-30 19:15
This looks like a duplicate of #38226; please see the resources linked there. I think the problem is between docker and recent versions of openssl.

> This is also using the same version of openssl as i replaced the default osx version with one i installed through brew 1.0.2c.

That's likely to break things. You can verify the openssl version against which your Python ssl module is built with `import ssl; print ssl.OPENSSL_VERSION`.

**Comment by michaeljs1990** [comment] 2015-06-30 19:31
the command above reports 1.0.2.c. I was also getting the same error using the mac osx built in openssl 0.9.8 which prompted my upgrade.

**Comment by tdsmith** [comment] 2015-06-30 19:34
> the command above reports 1.0.2.c

In which circumstances?

**Comment by michaeljs1990** [comment] 2015-06-30 20:27
something odd happened. Before the python install from python.org (When i was using brew python) the above command would output 1.0.2c. After the install from python.org It now reports OpenSSL 0.9.8zd which i find odd because openssl on machine per openssl version reports...

```
| => openssl version
OpenSSL 1.0.2c 12 Jun 2015
```

So i'm not sure how python.org is using an older version unless that is bundled into it.

**Comment by mistydemeo** [comment] 2015-06-30 20:28
Can you explain what you mean when you say you "replaced the default osx version"?

**Comment by michaeljs1990** [comment] 2015-06-30 20:32
yes, I ran the following ...

```
unlink /usr/bin/openssl
brew install openssl
sudo ln -s /usr/local/Cellar/openssl/1.0.2c/bin/openssl /usr/bin/openssl
```

which i understand may not actually change the version of openssl being used by python but on the brew version it did.

**Comment by michaeljs1990** [comment] 2015-06-30 20:56
I got it working with 1.0.2c somehome... I am not sure exactly. I forced the removal of python and openssl. I then installed with...

```
brew install python --with-openssl
```

and then I tried to run it again and everything worked. I am not sure why the install with openssl command would fix it but unfortunately I am not sure how to reproduce the error at this point.

**Comment by michaeljs1990** [comment] 2015-06-30 21:00
My plan for now is to go ahead with the pull request to ansible modules and have an error message to submit a bug to ansible modules and tag me so I can work through it again until I am able to fully resolve whatever issue is causing it.

**Comment by tdsmith** [comment] 2015-06-30 21:06
I'm glad it's working. A few observations, though: --with-openssl has no effect; it doesn't change how python is built or how Homebrew behaves. Modifying the /usr/bin/openssl executable should have no effect since the Python _ssl.so module is linked to the library (not the executable) and nothing should invoke the openssl executable directly. Modifying OS-installed executables and libraries can break your system and we don't recommend it.

If you find a solution please let the docker team know.

**Closed by tdsmith** 2015-06-30 21:06 UTC
Labels: python
