### ISSUE TITLE
Zsh cargo site-function completion parse error

### ISSUE THREAD

**Issue by Kerosene2000** [Homebrew/homebrew#41374] opened 2015-07-05 14:56 UTC
```
$> cargo \tab
_cargo:293: parse error near `]]'
_cargo:293: parse error near `]]'
$> cargo 
```

if you change `if ! [[ $manifest ]]; then` by `if ![[ $manifest ]]; then` (the space)
you don't have the error, zsh 5.0.5 and 5.0.8 have the same parse error detection in that case...

I wanted to fix it but I didn't find the `_cargo` file ;( sorry

**Comment by apjanke** [comment] 2015-07-05 23:44
I believe you'll find _cargo in the [rust-lang/cargo](https://github.com/rust-lang/cargo) repo under [`src/etc`](https://github.com/rust-lang/cargo/tree/master/src/etc). [Here's the line.](https://github.com/rust-lang/cargo/blob/d7cf7d9128eb15759cdddf3b7a6da30a874b169a/src/etc/_cargo#L293) Sounds like something to report to upstream to the cargo maintainers.

Changing `! [[` to `![[` is probably the wrong fix. That removes the parse error, but changes the interpretation of the line so that it's now doing a history recall instead of a boolean inversion (I think). Instead, the `!` should probably move inside the `[[ ... ]]` brackets, or better yet, just be replaced with `[[ -z $manifest ]]`. The `[[ $foo ]]` syntax isn't supported the way the single-bracket `[ $foo ]` nonempty test is, I don't think.

**Comment by apjanke** [comment] 2015-07-28 08:47
Looks like that fix was already done at rust-lang/cargo#920. I don't understand why it's not showing up in their master yet. (I think it's wrong, anyway, and would still need another patch.)

Reported the issue upstream at rust-lang/cargo#1852.
Submitted a patch upstream at rust-lang/cargo#1853.

**Comment by apjanke** [comment] 2015-07-28 08:49
BTW, to reproduce this issue under Homebrew, I did this (in zsh). After that, `cargo<tab>` would produce the "parse error" message.

```
brew install rust
fpath+=/usr/local/Cellar/rust/1.1.0/share/zsh/site-functions
autoload -U compinit; compinit
```

**Comment by mikemcquaid** [comment] 2015-08-01 13:33
@apjanke Could you try and open a pull request for that (to us)? Thanks!

**Comment by DomT4** [comment] 2015-08-22 14:27
This was merged in the latest Rust update in Homebrew. Thanks for getting this done upstream @apjanke :heart:.

**Closed by DomT4** 2015-08-22 14:27 UTC
Labels: upstream issue
